### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by ghost** [stevenschobert/instafeed.js#10]
Having trouble getting the 'locationid' working. I'm able to get users and hashtag, but can't figure out the location.

Would you be able to put an example of the location ID in the example page?

Thanks so much for the killer plugin.

**Comment by nguila** [comment]
Where i have to put the : https://api.instagram.com/v1/locations/search?lat=48.858844&lng=2.294351&access_token=YOUR_ACCESS_TOKEN to receive that response?
