### ISSUE TITLE
Unslider comptability issues?

### ISSUE THREAD

**Issue by astrolope** [stevenschobert/instafeed.js#105]
Was working on a way to create a simple unslider instance using a templating system of a list to generate the unslider with up to 10 images. The issue is I get one image or all ten. but they won't scroll consecutively. I'm using jekyll so I have the url image fix in place. I also created a fiddle with the code that I'm using so you can take a look.. thanks for your time!

http://jsfiddle.net/8JVSC/

**Comment by benjamin-hull** [comment]
Closing as stale.
