### ISSUE TITLE
Display photos of you (i.e. photos you’re tagged in).

### ISSUE THREAD

**Issue by jeffcastle** [stevenschobert/instafeed.js#108]
Looks like they recently added this functionality to their api. Would love to see it here. Cheers

**Comment by jeffcastle** [comment]
Hi. I've been patient about this, and tried a few things myself to get it to work. It's still #1 on our wishlist though, so I'd love some suggestions if you have time.

Btw, we're getting great mileage out of the plugin in general. It might not look like much, but I'm particularly proud of my Google Sites integration. Sites tries to resist all customization, so we have Instafeed running on a separate domain. Sites only allows iframes from secure sites, so we run the page through a free shared ssl scrubber and then insert it into our Google page: http://ahs.ausdk12.org (We're also using it on our sister site here: http://albanyhighca.org/).

So rad. Thanks for such a simple and elegant tool.

**Comment by benjamin-hull** [comment]
Closing this one as stale. It's not supported by [IG's API anyway](https://www.instagram.com/developer/changelog/).
