### ISSUE TITLE
Filter - excluding by ID

### ISSUE THREAD

**Issue by feedersticks** [stevenschobert/instafeed.js#117]
Hi,

How do I properly exclude a post by filtering its ID? 

I tried doing this using the code below, it was successful in filtering the images but the excluded images were not replaced with a post. For example, the limit is set to 12 after applying the filter which excluded 2 posts. it returned only 10 items in the list. I was expecting to have a total of 12 items. 

I think this is happening because the filter is applied after the API request . Is there any way to filter before the API request? Thanks!

```
         var feed = new Instafeed({
            get: 'tagged',
            tagName: 'love',
            limit: 12 ,
            clientId: '111111111',
            template: ' <li class="col-lg-2 col-md-2 col-sm-2 col-xs-4"><img src="{{image}}" /></li>',
            filter: function(image) {
                if(image.id  != "POST_ID" ) {
                    return true;
                }else{
                    return false;
                }
              }
        });
        feed.run();

```

**Comment by JimmyRittenborg** [comment]
I'm fiddling with the same problem too https://github.com/stevenschobert/instafeed.js/issues/97#issuecomment-42217785 have some good suggestions, but it'll leave some images out completely :disappointed:

**Comment by benjamin-hull** [comment]
Closing as stale.
