### ISSUE TITLE
Trouble integrating with masonry.js

### ISSUE THREAD

**Issue by mattgp** [stevenschobert/instafeed.js#118]
Hi There, 

I'm loving instafeed and have been using it for a while with good results, I have recently been trying to output the thumbnails in to a layout parsed with masonry.js however having no success.  I have more or less managed to get instafeed to output the right html structure for masonry to interpret however no results.

Has anyone had any luck with this?

**Comment by benjamin-hull** [comment]
Closing this one as stale, but @mattgp if you're out there, yes, you can only have one `after` callback (though that function can just call two other functions).
