### ISSUE TITLE
Is it possible to have the feed display more then one tag/user?

### ISSUE THREAD

**Issue by elhigo** [stevenschobert/instafeed.js#12]
Hi,

Don't know if this is a feature that instafeed.js has but I tried a couple of ways but didn't get it to work so I figured its easiest just to ask.

Is it possible to have one feed display more then one tag or user? If so, what is the proper way to do so?

// Axel

**Comment by edonbajrami** [comment]
Ok, but is there any chance to mix content from two hashtages. Show latest images from two hashtags and not to be seperated on different div. Not to be first contetn from the #hashtag1 and then #hashtag2. I need to mix them :)

**Comment by kmtaylor62** [comment]
@stevenschobert Is it possible to pull two different image sizes based on device being used? I like the smaller thumbnail size for desktop, but curious if there's a way to use the low_rez or standard_rez option for smartphones and tablets?

**Comment by stevenschobert** [comment]
@kmtaylor62 That's not something Instafeed.js has any options for. You'll have to use CSS and media queries to control the image sizes. You may want check out #143 and ask how they implemented it.

**Comment by kmtaylor62** [comment]
Thanks @stevenschobert. I was curious if you've had any issues with the instagram.js displaying in Chrome? It doesn't seem to be viewing properly.

**Comment by stevenschobert** [comment]
@kmtaylor62 I'm not aware of any issues currently, but feel free to open another issue if you're running into something!

**Comment by apo11oCreed** [comment]
Thank you Steven, this solution helped me out just in time!

**Comment by catsgomeyow** [comment]
Is it possible to have three tags being put into one feed on your website? So, say, you have one feed but it shows the most recent tagged photo between all three feeds. For example, if I have the three tags but one tag has newer photos than the other two... I want those newest photos to show. Right now, it just shows the latest of each feed.
