### ISSUE TITLE
<tr> and <td> doesn't reflect in the output using template option

### ISSUE THREAD

**Issue by jerb0x** [stevenschobert/instafeed.js#120]
Hi There,

I'm trying to display the result in a table layout. However, once I've load the page it doesn't read or display the < tr > and < td > tag in html.  However, if I include the < table > tag it does work. But I only need the < tr > or the < td > in the template option. 

Hope you can help me out.

Thanks!

**Comment by mingtam** [comment]
I found the same problem as well, is there any way to resolve this problem?

**Comment by benjamin-hull** [comment]
This is just the nature of dynamically inserting content - the browser needs to turn the template string into something like 'valid' DOM structure. If what you're inserting is valid, then no changes need to be made, but if not, the browser tries to massage the DOM as it does the inserting so things make sense (or at least don't break the whole page).

If you try to put table structure into something that's not a table, the browser strips out a lot of the surrounding content, leaving the text. You should have more luck if you try to use a `table` (or better yet, a `tbody`) as your instafeed.js target - that way your template will be valid when the browser tries to insert it.

Please see this [codepen](https://codepen.io/benjamin-hull/pen/GdxmpL) for an example. Good luck!
