### ISSUE TITLE
Template isn't working for me!

### ISSUE THREAD

**Issue by ajohnston101** [stevenschobert/instafeed.js#126]
I've probably done something stupidly wrong, but when I add in any template style it doesn't have an effect on the output! The images still show up, but I'd really like to show the like count and the caption with it (underneath it) and I don't know how to display it! Can someone help me?

This is what I have now...

```
var feed = new Instafeed({
    get: 'user',
    userId: 51013702,
    accessToken: '3122829.c3055c7.82d9d5a4b2ae4a95a9d966005e08d5cb',
    clientId: 'c3055c7b501f428386e2eb9d2e5329eb',
    resolution: 'low_resolution',
    template: '<a href="{{link}}" target="_blank"><img src="{{image}}"/><p>{{caption}}</p><p>{{likes}}</p></a>',
});
feed.run();
```

**Comment by designMoreWeb** [comment]
I am trying to get the captions centered how do i do that ?

**Comment by benjamin-hull** [comment]
Closing this one as stale.
