### ISSUE TITLE
Access individual instafeed objects

### ISSUE THREAD

**Issue by cecilgol** [stevenschobert/instafeed.js#127]
Really love this lib, but i have an issue.

i am using a filter: callback on an unknown number of instafeed objects, to grab tagged images. i successfully got my after: callbacks working using the solution posted here: #85; but cannot get a unique TAG passed to 

``` javascript
filter:function(image){}
```

``` javascript
else if (targets[i][1].match("col-header")){ //this fires an undefined number of times
  var TAG = targets[i][2];
  console.log(TAG); // yields correct tag
  opts = {
  ...
  filter: function(image){
    console.log(TAG); // yields undefined OR the last set value for TAG
    return image.tags.indexOf(TAG) >= 0;
  }
}
```

i know its a scoping issue, but i see the filter function is associated with each created object, and i could ostensibly use 

``` javascript
    opts = {
    name: TAG,
  ...
  filter: function(image){
    return image.tags.indexOf(this.name) >= 0; //this.name or self.name or some reference to the resulting object
  }
```

Does anyone know of a way to achieve what i'm describing, or a way to avoid the scoping issue?

**Comment by benjamin-hull** [comment]
Closing this one as stale, but for future reference, you can manipulate or 'pre-filter' the raw data in the response with the `success` callback.
