### ISSUE TITLE
Get photos by username and tag? 

### ISSUE THREAD

**Issue by rudidev08** [stevenschobert/instafeed.js#13]
It seems that getting photos by username and tag is mutually exclusive. Is it possible to do to both in the same time?

**Comment by vanrooj** [comment]
I know this has been closed but I can't get this to work. nothing shows up, here's the code:

<script type="text/javascript">
var feed = new Instafeed({
  get: 'user',
  userId: 1115980238,
  filter: function(image) {
    return image.tags.indexOf('vanrooj') >= 0;
  }
});
feed.run();

</script>

**Comment by toomanychrises** [comment]
I have the same problem, it shows up blank if there is a new post without the tag using the code example above:
var feed = new Instafeed({
        get: 'user',
        userId: 'user-id',
        limit: 1,
        clientId: 'client-id',
	filter: function(image) {
		 return image.tags.indexOf('tag-name') >= 0;
	}
    });
    feed.run();
