### ISSUE TITLE
slideshow from feed

### ISSUE THREAD

**Issue by thomyerk** [stevenschobert/instafeed.js#134]
hello! 
i just saw steven's solutions for a carousel from a feed, and I think that would be super fast, because only loads a few (?) images. I had "hacked" the instafeed with an 'after: function { feed.next() }, so I've got all the results. The problem is that i would like to use a slider, which only begins to work if all the images fetched, and that takes a long time. Is that possible to make it work with steven's solution?

here's the fork: http://codepen.io/anon/pen/oaHes
here is the comment he mentioned it: https://github.com/stevenschobert/instafeed.js/issues/78#issuecomment-39860690

also I did'nt really sure how that code works, where did it fetch images for example? I'm so confused but really need that feature

edit: also it can only fetch 15 pictures. I removed the limit, but still. how is that possible?

**Comment by benjamin-hull** [comment]
Closing this one as stale - the answer is really up to the carousel library in use.
