### ISSUE TITLE
Hov I can add an element after 3 photo?

### ISSUE THREAD

**Issue by how3ver** [stevenschobert/instafeed.js#136]
Hi, I love this plugin!!! It is very useful for my business but now I have a new necessity, I must add a div with textual element after three pictures counted and before the other pics.

So I want a sort of this scheme:

<li><a>Photo 1</a></li>
<li><a>Photo 2</a></li>
<li><a>Photo 3</a></li>
<li>Hello dudes!</li>
<li><a>Photo 4</a></li>
<li><a>Photo 5</a></li>
<li><a>Photo 6</a></li>
<li><a>Photo 7</a></li>
<li><a>Photo 8</a></li>

How can I obtain this? I hope in you!

**Comment by benjamin-hull** [comment]
Closing as complete.
