### ISSUE TITLE
not able to select elements created by instafeed.js

### ISSUE THREAD

**Issue by alekks** [stevenschobert/instafeed.js#139]
Heya,

I'm trying to get the value of the class of <img> with jquery, it works with all elements that instafeed.js doesn't create. But the elements created with the template aren't able to select.

So my jQuery is not best practice, I'm just trying to get the idea to work before I optimize it, anyways, what I'm not figuring out is that this works just fine on `#thumb` and `#max` but if I move the selectors "up" one level, but not with anything within these divs, the elements that have been created by instafeed.js.

What's weird is that css is selecting the elements just fine but seem invisible to jQuery...

Concept (no Instafeed implemented):
[JSFiddle here.](http://jsfiddle.net/alekks/s3B9F/12/)

**Comment by benjamin-hull** [comment]
Closing as stale. Sounds like an order of execution thing, though.
