### ISSUE TITLE
"Like" from website?

### ISSUE THREAD

**Issue by DNevens** [stevenschobert/instafeed.js#140]
Hi,

Love Instafeed!

On Gramfeed you can like photos right from their website. Is it possible to have this same functionality with Instafeed? 

Essentially I would like the pictures in my website feed to be "likeable" directly from there as opposed to having to click on the picture, have Instagram open, and then clicking the heart.

Thanks!

**Comment by benjamin-hull** [comment]
Closing as stale (and unlikely to be possible with the API as it is now)
