### ISSUE TITLE
Is there a way to get the whole feed of the people I follow?

### ISSUE THREAD

**Issue by mlaeng** [stevenschobert/instafeed.js#141]
Hello,
I might be missing something, but can I get the whole feed of all the people I follow? If yes, how?

I just set up a page to deliver pictures to a DYI digital Instagram photo frame and it would be great to see other pictures than my own... (especially those of the people I follow...)

Thanks for any help! And also thanks for this great peace of code. Will pay for beer/coffee for sure!

**Comment by benjamin-hull** [comment]
Closed as part of https://github.com/stevenschobert/instafeed.js/pull/149
