### ISSUE TITLE
Dynamic image resolution.

### ISSUE THREAD

**Issue by jamesscholeyweb** [stevenschobert/instafeed.js#143]
Hi, first off love the plugin.

I was just wondering is there anyway of dynamically changing the resolution dependent on window width? played around for a while but no luck.

Basically I want to get the window width with js and serve low_resolution by default but if window is wider than 320px then pull in the standard_res.

Any pointers in the right direction to access the options would be much appreciated.

Thanks in advance

**Comment by kmtaylor62** [comment]
@jamesscholeyweb Were you able to figure out the resolution dependent window width? I'd like to get the images to display at different sizes between, desktop and mobile. If you could shine some light on this that would be great.

**Comment by jamesscholeyweb** [comment]
@kmtaylor62. I did figure it out but I don't remember how off the top of my
head it was a while ago now and the project was abandoned by the client
before it got finished. I'm just in process of moving but will have some
time to kick back later in the week so I'll take a look and link up a
codepen or something.

**Comment by kmtaylor62** [comment]
Thanks man, take your time.
