### ISSUE TITLE
load more loop

### ISSUE THREAD

**Issue by vmkazakoff** [stevenschobert/instafeed.js#145]
Hi, first of all - thanks for the script! It is awesome!!!

I run in a problem with loading next images with `.next` function. It load new one, but it load it like this: first page, second page, _again_ first page, second page, **again** first page...  **again** first page... and so on... I did not find any dependences on how many photos have tag, or what limit or sorting I use...

I want reload it (without click) every 60 second (5 is only for testing) _(and I know about limits, I will use this app to show fotos on TV on my events, so I am only one user)_. All photos will be showed on screen in one time - in 3x4 grid.To avoid problems with image downloading I make fadeOut - fadeIn effect.

code:

``` javascript
var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
    limit: '12',
    sortBy : 'random',
        resolution: 'standard_resolution',
        clientId: 'ID',     
    template:'<div class="tile"><img class="item" src="http:{{image}}"></div>'
    });

feed.run();

setInterval(function() {
        $( "#instafeed" ).fadeOut( "slow", function() {
        feed.next();
        $( "#instafeed" ).empty();
        feed.run();
        $( "#instafeed" ).fadeIn( "slow")
    });
}, 5000);
```

if someone want to use page like this, here is a CSS:

``` javascript
body {
    height: 100%;
    background-color:#000;
    overflow:hidden;
}

#instafeed {
    width:100%;
    height: 100%;
    -moz-column-count:4;
    -webkit-column-count:4;
    column-count: 4;
    column-gap: 2.5%;
    -moz-column-gap: 2.5%;
    -webkit-column-gap: 2.5%;
}
.tile {
    margin-bottom:10px;
    height: auto;
}

.tile img {
    width:100%;
    max-height: 100%;
    display:block;
}
```

**Comment by LaylinesSteve** [comment]
I am looking to create a scroller that shows one images at a time and changes to a new images every 7 seconds.  I seem to have the same issue where the images goes 1, 1 ,1, 2, ,1,2,3,1,1,1.  In fact it seem that the images load at random.  Here's the code I'm working with `<script>
    var nextt = 1;
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'WeAreMarquette',
        sortBy : 'most-liked',
        limit:'2',
        resolution: 'standard_resolution',
        clientId: 'a164a0f6607c4aca9e0e4dff13937277',  
        after: function() { if (this.hasNext()) {nextt = 1;} else {nextt = 0;} },
        //{{caption}} {{likes}} http:{{image}}
        template:'<div class="tile"><img class="item" src="http:{{image}}"></div>'
    });
    feed.run();
    if (nextt == 1) {
        setInterval(function() {
            $( "#instafeed" ).fadeOut( "slow", function() {
            feed.next();
            $( "#instafeed" ).empty();
            feed.run();
            $( "#instafeed" ).fadeIn( "slow")
            });
        }, 2000);
    } else {
        setInterval(function() {
            $( "#instafeed" ).fadeOut( "slow", function() {
            $( "#instafeed" ).empty();
            alert ("!!!");
            feed.run();
            $( "#instafeed" ).fadeIn( "slow")
            });
        }, 5000);
    }
		</script>`
