### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by roowilliams** [stevenschobert/instafeed.js#147]
Hello,

I have followed the set up instructions and written the request below (replaced userId and accessToken with x's obv), but I am always getting this error: `Uncaught TypeError: Cannot read property 'appendChild' of null`

It's driving me mad, any ideas?

Best

Andrew

```
        <script type="text/javascript">
          var userFeed = new Instafeed({

            get: 'user',
            userId: xxxxx,
            accessToken: 'xxxxx',
            template: '<a href="{{link}}"><img src="{{image}}" /></a>',
            sortBy: 'most-recent',
            limit: 3

          });
          userFeed.run();
        </script>
```

**Comment by wesley-foxtech** [comment]
Boa @stevenschobert, estava com o mesmo problema! E @roowilliams precisamos prestar mais atenção nas documentações. huahuhauhu
