### ISSUE TITLE
Return Images By Filter Used

### ISSUE THREAD

**Issue by andrewteman** [stevenschobert/instafeed.js#150]
Hey Steven,

I am a total hackaround guy, but I have everything working nicely so far.

One thing I'd like to do though, is be able to pull images by tag, but then additionally restrict what is returned, to be only images using certain filters (e.g. 'mayfair' or 'valencia').

So conversationally, I want to find any images (from all users) tagged "donut", that use the filter 'mayfair' or 'valencia'.

What additional parameters would I add in to do this, and where would they be placed?

Thanks!

**Comment by benjamin-hull** [comment]
Closing as complete.
