### ISSUE TITLE
Get time ago ?

### ISSUE THREAD

**Issue by DonDi1989** [stevenschobert/instafeed.js#151]
Is there any option to get time as time ago. I am using image.created_time but is there any other option to get time in time ago format ?

**Comment by dkjoseph** [comment]
I can't seem to get this work correctly.  My code says 45 years ago for all the photos in my feed

**Comment by piperhaywood** [comment]
@dkjoseph I was referring to this issue to get a similar thing going recently and found I needed a slightly different filter using moment.js, thought I'd add what works for me here in case it's useful for anyone else. 

```javascript
var feed = new Instafeed({
  // ... other settings
  filter: function(image) {
    image.create_time_ago = moment.unix(image.created_time).fromNow();
    return true;
  },
  template: '<img src="{{image}}" /> {{model.created_time_ago}}'
});
feed.run();
```
