### ISSUE TITLE
Hello MIN_TIMESTAMP, MAX_TIMESTAMP

### ISSUE THREAD

**Issue by carlyle-v** [stevenschobert/instafeed.js#152]
Do you can help me with options for taking instagram photos in period of time?
How to do it?

**Comment by albertozayas** [comment]
Hello Steven, is there a way I can do this too? Get photos in Central Park NY City (location), #kiss (tag), June 21, 2015, 3:00  to 5:00 pm (time).

Thanks, Alberto Zayas
