### ISSUE TITLE
Pull from multiple specific users

### ISSUE THREAD

**Issue by Danielfsp** [stevenschobert/instafeed.js#155]
Hello!

Thanks for the great code.

I would like to pull images from 2 specific users, with a filter consisting of 2 hashtags.
There is an example with one specific user and one hashtag as filter, but I cannot figure out to do what I'm seeking because of very limited js experience.

Anyone with a solution that might help me? :)

**Comment by benjamin-hull** [comment]
Closing as stale, also not easily viable with the API in its current state.
