### ISSUE TITLE
how to fill userId and accessToken with before method?

### ISSUE THREAD

**Issue by vladimirsbudkins** [stevenschobert/instafeed.js#156]
Hi, Your app is great )
I am not so good at javascript, and i have small problem to insert userId and accessToken.
I'am gettiing this from php with ajax. Here is my code:
var loadButton = document.getElementById('load-more');
    var userFeed = new Instafeed({
        get: 'user',
        userId: //???,
        accessToken: '//???',
        resolution: 'standard_resolution',
        limit: 24,
        before: function() {
            $.ajax({
                type: 'post',
                url: base + lang + "/magnets/access",
                dataType: 'json',
                success: function(data) {
                   var user_id = data.id;
                   //this one i need to insert userId
                   var user_token = data.token;
                   //this one i need to insert accessToken:
                },
            });
        },
        after: function() {
            if (!this.hasNext()) {
                loadButton.setAttribute('disabled', 'disabled');
            }
        },
        template: ''
    });
    loadButton.addEventListener('click', function() {
        userFeed.next();
    });
    userFeed.run();

Thanks!

**Comment by benjamin-hull** [comment]
Closing as stale. For future reference, the `before` callback fires before instafeed.js makes the request, but _after_ the initial configuration. You'd need to fetch your credentials via AJAX, then initialise instafeed.js.
