### ISSUE TITLE
What is the radius of LocationID? Can you target just a city?

### ISSUE THREAD

**Issue by romeroz** [stevenschobert/instafeed.js#157]
When specifying the locationId how specific is instafeed.js? In this Eiffel tower example (https://github.com/stevenschobert/instafeed.js/issues/10) you got a locationId from some lat + long cords and put it in your search. How wide is the radius of search? 

The reason I ask is because what I really want to do is search for images from a specific city. So for example, I want all images from New York City. Is there a clever way to be able to roughly capture the whole city? Keeping in mind that every city has a different size.

I know it must be possible because sites like http://worldc.am/ can do it so I want to be able to do the same thing.

Thanks, and I really enjoy instafeed.js!

**Comment by benjamin-hull** [comment]
Location is no longer available in the current API.
