### ISSUE TITLE
'Like' count doesn't match returned objects

### ISSUE THREAD

**Issue by motleydev** [stevenschobert/instafeed.js#158]
It seems that there is a cap of 4 objects returned when getting the likes on an image. The count of likes  seems to be accurate but the actual returned objects always caps at 4.

**Comment by kromegillian** [comment]
Hi, just checking if anyone managed to return a complete list of users who liked an image?

I'm trying to query post by a hashtag and if it's liked by a specific user.

Appreciate much help!

**Comment by benjamin-hull** [comment]
Closing this as stale, it's no longer support by IG's API anyway.
