### ISSUE TITLE
Remove images with hashtags using the filter option

### ISSUE THREAD

**Issue by zkellerdevelops** [stevenschobert/instafeed.js#159]
I am trying to prevent images with a certain hashtag from being shown.

I am currently successfully using the plugin to show my desired hashtags, but we have a request to make sure some of these photos with a specific additional hashtag are not shown.

  var routeFeed = new Instafeed({
    get: 'tagged',
    tagName: 'TagToShow',
    clientId: 'myID',
    limit: '18',
    resolution: 'low_resolution',
    filter: function(image) {
      return image.tags.indexOf('TagToBlock') >= 0;
    },
    template: 'markup here'
  });

Obviously the filter section of this script doesn't work how I;d like it to.
When i see "filter" I guess in my mind I am thinking "exclude". This script obviously only shows the hashtag I'd like to block.

How can i reverse this so that I don't see the hashtags of the tag I'd like to block?

**Comment by czmarcos** [comment]
How to block when is more than 1 tag name?
