### ISSUE TITLE
Randomise Image Sizes?

### ISSUE THREAD

**Issue by muddie20** [stevenschobert/instafeed.js#163]
Is it possible to show say, 20 images and then have their resolution and in turn their actual size, change randomly but with a maximum of 5 standard size, 10 low res and 5 thumbnail?

**Comment by syrcom** [comment]
Hi,

I need help on this as well, it seems like it won't work from the above advice.

Please see the code below-
https://gist.github.com/anonymous/7f63ba27ea5b278f7936

**Comment by stevenschobert** [comment]
@muddie20 Your example isn't going to work, because you are trying to set the width of an element that, at the time that function runs, won't yet be inserted into the dom.

Did you try the original example I had posted?

**Comment by stevenschobert** [comment]
@syrcom Sorry, but you'll have to help me out and be more specific about what you're having issues with! What exactly have you tried, and what is not working?

**Comment by jupiter01** [comment]
@stevenschobert I tried your code as I was looking to show images in various sizes, however when using it, the images simply dont show up.

**Comment by stevenschobert** [comment]
@jupiter01 Ah, that is my mistake. Make you have a `return true` at the end of the `filter` function. I've updated my original example.

**Comment by jupiter01** [comment]
Thanks for the quick response, images appeared, however seems {{random_size}} is returning null.

**Comment by stevenschobert** [comment]
@jupiter01 Wow, I'm so sorry. I must have been low on sleep when I wrote that. Try `{{model.random_size}}` instead.

**Comment by jupiter01** [comment]
Works, thanks.
