### ISSUE TITLE
Instafeed with Slideshow

### ISSUE THREAD

**Issue by sethhay** [stevenschobert/instafeed.js#168]
Is there a way to add a slideshow to this script? Not looking for a next/prev button but a simple fade in/out per Instagram photo. I looked into the "Cycle2" but was running into issues to get it to function. I'm open to using other slideshow plugins to make it work.

Cycle2:
http://jquery.malsup.com/cycle2/

My files:
https://github.com/sethhay/instafeed-test

**Comment by benjamin-hull** [comment]
Closing as stale - for reference, instafeed.js is 'styling neutral' by design: it doesn't do any visual effects so you are free to add your own with whatever library you like. If you're using jQuery, [Slick slider](https://kenwheeler.github.io/slick/) looks like a solid option.
