### ISSUE TITLE
Template tag doesn't work with IE

### ISSUE THREAD

**Issue by leecollings** [stevenschobert/instafeed.js#169]
I'm trying to use Instafeed with Joomla. But when using

```
template: '<a href="{{link}}"><img src="{{image}}" /></a>'
```

in the code block, there a few strange behaviours that happen:
1. In IE, the images can't be displayed at all, and just display white icons with black Xs
2. The URLs display as `http://mydomain.com/http://instagram.com/...` causing the link to reload the index of my website.

I'm trying to add `target="_blank"` to the links, and saw this as the best way, but it's screwing up the markup.

What can I do to fix?

**Comment by Nikjoom** [comment]
Thank you filipe-torres.
I searched a long time for a solution.
On my website i have more Pictures and i solved this with a 'while':

<script type="text/javascript">
    jQuery(document).ready(function($){
        $(window).on('load',  function() {
			var correktur = 0;
			while(correktur < 11) {
           		var link = $('#instafeed img:eq('+correktur+')');
           		var errorHref = link.attr('src');
           		var correctHref = errorHref.match(/http(.*)/g);
           		link.attr('src',correctHref);
				correktur++;
			}
        });
    });
</script>

Maybe it will be helpfull if somebody have the same porblem :)

**Comment by johndeffme** [comment]
`<script type="text/javascript">
    jQuery(document).ready(function($){
        $(window).on('load',  function() {
            var link = $('#instafeed a');
            var errorHref = link.attr('href');
            var correctHref = errorHref.match(/http(.*)/g);
            link.attr('href',correctHref);
        });
    });
</script>`

![2017-02-01_01-07-58](https://cloud.githubusercontent.com/assets/25468041/22486566/01ae2486-e81b-11e6-9c7d-3479a95995a4.png)

why there is an error?

**Comment by stevenschobert** [comment]
Because `errorHref` is `undefined`, which means you can't call `.match()` on it.

Most likely, this is because you are running your code using `$(window).on()` instead of Instafeed's `after` option. When you do that, your code will run as soon as the document is loaded, and most likely before Instafeed has finished running, so `$("#instagram a.animation")` won't be present in the DOM yet.

Try moving your code to the `after` option:

```js
var feed = new Instafeed({
  // other settings...
  after: function() {
    // put your custom code here
  }
});
```

**Comment by benjamin-hull** [comment]
Think this one is done?
