### ISSUE TITLE
document.getElementById(...) is null

### ISSUE THREAD

**Issue by hrdipto** [stevenschobert/instafeed.js#178]
my html part is 
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="js/modernizr.js"></script>
</head>
<body>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
<div class="photo-box">
<div class="image-wrap">
<div class="likes">300 Likes</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

```
<script type="text/javascript" src="js/bootstrap.js"></script>
<script type="text/javascript" src="js/instafeed.min.js"></script>
<script type="text/javascript" src="js/app.js"></script>
```

</body>

and callback function is
$(function() {

```
//Set up instafeed
var feed = new Instafeed({
    clientId: 'c5c1abe9d5fd4f13baf26c2dbc1bb492',
    target: 'instafeed',
    get: 'tagged',
    tagName: 'photographyportfolio',
    links: true,
    limit: 8,
    sortBy: 'most-recent',
    resolution: 'standard_resolution',
    template: '<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3"><div class="photo-box"><div class="image-wrap"><a href="{{link}}"><img src="{{image}}"></a><div class="likes">{{likes}} Likes</div></div><div class="description">{{caption}}<div class="date">{{model.date}}</div></div></div></div>'
});
feed.run();
```

});
but in firefox its say error 
TypeError: document.getElementById(...) is null
document.getElementById(this.options.target).innerHTML = '';
.... 
in instafeed.min.js

**Comment by ntsasng** [comment]
Same issue.
I have get multiple image instagram, but it not working.

**Comment by kokomomtl** [comment]
Same issue here
