### ISSUE TITLE
Change number of images based on screen width

### ISSUE THREAD

**Issue by sibarad** [stevenschobert/instafeed.js#181]
First great piece of code, thank you. Is there a way, to change the amount of instagram photos depending on screen width? So I might have limit 6 on a smaller screen width than increase that amount to 8 if wider. Thanks.

**Comment by kilinkis** [comment]
I have the same issue

**Comment by kilinkis** [comment]
here is what a did

`var img_qty;
if(window.innerWidth>980){
	img_qty=16;
}else{
	img_qty=4;
}`

and then

`limit: img_qty`

and voilà!

**Comment by benjamin-hull** [comment]
Closing this one - but for future reference, I would handle this with CSS. Request the maximum number of images you want to display, and then hide some of them with media queries (probably using `.feed-image:nth-child(n+6) { display:none;}` or something similar.
