### ISSUE TITLE
Injecting Instafeed.js photos into an Owl Carousel

### ISSUE THREAD

**Issue by njacoy** [stevenschobert/instafeed.js#186]
Question: I am currently trying to build an image carousel (using Owl Carousel) that dynamically pulls in the photos generated from Instafeed.js and am having some trouble syncing these two plugins.

I set up a fiddle here: http://jsfiddle.net/njacoy/zcrwvsuu/embedded/result/

For display purposes, I have separated the carousel and Instagram feed divs so that you can see them both working as individual plugins.

It would make sense to just add "target: 'owl2row-plugin'," so that the photos get injected into my carousel, but this does not work.

Thanks!

**Comment by ohabash** [comment]
Did you ever get this to work?

**Comment by wuno** [comment]
Ya anyone get this to work?
