### ISSUE TITLE
How to get a user's ID?

### ISSUE THREAD

**Issue by marknuyens** [stevenschobert/instafeed.js#188]
First off, thanks for this great plugin.

Question though, from what I understood, users need to authorize my app in order to browse through their feed, right?

I've read Instagram's API documentation, but I still can't figure out how to retrieve a user's ID and accessToken based on the code that I receive through the URL ("?code=1234567890").

Does anyone know how to do this?

P.s. The example given on the plugin's website ("Don't know your user id or token? Click here to get one.") is actually the thing I want.

**Comment by benjamin-hull** [comment]
Closing as stale based on the current API.
