### ISSUE TITLE
Is it possible to get the photos as an array?

### ISSUE THREAD

**Issue by balloonboy** [stevenschobert/instafeed.js#195]
Hey Steven,

I love Instafeed, it's awesome :) I'm messing around with the JavaScript and am wondering whether there's an easy way to add the photos to an array rather than just spitting them out onto the page. I want to do some stuff with the photos before rendering them to the page and so could do with getting them in an array format. I guess I could just wait for the photos to be rendered to the page and then loop through them all to add them to an array, then manipulate them and add them back to the page but that seems inefficient. Is there an easy way to do this?

Thanks in advance for any direction you can provide. Keep up the awesome work!!

John

**Comment by dkjoseph** [comment]
Bring this topic back from the dead :+1:

I would also like to do this. 

Can an example be provided if there's 10 divs already on a page and i only want 7 of the latest images to be placed in specific containers?

**Comment by Seymourthings** [comment]
Hey, @stevenschobert I'm a little confused by the function that puts images into an array. My question is what does the parameter "data" stand for? Also can I still integrate other filters into this function such as "sortBy", "limit", "tagname", etc.?  I'm assuming these filters would have to precede being put into an array.

**Comment by pontusk** [comment]
images is undefined in the global scope, even if I declare it as a variable before calling the function. How do I get the array outside of the feed function?

**Comment by niconoloco** [comment]
Same problem as ^(pontusk)

**Comment by benjamin-hull** [comment]
@pontusk, @NicoChampagne - storing the response data in a context outside of the instafeed setup should definitely do the trick. Something (roughly) like this should do the trick:

```
var images = [],
    feed = new Instafeed({
      mock: true,
      success: function(response){
          images = data.data;
     }
});

console.log(images);
```
