### ISSUE TITLE
Replace value of Location if empty

### ISSUE THREAD

**Issue by raziraz** [stevenschobert/instafeed.js#197]
Hi and thanks for an amazing script.

I just wonder if it's possible to replace the name of the location with a string if image.location is empty?

Played around a bit with the filter but didn't got it to work.

**Comment by markhillard** [comment]
Hey Steven,

I'm trying to do something very similar here so I tried the snippet above exactly as shown and it's causing images to not load. It works fine without that code so I did some digging and found the following error in console:

`TypeError: invalid 'in' operand e` ... instafeed.min.js (line 2, col 5705)

What I'm trying to do is simply hide the HTML element that contains the location name if there is no location set. I've tried a couple hacky things to get this to work properly but I've had no luck.

Either way, I'd like to do this the proper way so any help you could provide would be greatly appreciated.

**Comment by markhillard** [comment]
I was able to get @raziraz 's original request working by writing a function inside the `after` option:

```js
after: function () {
    // cache location name
    var loc = $(".loc-name");
    // display message if location is not set
    loc.each(function () {
        if ($(this).is(':empty')) {
            $(this).text('No Location');
        }
    });
}
```

I set the `loc-name` class to a `<span>` that holds the location name in the `template` option and (for each image) if there is no location set, I'm simply adding a text string.

Inside that `if` statement you could do whatever you want.

P.S. - Instafeed is the bomb.
