### ISSUE TITLE
Feed Not Displaying

### ISSUE THREAD

**Issue by reececropley** [stevenschobert/instafeed.js#199]
I am trying to  use the instafeed to get the users profile feed displayed on the site. The following code works: 

```
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: '2d276c7bc8e940e9a47c4432667c7972',
    });
    feed.run();
</script>
```

This is the code I am using to get the userfeed display:

```
<script type="text/javascript">
    var userFeed = new Instafeed({
        target : 'instagram',
        get: 'user',
        userId: '240494304',
        accessToken: 'cee54e19824f48685b66f699a5b5203c'
    });
    userFeed.run();
</script>
```

However this displays nothing. Now it could be a problem with the access token (i have altered the one in the above code so its not handed out), but I have followed the auth process and thats what was returned.

Is there anything standing out from the code that is wrong? I'm stumped on this.

**Comment by coen-ish** [comment]
I've been strugling with this for a while as well, turns out: userId: shouldn't have quotes:

userId: '240494304',   =   userId: 240494304,

**Comment by ChicerMan** [comment]
if anyone is using liquid...i just found this awesome solutions @stevenschobert ...

basically, put "raw" over the image template code and it works perfectly!

{% raw %}

...lots of liquid code goes here and it doesn't get interpreted...

{% endraw %}
