### ISSUE TITLE
Limit number while using a filter; also date problems?

### ISSUE THREAD

**Issue by jwegner13** [stevenschobert/instafeed.js#201]
First off, the implementation of this is great, so kudos! However, I have searched github for multiple issues regarding my problem and I have tried some of the "fixes". But it's not getting me anywhere.

I am trying to filter and it's not working with limit. Then I started to just work around that and finding that adding filter to a 9 week old photo it doesn't show. So is there some date limit? 

filter: function(image) {
          return image.tags.indexOf('huntingproductguru') >= 0;
        },

Also I am wondering what the "0" is after ">="? 

Thanks in advance for any help with this great tool to utilize instagram.

**Comment by MuTLY** [comment]
Check out this https://github.com/stevenschobert/instafeed.js/issues/244#issuecomment-84038956 and see if that helps you.
