### ISSUE TITLE
Identifying last result

### ISSUE THREAD

**Issue by dham84** [stevenschobert/instafeed.js#203]
Hello,

I'm using your plugin to get the last 6 posts from my account, however because of my column design, which is responsive, I need to add a "last" class to the 6th post fetched. Is there a way I can identify the last post?

I tried to run a function with the "after" command, as well as running the function after the "run", but it seems like by the time it runs, the divs have not been created in the DOM and therefore jQuery doesn't find it to add the class.

This is my constructor:

`var userFeed = new Instafeed({
        get: 'user',
        userId: xxxxxxx,
        accessToken: 'xxxxxxx',
        links: true,
        limit: 6,
        template: '<div class="col_2 instaDiv"><a href="{{link}}"><img src="{{image}}" /><div class="instaLikes">{{likes}}</div></a></div>'
    });
    userFeed.run();`

Thanks a lot in advance, and great plugin!

**Comment by benjamin-hull** [comment]
I'm about to close this one, but for future reference, `after` does indeed run after the elements are inserted into the DOM. This also seems like something that can be handled with a `:nth-child(6n+6)` CSS rule, too.
