### ISSUE TITLE
CORS enabling

### ISSUE THREAD

**Issue by GrigoreG** [stevenschobert/instafeed.js#205]
How can I enable CORS in instafeed? Or how can I send some user credentials? When accessing the page using www.example.com, I get the cross-origin error, but it works fine when accessing example.com!
Edit: This only happens when using instafeed inside an iframe/div (part of a CMS site)! When directly accessing the html page that contains the feed, it perfectly loads the page, with or without www!

**Comment by benjamin-hull** [comment]
Closing this as stale.
