### ISSUE TITLE
Cannot get instafeed to show anything

### ISSUE THREAD

**Issue by SRW46** [stevenschobert/instafeed.js#207]
I feel as though I am an absolute idiot for not being able to get this to work but I can't for the life of me figure out what is going wrong.

My markup is as follows:

```
<div class="photo-container">
<div id="instafeed"></div>
</div>
```

Here is my JS:

```
<script type="text/javascript">
var userFeed = new Instafeed({
clientId: '33a######################76569e',
get: 'user',
userId: 22####892,
accessToken: '2######92.46######.108#######403e8088#####05',
limit: 9,
useHttp: true,
target: 'instafeed',
template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes">&hearts; {{likes}}</div></a>'
});
userFeed.run();
</script>
```

I also have the following line above the script:

```
<script src="js/instafeed.min.js"></script>
```

I checked the JS file in Network via Developer Tools and it was coming up with a 403 forbidden error so I changed the files permissions and that is now fixed, although it still doesn't display the feed!

**Comment by benjamin-hull** [comment]
Closing as stale.
