### ISSUE TITLE
Problem getting tags filter to work 

### ISSUE THREAD

**Issue by MrDesigna** [stevenschobert/instafeed.js#209]
Just a note which may help others out.  When using the image filtering

  filter: function(image) {
    return image.tags.indexOf('thetagname') >= 0;
  }

thetagname must be lower case.  I spent ages trying to figure out why Thetagname was not working

**Comment by rhysburnie** [comment]
Its not up to the developer of this API to teach you how to authorize - read Instagrams API

**Comment by MrDesigna** [comment]
Absolutely agree however its always nice to add pointers to help others out.

**Comment by stevenschobert** [comment]
Thank you for sharing @MrDesigna! Sorry about the confusion over tag names! If it helps, I always do a `console.log(image)` inside my function so I can look at what data the image has. There's also another issue (#21) that covers what data is in the API response.

Also, the access token is only required if you are fetching images from your own account. If you were filtering images fetched from the "popular" tab, you can get by with only a client Id. But you are correct that I did not specify that in the docs!

Again, thanks for the input!

**Comment by thunderkee** [comment]
Hi, I am starting to use instafeed.js to **fetch images of a user with one selected tag**, I tried the sample featured in instafeed page but it didn't work. It worked when I deleted the filter, but I really need to get images of a user with selected tab. Anyone can help? Thank you very much.

Here's my code :

<script type="text/javascript">
        var feed = new Instafeed({
        	get: 'user',
  userId: XX,
  filter: function(image) {
return image.tags.indexOf('vsco') >= 0;
},
  clientId: 'XX',
 accessToken: 'XX',
     
            resolution: 'low_resolution',
            useHttp: 'true',
            sortBy: 'most-liked',
            limit:4,
            template: '<div class="col-md-3"><div class="instagram-card"><a href="{{link}}"><div class="info-top"><img class="instagram-profile-photo" src="{{model.user.profile_picture}}">{{model.user.username}}</div><img class="instagram-post-photo" src="{{image}}" /><div class="info-bottom"><div class="meta text-center"><ul><li class="likes"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> {{likes}}</li><li class="comments"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> {{comments}}</li></ul></div></a></div></div></div>',
               
        });
        feed.run();
    </script>

**Comment by thunderkee** [comment]
Hello, I am a noob trying to fetch image of a user(myself) with selected tag(ex:'vsco'). I tried sample from instafeed.js web, but it didn't work. It worked just when I removed the filter function. What am I doing wrong? 
Here's the code : 
<script type="text/javascript">
        var feed = new Instafeed({
        	get: 'user',
  userId: xxx535466,
  filter: function(image) {
return image.tags.indexOf('vsco') >= 0;
},
  clientId: 'xxx26456d268470b95f3a621df85f4f1',
 accessToken: 'xxx535466.xxxede5.xxx822de6ad94ff6a574dd7882abba85',
            resolution: 'low_resolution',
            useHttp: 'true',
            sortBy: 'most-liked',
            limit:4,
            template: '<div class="col-md-3"><div class="instagram-card"><a href="{{link}}"><div class="info-top"><img class="instagram-profile-photo" src="{{model.user.profile_picture}}">{{model.user.username}}</div><img class="instagram-post-photo" src="{{image}}" /><div class="info-bottom"><div class="meta text-center"><ul><li class="likes"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> {{likes}}</li><li class="comments"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> {{comments}}</li></ul></div></a></div></div></div>',
               
        });
        feed.run();
    </script>
