### ISSUE TITLE
{{model}} ?

### ISSUE THREAD

**Issue by belham** [stevenschobert/instafeed.js#21]
Hey! Is it possible to have a list of all the things one can request from {{model}} (in particular how to request the post date of the image :) )
Thanks!

**Comment by nwsm** [comment]
template: '<a href="{{link}}"><img src="{{image}}" /></a><br>{{model.users_in_photo[0].username}}<br>'

I am trying to access the users tagged in the photo, is something like the above correct? What do I put in the index of the users_in_photo array?
