### ISSUE TITLE
Sort all images automatically after "load more"

### ISSUE THREAD

**Issue by Meissam** [stevenschobert/instafeed.js#214]
Hey Steven

Thanks for Instafeed, its really awesome.  I'm looking for an easy way to fetch specific number of images (for example 60) and sort them by most like.

there is two problems:
1. when feed.run() function called, the maximum number of  images API has sent, is 33, even we set limit to 60.
2. suppose that I set the "limit" to "30" and "sortBy" to "most-liked" and call feed.run() twice. in first fetch, we have 30 images that sorted, in second fetch by "feed.next()", new 30 fetched images append to previous. second group is sorted too. but whole of these 60 images that we have, are not sorted by "most-liked". to make clear in image below for example we set limit to:6 and we need 18 images that sorted by "most-liked"
   ![untitled-1](https://cloud.githubusercontent.com/assets/10414104/5625482/6a57608c-9530-11e4-86b4-52b28cc8c40a.jpg)

how can i do that?! :)
Thanks in advance for any direction you can provide. Keep up the awesome work!!
Sincerely

**Comment by x-raizor** [comment]
Thank you for describing the problem. I have the same question.

**Comment by Meissam** [comment]
@x-raizor 
your welcome, finally due to limitations of Instagram API and Instafeed, I had to sort DOM elements after each load manually, not by instafeed. after each load more, the number of photos increase and this cause to increase time of sorting. this function can be better and can be improved.
here is jquery codes:

$(document).ready(function () {
    var loadButton = document.getElementById('load-more');
    loadButton.addEventListener('click', function () {
        feed.next();
        // after each click on load more, we call sort function
        sortElemetns();
    });

    // feed.run();
    var feed = new Instafeed({
        clientId: '.....',
        accessToken: '....',
        userId: .....,
        get: 'user',
        useHttp: true,
        sortBy: 'most-liked',
        resolution: 'standard_resolution',
        limit: 15,
        filter: function(image) {
            return image.tags.indexOf('tag-name') >= 0;
        },
        template: '<article class="item" data-like="{{likes}}"><img src="{{image}}" /></article>',
        after: function () {
            // disable button if no more results to load
            if (!this.hasNext()) {
                loadButton.setAttribute('disabled', 'disabled');
            }
            // call sort function
            sortElemetns();
        },
    });
    feed.run();


// sort function - this function sort elements by data-like attr (a custom attr).
    function sortElemetns() {
        // get array of elements
        var myArray = $("#instafeed article");
        var arrCount = 0;

        // sort based on timestamp attribute
        myArray.sort(function (a, b) {

            // convert to integers from strings
            a = parseInt($(a).attr("data-like"), 10);
            b = parseInt($(b).attr("data-like"), 10);
            arrCount += 2;
            // compare
            if (a < b) {
                return 1;
            } else if (a > b) {
                return -1;
            } else {
                return 0;
            }
        });

        // put sorted results back on page
        $("#instafeed").append(myArray).show('slow');
    }
});

**Comment by Meissam** [comment]
@x-raizor 
your welcome, finally due to limitations of Instagram API and Instafeed, I had to sort DOM elements after each load manually, not by instafeed. after each load more, the number of photos increase and this cause to increase time of sorting. this function can be better and can be improved.
here is jquery codes:
```
$(document).ready(function () {
       var loadButton = document.getElementById('load-more');
       loadButton.addEventListener('click', function () {
       feed.next();
       // after each click on load more, we call sort function
       sortElemetns();
      });
// feed.run();
var feed = new Instafeed({
clientId: '.....',
accessToken: '....',
userId: .....,
get: 'user',
useHttp: true,
sortBy: 'most-liked',
resolution: 'standard_resolution',
limit: 15,
filter: function(image) {
return image.tags.indexOf('tag-name') >= 0;
},
template: '  ',
after: function () {
// disable button if no more results to load
if (!this.hasNext()) {
loadButton.setAttribute('disabled', 'disabled');
}
// call sort function
sortElemetns();
},
});
feed.run();
// sort function - this function sort elements by data-like attr (a custom attr).
function sortElemetns() {
// get array of elements
var myArray = $("#instafeed article");
var arrCount = 0;
// sort based on timestamp attribute
myArray.sort(function (a, b) {
// convert to integers from strings
a = parseInt($(a).attr("data-like"), 10);
b = parseInt($(b).attr("data-like"), 10);
arrCount += 2;
// compare
if (a < b) {
return 1;
} else if (a > b) {
return -1;
} else {
return 0;
}
});
// put sorted results back on page
$("#instafeed").append(myArray).show('slow');
}
});
```

**Comment by x-raizor** [comment]
@Meissam thank you for the example!

**Comment by zaharbaz** [comment]
I can not get to work, i try to use your example. Photos are loaded, but not sorted.
I do not need a button, I need photos loaded with an interval

I just do not write on the JS, so i am make a mess
Thank U
(it's google translate)

```javascript
$(document).ready(function () {
       // feed.run();
    var feed = new Instafeed({
        clientId: '...',        
        accesToken: '...',
        target: 'instatop',
        get: 'tagged',
        tagName: 'awesome',
        links: true,
        limit: 3,
        sortBy: 'most-liked',
        resolution: 'standard_resolution',
        template: '<div class="block"><a href="{{link}}"><img class="instagram_image" src="{{image}}"></a><img class="userpic" src="{{model.user.profile_picture}}"><div class="likes"><img src="images/like.png" alt="" />{{likes}}</div><div class="username">{{model.user.username}}</div></div>',
        after: function () {
            // call sort function
              sortElemetns();
            },
     });
     feed.run();
     // sort function - this function sort elements by data-like attr (a custom attr).
     function sortElemetns() {
     // get array of elements
      var myArray = $("#instatop article");
      var arrCount = 0;
      // sort based on timestamp attribute
      myArray.sort(function (a, b) {
      // convert to integers from strings
       a = parseInt($(a).attr("data-like"), 10);
      b = parseInt($(b).attr("data-like"), 10);
      arrCount += 2;
     // compare
       if (a < b) {
         return 1;
          } else if (a > b) {
          return -1;
        } else {
         return 0;
       }
      });
      // put sorted results back on page
     $("#instatop").append(myArray).show('slow');
    }
     setInterval(function () {
     feed.next();
    sortElemetns();
  }, 5000);
});
```
