### ISSUE TITLE
Problem with filter function

### ISSUE THREAD

**Issue by farizgkz** [stevenschobert/instafeed.js#215]
first, thank you very much for @stevenschobert , instafeed.js so useful for my web. 

i have a problem with filter function, i try to show image from my instagram with condition like #13 , but not all of my hastag work with this code.

script : 
var favFeed = new Instafeed({ 
target: 'favFeed', //my id div target 
get: 'user',
userId: MY_USER_ID, 
limit:1,
useHttp: true,
filter: function(image) {
return image.tags.indexOf('fooblogger') >= 0;
}
}); 
favFeed.run();

is there something wrong with my code ? or anyone know what is my problem ?

**Comment by stevenschobert** [comment]
Try changing your filter function to:

```js
filter: function(image) {
  return image.tags && image.tags.indexOf('fooblogger') >= 0;
}
```

Sometimes, if you have images that don't have *any* tags, the API sets `tags` to `null`, so you need that extra check before trying to call `indexOf()` on the array.

**Comment by rinzl3r** [comment]
HI Steven! Great script, I set this up with a tag but now I want user and tag. this is my code below but it is returning nothing, what am I doing wrong? Thankyou in advance! 

fake userId here obviously

  <script type="text/javascript">
var feed = new Instafeed({
  target:'instafeed',
  get: 'user',
  userId: 123456,
  limit:50,
  template: '<div class="contentwall"><div class="contentwallimage"><a href="{{link}}" target="_blank"><img src="{{image}}" style="margin-right:20px; border-bottom:5px solid black" width="220px"/></a></div><div class="contentwalltext">{{caption}}</div></div>'
filter: function(image) {
  return image.tags && image.tags.indexOf('stylenoir') >= 0;
}
  }
});
feed.run();
</script>

**Comment by Djules** [comment]
Please do not post raw JavaScript but use the Markdown syntax.

You seem to miss a comma just before the filter property.

**Comment by benjamin-hull** [comment]
Closing as stale based on the current API.

**Comment by steelbridge-io** [comment]
Ben needs a life.. sheeeeesh

**Comment by benjamin-hull** [comment]
@steelbridge-io this is highly therapeutic, mate!
