### ISSUE TITLE
Template Issues

### ISSUE THREAD

**Issue by ehayne** [stevenschobert/instafeed.js#216]
When I try to implement templates, no data seems to be passed into the available tags.

This works fine:

 var feed = new Instafeed({
    get: 'tagged',
        tagName: 'love',
        limit: '3',
        clientId: 'xxxx'
)};

But when I add in a basic template it breaks:
 var feed = new Instafeed({
        get: 'tagged',
        tagName: 'love',
        limit: '3',
        clientId: 'xxxx',
`        template: '<a href="{{link}}"><img src="{{image}}" /></a>'`
)};

When I view the source when I try to add in the template, it comes through as:
`<a href=""><img src=""></a>`

What am I doing wrong?  This doesn't seem to be a case for using useHttp (which I tried) since none of the link is coming through.  I wasn't able to find anyone else with a similar issue.

**Comment by stevenschobert** [comment]
Are you using Jekyll, Drupal, or any other system where `{{ }}` are used for the template syntax? If so, you'll need to either load your Instafeed.js code using a `<script src="">` tag (instead of inline on a page), or set your template string using the built in template system (see #41).

**Comment by ehayne** [comment]
That's it.  I'm using Django - just had to wrap it in the verbatim tag.  Thanks!

**Comment by stevenschobert** [comment]
No problem, glad that helped!
