### ISSUE TITLE
Make a login for users to enter their "ClientId"..

### ISSUE THREAD

**Issue by syrcom** [stevenschobert/instafeed.js#218]
How do i make a login for users to login to see their InstaFeed?

Make a login for them to enter their ClientId and Token?

Please help.

**Comment by stevenschobert** [comment]
Hey @syrcom. Instafeed.js does not provide any sort of logic for handling anything like that. It's just a simple script for quickly pulling some specific images onto a web page.

You may want to search for some server-side solution to handle something like that.
