### ISSUE TITLE
feed not showing in django

### ISSUE THREAD

**Issue by martibosch** [stevenschobert/instafeed.js#219]
First of all, thanks @stevenschobert for this great plugin.

I'm trying to use it in a django application, in the following way:

```
var userFeed = new Instafeed({
        get: 'user',
        userId: 13740*****, 
        accessToken: '13740*****.46*****.90b1f6a020e947038a852950ab6*****',
  limit: 9, 
  resolution: 'low_resolution',
  sortBy: 'most-recent',
    });
userFeed.run();
```

I tried it on http://codepen.io, and it worked. However, I can't get it to work on django. I have an html template "instagram_feed.html"

```
{% load staticfiles %}
<script type="text/javascript" src="{% static "instafeed.min.js" %}></script>
var userFeed = new Instafeed({
        get: 'user',
        userId: 13740*****, 
        accessToken: '13740*****.46*****.90b1f6a020e947038a852950ab6*****',
  limit: 9, 
  resolution: 'low_resolution',
  sortBy: 'most-recent',
    });
userFeed.run();
```
and then index.html

```
{% extends "base.html" %}

{% block social_sdk %}
{% include "facebook_sdk.html" %}
{% include "twitter_sdk.html" %}
{% include "instagram_feed.html" %}
{% endblock %}

{% block main_content %}
...
<div id="instafeed"></div>
...
{% endblock %}
```
where the block social_sdk is just after the <body> tag in base.html. Both facebook_sdk.html and twitter_sdk.html contain JavaScript under a <script> tag and both work.

See http://ec2-54-77-118-44.eu-west-1.compute.amazonaws.com:5000/ for the test page.
Do I do anything wrong, or is there any django setting I should change? Remember that it works on codepen.io.

Thanks

**Comment by stevenschobert** [comment]
@martibosch It looks like you might be loading in that `script` block with all the Instafeed.js code _before_ the `<div id="instafeed">`. This means that Instafeed.js won't be able to see that div when it tries to run, since it isn't yet on the page.

You need to either load that block _after_ the `<div id="instafeed">`, or wrap your Instafeed.js code in something so that it doesn't run until the entire page is loaded.

Let me know if you need further help with doing that.

**Comment by martibosch** [comment]
I struggled a little bit, and it was something as missing the closing dobule quotes:

```
<script type="text/javascript" src="{% static "instafeed.min.js" %}></script>
```
replaced by
```
<script type="text/javascript" src="{% static "instafeed.min.js" %}"></script>
```
Thanks anyway @stevenschobert and sorry for posting the issue.

**Comment by stevenschobert** [comment]
Ah! Didn't even notice that, sorry. Glad you got it worked out.
