### ISSUE TITLE
default padding

### ISSUE THREAD

**Issue by dukeimus** [stevenschobert/instafeed.js#220]
Even I didn't mess with the CSS, there's a bottom padding when images display on the next line. Anybody else have that issue?

**Comment by thewatts** [comment]
@dukeimus -- could it be default padding added by the browser?

**Comment by dukeimus** [comment]
@thewatts -- I tested on Firefox, Chrome and Safari. Attached screenshot. Thanks
      
![screenshot](https://cloud.githubusercontent.com/assets/2184627/5783183/b4394682-9d75-11e4-87f7-6c8069f676e8.png)

**Comment by thewatts** [comment]
@dukeimus what happens if you add:

```
img { padding: 0; margin: 0 }
```

to your css?

**Comment by dukeimus** [comment]
@thewatts -- same result: attached my html page. Thanks

```
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled Document</title>
<script type="text/javascript" src="js/lib/jquery-1.9.1.min.js"></script>

<script type="text/javascript" src="js/instafeed.min.js"></script>
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
		useHttp: 'true',
        tagName: 'passthetag',
		resolution: 'thumbnail',
        clientId: '7b31b568e39e461e82672d8b1d79e6db'
    });
    feed.run();
</script>
<style>
#instafeed img { padding: 0; margin: 0 }
</style>
</head>

<body>

   <div id="instafeed"></div>
</body>
</html>

```

**Comment by thewatts** [comment]
hey @dukeimus --- I downloaded your example.

In order to remove that padding (which is because the line of images of wrapping ) - I had to set a width and height for the wrapping link tags (that surround the images). I also had to float them.

@stevenschobert is much more of a CSS mastermind than myself - perhaps he has a better solution?

```
  #instafeed a img {
    width: 100%;
    padding: 0;
    margin: 0
  }

  #instafeed a {
    float: left;
    padding: 0;
    margin: 0;
    height: 150px;
    width: 150px;
  }
```

**Comment by dukeimus** [comment]
@thewatts thanks for heads up regarding line of images wrapping, I was able to find better solution for it. Thanks!

```
#instafeed img {
vertical-align: middle;
}

```

**Comment by stevenschobert** [comment]
@dukeimus Glad you were able to get it worked out (also thanks @thewatts).
