### ISSUE TITLE
How to query photos from a specific user + specific hashtag

### ISSUE THREAD

**Issue by jeremypbeasley** [stevenschobert/instafeed.js#226]
I'd like to pull photos from a specific @handle but also only photos from @handle with a specific hashtag. This way my client can filter which photos appear and which don't on their site easily without any sort of CMS integration.

Not sure I see how to do this or if it's even possible. Any help would be much appreciated!

**Comment by Djules** [comment]
This is all explained in the Advanced Options section :

__Example Filter (get username + tagged):__

```js
var feed = new Instafeed({
  get: 'user',
  userId: USER_ID,
  filter: function(image) {
    return image.tags.indexOf('TAG_NAME') >= 0;
  }
});
feed.run();
```
Replace TAG_NAME with your specific hashtag.

**Comment by FlashJunior** [comment]
@djules THX!
