### ISSUE TITLE
Two hashtags

### ISSUE THREAD

**Issue by edonbajrami** [stevenschobert/instafeed.js#227]
Hi, is there any option to get latest images at the same time from two different hasthags ? Example we have #hashtag1 and #hashtag2 and need to add latest images from this two hashtags. How can i do that?  :)

**Comment by alexjustesen** [comment]
+1 would be a nice feature if it already doesn't exist.

**Comment by stevenschobert** [comment]
It's not super convenient, but you can create multiple feeds on the same page, see #12.

Hope that helps!
