### ISSUE TITLE
Getting images with hashtags seems to only work for recent images

### ISSUE THREAD

**Issue by MrDesigna** [stevenschobert/instafeed.js#229]
For some reason I only get two images with this however there are definitely more that have been hashtagged.  The only thing I can think is that images older than a certain age are not reviewed.  Can you help with this?

var feed = new Instafeed({
  get: 'user',
  userId: ********_,
  accessToken: '**_**************',
  limit: '4',
  template: '<a class="imagebutton" href="{{link}}" target="_blank"> Image code in here</a>',
  filter: function(image) {
    return image.tags && image.tags.indexOf('thetagname') >= 0; 
  }
});
feed.run();
</script>

**Comment by Djules** [comment]
Assuming you have only 2 images with your specific hashtags within the 4 loaded. Try to increase the limit option to get more images with the hashtag.

**Comment by MrDesigna** [comment]
Cheers that kind of makes sense however I thought this command would only return the first four images that had the hashtag 'thetagname' rather than return the first four images and if some happened to have that hash tag in then great you get some images if not then bad luck!  So if I expand to say 100 then I may get four but I might get thirty!  How do I then limit the display to four if I have 30!

**Comment by Djules** [comment]
If you look at the source code you will see that the limit is applied just before the call of the filter function, it may has been right after.

Anyway, you can use the following trick to limit the result and achieve what you want :

```javascript
var limit = 4, // set here the number of images you want to display
    count = 0;
var feed = new Instafeed({
    get: 'user',
    userId: ******,
    accessToken: '**************',
    limit: 50, // or even more
    template: ' Image code in here',
    filter: function(image) {
        count++;
        return count <= limit && image.tags && image.tags.indexOf('thetagname') >= 0;
    }
});
feed.run();
```

**Comment by MrDesigna** [comment]
I appreciate your comments thank you.  I will give it a go.
