### ISSUE TITLE
limit:60 not working

### ISSUE THREAD

**Issue by ankeetguha88** [stevenschobert/instafeed.js#23]
Hey!

So regardless of what number I put over 33, it always returns only 33 images. The user account has 143 images currently. I've added the JS part of it hiding the ID and token.

``` js
var userFeed = new Instafeed({
    get: 'user',
    userId: ID,
    accessToken: 'token',
    resolution: 'low_resolution',
    limit: 60,
    sortBy: 'most-recent',
    template: '<div><img src="{{image}}" /><span class="caption">{{caption}}</span><span class="likes">{{likes}}<i class="icon-heart"></i></span></div>'
});
userFeed.run();
```

Thanks for the help!

**Comment by d4nyll** [comment]
For anyone with the same issue, and for whom the `-1` hack didn't work. I have written a [short script](https://github.com/d4nyll/infinstagram) that provides a hack for this limit, but of course in exchange for more API calls.

**Comment by d4nyll** [comment]
Regarding the above, the API is now much cleaner, and can filter and fetch by tags.

**Comment by gdubb921** [comment]
@d4nyll would you be able to show me how to fetch by tags and not limited to user? i tried the setting shown in the documentation but that yielded zero images:

<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: 'YOUR_CLIENT_ID'
    });
    feed.run();
</script>

i'm fairly new to all this so could be missing something obvious. any help is appreciated, thanks!

**Comment by FranciscoG** [comment]
I can only ever get a max of 20 images no matter how big a number I put

**Comment by tstizzle** [comment]
my understanding is that instagram limits sandbox users to the most recent 20 posts, no more.  starting in june you have to be approved as an "app" to get out of sandbox, where you can then specify scope.

**Comment by iset2012** [comment]
Hi there,
Like @FranciscoG I'v tried to submit my "app" and this is what I get : 
I want to display my Instagram posts on my website. >>"You do not need to submit for review for this use case [...]By using a client in sandbox mode, you can still access the last 20 media[...]"
I don't understand : instagram don't allow me to submit my app, so how can I get out of sandbox mode ??

**Comment by tstizzle** [comment]
you don't have to be out of sandbox mode if all you want to do is display your 20 most-recent posts.  leave your "app" in sandbox mode, don't specify scope, and you will be able to display your 20 most-recent.

**Comment by iset2012** [comment]
but what I have to do if I want to display more then 20 posts ? in fact I want to display ALL my posts not only the last 20 !

**Comment by tstizzle** [comment]
you can't, as far as i know. instagram requires you submit as an app to display more than 20, and they're not approving your usage type.  not unless by displaying your posts you gave created a new user experience which is greater than just your website (aka an app or branding experience).

if it's just to display posts solely on your website, all you get is 20.  period.
