### ISSUE TITLE
Sort and limit multiple instances within same div

### ISSUE THREAD

**Issue by kylesimmonds** [stevenschobert/instafeed.js#230]
I'm running two instances of Instafeed on a site to pull in images from a specific user, and tagged images from anyone. If I place both instances within the same div, is it possible to sort and limit the combined photos by time?

My goal is to show only three items total (from either feed) and sort them by the latest.

````
instagramUser = new Instafeed {
      target: 'instagram-feed',
      limit: '3',
      get: 'user',
      userId: id,
      accessToken: '###'
    }

    instagramTag = new Instafeed {
      target: 'instagram-feed',
      get: 'tagged',
      tagName: 'tag',
      limit: 3
      clientId: '###'
    }

    instagramUser.run()
    instagramTag.run()
````

**Comment by stevenschobert** [comment]
Currently, no. Each feed can only operate on it's own element.

You might be able to use the `after` callback to manually sort and and control your images through. This is just pseudo-code, but hopefully gives you a rough idea to get started:

```html
<div id="instafeed-combined">
  <div id="instafeed-1"></div>
  <div id="instafeed-2"></div>
</div>
```

```js
var resortImages = function resortImages() {
  // manually sort through all images in #instafeed-combined's divs
};

var feed1 = new Instafeed({
  // options...
  after: function() {
    resortImages();
  }
});
var feed2 = new Instafeed({
  // options...
  after: function() {
    resortImages();
  }
});

feed1.run();
feed2.run();
```

Hope it helps!

**Comment by kylesimmonds** [comment]
I like the direction your example is pointing, but the key part is integrating both feeds within a final div. So while you could have:

    <div id="instafeed-combined">
      <div id="instafeed-1"></div>
      <div id="instafeed-2"></div>
    </div>

My goal was to have:

    <div id="instafeed-combined">
      <img id="instafeed-1-image-1" src="" />
      <img id="instafeed-2-image-1" src="" />
      <img id="instafeed-1-image-2" src="" />
    </div>

I ended up just using one feed without the tagged photos. I saw in your options the `mock` and `success` options, which could probably be used to pass each image from each feed to an array, which would then be sorted by date. That's something I would like to revisit, but was limited by time.
