### ISSUE TITLE
Multiple hashtags

### ISSUE THREAD

**Issue by daniyalov** [stevenschobert/instafeed.js#234]
A great script! How to use multiple hashtags in one feed?

**Comment by rhysburnie** [comment]
Use regular expressions in filter:

simple: "tagone" or "tagtwo" `/tagone|tagtwo/gi`

```
filter: function()
    {
       // get array of matches or an empty array if it fails
       var match = image.tags.join(',').match(/tagone|tagtwo/gi) || [];

        if(match.length) {
           return true;
        }
        return false;
    }
```

Also works for plurals, say I want "plan", "plants", "cat", "cats"

`/plant[s]{0,1}|cat[s]{0,1}/gi`

/plants[s]*/ would work but would also get plantsssss but maybe you'd like that.

**Comment by stevenschobert** [comment]
Hey @daniyalov. It's not the most convenient, but you can run two instances of Instafeed.js on the same page. See #12.
