### ISSUE TITLE
Please could we have a tiny bit of instruction on how to get a locationid

### ISSUE THREAD

**Issue by mkstix6** [stevenschobert/instafeed.js#235]
I'm a bit stuck on how to get the locationID feature working as i don't know how to get a valid location ID.

I've found some things in the instagram developer section about location endpoints but I don't really know if that's the right thing.

Not expecting a step by step breakdown at this point but a couple of sentences about where to start would be helpful for a person of my skill level.

**Comment by stevenschobert** [comment]
Hey @mkstix6. Sorry for lack of support there, that's my fault. Fetching images by location is one of the least-documented parts of the library.

Check #10 for a bit more detail on how to find an ID. If you have any other questions feel free to comment back on that thread.

**Comment by mkstix6** [comment]
Thanks Steven. Sorry for the late reply.

**Comment by Praburajendran** [comment]
Hi Steven,

@stevenschobert I can able to get data from userId, but not with tagged and using locationId also. 
This call is going in the network, but not returning proper values.

https://api.instagram.com/v1/locations/1494866470783660/media/recent?access_token=xxx&callback=instafeedCachebae37999dfa1fcc6.parse

 it is returning empty data.

**Comment by stevenschobert** [comment]
@Praburajendran I don't think the Instagram API supports fetching data for locations, see [this section of the README](https://github.com/stevenschobert/instafeed.js#warning-important-instagram-is-changing-the-api-that-instafeedjs-depends-on).
