### ISSUE TITLE
instafeed not displaying anything

### ISSUE THREAD

**Issue by lschneiderman** [stevenschobert/instafeed.js#236]
I'm getting no results on my instafeed.js page, however, the instagram api is returning images. Can anyone tell me what I'm doing wrong? There are no console errors.

html:
   &lt;div id="instafeed"></div>

jquery:

```
$(function() {

//Set up instafeed
var feed = new Instafeed({
    clientId: '2b3f8303808e4dd6bbba72023c7c5d65',
    target: 'instafeed',
    get: 'tagged',
    tagName: 'testlaura', 
    links: true,
    limit: 8,
    sortBy: 'most-recent',
    resolution: 'standard_resolution',
    filter: function(image) {
        return image.user_has_liked;
    },
    template: '<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3"><div class="photo-box"><div class="image-wrap"><a href="{{link}}"><img src="{{image}}"></a><div class="likes">{{likes}} Likes</div></div><div class="description">{{caption}}<div class="date">{{model.date}}</div></div></div></div>'
});
feed.run();
```

});
"lauratest" is the tag I used on some photos on a different account.

**Comment by stevenschobert** [comment]
Hey @lschneiderman! If you don't mind me asking, why are you checking `image.user_has_liked` in your filter function? It's possible that might not be doing what you originally intended for it to do.

Most likely, that is filtering out every single image from your feed, which would be why you don't see any results?

**Comment by lschneiderman** [comment]
Hi, Steven,

Thanks for responding!

I want to just display the images that users submit to a hashtag that *we*
liked.

Best,
Laura

Laura Malt Schneiderman
Web Content Producer
Pittsburgh Post-Gazette
post-gazette.com
412.263.1923

**Comment by stevenschobert** [comment]
Ah, I see. In that case, you may want to try filtering based on the `likes.data` array. That array will contain an object for each like the image has received. You could then check the `username` property of each object to see if your account liked it.

The `user_has_liked` would require an `accessToken` to be accurate, since that is what tells the API what the current user is.

**Comment by lschneiderman** [comment]
Thank you!

Laura Malt Schneiderman
Web Content Producer
Pittsburgh Post-Gazette
post-gazette.com
412.263.1923

**Comment by benjamin-hull** [comment]
Closing as complete.
