### ISSUE TITLE
Get caption without tags or filter tags

### ISSUE THREAD

**Issue by bramvanoost** [stevenschobert/instafeed.js#240]
Hi,

Been looking for this for a while now - is there any way to call for the caption without tags, or filter them out afterwards? object.tags gives only the tags, but there seems to be no way to get the reverse?

Thanks for your help! Loving the script.

**Comment by stevenschobert** [comment]
Hey @bramvanoost!

Since Instafeed.js doesn't decorate Instagram's API data, I'm afraid that'll be something you have to do custom. A few folks have used the `filter` option to change/add API data before it gets printed on the page, so you might be able to do something like this:

```js
var feed = new Instafeed({
  // other options...
  filter: function(image) {
    var newCaption = [];
    var captionParts;

    if (image.caption && image.caption.text && image.caption.text.length > 0) {
      captionParts = image.caption.text.split(' ');
      for (var i=0; i < captionParts.length ; i++) {
        if (captionsParts[i].charAt(0) !== '#') {
          newCaption.push(captionParts[i]);
        }
      }
    }

    image.caption_without_tags = newCaption.join(' ');

    return true; // so we don't exclude any images
  }
});

**Comment by bramvanoost** [comment]
Hey @stevenschobert!

Thanks a lot for your reply. Took me a while to get to it.

I'm getting this error, and am not at the level of bugfixing it :-)
```
ReferenceError: captionsParts is not defined
	if (captionsParts[i].charAt(0) !== '#') {
```

Any suggestions?
I'm guessing this is causing the problem: ```captionParts = image.caption.text.split(' ');```

**Comment by stevenschobert** [comment]
@bramvanoost Sorry, typo in my example. It should be `captionParts`, not `captionsParts` (extra `s`). Updated my example with the correction.

**Comment by bramvanoost** [comment]
@stevenschobert thanks for the update!
It's not filtering anything yet, maybe/probably I'm doing something wrong with filtering twice.
```
filter: function(image) {
	 
		var date = new Date(image.created_time*1000);
		 
		m = date.getMonth();
		d = date.getDate();
		y = date.getFullYear();
		 
		var month_names = new Array ( );
		month_names[month_names.length] = "Jan";
		month_names[month_names.length] = "Feb";
		month_names[month_names.length] = "Mar";
		month_names[month_names.length] = "Apr";
		month_names[month_names.length] = "May";
		month_names[month_names.length] = "Jun";
		month_names[month_names.length] = "Jul";
		month_names[month_names.length] = "Aug";
		month_names[month_names.length] = "Sep";
		month_names[month_names.length] = "Oct";
		month_names[month_names.length] = "Nov";
		month_names[month_names.length] = "Dec";
		 
		var thetime = month_names[m] + ' ' + d + ' ' + y;
		 
		image.created_time = thetime;
		
		var newCaption = [];
	    var captionParts;
	
	    if (image.caption && image.caption.text && image.caption.text.length > 0) {
	      captionParts = image.caption.text.split(' ');
	      for (var i=0; i < captionParts.length ; i++) {
	        if (captionParts[i].charAt(0) !== '#') {
	          newCaption.push(captionParts[i]);
	        }
	      }
	    }
	    
	    image.caption_without_tags = newCaption.join(' ');  
		
		return true;
	}
```

**Comment by stevenschobert** [comment]
@bramvanoost Oh sorry, maybe I misunderstood. I thought you were trying to just display captions without the tags in them. Were you trying to filter them instead?

**Comment by bramvanoost** [comment]
@stevenschobert  Isn't it the same thing, since you also use filter?

I change some values of the date to show the month in Jan, Feb in stead of just timestamp.
So I tried to combine the two filters (date and yours) into the same filter function.

**Comment by bramvanoost** [comment]
@stevenschobert but to get back to this - yes, I'm trying to filter the hashtags out, in combination with the date formatting (see code snippet). Have a great weekend!

**Comment by horcris** [comment]
@stevenschobert sorry for disturbing, can i ask where i should put the script? inside instafeed.js or under the js template segment?

**Comment by horcris** [comment]
i'm a beginnner!
