### ISSUE TITLE
Option 'accessToken' is not needed when getting user feed

### ISSUE THREAD

**Issue by samisiuvatti** [stevenschobert/instafeed.js#242]
Instagram user's recent feed can be fetched without accessToken if clientId is provided, but your script throws an error if accessToken is not provided. I commented rows 225-227 and it works perfectly ( https://github.com/stevenschobert/instafeed.js/blob/master/instafeed.js ).

https://api.instagram.com/v1/users/{user-id}/media/recent/?client_id=YOUR-CLIENT_ID

**Comment by 303Michael** [comment]
This worked for me also.

**Comment by knauso** [comment]
I tried commenting those lines, but still get the same error. ANy help?

**Comment by juhamust** [comment]
@knauso I've created a fork and branch that has both AMD support added and accessToken check disabled, maybe it is helpful for you too? https://github.com/SC5/instafeed.js/tree/amd-access

**Comment by knauso** [comment]
Great! So i can just grab the minimized js file and everything will work?

On Wednesday, June 3, 2015, Juha Mustonen <notifications@github.com> wrote:

> @knauso <https://github.com/knauso> I've created a fork and branch that
> has both AMD support added and accessToken check disabled, maybe it is
> helpful for you too? https://github.com/SC5/instafeed.js/tree/amd-access
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenschobert/instafeed.js/issues/242#issuecomment-108545858>
> .
>


-- 
Ognjen Knaus
Skype: KnausO
Gtalk: ognjenknaus@gmail.com

-----------------------------------
This e-mail is confidential and may also contain privileged information. If
you are not the intended recipient, you are not authorized to read, print,
save, process or disclose this message. If you have received this message
by mistake, please inform the sender immediately and delete this e-mail,
its attachments and any copies. Thank you!

**Comment by juhamust** [comment]
Well, it did work for me :) In a case it doesn't, maybe we're initializing it differently.

**Comment by knauso** [comment]
Thanks! Will try it in the morning :)

On Wednesday, June 3, 2015, Juha Mustonen <notifications@github.com> wrote:

> Well, it did work for me :) In a case it doesn't, maybe we're initializing
> it differently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenschobert/instafeed.js/issues/242#issuecomment-108580285>
> .
>


-- 
Ognjen Knaus
Skype: KnausO
Gtalk: ognjenknaus@gmail.com

-----------------------------------
This e-mail is confidential and may also contain privileged information. If
you are not the intended recipient, you are not authorized to read, print,
save, process or disclose this message. If you have received this message
by mistake, please inform the sender immediately and delete this e-mail,
its attachments and any copies. Thank you!

**Comment by knauso** [comment]
It is still giving me Unexpected token

I am initializing it like this, actually if I understand well, accessToken can be removed, but not working with or without it :

<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: '52861203',
        accessToken: '7d93cc0.e101f4afc37a4ea1af9f7cd663ee5807'
    });
    userFeed.run();

**Comment by samisiuvatti** [comment]
You would still need clientId, if you removed accessToken

**Comment by knauso** [comment]
Yes, I left the userID

**Comment by samisiuvatti** [comment]
Not userID but clientID. It's a different thing.

**Comment by knauso** [comment]
So is this the proper setting?
Can get it to work.
```
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        clientId: '7d93cc0de3b7417497923c1fdb5a7cfe'
    });
    userFeed.run();
```
I am using this js:
 https://raw.githubusercontent.com/SC5/instafeed.js/amd-access/instafeed.min.js

**Comment by juhamust** [comment]
@knauso You need _both_ userId and clientId:

```javascript
var userFeed = new Instafeed({
  get: 'user',
  // Instagram user id you want to list images from
  userId: 1549781111, 
  // Your client id registered in Instagram developer site
  clientId: '2e5a3f8cc1754723a81d216f3d302a69'
});
```

**Comment by knauso** [comment]
Working! :)

thanks so much for the help. really appreciate it, you are da man!

**Comment by julesfromparis** [comment]
Hi, 
Don't work for me on my local serveur mamp... is't normal ? 

    var userFeed = new Instafeed({
        get: 'user',
        userId: 1030277,
        clientId:'323195e2be5432dfb9103d13fe5a0281',
        resolution: 'standard_resolution', 
        limit:'6',
        template: '<li class="instagram__item"><a target="_blank" href="{{link}}"><img class="instagram__image" alt="Instagram Image" src="{{image}}"/></a></li>'
    });
    userFeed.run();

**Comment by julesfromparis** [comment]
It's ok :+1: 
Thanks for this great module

**Comment by wleofeng** [comment]
@samisiuvatti Hi, does this still work as of now? Doing this returns page Not Found for me:  https://api.instagram.com/v1/users/{user-id}/media/recent/?client_id=YOUR-CLIENT_ID

**Comment by samisiuvatti** [comment]
@wleofeng Yes it should still work. That url is not supposed to work as it's just Instagram's API endpoint. You may get acquainted to that part of API here: https://www.instagram.com/developer/endpoints/users/#get_users_media_recent

**Comment by samisiuvatti** [comment]
@wleofeng This seems to be fixed in the new releases.

**Comment by fabioguina** [comment]
@juhamust Hi! I've been using your version of this plugin(without acess token) for some time. 
But now it stoped working. Any idea why?

**Comment by juhamust** [comment]
@fabioguina based on quick look into Instagram API documentation, they've introduced a new review policy that might have something to do with it. https://www.instagram.com/developer/endpoints/

> Any app created before Nov 17, 2015 will continue to function until June 1, 2016. On that date, the app will automatically be moved to Sandbox Mode if it wasn't approved through the review process. The previous version of our documentation is still available here.

Also, the API might have changed itself.

**Comment by fabioguina** [comment]
@juhamust Thanks for the reply. 
The documentation says that no longer support making requests using just the client_id.  I was afraid that was something like that. Looks like i'm gonna have to use the official version of the plugin. 
I appreciate your help.

**Comment by georgeu2000** [comment]
> @samisiuvatti Hi, does this still work as of now? Doing this returns page Not Found for me: https://api.instagram.com/v1/users/{user-id}/media/recent/?client_id=YOUR-CLIENT_ID

This returned 400 for me:

> The access_token provided is invalid.

 According to the docs, it requires an Access Token.
