### ISSUE TITLE
Image filter seems to not work properly

### ISSUE THREAD

**Issue by axelferdinand** [stevenschobert/instafeed.js#243]
Hello, and thank you for an amazing script - I've been using it for a while and I'm impressed over how it's so easy to use...!

I have one issue that I can't figure out - I'm trying to display images from a specific user and a specific tag at the same time. I've been reading the documentation, but the code doesn't seem to work. The code I'm using is displaying all the images from the specific user, but the code is ignoring the image filter.

Please have a look at the following code (I have hidden the userId, clientId and the accessToken) - do you have any idea why the script is ignoring the image filter?

```
var feed = new Instafeed({
        get: 'user',
        userId: HIDDEN,
        clientId: 'HIDDEN',
        accessToken: 'HIDDEN',
        template: '<div class="instafeed__item"><img src="{{image}}" alt="{{caption}}" class="instafeed__item__img" /><a href="{{link}}" target="_blank" class="instafeed__item__link">Gå til Instagram</a></div>',
        limit: '10',
        resolution: 'standard_resolution',
        filter: function(image) {
            return image.tags.indexOf('interiør') >= 0;
        }
    });
    feed.run();
```

**Comment by esmic** [comment]
i have this problem also

**Comment by stevenschobert** [comment]
@axelferdinand What result are you seeing? Are you seeing 0 images, or all the images? Are you experiencing any errors?

**Comment by userofit123** [comment]
i also have this problem, the filter seems to be doing nothing, and all of the images are being shown regardless of what i put in the filter, any fix for this?
