### ISSUE TITLE
Limit and Filter issue

### ISSUE THREAD

**Issue by farizgkz** [stevenschobert/instafeed.js#244]
another question for this good work :) 

i want show 1 picture from my instagram, where the picture have hastag #yeahkulineroftheweek.
and i have 2 picture with hastag #yeahkulineroftheweek on my feed, those picture is fourth and fifth in my instagram feed.

then i use filter #yeahkulineroftheweek to show that image in my web and also set the limit with 3, the picture won't show up. But if i set the limit with 6, 2 pictures show up.

anyone can give me a solution ? i want show 1 picture from all my feed, where that picture have a specific hastag.

``` javascript
var userFeed = new Instafeed({      
        //ngambil foto dengan hastag tertentu di user tertentu
        target:'instaweek',
        get: 'user',
        userId: *******, 
        limit:4,
        useHttp: true,
        resolution: 'standard_resolution',
        accessToken: '*******************',
        filter: function(image) {
          return  image.tags && image.tags.indexOf('yeahkulineroftheweek') >= 0;
        },
        template: ' <div class="col-md-3 portfolio-item" > <a href="{{link}}"> <img class="img-responsive" src="{{image}}" alt=""> </a> </div>'

    });
    userFeed.run();
```

**Comment by stevenschobert** [comment]
Hey @farizgkz! The reason behind what you're running into, is that the `filter` option always gets applied *after* the `limit` option.

To get around that, set the `limit` option to a higher value, and just filter out any images after the first match:

```js
var matches = 0;
var userFeed = new Instafeed({      
  //ngambil foto dengan hastag tertentu di user tertentu
  target:'instaweek',
  get: 'user',
  userId: *******, 
  limit:4,
  useHttp: true,
  resolution: 'standard_resolution',
  accessToken: '*******************',
  filter: function(image) {
    if (matches < 1 && image.tags && image.tags.indexOf('yeahkulineroftheweek') >= 0) {
      matches += 1;
      return true;
    }

    return false;
  },
  template: ' <div class="col-md-3 portfolio-item" > <a href="{{link}}"> <img class="img-responsive" src="{{image}}" alt=""> </a> </div>'

});
userFeed.run();
```

**Comment by farizgkz** [comment]
it's work !! thank you @stevenschobert . i'll update my website soon, check this out http://kuliner.borizs.com

**Comment by crisgaret** [comment]
I was looking for a conditional like this to only display the latest photo from a specific user with a specific tag. This code does not work for me @stevenschobert, the console says "matches is not defined". This is the code I am working with: (Thank you very much for your assistance)

```javascript
var feed = new Instafeed({
          get: 'user',
          userId: ********,
          accessToken: '********************************',
          limit: 2,
          sortby: 'most-recent',
          resolution: 'standard_resolution',
          filter: function(image) {
            if (matches < 1 && image.tags && image.tags.indexOf('rethinkcomfort') >= 0) {
              return true;
            }
            return false;
          },
          template: '<a href="{{link}}" target="_blank"><img class="insta-image" src="{{image}}" /></a>',
        });
        feed.run();
```
