### ISSUE TITLE
Instafeed with owlcarousel

### ISSUE THREAD

**Issue by caseyrlentz** [stevenschobert/instafeed.js#247]
Are you able to use instafeed.js with owlcarousel ? Should I just use the "after:" settings to run owl carousel ?

**Comment by stevenschobert** [comment]
I'm not super familiar with that library, but I don't see any reason it would not work. And yes, you are correct, use the `after` function to create the carousel, that way you can be certain all the images have loaded before the carousel is started.

**Comment by ohabash** [comment]
What do you guys mean by after function?
