### ISSUE TITLE
'No user specified. Use the userId option' error, even though specifying userId. 

### ISSUE THREAD

**Issue by SiPiggles** [stevenschobert/instafeed.js#251]
Having some issues implementing Instafeed for a user feed.
Managed to initialise fine just pulling in tagged images, however now I'll always get the error
`Uncaught Error: No user specified. Use the 'userId' option.` in the console no matter how I initialise the script.
I'm currently using the following to initialise
```javascript
var feed = new Instafeed({
        get: 'user',
        clientId: '11c9fd1fe43f4098a288f87df941675c',
        accessToken: 'oAuth code generated from IG',
        userId: 'simonpiggles'
    });
    feed.run();
```

I'm probably missing something really stupid, but any help on this would be excellent.

**Comment by bryan-snyder** [comment]
yes


you want your code to look like so… you have to use the Access Token AND client ID to grab the User’s feed… this is explained in the instafeed readme but… took me a second to get it too… you have to get those tokens from IG.


    var feed = new Instafeed({
        get: 'user',
        userId: USER ID FROM IG,
	accessToken: ‘ACCESS TOKEN FROM IG‘,
        clientId: ‘CLIENT ID FROM IG‘,
      	template: '<a class="instagram-feed" href="{{link}}"><img src="{{image}}" /></a>',
      	limit: 14,
        sortBy: 'most-recent',
    });
  feed.run();




good luck!
B

**Comment by SiPiggles** [comment]
Thank you.
It's a shame I'm now getting ILLEGAL token returned...

**Comment by bryan-snyder** [comment]
You're learning; no shame in that.

**Comment by SiPiggles** [comment]
Yeah, I really can't work out why im getting `Uncaught SyntaxError: Unexpected token ILLEGAL`

I've gone through all the steps to getting an authorisation token from IG.

**Comment by bryan-snyder** [comment]
I can help you with this later today.  Got a URL for me to look at?

**Comment by SiPiggles** [comment]
Unfortunately not, it's all on localhost.

This is what im using though

```
var feed = new Instafeed({
        get: 'user',
        userId: 373131622,
		accessToken: ‘token-generated-from-curl-request‘,
        clientId: ‘11c9fd1fe43f4098a288f87df941675c‘,
      	template: '<a class="instagram-feed" href="{{link}}"><img src="{{image}}" /></a>',
      	limit: 14,
        sortBy: 'most-recent',
    });
  feed.run();
```

**Comment by lksmartins** [comment]
All you gotta do is to parseInt the userId.
Here is how I'm using:


    var u_id = parseInt('your-user-id');
    var token = 'your-token;

    var feed = new Instafeed({
	    get: 'user',
	    userId: u_id,
	    accessToken: token
    });
    feed.run();

**Comment by tiafaupurcell** [comment]
I'm having the same issues as @SiPiggles.

**Comment by ry167** [comment]
I had this problem too but fixed it. The `userId` must be an integer, so you can use `parseInt()` as @lksmartins suggested or just not have quotes around your `userId` field.

Also, @SiPiggles the reason you got an `Unexpected token ILLEGAL` Syntax Error was you were using something other than ' as quotes around your `accessToken` and `clientId`, fix this and it works

**Comment by stevenschobert** [comment]
Hey folks! As of [v1.4](https://github.com/stevenschobert/instafeed.js/releases/tag/v1.4.0), Instafeed.js no longer complains when you're using strings for the `userId` option.

Also, you aren't required to use an `accessToken` any more :)
