### ISSUE TITLE
Actually write HTML?

### ISSUE THREAD

**Issue by steelcowboy** [stevenschobert/instafeed.js#252]
I am trying to make a slider of my instagram images using the Materialize framework. Basically the template for this slider is:
```
<div class="slider">
   <ul class = "slides">
      <li><img src="img.png"></li>
      ...
   </ul>
</div>
```
What I naturally did is changed the target to "feed", added an id of "feed" to my ul, and add a template of `<li><img src="{{image}}"></li>`. However, this doesn't work: when I view source it just shows the ul is empty. Upon doing an inspect element, it shows the images have been loaded (and it actually shows the html), so I'm not sure what's going on. You can see the page at https://steelcowboy.me/photos.php

Btw, using the default options and just having the images be vomited onto my page works fine. 

Any suggestions? Thanks!

**Comment by MuTLY** [comment]
.slider .slides li {
        opacity: 0;
        ...
    }

It's probably something related to your slider script, not instafeed.js. The reason your images don't show on screen is because of the opacity property on the slider.css. Change that to 1 and you'll see your images.

**Comment by MuTLY** [comment]
On a side note, you're putting a lot of <script>s tags all around your HTML. Best practice is to put all of the scripts just above the </body> tag and make sure they're loaded in the correct order, unless stated otherwise by the creator of the script.

Check the source code of http://www.iguatemiportoalegre.com.br/frozen for a quick example, there I load jQuery, then all of the jQuery plugins needed (I put them all on a single file), and then the rest of my scripts on the default.js script.

**Comment by steelcowboy** [comment]
Thanks for the tips! The opacity did the trick to display *an* image, but it doesn't initialize the slider still... console shows no errors, I believe I used the "after" directive correctly, so I'm still not sure what's wrong. Any suggestions?

**Comment by steelcowboy** [comment]
Just for fun, I tried running the jQuery script for the slider 
```
$(document).ready(function(){
                        $('.slider').slider({full_width: true});
                    });
```
In the console, and lo and behold it worked just fine. However, I just tried adding it to the end of the document (right after `</body>`) and it still isn't working. 
This is how I implemented the "after": 
```
var userFeed = new Instafeed({
                    get: 'user',
                    userId: 720550896,
                    accessToken: '720550896.467ede5.985cd905f9494004848416660a3fcf82',
                    resolution: 'low_resolution',
                    template: '<li><img src="{{image}}"></li>',
                    target: 'feed',
                    after: $(document).ready(function(){
                        $('.slider').slider({full_width: true});
                    })
                });
                userFeed.run();
```

**Comment by MuTLY** [comment]
Ok, you're almost there. Just so you can learn a bit more, I fixed your entire HTML. Take a look on http://codepen.io/anon/pen/aOowWR and check where I put each element, each script, etc.

There's some problems with your code, among them:

1. It's a mess ;)
2. It was missing some elements, like the <body> tag
3. You were calling methods - for example, the slider() - before there were any elements written on the document for the method to work with
4. Etc.

Good luck!

**Comment by steelcowboy** [comment]
Oh whoops I was updating localhost but not my webserver to reflect the changes I made lol. Thank you so much for your help, definitely still learning with Javascript but really enjoying it!
