### ISSUE TITLE
Mod_Instafeed No user pictures

### ISSUE THREAD

**Issue by Tutje** [stevenschobert/instafeed.js#253]
I installed the Instafeed module into my website www.tutje.nl
I can get pictures with a hashtag, but not from my own instagram account @tutje.nl
What am I doing wrong?
I installed my client ID, My user ID and created an acces token.
Still nothing
http://www.tutje.nl/index.php
When I set it to user, I only get  the "#"
When I set it to tag, I get the pictures.
Does anybody know what I am missing? (Joomla 3.4.1)

**Comment by Tutje** [comment]
Where can I add  >>>  target="_blank" <<< to open the instagram pictures to open in a new window?
Should't be that hard... but I'm no programmer...

Is it also possible to add the likes and comment indicaters to the pictures?

(help! .....)

**Comment by calebmichaelsanchez** [comment]
Inside of the new Instafeed object you would add a template option and add something like this. 

`template: '<a target="_blank" href="{{link}}" class="info">{{caption}}</a>'`

As for the problem of getting images from your user, you are going to need an oauth code. You'll need to follow the directions on this page using the recommended Server-side (explicit) Flow. https://instagram.com/developer/authentication/

 If you are not comfortable in the command line this may pose a problem for you.

**Comment by Tutje** [comment]
Thans for the reaction.
If I want to create my own instafeed, do I use php or html to include the instafeed.min.js and css?

**Comment by calebmichaelsanchez** [comment]
I just added it through a `script

**Comment by calebmichaelsanchez** [comment]
I just added it through a `script` tag at the bottom of the page for example.

`<script src="path/to/folder/instafeed.min.js"></script>`

If you're needing more direction with html + css you should check out http://codeacademy.com. Lots of useful tutorials.

**Comment by Tutje** [comment]
Thanks for the help!
I learn every day!

I'll use the Instafeed Joomla module for now. Í will replace it when I figure it all out...

But another Issue:
How to use template in that module: I have a template option there, but no mather what I try, it doesn't change anything.

I Use:
template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes"><img src="images/heart.png" /> {{likes}} <img src="images/bubble.png" /> {{comments}}</div></a>'
	})
or:  '<a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes"><img src="images/heart.png" /> {{likes}} <img src="images/bubble.png" /> {{comments}}</div></a>'
	})
in the input-box.
But no result eitherway ...

When I use it just as JS, it is working (but then there are resizing isues in ie....)(maybe variable output in Instafeed? 214px...) like on test.epdijkhuis.nl
