### ISSUE TITLE
Improve userID error message

### ISSUE THREAD

**Issue by ultrawebsites** [stevenschobert/instafeed.js#254]
If you specify an incorrect userId value when configuring Instafeed.js, the error message currently writes to the console: 
`throw new Error("No user specified. Use the 'userId' option.");`

However, this message is not entirely correct, as it also gets thrown when you specify a string rather than a number also (I thought my userId was just my Instagram username). So suggest the line of code is more like: 
`throw new Error("No userId specified, or a non-numeric userId has been specified.");`

**Comment by jamesdh** [comment]
No matter what I do currently, I'm unable to get beyond this error. 

```
var feed = new Instafeed({
    get: 'user',
    userId: 16035277,
    accessToken: '16035277....'
  });
  feed.run();
```
...results in the same error. I've tried every combination of username, user id as a string, user id as a number, without any luck.

**Comment by stevenschobert** [comment]
Hey @ultrawebsites! Thanks for bringing this up!

As of [v1.4](https://github.com/stevenschobert/instafeed.js/releases/tag/v1.4.0), Instafeed.js no longer complains about string/number mismatches for these options, so you shouldn't see those errors anymore!
