### ISSUE TITLE
Fetch photos from 2 profiles into same target

### ISSUE THREAD

**Issue by dsbahr** [stevenschobert/instafeed.js#255]
Hi. 

I have a client who needs to have an Instagram slideshow, fetching pictures from two Instagram profiles, one for woman, one for men. 

Now I need to make a slideshow of the complete collection of images, but show one image from the woman profile, followed by one picture from the men profile.

I know Instafeed supports multiple feeds, but that is for different targets. 

Is it possible to do what I want?

Awesome plugin otherwise!

Thanks, 

/David

**Comment by chetanraj** [comment]
You can have two instances of Instafeed, i'm hoping that would help

**Comment by Fenton49** [comment]
Hi there,

I need to accomplish the same: merge multiple Instagram streams into one target (and not two instances of instafeed)e.g.:

get: 'user',
userId: 179010558, 359014467, 672032467,

is that somehow possible? or is there any other script that could do that?

thanks & cheers, j

**Comment by moogreentea** [comment]
Hi :)

same problem here

i need to get image from multiple account and sort them by date.
e.g.
<div class="instafeed">
image from user 1
image from user 2
image from user 1
image from user 3
image from user 4
</div>

two instances of Instafeed are good but this way can't sort all image of them.
it only can sort themeself but not all of them.
 
anyone can help me?

Thanks,
Chan
