### ISSUE TITLE
Pagination/Load More automatically without a Next Button.

### ISSUE THREAD

**Issue by death2all110** [stevenschobert/instafeed.js#258]
Hey there.

I really like this javascript instagram feed you created here. I'm using it for my wedding website, to load a feed automatically. when it comes to the wedding we will be having it stream on a tv screen. 

I was wondering if it would be possible to use the pagination without a 'next' button, as in it auto loads every 5 minutes or so... I could do an http refresh in HTML but I feel that's not as 'clean' as say having the javascript auto-load. 

And if possible. could you provide a sample of how I could implement this? I'm just starting to learn javascript. Thanks!

**Comment by d3viliz3d** [comment]
Yes it's possible with a few simple jQuery lines. Put them inside the <script> tags:

$(function() {
	loadMore();	// launches the loadMore function below.
});

function loadMore() {
	if(feed.hasNext())	// check if there are more pictures available
		feed.next();	// if so, loads them
	setTimeout("loadMore()",10000);	     // 10 seconds timeout before running the function again
}

**Comment by death2all110** [comment]
Hmm i tried this but it didn't work :/

**Comment by waisie** [comment]
it doesn;t work.

My code look like this


$(document).ready(function() {
	instafeed();
	loadMore();
});

function instafeed() {
	var userFeed = new Instafeed({
        get: 'user',
        userId: 1537997294,
        accessToken: '1537997294.467ede5.82d3948b2e934f5eaf7b695332347df5',
        limit: 12,
        resolution: 'low_resolution',
        template: '<div class="insta-wrap"><img src="{{image}}" /><a href="{{link}}" target="_blank"><div class="likes">&hearts; {{likes}}</div></a></div>'
    });
    userFeed.run();
}


function loadMore() {
    if(feed.hasNext())  // check if there are more pictures available
        feed.next();    // if so, loads them
    setTimeout("loadMore()",1000);      // 10 seconds timeout before running the function again
}

**Comment by waisie** [comment]
it doesn't work

**Comment by jerewall** [comment]
I use jQuery and it works fine both desktop and mobile :) 
  
<script>
 jQuery(document).ready(function(){
  $(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() == $(document).height()) {
       
         // call feed.next() once the page reaches the bottom
		 
		 your-feed-name-here-Feed.next();
 
     }

      });
</script>

**Comment by waisie** [comment]
is not working for me. 
$(document).ready(function() {
	instafeed();
});

function instafeed() {
	var userFeed = new Instafeed({
        get: 'user',
        userId: XXXX,
        accessToken: 'XXXX',
        limit: 12,
        resolution: 'low_resolution',
        template: '<div class="insta-wrap"><img src="{{image}}" /><a href="{{link}}" target="_blank"><div class="likes">&hearts; {{likes}}</div></a></div>'
    });
    userFeed.run();
}

--------------------------------------------------

$(function() {
    loadMore(); // launches the loadMore function below.
});

function loadMore() {
    if(feed.hasNext())  // check if there are more pictures available
        feed.next();    // if so, loads them
    setTimeout("loadMore()",10000);      // 10 seconds timeout before running the function again
}

**Comment by jerewall** [comment]
Try mine..

**Comment by waisie** [comment]
where is your code?

**Comment by jerewall** [comment]
```javascript

   $(window).scroll(function() {

   if($(window).scrollTop() + $(window).height() == $(document).height()) {


     // call feed.next() once the page reaches the bottom
      your-feed-name-here-Feed.next();
  }

```

**Comment by waisie** [comment]
thank you Jerewall.

where do I add that code?

**Comment by jerewall** [comment]
It goes in the head with your other jquery,

```javascript

<script>
     jQuery(document).ready(function(){

    $(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() == $(document).height()) {
       
         // call feed.next() once the page reaches the bottom
		 
		 nseuroFeed.next();
 }
});
   
      });
</script>
```

full thing should look like that.

**Comment by nguila** [comment]
Can you please put the html code? i would like to see how it works?
