### ISSUE TITLE
Images from user Id method doesn't work on certain host after a while

### ISSUE THREAD

**Issue by thomasverleye** [stevenschobert/instafeed.js#260]
Hi great plugin!

I've got a problem with the user ID method on a online host, it worked from the start perfectly, after a week it went down showing the following error in my console: "Uncaught Error: Error from Instagram: The access_token provided is invalid."
I've removed the authorization of the instafeed.js and re-run the authorization because I thought it was just expired or something but it still gave me the same error.
When I run the completely same instafeed code on a test project on my local machine it works perfectly.
So my conclusion is that instagram (or instafeed) blocks certain hosts after a while?

Here's the source code:

<html lang="en">
<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="instafeed.js"></script>
</head>
<body>

<div id="instafeed"></div>
      

```
  <script type="text/javascript">
      var feed = new Instafeed({
          get: 'user',
          userId: 1457616306,
          accessToken: '################',
          limit: 8, 
          template: '<a class="animation" href="{{link}}"><img src="{{image}}" /></a>'
      });
      feed.run();
  </script>
```

</body>
</html>

**Comment by phirschybar** [comment]
I am having the same issue.
