### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sasscanoodle** [stevenschobert/instafeed.js#261]
Hi, I have been trying all of the examples on here to try and get a load more button functional and have had no success at all. Can someone take a look and give a suggestion? Thanks in advance!

<script type="text/javascript">
$(document).ready(function() {
    var userFeed = new Instafeed({
        get: 'tagged',
        tagName: 'commencement',
        clientId: '82c8dd10df8241b19f975d3fd6d5f76d',
        limit: 4,
        resolution: 'standard_resolution',
        template: '<a class="animation" href="{{link}}"><img src="{{image}}" /></a><img alt="" src="{{model.user.profile_picture}}" />{{model.user.username}}<br/>{{caption}}',
    });
    userFeed.run();
});

$('#mybutton').on('click', function() {
     $("#instafeed").fadeTo(400, 0, function() {
        userFeed.next();
     })
});

</script>

<div id="instafeed">
    &nbsp;</div>

<div class="myButton">
    Load More</div>

**Comment by stevenschobert** [comment]
Can you share the code that you've tried so far?

**Comment by sasscanoodle** [comment]
Yes I can, sorry thought I did, guess it cleared it out because I didn't use markdown. Trying again:
```javascript
$(document).ready(function() {
    var userFeed = new Instafeed({
        get: 'tagged',
        tagName: 'commencement',
        clientId: '82c8dd10df8241b19f975d3fd6d5f76d',
        limit: 4,
        resolution: 'standard_resolution',
        template: '<a class="animation" href="{{link}}"><img src="{{image}}" /></a><img alt="" src="{{model.user.profile_picture}}" />{{model.user.username}}<br/>{{caption}}',
    });
    userFeed.run();
});

$('#mybutton').on('click', function() {
     $("#instafeed").fadeTo(400, 0, function() {
        userFeed.next();
     })
});

<div id="instafeed">
	&nbsp;</div>
<div class="myButton">
	Load More</div>
```

I added the little bit of html I have in the body of the page as well at the bottom, in case something is wrong there. Thanks again in advance!

**Comment by stevenschobert** [comment]
I noticed a couple of things you'll want to change:

1. Your `userFeed` variable is only accessible from inside your `$(document).ready()` function, but you are trying to access it from outside of that function. Try moving your click handler `$(...).click` to inside your `$(document).ready()` function.

2. Your click handler `$(...).click` is trying to bind to an element with `id="#myButton"` (the `#` represents an ID), but your HTML button has a class `<div class="myButton">`. Try changing your click handler to grab the button by its class name using a period `$('.myButton').click(...)`:

Try this updated code that includes those two changes:

```js
$(document).ready(function() {
    var userFeed = new Instafeed({
        get: 'tagged',
        tagName: 'commencement',
        clientId: '82c8dd10df8241b19f975d3fd6d5f76d',
        limit: 4,
        resolution: 'standard_resolution',
        template: '<a class="animation" href="{{link}}"><img src="{{image}}" /></a><img alt="" src="{{model.user.profile_picture}}" />{{model.user.username}}<br/>{{caption}}',
    });
    userFeed.run();
    $('.myButton').on('click', function() {
         $("#instafeed").fadeTo(400, 0, function() {
            userFeed.next();
         })
    });
});


<div id="instafeed">
    &nbsp;</div>
<div class="myButton">
    Load More</div>
```

**Comment by popesey** [comment]
Hi Steve - have been following this post. I have implemented the code above. But i'm still getting the error
Uncaught ReferenceError: $ is not defined - in the javascript console.  I have placed the script in the html just before the </body> tag. Any help would be much appreciated.

**Comment by popesey** [comment]
Hi Steve - I have been following this issue. I have used the code above. But i'm still getting the error
Uncaught ReferenceError: $ is not defined - in the javascript console. I have placed the script in the html just before the end of body tag. Any help would be much appreciated.

**Comment by han4fi** [comment]
hi I try to follow that code above, but its doesn't work. here is my code

`<script language="javascript" type="text/javascript">
  var userFeed = new Instafeed({
    get: 'user',
    userId: '2302178792',
	clientId: 'd94a04876779463a94a93f9efbdb0973',
    accessToken: '2302178792.1677ed0.5c8a088c2bb845d0b4b600a4298e2cda',
    resolution: 'standard_resolution',
    template: '<a href="{{link}}" target="_blank" id="{{id}}"><img src="{{image}}"/><div class="footer"><div class="insta-likes"><div style="display: table; vertical-align: middle; height: 100%; width: 100%;"><span style="display: table-cell; vertical-align: middle; height: 100%; width: 100%;"><i style="color:#FF0000;" class="icon-heart"></i> {{likes}} <i style="margin-left:15px;" class="icon-comment"> </i>{{comments}} </span></div></div><div class="user"><img src="{{model.user.profile_picture}}"/><span class="name">{{model.user.username}}</span></div></div></a>',
    sortBy: 'most-recent',
    limit: 12,
    links: false
  });
  userFeed.run();
  $('#myButton').on('click', function() {
         $("#instafeed").fadeTo(400, 0, function() {
            userFeed.next();
         })
    });

  
</script>
</div>
<button id="myButton">Load More</button>`
