### ISSUE TITLE
Project uses out-dated version of coffee-script

### ISSUE THREAD

**Issue by juhamust** [stevenschobert/instafeed.js#264]
According to `package.json` the depends on `coffee-script` version 1.3.x, ending up to version 1.3.3. The build with this version fails because of the changed API path.exists --> fs.exists.

Upgrading for example to version 1.4.x helps. Having said that, the latest version of coffee-script at the moment is 1.9.2.

**Comment by stevenschobert** [comment]
Thanks for the heads up! Fixed in 9a3b7e5c70a06fe1c06902aa48dcec55600f377c.
