### ISSUE TITLE
Trying to Grab 5 Most Recent Photos from Specific Account

### ISSUE THREAD

**Issue by jsites123** [stevenschobert/instafeed.js#267]
I'm trying to build an instagram feed for the footer of a website. All I want to do is grab the 5 most recent photos for my client's Instagram account, but when I run the below code, I seem to get 5 random photos from anyone's account.

    //Get Instagram Photos
    var i = 0;
    var feed = new Instafeed({
        clientId: 'CLIENT_ID_REMOVED_FOR_THIS_POST',
        limit: 5,
        resolution: 'low_resolution',
        //sortBy: 'most-recent',
        template: '<img class="instagramPhoto" src="{{image}}" />'
    });

    feed.run();

I went through the Instagram process to register my application, and got my client ID, and I put that ID into my code, but I seem to just get random images.

Thoughts?

**Comment by stevenschobert** [comment]
If you take a look at the section on ["Getting images from your user account"](http://instafeedjs.com/#user), you'll notice you need to supply the `get: "user"` option, as well as a user ID & access token:

```js
var userFeed = new Instafeed({
  get: 'user',
  userId: YOUR_USER_ID,
  accessToken: 'YOUR_ACCESS_TOKEN'
});
userFeed.run();
```

Try following the steps from that section, and let me know if you have any other issues!
