### ISSUE TITLE
Error: Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by alexanderchacon** [stevenschobert/instafeed.js#268]
I try to use instafeed but not load anything, i use the div whit id instagram in the html

var feed = new Instafeed({
get: 'tagged',
tagName: 'awesome',
clientId: '8e181ded71554daaab236297c8954295'
});
feed.run();

In te console show this error:
Uncaught TypeError: Cannot read property 'appendChild' of null

**Comment by stevenschobert** [comment]
Make sure your `<div id="instafeed"></div>` is on the page, and that you're not running the javascript until the page has been loaded.

**Comment by alexanderchacon** [comment]
Hi, Steven yes this is my mistake, I was not using div "instafeed".
Thanks!
