### ISSUE TITLE
multiple hashtags

### ISSUE THREAD

**Issue by jfmphoto** [stevenschobert/instafeed.js#269]
Hello,
I'm looking for a way  to be able for my stream to display images from more than one hashtag.

Thank you

**Comment by stevenschobert** [comment]
Do you want the images to come from _any_ of the tags, or does each image need to have _all_ the tags?

**Comment by jfmphoto** [comment]
any of the tags

**Comment by stevenschobert** [comment]
You can use multiple feeds for that. See #12.

**Comment by jfmphoto** [comment]
thank you so much!!!!
