### ISSUE TITLE
filtering out images

### ISSUE THREAD

**Issue by jfmphoto** [stevenschobert/instafeed.js#270]
Hi, thank you so much.

I wanted to be able to remove images with specific tags.
for example:

I display the images with a tag "nyc" but from the images displayed,  i want to remove images that contain the tag "jersey"
any thoughts?

**Comment by stevenschobert** [comment]
Good news! This is exactly what the [filter feature](https://github.com/stevenschobert/instafeed.js/blob/5440006b63f0439f3ea8b622de31e472f4c90207/README.md#advanced-options) was invented for!

```js
var feed = new Instafeed({
  // -- your other settings go here
  get: "tagged",
  tagName: "nyc",
  filter: function(image) {
    if (image.tags && image.tags.indexOf("jersey") >= 0) {
      return false;
    }
    return true;
  }
});
feed.run();
```

**Comment by jfmphoto** [comment]
cool!
is there a way to add more than one word to the filter?

p.s. thank you for this script. its awesome!

**Comment by stevenschobert** [comment]
Sure, you just have to loop through multiple tags and check each of them.

Try modifying the example in #196 and see if that gets the job done :)
