### ISSUE TITLE
GET BY LOCATION AND FILTER BY TAG FOR SPECIFIC DATE AND TIME

### ISSUE THREAD

**Issue by albertozayas** [stevenschobert/instafeed.js#271]
Hello Steven and everyone else!

Is there a way I can do this? Like for example, get photos in Central Park NY City, #kiss, June 21, 2015, 3:00  to 5:00 pm.

Thanks, Alberto Zayas

**Comment by gregology** [comment]
The Instagram API doesn't all you to do this :( What you'd have to do is pull all posts from the specific area and then filter them on caption and create_time. Not doable with instafeed.js

**Comment by albertozayas** [comment]
OK, you are the only one that has responded so far, thanks Gregory. You can
take a look at my website here: hashtagdevents.com

ALBERTO

2015-07-05 0:01 GMT-04:00 Gregory Clarke <notifications@github.com>:
