### ISSUE TITLE
FIND LOCATION ID EXAMPLE USING FB AND FOURSQUARE

### ISSUE THREAD

**Issue by albertozayas** [stevenschobert/instafeed.js#272]
Hello Steven!

Do you have a sample for how to get the locationid using FACEBOOK_PLACES_ID and FOURSQUARE_V2_ID with the Instagram API? Issue #48 only shows how to get it by geographic coordinates.

Thanks, Alberto Zayas

**Comment by stevenschobert** [comment]
Hey @albertozayas! I actually don't have a sample on hand, sorry about that.

I bet if you post your question to StackOverflow you'll get some good help though!
