### ISSUE TITLE
Arranging photos pulled into div classes

### ISSUE THREAD

**Issue by thomasm-harris** [stevenschobert/instafeed.js#274]
Hey, I'm having trouble figuring out how to fit the pictures from instagram into the gallery one of my pages. Tell me what code, pictures, etc. you need and I will provide it. Thank you!

**Comment by stevenschobert** [comment]
Hey @geminitydesigns, can you share what code you've got so far, and explain what you're trying to do a little more?

**Comment by geminitydesigns** [comment]
Of Course, Here is the coding that I have so far:

<script type="text/javascript" src="js/plugin/instafeed/instafeed.min.js"></script>
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'smoothiegang',
        clientId: '1106e290de9647a3add9852f4047571d',
		useHttp: true,
		target: 'instafeed',
		resolution: 'standard_resolution',
		template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes">&hearts; {{likes}}</div></a>'
    });
    feed.run();
</script>


I want the images that are obtained from this to fit into my css that is organized differently. I want to know is there some way where I can receive the images and have them automatically put into the same styling of an image gallery that I already have in place?

**Comment by stevenschobert** [comment]
Have you taken a look at the [template](https://github.com/stevenschobert/instafeed.js/blob/master/README.md#templating) options?

Instafeed.js doesn't come with and preset styles, so you should be able to completely control the look and feel though the template and your own CSS.

**Comment by geminitydesigns** [comment]
Alright thank you, I wanted to know how do I incorporate instafeed.js into my gallery through the html's css. So that every single image that is gathered from instagram is loaded into the gallery, what do I need to do? Use the "After:" option to add it in or would this mainly need to to make another div class where this would happen automatically?

**Comment by stevenschobert** [comment]
What library/code are you using to create your slideshow?

**Comment by geminitydesigns** [comment]
.portfolio_wraper {
	float: left;
	width: 100%;
	padding-bottom: 50px;
	margin-top: 30px;
	border-bottom: 1px solid #e7eaec;
}
.coolthing_portfolio{
	width: 100%;
	float: left;
	}
.portfolio_border {
	border-bottom: none;
}
.portfolioFilter {
	width: 100%;
	text-align: center;
	padding: 20px 0px 30px 0px;
}
.portfolioContainer {
	float: left;
	width: 100%;
}
.portfolioFilter a {
	display: inline-block;
	padding: 4px 17px;
	font-size: 18px;
	text-transform: capitalize;
	border: 2px solid transparent;
	text-decoration: none;
	color: #999999;
}
.portfolioFilter a:hover {
	border-color: #99a4bd;
}
.portfolioFilter a.current {
	border-color: #99a4bd;
}
.photography, .print, .video, .webdesign, .miscellaneous {
	float: left;
	width: 100%;
}
.portfolio_title {
	float: left;
	width: 100%;
}
.portfolio_title h3 {
	text-transform: uppercase;
	margin: 0px;
}
.portfolio_sub_title {
	float: left;
	width: 100%;
	font-size: 16px;
	font-style: italic;
	color: #a9a9a9;
	text-transform: capitalize;
	min-height: 32px;
}
.portfolio_text {
	float: left;
	width: 100%;
	padding: 10px 0px;
}
.portfolio_list {
	float: left;
	width: 100%;
}
.portfolio_list li a {
	color: #949494;
	font-size: 13px;
	padding: 8px 0px;
	display: inline-block;
	text-decoration: none;
}
.portfolio_list ul {
	list-style: none;
}
.portfolio_list li a:before {
	content: "";
	width: 7px;
	height: 7px;
	display: inline-block;
	margin-right: 10px;
	line-height: 5px;
	background-color: #949494;
}
.portfolio_quote {
	float: left;
	width: 100%;
}
.portfolio_quote blockquote {
	margin: 10px 0px;
}
.portfolio_img {
	float: left;
	width: 100%;
	position: relative;
}
.portfolio_img img {
	width: 100%;
}
.portfolio_img_overlay {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-color: rgba(153, 164, 189, 0.9);
	border-radius: 2px;
	display: none;
	text-align: center;
}
.portfolio_img:hover .portfolio_img_overlay {
	display: block;
	-webkit-animation: zoomIn 0.2s;
	-moz-animation: zoomIn 0.2s;
	-ms-animation: zoomIn 0.2s;
	-o-animation: zoomIn 0.2s;
	animation: zoomIn 0.2s;
}
.portfolio_img:hover .portfolio_img_overlay a i {
	-webkit-animation: rotateIn 0.4s;
	-moz-animation: rotateIn 0.4s;
	-ms-animation: rotateIn 0.4s;
	-o-animation: rotateIn 0.4s;
	animation: rotateIn 0.4s;
}
.portfolio_project_detail a i {
	color: rgb(255, 255, 255);
	font-size: 40px;
}
.portfolio_project_detail a span {
	display: inline-block;
	text-align: center;
	position: absolute;
	top: 28%;
	left: 50%;
	margin-left: -20px;
	margin-top: -17px;
}
.project_name {
	color: #fff;
	position: absolute;
	bottom: 10%;
	text-align: center;
	float: left;
	width: 100%;
}
.project_name h4 {
	color: #fff;
	text-transform: capitalize;
	font-family: 'Lato', sans-serif;
	margin-bottom: 0px;
}
.project_name a {
	text-decoration: none;
	color: #fff;
}
.portfolio_pagination {
	width: 100%;
	text-align: center;
	padding-top: 20px;
}
.portfolio_pagination .post_pagination {
	display: inline-block;
	float: none;
	width: auto;

**Comment by geminitydesigns** [comment]
This is the coding I was able to compile for my gallery, I want each picture to follow this css styling so that as the images come in it naturally builds up the gallery
