### ISSUE TITLE
Is there a way to get the user object when i'm accessing the user

### ISSUE THREAD

**Issue by chetanraj** [stevenschobert/instafeed.js#275]
I'm using the user feed to render images particular to that user, but i need the user object to build a separate profile, is there a way to access it ?

**Comment by stevenschobert** [comment]
Yes, there are 3 points of access:

- In the template, by using `{{model.user}}`.
- In the `filter` callback, through the image object that gets passed in.
- In the `success` callback, through the entire API response that gets passed in.
