### ISSUE TITLE
Limit problem

### ISSUE THREAD

**Issue by WebAtelier47** [stevenschobert/instafeed.js#276]
Hello i have a problem when i set a limit to 1 i have the image display 2 times, my code:

```
<script type="text/javascript">
var feed = new Instafeed({
    sortBy: 'most-recent',
    get: 'tagged',
    limit: '1',
    tagName: 'marmande',
    clientId: 'f3cdb74f5df14cfab3f4cdf0143f51ef',
    template: '<a href="{{link}}"><img src="{{image}}" /></a>'
});  
feed.run();
</script>
<div id="instafeed"></div>
```

Thanks

**Comment by OstrichProjects** [comment]
I wasn't able to reproduce your error.  Copying and pasting your block of code (and changing the clientId) yields a single image.  The only explanation I can think of is that you have two blocks of javascript running

``` javascript
var feed = new Instafeed({
    sortBy: 'most-recent',
    get: 'tagged',
    limit: '1',
    tagName: 'marmande',
    clientId: 'f3cdb74f5df14cfab3f4cdf0143f51ef',
    template: '<a href="{{link}}"><img src="{{image}}" /></a>'
});  
feed.run();
```

Check to make sure that you don't have the inline javascript as well as a script tag with a link to another javascript file (having two separate, equivalent blocks of javascript led to 2 images for me).
