### ISSUE TITLE
Sortby most-liked when 60+ images

### ISSUE THREAD

**Issue by lasbrojen** [stevenschobert/instafeed.js#278]
Hello,

I got 1000+ images I would like to sortby most-liked and load 60 at a time.

When I use  "sortBy: most-liked" it looks like instafeed.js loads the 60 recent images and then sort these 60 by most-liked. When I load the next 60 images I get the next 60 recent images and these sorted by most liked.

It looks like it is not posible to sort all 1000+ images by most-liked. And then load 60 at a time?

Is this how instafeed.js works? Or is it a bug?

Kind regards

**Comment by OstrichProjects** [comment]
This is not a bug, but rather a consequence of Instagram's API.  The API does not have a `sortBy` parameter so all sorting is done once the data is received.  This will force you to make 1000+/60 requests often unless you cache your results ([Instagram's API limit is 5000 calls/hour](https://instagram.com/developer/limits/)).

**Comment by stevenschobert** [comment]
Hey @lasbrojen! I'm afraid @OstrichProjects is correct, the sorting isn't something provided by Instagram's API (at least not at the time this library was written), it's just something extra I added in.

At that volume of images, you'll probably want to create a server-side solution that saves images in a database or some other persistent store, and sorts them on the server side.
