### ISSUE TITLE
Random sort doesn't appear to work with picture limit

### ISSUE THREAD

**Issue by lordchancellor** [stevenschobert/instafeed.js#282]
Hi,

Thanks for this plugin, it's incredibly awesome. One issue that I have noticed this morning though is that if I limit the number of pictures being pulled through from Instagram (in my case I only want 4), Instagram seems to send the same 4 pictures every time (please note I am trying to capture a specific user feed). I've got sortBy set to random, but this only randomises the same four images. 

It actually looks like I'm getting the four most recent images from the user feed every time and it's these that are being randomised, not the images coming in.

Is this something that you think you might be able to fix from your end?

**Comment by stevenschobert** [comment]
Hey @lordchancellor! You are right is an issue!

The limit mechanism comes straight from Instagram's API, where as the sorting is something extra I built into the library. So the limit always gets applied before the filter, leading to the same 4 images, but sorted differently. 

That probably will stay the case until a rewrite, or if Instagram adds sorting to their API.

In the meantime, you can work around it by setting the limit higher and removing extra images manually. See #8.

**Comment by lordchancellor** [comment]
Hey @stevenschobert, thank you for your response! I appreciate your input on this and I'm starting to think of a work around. If I come up with anything truly magical I'll post it back here!
