### ISSUE TITLE
Centre-align my instagram photos

### ISSUE THREAD

**Issue by ghost** [stevenschobert/instafeed.js#283]
Hello, 

I followed the instructions on instafeed.js website in order to add my company's instagram feed on my website, and it has been very successful. However, my feed (located on my homepage) is off-centre...it is too far to the left of the page. How do I centre-align my feed?

Thanks, 

Dani

**Comment by nguila** [comment]
Dani.

Can you please explain how do you add my company's instagram feed on my website? 

I have the same issue in my company.

Thanks...

Jorge

**Comment by mikekresnik** [comment]
I fixed this issue by using the "text-align" attribute on my parent div in my css:

```css
section.social {
	text-align: center;
}
```
Since my instafeed div is the child, it centers it! I hope this makes sense and is helpful!
