### ISSUE TITLE
Get images from username + filter on tag with mock 

### ISSUE THREAD

**Issue by konsulenten** [stevenschobert/instafeed.js#284]
I want to get images from a specific UsedID and (sometimes) a specific tag. 
Assigning them to an array and then appending each image to specific divs (in special grid..).

But cant get this filter-function to work:

```javascript
    filter: function(image) {
      return image.tags.indexOf('TAG_NAME') >= 0;
  }
```

The following code works to fetch images, but I can't get images filtered on tag using the above filter.

```javascript
// Instafeed forside
var imgs = [], tags = [], Instafeed;
var feed = new Instafeed({
    get: 'user',
    userId: USER ID,
    accessToken: ACCESS TOKEN,
    mock: true,
    resolution: 'standard_resolution',
    template: '<a href="{{image}}"><img src="{{image}}" /></a>',
    success: function (data) {
        "use strict";
        var images = data.data, result, i, image;
        for (i = 0; i < images.length; i++) {
            image = images[i];
            result = this._makeTemplate(this.options.template, {
                model: image,
                id: image.id,
                link: image.link,
                tags: image.tags,
                image: image.images[this.options.resolution].url
            });
            imgs.push(result);
        }
        // loop through
        for (i = 0; i < imgs.length; i++) {
            $(".insta0" + (i + 1)).append(imgs[i]);
        }
    }
});
feed.run();
```

Is the best way to add a function inside this one and filter on tags?
I would appreciate some help and/or advice on this code :)

See also attached screenshot of result in page:
![skjermbilde 2015-07-30 kl 10 45 05](https://cloud.githubusercontent.com/assets/10710013/8979166/13adf358-36a8-11e5-8da4-7013431d2073.png)

Best regards,
Reidar Nygård

**Comment by stevenschobert** [comment]
The `filter` option won't get run when you have `mock: true`, so you'll want to manually check the images in your `success` function:

```js
success: function (data) {
  var images = data.data, result, i, image;
  
  for (i = 0; i < images.length; i++) {
    image = images[i];
    
    // check for tags
    if (image.tags && image.tags.indexOf('TAG_NAME') >= 0) {
      result = this._makeTemplate(this.options.template, {
        model: image,
        id: image.id,
        link: image.link,
        tags: image.tags,
        image: image.images[this.options.resolution].url
      });
    
      imgs.push(result);
    }
  }
  
  // loop through
  for (i = 0; i < imgs.length; i++) {
      $(".insta0" + (i + 1)).append(imgs[i]);
  }
}
```

Hope that helps!

Props are digging through the messy source code to find how to manually template things!

**Comment by konsulenten** [comment]
Thanks alot @stevenschobert !

Great plugin and good documentation.

Best regards,
Reidar
Norway

**Comment by ghozylab** [comment]
Awesome, really helpful... Thanks a lot @stevenschobert !
