### ISSUE TITLE
Is possible to display followers?

### ISSUE THREAD

**Issue by rgbesteban** [stevenschobert/instafeed.js#287]
I'm trying to display total number of followers within an Instagram account.  Is there a way I can pull this data with instafeed? 

Thanks!

**Comment by nirvana-msu** [comment]
Not directly, but you can leverage instafeed widget (say, if you use it on the page already) as it contains configuration such as `accessToken` and `userId`, that you'd need to make your own ajax call. You can set `before` callback, as described in the documentation, to something like:

```js
function instafeedBefore() {
    var url = 'https://api.instagram.com/v1/users/' + this.options.userId + '/?access_token=' + this.options.accessToken;

    $.ajax({
        method: 'GET',
        url: url,
        dataType: 'jsonp',
        jsonp: 'callback',
        success: function (response) {
            console.log(response.data.counts.followed_by);
        }
    });
}
```
The response contains other useful profile information such as number of posts, bio, etc.

You can obviously make a call to any other Instagram API endpoint this way as well.
