### ISSUE TITLE
Limit tags to first one?

### ISSUE THREAD

**Issue by Webdinge** [stevenschobert/instafeed.js#289]
Hi,

I'm pretty bad with jQuery, but is it possible to grab just the first #tag of each photo?

So you get all tags with {{ model.tags }}, but how do you limit this to just the first tag?

What I try to do is making the feed some sort of shoppable for a webshop. So I want to use the first tag to create a link to a productpage.
This would be a very nice addition but probably a ton of work ;)

I tried this:
  filter: function(image) {
    image.tagsFormatted = '';
    for (var i = 0; i <= 4; i++) {
      image.tagsFormatted += image.tags[i];
    }
    return true;
  },

**Comment by stevenschobert** [comment]
Sure! You've basically got the right approach, you just need to grab the first tag and assign it to a variable:

```js
filter: function(image) {
  image.firstTag = "";
  if (image.tags && image.tags.length > 0) {
    image.firstTag = image.tags[0];
  }
  return true;
},
template: '... <p>{{model.firstTag}}</p>'
```
