### ISSUE TITLE
Possible to add ID's to Images?

### ISSUE THREAD

**Issue by ajsingh007** [stevenschobert/instafeed.js#290]
Hello!

I enjoy using Instafeed.js, I think it is great. I'm looking for some assistance. I'm pulling a feed of 7 images based on a specific hashtag. What I would like to do is assign an ID to each these images so I may alter their appearance/layout. 

What I was trying to do was use the below jQuery to give the <a> tag of the first image an ID of 1, the <a> tag of the second image an ID of 2, and so on:

for ( var i = 1; i < 8; i += 1 ) {
    		$('div#instafeed').children(':nth-child(' + i + ')').attr('id', i);
    		console.log(i);	
    	};

Can't get it to work -- I think it is because the template of the generated images is also produced via JavaScript... Any help or insight would be appreciated!

**Comment by stevenschobert** [comment]
You'll want to place that code in the `after` function, so it runs after all the images have been put onto the page.

Something like this should do this trick:

```js
var feed = new Instafeed({
  // other settings
  after: function() {
    $("#instafeed").children().each(function (index, el) {
      var count = index + 1;
      $(el).addClass("item-"+ count);
    });
  }
});
feed.run();
```

**Comment by ajsingh007** [comment]
Hey thank you so much for your reply! Will give this a try

**Comment by nguila** [comment]
Can you please put all the code here, as even with this suggestion i can not load the photos?
Thanks

**Comment by ajsingh007** [comment]
Hey nguila, here is my full code used on a recent build:

var feed = new Instafeed({
        get: 'tagged',
        tagName: 'Lion',
        clientId: '<CLIENT_ID_GOES_HERE>',
        limit: 10,
        resolution: 'low_resolution',
        template: '<a target="_blank" class="shadow" href="{{link}}"><div class="tint"><img class="slamson-ig" src="{{image}}" /></div></a>',
        after: function() {
    		$("#instafeed").children().each(function (index, el) {
      			var count = index + 1;
      			$(el).addClass("item-"+ count);
    		});
		}
    });
    feed.run();

**Comment by nguila** [comment]
Thanks a lot ajsingh007 for your quick reply...

Let me test it....i will feedback...

**Comment by nguila** [comment]
how can i see the Photo ID?
I only get the photos and no more information.
