### ISSUE TITLE
404 Unsupported SIze error

### ISSUE THREAD

**Issue by zanonnicola** [stevenschobert/instafeed.js#292]
Hi there,

I'm getting a weird error on this page : http://www.danddlondon.com/60-days-of-summer/

```
index.html:1 GET https://scontent.cdninstagram.com/hphotos-xfa1/t51.2885-  15/s612x612/e35/11313788_922281347843927_2093010486_n.jpg 404 (Unsupported Size)
```

You can see it by opening the console. The plugin was working until few days ago.
This is my script:

```
var feed = new Instafeed({
    get: 'user',
    userId: 58.....,
    accessToken: 'token.....',
    clientId: 'de.......',
    resolution: 'standard_resolution',
    sortBy: 'most-recent',
    limit: 40,
    template: '<li class="square-insta"><a href="{{link}}"><img src="{{image}}" /></a></li>',

    error: function(error) {
      console.log(error);
      $('#ri-grid').hide();
    },
    after: function() {
        $( '#ri-grid' ).gridrotator( {
            rows        : 4,
            columns     : 5,
            animType        : 'fadeInOut',
            animSpeed   : 1000,
            interval    : 1000,
            step        : 4,
            w1024        : {
                rows    : 4,
                columns : 5
            }
        } );
    }
});

feed.run();
```

Any clue?

Thanks in advance.
Great job btw!

**Comment by fade-agency** [comment]
I got the same error happening this week.
Seems to be a problem with the 'resolution' variable.
If you change it from 'standard_resolution' to 'low_resolution' (or remove that variable entirely), the images seem to load fine.

No idea why, but it will fix the issue for you quickly until someone else gives us the correct fix/answer! ha.

**Comment by zanonnicola** [comment]
Thanks @fade-agency . That worked out.

**Comment by studio31** [comment]
I'm having the same problem, seems like something changed in the Instagram API.

**Comment by studio31** [comment]
I also I tried this:

```
<img src="{{model.images.standard_resolution.url}}" alt="" />
```

But it didn't work, so I'm pretty sure is not a problem related to instafeed.js more likely a problem related to the Instagram API.

**Comment by stevenschobert** [comment]
Huh, strange. Is this happening consistently to all images, or just a handful?

I haven't seen any changes to Instagram's API docs recently.

**Comment by fade-agency** [comment]
All images as far as I could see and across a couple of different sites I use instafeed on as well.
