### ISSUE TITLE
Issues viewing in Firefox and Chrome

### ISSUE THREAD

**Issue by kmtaylor62** [stevenschobert/instafeed.js#293]
Steven, 

It looks like I'm having an issue viewing the instafeed in both Firefox and Chrome. I've looked at the code and I'm not sure what is going on. I'm using Squarespace to host my site and it looks like it's disabling the script in Chrome and Firefox. Any idea why? Here's the page, so you can see for yourself. http://www.kevinmarktaylor.com/lands/

Any suggestions would be very helpful. Thanks

**Comment by stevenschobert** [comment]
Looks okay to me in latest Chrome and Safari. Whats the issue you're having?

<img width="270" alt="screen shot 2015-08-20 at 11 45 33 pm" src="https://cloud.githubusercontent.com/assets/896486/9401477/90102be8-4795-11e5-812c-739cb60e76f4.png">

**Comment by kmtaylor62** [comment]
I'm actually referring to the left side of the page.

http://www.kevinmarktaylor.com/lands/

In Firefox and Chrome the images don't load. But it does in Safari. There's should be images below each line.﻿

Screen Shot 2015-08-21 at 12.43.29 PM.png


Cheers,

KT
Kevin Taylor
204 W. Hyde Park Place Apt. 103
Tampa, FL 33606
919.413.8829
kmtaylor1@mac.com
kevinmarktaylor.com
