### ISSUE TITLE
add main field to package.json

### ISSUE THREAD

**Issue by mderazon** [stevenschobert/instafeed.js#294]
Some build tools (gulp etc) can automatically take the js files and concatenate them to the build artifacts

This requires adding a small line on the `package.json` file:
```
"main": "./instafeed.min.js"
```

see https://docs.npmjs.com/files/package.json#main

**Comment by stevenschobert** [comment]
There is already a `main` entry in `package.json`. See https://github.com/stevenschobert/instafeed.js/pull/190

**Comment by mderazon** [comment]
Hah

I swear it wasn't there when I checked :-)

**Comment by stevenschobert** [comment]
Ah no worries at all! 😁
