### ISSUE TITLE
how to put the location and dte in the photos?

### ISSUE THREAD

**Issue by nguila** [stevenschobert/instafeed.js#295]
Can you please let me know to do put this script to viewer in any tag photos?
I can only see the photos...

Thanks.

**Comment by stevenschobert** [comment]
Hey @nguila. Sorry, but I don't understand what you're asking. What are you trying to do, and what issues are you having?

**Comment by octavioamu** [comment]
you can access the json data with {{model}} in the template, so for example {{model.location.name}} will give you the location name, take a look at the json request, use some tool (https://jsonformatter.curiousconcept.com) to see the data order and add it to your template.
I think with dte you mean date this is "created_time" in the json so   {{model.created_time}} but you will need to format it 

Example of template with location name:
```
template: '{{model.location.name}} <a href="{{link}}"><img src="{{image}}" /></a>'
```
