### ISSUE TITLE
Template link URL wrong format

### ISSUE THREAD

**Issue by BeatLaG** [stevenschobert/instafeed.js#296]
Hi!

Since I´m using the layout option I´m having a problem with the href value. Now this is rendering like this:

`<a class="animation href=" https:="" instagram.com="" p="" 6h9olecpwx="" "="" style="width: 480px;">`

If I remove the template, I can click the thumbs normally but not when using the templating functionality.

Any solution/workaround for this, please?

Thanks for such great plugin! :)

**Comment by stevenschobert** [comment]
Are you using any special hosting platforms, or tempting languages? For example Tumblr, Squarespace, Jeklly, etc.

**Comment by jtwhite14** [comment]
Having the same problem as@BeatLaG. Using Django via Cactus. Any suggestions?

**Comment by BeatLaG** [comment]
Hi @stevenschobert,

not really, this is a plain HTML document by now. We are implementing the site into WP now but the problem is there since that basic HTML markup was written. Any workaround in order to get fixed this, Steven?

Thanks for your reply :)
