### ISSUE TITLE
Is it possible to have different instagram account to show different feed in instafeed?

### ISSUE THREAD

**Issue by waisie** [stevenschobert/instafeed.js#298]
I was trying to do this. So I can have more than one feed. I will have 4 different instagram feed. I send the screenshot. When I click “the bravesoftheworld hashtag btn”, it should give me bravesoftheworld  images about that hashtag. 

![screen shot 2015-08-18 at 3 07 10 pm](https://cloud.githubusercontent.com/assets/6139379/9386373/37e3c0fe-4729-11e5-8a86-9ad6fe56b53f.png)

I look forward to hearing from you.
Thank you

**Comment by stevenschobert** [comment]
Yeah, you can run as many instances of Instafeed on a page as you want.

See #12.
