### ISSUE TITLE
Is it possible to do infinite scroll instead of load more button?

### ISSUE THREAD

**Issue by waisie** [stevenschobert/instafeed.js#300]
I want to do something like this. When you keep scrolling new images will come up like pinterest.
https://www.pinterest.com/

also when I do the load more button, it will works, but when I click load more, more images are showing up but it will show the top images first not from the bottom one. Do you know why? But I also want to know how to do the infinite scroll for instafeed.

**Comment by jerewall** [comment]
```javascript
   
 $(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() == $(document).height()) {
       
         // call feed.next() once the page reaches the bottom
		 
		 waiseiFeed.next();
 
     }
});

```

**Comment by waisie** [comment]
Is this right? it doesn't work. let me know if i did something wrong. I put the code in the head section.

    <script>
     jQuery(document).ready(function(){

    $(window).scroll(function() {
    if($(window).scrollTop() + $(window).height() == $(document).height()) {

          var userFeed = new Instafeed({
	        get: 'user',
	        userId: XXXX,
	        accessToken: 'XXXX',
	        limit: 12,
	        resolution: 'low_resolution',
	        template: '<div class="insta-wrap grid"><img src="{{image}}" /><a class="grid-link" href="{{link}}" target="_blank"></a></div>'
	    });
	    userFeed.run();

        userFeed.next();
          }
        });
      });
    </script>

**Comment by jerewall** [comment]
Not quite.. but almost Lol

the function itself runs in Javascript, not jQuery, the calculation of next is done with jQuery. 

Try this:

```javascript

<script>
     jQuery(document).ready(function(){
      
    $(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() == $(document).height()) {
          // call feed.next() once the page reaches the bottom
 		 userFeed.next();
 
     }
});
   
      });
</script>
 
 <script type="text/javascript">
  
var userFeed = new Instafeed({
      get: 'user',
        userId: XXXX,
        accessToken: 'XXXX',
        limit: 12,
        resolution: 'low_resolution',
       template: '<div class="insta-wrap grid"><img src="{{image}}" /><a class="grid-link" href="{{link}}" target="_blank"></a></div>',
 
    });
 
         userFeed.run();
     
</script>

```

**Comment by waisie** [comment]
Thks Jerewall. it works. but when I refresh the page all images show at once . Is that normal?

**Comment by jerewall** [comment]
Only if you're already scrolled to the bottom.. Scroll back to top then
refresh.

**Comment by waisie** [comment]
oh so that is normal?

**Comment by waisie** [comment]
is it possible to start from the top if i already scrolled to the bottom  when i refresh?

**Comment by waisie** [comment]
is it okay to put in the main.js file?

**Comment by jerewall** [comment]
Yes.

**Comment by waisie** [comment]
how ?

**Comment by waisie** [comment]
can u show me? thank you

**Comment by waisie** [comment]
@jerewall  I try it and it doesn't work. Can you show me ? Thank you...

**Comment by waisie** [comment]
@jerewall how do I put the code in main.js?

**Comment by waisie** [comment]
I put the code in main.js and it works. But the scrolling doesn't work in mobile. Do you know why?
