### ISSUE TITLE
Limit Issue -- Setting to 60 always returns 33

### ISSUE THREAD

**Issue by relish27** [stevenschobert/instafeed.js#303]
Hello.  This is a great plugin, so thanks.

One issue is that I want to pull in as many as possible.  I tried with tags that I can verify have more than 60... and they always return 33.  If I don't set the limit, then it returns 20.  Seems like something odd is going on with the limit option.  Do you see this, too?

**Comment by hahahalif** [comment]
I'm getting this too, exactly the same issue! I thought I was the only one.

**Comment by nickmblain** [comment]
+1 This. I had to get around it using feed.next() until I reach the desired amount of images. It isn't slow and seems to work so I'll leave it as of now. I think the instagram api will only return 40 anyways...
