### ISSUE TITLE
how do you add extra instafeed div for the html file?

### ISSUE THREAD

**Issue by waisie** [stevenschobert/instafeed.js#304]
for example, if i have 2 or more instagram feed.
How can I make it to 2 or more instafeed in the html file?
I will have 2 or more button for different instafeed.I can't use it for the second time since its an ID.
        <div id="instafeed"></div>

**Comment by garand** [comment]
You want the same feed of images in two different divs?

**Comment by waisie** [comment]
yes, but i solve the problem. thank you.

**Comment by garand** [comment]
Awesome, can you close out the issue?
