### ISSUE TITLE
Wrong .bower.json

### ISSUE THREAD

**Issue by octavioamu** [stevenschobert/instafeed.js#306]
missing "main": "instafeed.min.js", for wiredep work. in bower installation

**Comment by stevenschobert** [comment]
Sorry @octavioamu, not sure I follow. What issue are you having?

**Comment by octavioamu** [comment]
The bower package have the .bower.json like this:
```
{
  "name": "instafeed.js",
  "homepage": "https://github.com/stevenschobert/instafeed.js",
  "version": "1.3.2",
  "_release": "1.3.2",
  "_resolution": {
    "type": "version",
    "tag": "v1.3.2",
    "commit": "148b6dec6eceeb8a5512e815a82ba7869beb3197"
  },
  "_source": "git://github.com/stevenschobert/instafeed.js.git",
  "_target": "~1.3.2",
  "_originalSource": "instafeed.js"
}
```
And should be like this:
```
{
  "name": "instafeed.js",
  "homepage": "https://github.com/stevenschobert/instafeed.js",
  "version": "1.3.2",
  "main": "instafeed.min.js",
  "_release": "1.3.2",
  "_resolution": {
    "type": "version",
    "tag": "v1.3.2",
    "commit": "148b6dec6eceeb8a5512e815a82ba7869beb3197"
  },
  "_source": "git://github.com/stevenschobert/instafeed.js.git",
  "_target": "~1.3.2",
  "_originalSource": "instafeed.js"
}
```

Because grunt wiredep ( a plugin to automatic injection of the bower packages into the html) need this to know how to create the link inside the html files.

For example in this case the plugin will create the link
```
<script src="bower_components/instafeed.js/instafeed.min.js"></script>
```

**Comment by davidyeiser** [comment]
This was an issue for me as well. Added the "main" and it worked fine afterwards.

Running gulp command wasn't building it into main.js.

File updated was: /bower_components/instafeed.js/package.json

**Comment by octavioamu** [comment]
@davidyeiser recommend you to use the bower overrides in bower.json of your project and not inside bower_components. 
The way you do gulp will override in any npm update of the project or when you decide to install again etc. Yo never should modify anything inside "bower_components" this can be overrided in many situations, instead write this in /bower.json :
```
"overrides": {
    "instafeed.js": {
      "main": [
        "instafeed.min.js",
      ]
    }
  },
```

**Comment by davidyeiser** [comment]
Ah, good to know, this is very helpful. Thank you for taking the time to mention it.

**Comment by mocon** [comment]
Thank you guys! This fixed my issue with `gulp wiredep` perfectly. This is an awesome tool @stevenschobert!

**Comment by octavioamu** [comment]
specs about main https://github.com/bower/spec/blob/master/json.md#main 
Again, this is "recommended" but must be required since a lot of tasks runners need it to know what files to inject in the project for the plugins works fine, otherwise people need to write the calls manually.
