### ISSUE TITLE
How to just get images?

### ISSUE THREAD

**Issue by klombomb** [stevenschobert/instafeed.js#309]
Am i missing something or is it not possible to just get images?
Without the video thumbnails in between?

Thanks :+1:

**Comment by garand** [comment]
It's not possible currently, but the API returns a `type` value in the JSON that is either `image` or `video`, so it is possible to add in an option to only return one type or another.

**Comment by klombomb** [comment]
Sounds like a good idea. Thanks for answering anyway!

**Comment by stevenschobert** [comment]
Hey @klombomb!

You should be able to use the `filter` option for that:

```js
var feed = new Instafeed({
  // other settings...
  filter: function(image) {
    return image.type === "image";
  }
});
feed.run();
```

**Comment by klombomb** [comment]
@stevenschobert Thank you! It works fine. The only problem is that it filters the posts it has already fetched and not while it is fetching them.
