### ISSUE TITLE
Question: How often do I have to change the access token?

### ISSUE THREAD

**Issue by jlevinsohn31** [stevenschobert/instafeed.js#31]
Love the plugin. Using it to get specific user's photos and it works great. I was wondering how often I have to switch out the access token though? I used the tool on your site to grab the access token and just pasted it in my js. Does that access token ever have to update?

Thanks for any help.

**Comment by solcre-at** [comment]
**Short answer**
Never _(for now)_

@stevenschobert nowadays it keeps working of the same way or the access tokens have expiration?
