### ISSUE TITLE
Add option to only display images or videos 

### ISSUE THREAD

**Issue by garand** [stevenschobert/instafeed.js#310]
The API returns a `type` value in the JSON that is either `image` or `video`. There should be an option here to only display one, or both, of these.

**Comment by stevenschobert** [comment]
Might not be very straight-forward, but you should be able to do this now, via a `filter`:

```js
var feed = new Instafeed({
  filter: function(image) {
    return image.type === "image";
  }
});
```

**Comment by lmartins** [comment]
While filter does work, it also changes the total number of tiles displayed, that is if I ask for 10 images and two of them are videos, I end up with just 8 images. Any way to get around this?

**Comment by stevenschobert** [comment]
@lmartins yeah unfortunately the `filter` is applied _after_ the API call, so it doesn't take the `limit` into account.

You can work around it by keeping track of the limit yourself inside your filter: http://stackoverflow.com/questions/39534166/javascript-instafeed-js-limit-with-filters/39536776#39536776
