### ISSUE TITLE
Templating output is empty

### ISSUE THREAD

**Issue by timdonaldson** [stevenschobert/instafeed.js#311]
I've just set up this app on the site and it works fine with the basic markup:
```
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'littlebigmarkets',
        clientId: 'YOUR_CLIENT_ID'
    });
    feed.run();
</script>
```
But when I try this with the basic templating example code:
```
  <script type="text/javascript">
    var feed = new Instafeed({
      get: 'tagged',
      tagName: 'littlebigmarkets',
      clientId: 'YOUR_CLIENT_ID',
      limit: 6,
      template: '<a href="{{link}}"><img src="{{image}}" /></a>'
    });
    feed.run();
  </script>
```
the output is empty:
```
<div id="instafeed">
   <a href="">
      <img src="">
    </a>
</div>
```

Is there a special trick or something that I'm overlooking here?

**Comment by garand** [comment]
Can you post your javascript here?

**Comment by timdonaldson** [comment]
Sorry Garand, the script should be displaying now : )

**Comment by yayromina** [comment]
I am also having this issue

**Comment by timdonaldson** [comment]
Nice to hear I'm not the only one! I still haven't been able to determine whether this is an issue with instafeed.js, my site, hosting (it's a shopify site) or my instagram account.

Would anyone have an guess as to were the problem might be arising?

**Comment by yayromina** [comment]
My site is also on Shopify.  Interestingly, I used the same script/template for a non-SSL site, and it is still working correctly.  But all the sites that I've used this on that use HTTPS, instafeed has stopped working.

**Comment by yayromina** [comment]
Here is my script, with the only variations between the working and non-working instances being the userId and accessToken, and HTTPS

var userFeed = new Instafeed({
        get: 'user',
        userId: XXX,
        accessToken: 'XXX',
        template: '<div class="gram"><a href="{{link}}" target="_blank"><img src="{{image}}" /></a></div>',
        limit: 4,
        resolution: 'low_resolution'
    });
    userFeed.run();

**Comment by stevenschobert** [comment]
@timdonaldson @yayromina Hey folks! If you are having problems with the `template` option on your Shopify site, please take a look at issue #318. :)

**Comment by timdonaldson** [comment]
Awesome, thanks for that Steven!
