### ISSUE TITLE
Is there a way to get more than one tagName?

### ISSUE THREAD

**Issue by nickmblain** [stevenschobert/instafeed.js#314]
I have succesfully made a instagram photowall that serves as a background. I would now like for that background to pull images from two tags. Does anyone know how I can accomplish this?

**Comment by greystate** [comment]
It doesn't seem possible even in the API - also, [this StackOverflow article](http://stackoverflow.com/questions/19698547/how-to-add-more-tags-when-using-instagram-api) has the same answer...

**Comment by nickmblain** [comment]
Thank you for your reply greystate

**Comment by stevenschobert** [comment]
@nickmblain @greystate even though the API doesn't support it, you can create multiple instances of Instafeed.js on a single page. See #12.
