### ISSUE TITLE
1080x1080 resolution

### ISSUE THREAD

**Issue by 9kolaj** [stevenschobert/instafeed.js#317]
Hi,

I'm using instafeed.js and was wondering if it will be possible to use the new 1080x1080 resolution.

Not sure if this is the place to ask, so bare with me.

**Comment by 9kolaj** [comment]
anyone?

**Comment by kristiandavid** [comment]
Not sure if you're still looking for this, and this isn't the best solution ever but I updated instafeed.js around line 143 and i now get 1080 x 1080 images.

<pre>
if(this.options.resolution == 'standard_resolution'){
              imageFull = imageObj.url.replace("s640x640","s1080x1080");
              imageUrl = imageFull;
            } else{
              imageUrl = imageObj.url;  
            }
 </pre>

**Comment by onedrawingperday** [comment]
Thank you for the tip @kristiandavid ! I inserted your code right after line 193 of instafeed.js and it fetched 1080 X 1080 images but the image quality was not any good.

The images returned were very sharpened with jagged edges and in some cases they were larger than their original resolution. (In the past I had uploaded to Instagram a few images at 1040 X 1040 thanks to a misinformed blog post)

Anyway I looked a bit into how Instagram handles images and I found the following trick to access the original high resolution photo without any bizarre sharpening.

Change the second line of your code to:
<pre>
imageFull = imageObj.url.replace("/s640x640/sh0.08/","/");
</pre>

Et voilà! High res AND great quality!

**Comment by kristiandavid** [comment]
Nice! You're right, looks much better!

**Comment by 9kolaj** [comment]
Hi,

Im back - Sounds great however I dont know where to paste the code in the  instafeed.min.js file...

When I open it in notepad++ its one very long line. 

Hope you can help me?

**Comment by kristiandavid** [comment]
Hey @9kolaj, you need to make the change in the unminified file (instafeed.js) and then use the makefile in the minify it.

I've forked the repo and provided the updated minified folder here : https://github.com/kristiandavid/instafeed.js

hope that helps!

**Comment by rocco0734** [comment]
Hello @kristiandavid @onedrawingperday,

I followed the steps and made the change in the unminified file but no dice. it works but I'm still getting standard sized images. Any ideas as to why this is happening?

Would greatly appreciate any help

**Comment by rocco0734** [comment]
anyone?

**Comment by FloBorg** [comment]
same for me, i have the new instafeed.js but same image quality.

**Comment by danfiscus** [comment]
I am also unable to get the solutions here to work :frowning:

**Comment by sogen1us** [comment]
Hey @kristiandavid several users have complained that this fix isn't working. I myself have tested its functionality and can't seem to get it to work. Are there any extra configuration that needs to be added to make this work? I even tried copying your `instafeed.js` and `instafeed.min.js` from the [repo you listed above](https://github.com/kristiandavid/instafeed.js), and it doesn't pull 1080x1080 images. If anyone has a solution, please advise. Thanks all!

**Comment by z8137** [comment]
Have to agree with the user above, tried inserting the code listed above and no beuno. Also tried adding the one from the repo and still nothing. Hopefully we can find a way to pull high-res images!

**Comment by kristiandavid** [comment]
Hey folks, you're right, the code above no longer works.  Instagram must have caught on and updated that. I'm no longer using instafeed, instead I just use the Instagram API and use .replace with some regex to get the full size image.
`var image = response.data[i].images.standard_resolution.url;
  var imageLarge = image.replace(/s[0-9]+x[0-9]+\/(sh[0-9]+.[0-9]+\/)*/,"");`

Hope that helps.

**Comment by benjamin-hull** [comment]
Unfortunately workarounds like this, that are based on re-writing the image URL, no longer work, as instagram now enforce signed URLs for images in their CDN.
