### ISSUE TITLE
Shopify template conflicts, no images on page

### ISSUE THREAD

**Issue by stevenschobert** [stevenschobert/instafeed.js#318]
If you are trying to use the `template` option on a Shopify site, and you aren't seeing any images on your page, you're probably experiencing conflicts with Shopify's own templating system, and Instafeed.js'. Shopify uses [liquid](https://github.com/Shopify/liquid) for it's tempting language, which has the same curly brace `{{ var }}` syntax as Instafeed.js' templates. This causes Shopify to see the `template` option on your page, and tries parse it before it ever gets to Instafeed.js.

To work around this, try assigning your template to a variable in Shopify's template, then printing it out for Instafeed.js to use:

```html
{% assign instafeed_template = '<a href="{{link}}"><img src="{{image}}" /></a>' %}

<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: 'YOUR_CLIENT_ID',
        template: '{{ instafeed_template }}'
    });
    feed.run();
</script>
```

**Comment by hopk1ns87** [comment]
Been searching all over for an answer to this, thank you!
