### ISSUE TITLE
Background image missing /

### ISSUE THREAD

**Issue by hartey11** [stevenschobert/instafeed.js#322]
Hi,

I'm trying to use the Instagram images as a background image but the / in the URL are missing. When its an img src the links work fine! Any idea when the / disappear when its made into a background image?

Current template code
template: '<li style="background-image: url("{{image}}");"><img src="{{image}}"><a href="{{link}}" title="{{caption}}" target="_blank"><div><p>{{likes}}</p></div><div><p>{{comments}}</p></div></a></li>'

Generated content:
"background-image: url(" https:="" scontent.cdninstagram.com="" hphotos-xaf1="" t51.2885-15="" e35="" 11363830_1669856036634959_1782926698_n.jpg");"=""

src="https://scontent.cdninstagram.com/hphotos-xaf1/t51.2885-15/e35/11363830_1669856036634959_1782926698_n.jpg"

**Comment by FlorianSteller** [comment]
@hartey11 just try to remove the quotes from `url(  )` 

`template: '<li style="background-image: url( {{image}} );">`

**Comment by eleumas** [comment]
I have the same problem. Someone have a solution? This is my link: https://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/21107162_1760194814008241_3230612483802660864_n.jpg
