### ISSUE TITLE
Setting a standard size when using get= 'user'

### ISSUE THREAD

**Issue by vethcl** [stevenschobert/instafeed.js#323]
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: YOUR_USER_ID,
        accessToken: 'YOUR_ACCESS_TOKEN'
    });
    userFeed.run();
</script>

Where/what would I enter to make all of the images a standard, flush size with each other? Regardless of the image size on Instagram itself? 
![untitled](https://cloud.githubusercontent.com/assets/14909975/10199077/16d4fdce-676d-11e5-80b5-2be007b9f67d.png)

I tried doing as so, but it did not work: 

<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: YOUR_USER_ID,
        accessToken: 'YOUR_ACCESS_TOKEN'
        resolution: standard_resolution
    });
    userFeed.run();
</script>
 
Thank you!

Christian

**Comment by vethcl** [comment]
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: YOUR_USER_ID,
        accessToken: 'YOUR_ACCESS_TOKEN'
        resolution: standard_resolution
    });
    userFeed.run();
</script>
 This is what I tried adding, but it did not work.

**Comment by vethcl** [comment]
It won't let me add the code I typed?

**Comment by vethcl** [comment]
Here is a picture of the code I added (highlighted in red) but it did not work. 
![untitled2](https://cloud.githubusercontent.com/assets/14909975/10199337/370ae53a-676e-11e5-8c5b-fe93a5a3b58e.png)

**Comment by gbrandallen** [comment]
I think you need a comma after access:Token

**Comment by gbrandallen** [comment]
so it would read:

    <script type="text/javascript">
        var userFeed = new Instafeed({
            get:   'user',
            userID: YOUR_USER_ID,
            accessToken:'YOUR_ACCESS_TOKEN',
            resolution: standard_resolution
	});
    </script>
```

**Comment by vethcl** [comment]
Hmmm I tried that, however anytime I enter ANYTHING under this particular script, it causes the instafeed not to appear. Any ideas?

**Comment by gbrandallen** [comment]
Here's exactly how I have it set up on my page and it works great (i'm using it in wordpress so the javascript path is going to look a little funky):

```
<script type="text/javascript" src="<?php bloginfo('stylesheet_directory'); ?>/javascripts/instafeed.min.js"></script>
  <script type="text/javascript">
    var feed = new Instafeed({
       get: 'user',
       userId: YOUR_USER_ID,
       accessToken: 'YOUR_ACCESS_TOKEN',
       resolution: 'standard_resolution',
       limit: 4,
       template: '<a class="fancybox" rel="instagram" href="{{model.images.standard_resolution.url}}"><img class="instagram-image" src="{{image}}" /><div class="overlay"><p>{{caption}}</p></div></a>'
    });
       feed.run();
</script>
```

**Comment by vethcl** [comment]
Looking at yours, I noticed all it was is I forgot to put the comma as you said, and the apostrophes before and after the specified resolution. Thank you!

**Comment by gbrandallen** [comment]
I'm glad it helped.

**Comment by vethcl** [comment]
Do you know of a way to center align the pictures and text?

**Comment by gbrandallen** [comment]
Thats all done with CSS. If you look at my example that I posted, the "template" line item shows an example of putting together some html markup together with instafeed. From there just apply CSS.
