### ISSUE TITLE
Shopify + filter function

### ISSUE THREAD

**Issue by mattatwildly** [stevenschobert/instafeed.js#325]
I've been trying to implement the filter function that Steven has mentioned in several posts. When I place it in my code, all my images disappear. I've also read about some other issues with Shopify but don't know if they are applicable. Any suggestions?

My code:
 var feed = new Instafeed({
            get: 'tagged',
            tagName: $target.data('tag-name'),
            clientId: $target.data('client-id'),
            resolution: "low_resolution",
            limit: $target.data('count'),
            template: '<div class="one-fifth column"><a href="{{link}}" target="_blank"><img src="{{image}}" alt="{{caption}}" /></a></div>'

```
    });
      feed.run();
```
# 

When I place the following in my code, it breaks:
filter: function(image) {
  var blockedUsernames = [
    'username1',
    'username2'
  ];

  for (var i=0; i<blockedUsernames.length; i++) {
    if (image.user.username === blockedUsernames[i]) {
      return false;
    }
  }

  return true;
}

**Comment by blindMoe** [comment]
Try wrapping your < script > block in {% raw %} and {% endraw %} liquid tags
