### ISSUE TITLE
Instagram now uses new image sizes

### ISSUE THREAD

**Issue by jordanoverbye** [stevenschobert/instafeed.js#328]
As some of you may know, Instagram now allows all sorts of image dimensions (not just a square). However, Instafeed.js always pulls in a square photo. This causes some white margins around each photo.
Has anyone found a way around this?

**Comment by ekauffer** [comment]
Came here to ask this. I hope the API isn't limiting us to squares!

**Comment by stevenschobert** [comment]
I haven't seen any additions to the API that would allow me to grab the new image sizes.

The last time I checked, we still only have the same 3 entries in the `images` object:
```json
  "images": {
"images": {
  "low_resolution": {
    "url": "http:\/\/distilleryimage11.s3.amazonaws.com\/da687d12e2b611e2b20722000a1f97fa_6.jpg",
    "width": 306,
    "height": 306
  },
  "thumbnail": {
    "url": "http:\/\/distilleryimage11.s3.amazonaws.com\/da687d12e2b611e2b20722000a1f97fa_5.jpg",
    "width": 150,
    "height": 150
  },
  "standard_resolution": {
    "url": "http:\/\/distilleryimage11.s3.amazonaws.com\/da687d12e2b611e2b20722000a1f97fa_7.jpg",
    "width": 612,
    "height": 612
  }
}
```

And those URLs correspond to images that have the white border around them.

Please let me know if anyone is able to discover something different.

**Comment by ekauffer** [comment]
I think it's possible!

http://developers.instagram.com/post/128288227716/api-migration-for-landscape-and-portrait-formats

"This is done by enabling a new setting called Migrations in the “Edit Client” dashboard."

**Comment by jesseyuen** [comment]
Great minds think alike. Also looking for a solution...

**Comment by stevenschobert** [comment]
Cool, thanks @ekauffer, I should have checked the blog. I'll have to dig into that.

Interested that its an "opt-in" feature currently. I'm not sure yet how that will affect this library.

**Comment by ekauffer** [comment]
I was wondering the same. Maybe we can also have an option to "opt-in" with instafeed? Off my default but there if required.

That way nothing will change for those who already have styles based on the square format.

**Comment by nothingrandom** [comment]
+1 on this. I'd really like to be able to crop the white margins. On instagram, when browsing your feed, you see all square images; even if it's been shot as a different dimension. Something similar to that via this plugin would be fantastic.

**Comment by stevenschobert** [comment]
Hey everyone! I released an update today [v1.4](https://github.com/stevenschobert/instafeed.js/releases/tag/v1.4.0) that includes instructions on using the new sizes, as well as a few template helpers to work with the varying image sizes.

Hope it helps! :tada:

**Comment by jordanoverbye** [comment]
Thank you Steven. Works perfect.

**Comment by ekauffer** [comment]
Thank you Steven!

**Comment by 123ndy** [comment]
Hi! I can't make it work. What is the solution to display images without white bars if non-square image? :) (Could anyone provide an example?)
