### ISSUE TITLE
Error from Instagram: The client_id provided is invalid and does not match a valid application.

### ISSUE THREAD

**Issue by rimbaudhotel** [stevenschobert/instafeed.js#331]
Was working well until recently, when I started to get this error: Error from Instagram: The client_id provided is invalid and does not match a valid application.

I am not using a client ID but rather a user ID to get images from one user.

Any ideas why this is happening?

**Comment by stevenschobert** [comment]
Strange. I've not seen that before. Are you using your own client id?

**Comment by rimbaudhotel** [comment]
I have since fixed it. I was originally not using a client ID, I just took the code from the example of the instafeed website which didn't include a client ID. After getting the error and playing around a bit I created a client ID and added it to the code and it worked again.
