### ISSUE TITLE
Script tag not removed from header when mock is set to true

### ISSUE THREAD

**Issue by mabrodeur** [stevenschobert/instafeed.js#332]
In instafeed.js, you remove the script tag from the header is "mock" is set to false. 
Line 186-187:

``` javascript
header = document.getElementsByTagName('head')[0];
header.removeChild(document.getElementById('instafeed-fetcher'));
```

Line 126: 

``` javascript
if ((typeof document !== "undefined" && document !== null) && this.options.mock === false) 
```

The script should be removed if mock is true. Otherwise, the header is filled with a lot of script tags when you call .run() multiple times which can cause problems.

**Comment by stevenschobert** [comment]
Ah wow. Good find! You're the first to report that, and that option was released years ago.

I'll have to take a look and get it patched.
