### ISSUE TITLE
Issue with "username/client ID required " browser Dialogue Box popup on page load

### ISSUE THREAD

**Issue by colehpage** [stevenschobert/instafeed.js#333]
Hi,

So I'm embedding instagram photos from my account to div on my front page. This all works great, and the images show up perfectly, but I can't seem to fix one big issue and I haven't seen anyone else mentioning it so I'm not sure whats going on. On page load I get a browser dialogue box popup that you have to close or check not to see again. I can't have this. The error says:

"Both a Client ID and Instagram username are required to display Instagram profile images."

But I have my client ID, access token, and user ID and the instagram feed from my account is showing up fine, so what is this asking me and how do I have it not appear. Tried everything and looked all over the internet for a solution and I am at a loss. This happens on all browsers. Thanks for the help in advance.

**Comment by amandeepsinghvirdi** [comment]
Its not a bug in instafeed. You might be using Instagram Lite as well. So both plugins are working same time and instagram lite will be causing this error. So check your common js file and add comment to instagram lite function call.
