### ISSUE TITLE
Add "video" Class for Type of Post - [feature request]

### ISSUE THREAD

**Issue by nortin** [stevenschobert/instafeed.js#336]
on instagram video posts are recognizable by a play-button. 
if a the Class "video" would be added to the link-tag, it could be styled in an appropriate way...
it could be solved optionally by making it an option for individual theming ?! ...eg. {post-type} ...returning or "imgage" or "video"

Thanks so much

**Comment by stevenschobert** [comment]
In [v1.4](https://github.com/stevenschobert/instafeed.js/releases/tag/v1.4.0), you should be able to use `{{type}}` in the template option to do that:

```js
template: '<a class="instagram-{{type}}" href="{{link}}"><img src="{{image}}" /></a>'
// would result in:
// <a class="instagram-image" ...
// or <a class="instagram-video" ...
```

You should then be able to use CSS to style the items differently:
```css
.instagram-image {
}

.instagram-video {
}
```

**Comment by nortin** [comment]
wonderful - thank you so much for the fast update ...exactly as needed !
