### ISSUE TITLE
Filter images with a certain word in comments?

### ISSUE THREAD

**Issue by filipblaauw** [stevenschobert/instafeed.js#339]
As a little workaround for filtering unwanted images, I need to filter out images that have a certain word in one of the comments.

I tried something like this,

    filter: function(image) {
        return image.comments.data('bannedimage') === -1;
      }

But this is not a function, and the image.comments.data will have a variable array length. Any idea how I can get this to work? Basically search the comments for a specific word, and don't display the image if the word "bannedimage" is present.

**Comment by stevenschobert** [comment]
You're probably looking for something like this:

```js
filter: function(image) {
  var keyword = 'bannedimage';
  var allowed = true;
  var comment;

  if (image.comments && image.comments.data) {
    for (var i=0; allowed && i < image.coments.data.length; i++) {
      comment = image.comments.data[i];
      if (comment.text && comment.text.indexOf(keyword) >= 0) {
        allowed = false;
      }
    }
  }

  return allowed;
}
```

**Comment by filipblaauw** [comment]
This looks like the right solution, I agree. But I get `Uncaught TypeError: Cannot read property 'data' of undefined.`

Here's my complete code, loaded right before `</body>` tag:

    var feed = new Instafeed({

      filter: function(image) {
        var keyword = 'bannedimage';
        var allowed = true;
        var comment;

        if (image.comments && image.comments.data) {
          for (var i=0; allowed && i < image.coments.data.length; i++) {
            comment = image.comments.data[i];
            if (comment.text && comment.text.indexOf(keyword) >= 0) {
              allowed = false;
            }
          }
        }
        return allowed;
      },
      tagName: 'taggedimage',
      limit: 8,
      template: '<img src="{{image}}" />'
    });

**Comment by stevenschobert** [comment]
@filipblaauw Ah, sorry about that. I goofed typing up that snippet. Glad you found the typo! I updated my original reply with the correction.
