### ISSUE TITLE
UserFeed issues + template

### ISSUE THREAD

**Issue by martinltz** [stevenschobert/instafeed.js#340]
Hello!
i need some help with this please
when i use templates with " get Tag" it works fine , but it not works with "get User"
here is the code
    var userFeed = new Instafeed({
        get: 'user',
		limit: '20',
        userId: myuserid,
        accessToken: 'myaccesstoken'
		template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /></a>'

});
userFeed.run();

also i tried this but same result 
//
    var feed = new Instafeed({
        get: 'user',
		limit: '1',
        userId: myuserid,
		accessToken: 'myaccess'
		template: '<a href="{{link}}" target="_blank"><img src="{{image}}"/></a>',

    });
    feed.run();
//
when i removed template line it works fine
but with templates no images and no divs and no data at all for user 
how i can use the template with user feed?

**Comment by martinltz** [comment]
//
    var userFeed = new Instafeed({
        get: 'user',
		limit: '20',
        userId: myuserid,
        accessToken: 'myaccesstoken'
		template: '<a href="{{link}}" target="_blank"><img src="{{image}}" />'

});
userFeed.run();
//

**Comment by martinltz** [comment]
also i tried this but same result
//
    var feed = new Instafeed({
        get: 'user',
		limit: '1',
        userId: myuserid,
		accessToken: 'myaccess'
		template: '<a href="{{link}}" target="_blank"><img src="{{image}}"/></a>',

    });
    feed.run();
//
when i removed template line it works fine
how i can use the template with user feed?

**Comment by stevenschobert** [comment]
What errors are you seeing in your console @martinltz ?
