### ISSUE TITLE
Display images without white bars if non-square image

### ISSUE THREAD

**Issue by rorysmorris** [stevenschobert/instafeed.js#341]
At the moment this plugin returns 'standard_resolution' images with white bars top and bottom or left and right, if the image is uploaded to instagram as a non-square image.

Setting it to return 'thumbnail' images resolves this issue, but this is way too low resolution for my app.

How can I change the code to return standard resolution images that are cropped to square? 

This may help? http://stackoverflow.com/questions/32259367/will-instagram-serve-square-thumbnails-for-portrait-landscape-images

**Comment by stevenschobert** [comment]
@rorysmorris Please see the section title ["Portrait and Landscape Photos"](https://github.com/stevenschobert/instafeed.js/tree/11447a0298273e0679225457b7720a98d0dba94c#portrait-and-landscape-photos) in the readme.

Also see #328.

**Comment by rorysmorris** [comment]
Thanks @stevenschobert

**Comment by jennybeaumont** [comment]
Heya, I'm still getting this, though I have updated to latest version and info says this is only true before June 1, 2016. Ideas for how to get rid of margins? Have res set to standard, and template orientation set to square. Thnx!
