### ISSUE TITLE
Not showing all Images

### ISSUE THREAD

**Issue by romantwentyeight** [stevenschobert/instafeed.js#343]
I have the problem that on a page I am using this by getting the hashtag, not all the tagged images are shown, if I search on Instagram there are 57images but Instafeed only shows 19.

**Comment by gilbertobitt** [comment]
i'm trying today and i can't make it work the tagged pictures... even copying just the example on the page of the instafeed.js... so i think is almost the same problem!

**Comment by romantwentyeight** [comment]
I solved the "Problem" it was not any Problem with the Plugin, but with the Account Holder (my Client) having his own personal Account as Private, so the Pictures won't show. It can only show public images.

@gilbertobitt Check the pictures you get on your page via instafeed with the images you get if your are NOT logged into Instagram, maybe you had the same misconception

**Comment by gilbertobitt** [comment]
alright.. i will try... but i already logged in! u want see my code?
```html
<html>
<head>
<script src ="instafeed.min.js", type = "text/javascript"></script>
<script>
$(document).ready(function() {  
	var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
		//useHttp: true,
		clientId: '4190c65e5e3e47769b43489d8a032d7f',
		template: '<a href="{{link}}"><img src="{{image}}" /></a>'
	});
	feed.run();
  });
</script>
</head>
<body>
<div id="instafeed"></div>
</body>
</html>```

**Comment by romantwentyeight** [comment]
@gilbertobitt 

Just for the sakes, put the Script after the container and your are missing jQuery befor the instaffed.min.js , if it still isn't working, just answer me here, and I'll send you an E-Mail and we can go step by  step. Because we are really going offtopic here.
