### ISSUE TITLE
Using Tagged but no images are showed!

### ISSUE THREAD

**Issue by gilbertobitt** [stevenschobert/instafeed.js#344]
I think have some king of problem with tagged target becouse i'm trying using the example of the page and don't work but when i trying use to get user pictures it work really fine.. so.. something went wrong and i can't get recent images with the hashtag... and i even try diferents hashtags and even put limit!

**Comment by gilbertobitt** [comment]
<html>
<head>
<script src ="instafeed.min.js", type = "text/javascript"></script>
<script>
$(document).ready(function() {  
	var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
		//useHttp: true,
		clientId: '4190c65e5e3e47769b43489d8a032d7f',
		template: '<a href="{{link}}"><img src="{{image}}" /></a>'
	});
	feed.run();
  });
</script>
</head>
<body>
<div id="instafeed"></div>
</body>
</html>

**Comment by gilbertobitt** [comment]
```<html>
<head>
<script src ="instafeed.min.js", type = "text/javascript"></script>
<script>
$(document).ready(function() {  
	var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
		//useHttp: true,
		clientId: '4190c65e5e3e47769b43489d8a032d7f',
		template: '<a href="{{link}}"><img src="{{image}}" /></a>'
	});
	feed.run();
  });
</script>
</head>
<body>
<div id="instafeed"></div>
</body>
</html>```

**Comment by romantwentyeight** [comment]
Hello gilbertobitt, try the following:

<html>
<head>
</head>
<body>
<div id="instafeed"></div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src ="instafeed.min.js", type = "text/javascript"></script>
<script>
<script type="text/javascript">
    var feed = new Instafeed({
        clientId: '4190c65e5e3e47769b43489d8a032d7f',
        get: 'tagged',
        tagName: 'aswesome',
        template: '<img class="onehundert" src="{{image}}" /><a href="{{link}}"></a>',
        resolution: 'standard_resolution',
        limit: '300',
        sortBy: 'none',
    });
    feed.run();
        feed.next();   
</script>
</body>
</html>

**Comment by romantwentyeight** [comment]
Try adding a jQuery Source and adding the whole Javascript just before the Body tag and after the instafeed ID, and place clientID in front of the the get command. Hope it helps.

**Comment by benjamin-hull** [comment]
This endpoint is no longer supported in IG's API.
