### ISSUE TITLE
'limit' with 'image.type==image'-filter returns the wrong number of images

### ISSUE THREAD

**Issue by 123ndy** [stevenschobert/instafeed.js#346]
Hi,

```javascript
var feed = new Instafeed({
    clientId: CLIENT_ID
    get: 'user',
    userId: USER_ID,
    template: '<img src="{{image}}" style="width: 20%;" />',
    resolution: 'standard_resolution',
    filter: function(image) {
      return image.type === 'image';
    },
    limit: 5
  });
  feed.run();
```
With this code I wish to display five images in my HTML. Instead, it creates 3 `img` tags. 

I think it is because it fetches 5 elements from Instagram, filter out the videos (two of them) and then there is only 3 images left (which it displays). Is this right? If so, would it be a better solution to fetch 5 images from Instagram (instead of 3 images and 2 videos, whitch gives you 3 elements instead of 5)?

**Comment by stevenschobert** [comment]
Hey @123ndy! Sorry for your troubles.

This is one of the current draw backs of using filters. See #97 for more info.

**Comment by 123ndy** [comment]
Ah, ok, thanks for fast reply!
