### ISSUE TITLE
Fetch posts from wrong ID randomly

### ISSUE THREAD

**Issue by himelkazi** [stevenschobert/instafeed.js#347]
Hi,
I am using instafeed.js in one of my wordpress project. My configareation was...

			 var feed = new Instafeed({
		        get: 'popular',
		        target : 'instagram-feed',
		        limit   : 6,
		        sortBy  : 'most-recent',
				template: '<div class="col-xs-4 col-sm-2"><a href="{{link}}" id="{{id}}" target="_blank">'+
								'<img src="{{image}}" alt="">'+
								'<span class="insinfo_con">'+
									'<span class="ins_info_inner">'+
										'<span class="ins_info_in2">'+
											'<span class="in_likeNo"><i class="fa fa-heart"></i> {{likes}}</span>'+
											'<span class="in_commentno"><i class="fa fa-comment"></i> {{comments}}</span>'+
										'</span>'+
									'</span>'+
								'</span>'+
							'</a></div>',
		        accessToken : '475013199.1510000.7c45acb2b9c241e397dd0403c05abb34',
		        userId   : '475013199'

		    });
		    feed.run();

Its fine, everything show properly. But the problem is, its don't post from the referenced account. It fetch post from others account and every refresh it was updated with different post from different account.

**Comment by stevenschobert** [comment]
@himelkazi You need to tell Instafeed.js that you want to fetch images from a user account, by setting the `get` option to `"user"`:

```js
get: "user"
```

**Comment by himelkazi** [comment]
Thank You very much stevenschobert. It's help me a lot. Great plugin and great people !
