### ISSUE TITLE
Access Tokens Invalid

### ISSUE THREAD

**Issue by alexanderperrin** [stevenschobert/instafeed.js#349]
After registering an Instagram client and collecting clientID's, I've implemented instafeed.js to simply collect images under a hashtag.

```javascript
var feed = new Instafeed({
    get: "tagged",
    tagName: "tagName",
    clientId: "51b1e535cb1844a89c695a05adad1274",
});
feed.run();
```

Although the clientID matches what is specified in my application, Instagram is returning the following error:

*The access_token provided is invalid.*

I believe this is due to Instagram's update from the 17th of November 2015.

> Instagram Platform and documentation update. Apps created on or after Nov 17, 2015 will start in Sandbox Mode and function on newly updated API rate-limits and behaviors. Prior to going Live, and being able to be used by people other than the developers of the app, these apps will have to go through a new review process. Please read the API documentation or the Change Log for more details.

> Any app created before Nov 17, 2015 will continue to function until June 2016. After June 2016, the app will automatically be moved to Sandbox Mode if it wasn't approved through the review process. The previous version of our documentation is stil available here.

My app was created after this date and my clientID's throw this error, but other clientID's I've sourced as tests (created before Nov 17) don't throw the error

Having to issue an access token to everyone visiting the website just to see a feed of images isn't suitable. Does this new Instagram update mean that instafeed.js will no longer operate without an access_token, or am I missing something?

**Comment by sergeymakoveev** [comment]
+1

**Comment by alexanderperrin** [comment]
https://github.com/stevenschobert/instafeed.js/issues/345

Issue is already addressed here.

**Comment by joshuajameshunt** [comment]
I'm having this same issue using the following code. I double checked my userId and clientId, and I also messed around with Instagram's developer console with callback URIs and Oauth settings with no luck. It is in sandbox mode.

`var feed = new Instafeed({
	        get: 'user',
	        userId: 'MY_USER_ID',
	        clientId: 'MY_CLIENT_ID'
	    });
	    feed.run();`

**Comment by cwong2k16** [comment]
So.. Any solutions? D:

**Comment by maucincomdos** [comment]
My feed also stopped working. I have not modified any ID or token. Has Instagram changed their policies once again?

**Comment by danielvoicu** [comment]
I think Instagram made some changes, because I've seen this issue with Wordpress plugins too. Been searching for an announcement or something like that for days, but I can't find anything coming from Instagram. No article, changelog or anything.
