### ISSUE TITLE
How to use rel="shadowbox"?

### ISSUE THREAD

**Issue by keithburgie** [stevenschobert/instafeed.js#35]
Would like to load my images in a shadowbox or lightbox. The code below does print out the tag, as in the screenshot, but the shadowbox doesn't work.

```
template: '<a href="{{image}}" rel="shadowbox"><img src="{{image}}" /></a>',
```

Any ideas on how to add this functionality?
![screen shot 2013-09-20 at 11 53 05 am](https://f.cloud.github.com/assets/2370738/1181675/d9a25b10-220c-11e3-82cd-b6cebb77d655.png)

**Comment by benjamin-hull** [comment]
Closing as stale.
