### ISSUE TITLE
Setting limit is returning Uncaught Error

### ISSUE THREAD

**Issue by danneniko** [stevenschobert/instafeed.js#350]
Whenver I set a limit, I get:
Uncaught Error: No images were returned from Instagram

Anyone else had this? this is my code

```
    var feed = new Instafeed({
        sortBy: 'most-recent',
        get: 'location',
        limit: '5',
        locationId: '215160652',
        accessToken: '********************',
        resolution: 'low_resolution',
        template: '<a href="{{link}}"><img src="{{image}}" /></a>'
    });
    feed.run();
```

**Comment by danneniko** [comment]
Oh, when I set limit to '12', then it returns 5 images. Weird

**Comment by admench** [comment]
I'm seeing the same problem of unexpected quantity limit of images. It happens when I run the function:

```
    // filter: function(image) {
    //     return image.tags.indexOf('nps') >= 0;
    // },
```

To limit only posts with a certain hashtag.

**Comment by blueberryln** [comment]
Seeing the same issue when using a filter to get hashtag images

**Comment by spygyper** [comment]
Any update on this issue - I think what is happening is its performing the limit before the filter rather than filtering then limiting the filtered result set.
