### ISSUE TITLE
How do add user and hashtag for instafeed?

### ISSUE THREAD

**Issue by waisie** [stevenschobert/instafeed.js#353]
I want to show my instagram photos and I also want to show other users are using my hashtag.
For example, my hashtag is #braveandco , #bravesminimal , etc...
I want it to show my images that I upload to my braveandco account and I also want to show people who  are use hashtag #braveandco , #bravesminimal, etc.

```
    var feed = new Instafeed({
      get: 'user',
      userId: USER_ID,
      accessToken: 'XXXXXX',
      limit: 12,
      resolution: 'low_resolution',
      template: '<div class="insta-wrap"><img src="{{image}}" /><a href="{{link}}" target="_blank"><div class="likes-wrap"></div></a></div>',
      after: function() {
        if (!this.hasNext()) {
            myButton.hide();
        }
    }
});
});

feed.run();
```

**Comment by ongerit** [comment]
You will need to create new objects for each feed. You can't mash them onto the same feed.
