### ISSUE TITLE
How to get rid of white bars around rectangular photos?

### ISSUE THREAD

**Issue by agenciamilk** [stevenschobert/instafeed.js#354]
Sorry, i know that this issue was dealt with the template helpers on the new update, but i really don´t know how to use it. Can someone show me how should i proceed so every picture is "full", i mean, the picture is zoomed in so no white bars appears? Thanks

**Comment by MeestorHok** [comment]
in your options when initializing the instafeed object, add " resolution: 'standard_resolution' " as an option, this will request the full size images from instagram. Also, on your app page on the instagram site, make sure that the option "non-square media" is turned on, this will tell instagram that it is OK to send you full size pics.

**Comment by ampmtm** [comment]
I'm also a little confused as to how to use the orientation template helpers. I assume this can remedy the issue @agenciamilk is referencing as well as mine.

**Comment by ampmtm** [comment]
@agenciamilk The new `{{orientation}}` template helper allows you to return a value for what orientation that image is: `square`, `landscape`, and `portrait`. So after you turn on the "non-square media" option that @MeestorHok mentions, add that into the template helper in your JavaScript.

Example:

```javascript
template: '<a href="{{link}}"><img class="instagram-{{orientation}} src="{{image}}" /></a>'
```

That'll return a class specific to each orientation of those images so you can target the orientations specifically in your CSS. It seems like a bit of a workaround, but hopefully that helps.

**Comment by Yasp0** [comment]
Yesterday I turned on the option "Non square media" and have the resolution set to "standard_resolution", but still have the white borders on top and bottom. If you turn on the "Non square media" option, should the images immediately change? Or does it take a while?

**Comment by johanaarstein** [comment]
Hi, I still haven't figured out how to use the {{orientation}} feature. What I want to do is to crop and zoom landscape and portrait images so they all display as squares – as they automatically do when you use resolution:'thumbnail'. Exactly what values do you enter in the template section and in CSS in order for this to happen? Awesome if anyone could help me!

**Comment by johanaarstein** [comment]
Finally I figured out how to use the orientation-feature – but I also figured out a way to do what I was trying without using this work-around at all. In the template-section of the js-script, I put: <a style="background:url({{image}}) no-repeat center center;background-size: cover" href="{{link}}" target="_blank"></a>. Then in CSS set a to: display:block;position:relative;width:100%;height:0;padding-top:100%. This allows you to have a feed with standard_resolution images show as zoomed and fitted squares – all responsive and awesome! :)

(100% width and padding is of course just an example. Replace with whatever you like, as long as it's the same value for both. )

**Comment by ejf89** [comment]
@johanaarstein can you plz share an example of the orientation syntax you figured out?

**Comment by johanaarstein** [comment]
@ejf89 Actually I don't remember anymore. Since the background method worked so well I didn't need the old way anymore, so I just deleted it. I guess the idea is you are able to target specific formats in CSS – so something like:

template: '<a class="instagram-{{orientation}} href="{{link}}"><img src="{{image}}" /></a>'

CSS: .instagram-landscape img, .instagram-portrait img { transform: scale(1.5);} .instagram-landscape, .instagram-portrait {overflow:hidden;}

Here's the page I was building: https://www.dylanpanordnorsk.no/#media

**Comment by benjamin-hull** [comment]
Sounds like this one is complete.
