### ISSUE TITLE
Request: {{posted_on}} for template use

### ISSUE THREAD

**Issue by M-Willett** [stevenschobert/instafeed.js#356]
I'm using {{model.created_time}} and converting the string to a user-friendly date just to show "posted 8 days ago" or "posted on ..." - which is quite cumbersome. 
I'm wondering why there isn't a simple {{posted_on}} keyword, seems like a common thing to want on a website.

**Comment by richgcook** [comment]
+1

**Comment by sayapina** [comment]
+1. @M-Willett, May I ask how are you converting it?

**Comment by M-Willett** [comment]
@sayapina I've just been looking through the source history but I have a feeling it was never committed as the client decided to remove the "posted on date" from the design - will updated if I find it.

**Comment by benjamin-hull** [comment]
@M-Willett is correct - `model.created_time` is the timestamp of the post. For converting to a relative time stamp (8 days ago), something like [moment.js](https://momentjs.com/) is ideal. That conversion (and all the options people could want) is quite complex, and not something that should be built in to instafeed.js - moment.js is 16kb on its own.

If you add moment.js, you can use `{{moment(model.created_time).fromNow()}}` or similar to output the relative time.

This is an old one, so I'll close this, but please re-open if needed.
