### ISSUE TITLE
Error from Instagram: This client has not been approved to access this resource.

### ISSUE THREAD

**Issue by manatarms** [stevenschobert/instafeed.js#357]
I submitted my app after the new review process went into place. All I want to do is display my images on my wesite. I asked for basic permission but got an Invalid use case issue in the review feedback not sure what that means. 
Instafeed is throwing an error for client not approved but for some reason Instagram allowed me to go live. So I'm not really sure whats happening and how to proceed. 

Any help is much appreciated.
Thanks

**Comment by programmin1** [comment]
Good question - also, will existing apis work after going through approval?

**Comment by stevenschobert** [comment]
Heya @manatarms! This super disappointing to hear.

Would you mind moving your notes to #345, that's where I'm keeping track of these new API changes.
