### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by bisnuto** [stevenschobert/instafeed.js#358]
Is there a way to update the images in real time, with no need to refresh the page?

**Comment by kristiandavid** [comment]
hey @bisnuto, you ever get this sorted? I'm working on trying to figure it out as well.

**Comment by bisnuto** [comment]
Hey, I just forgot what kind of sort...could you tell me?

2016-02-23 4:43 GMT+07:00 Kristian David <notifications@github.com>:

> hey @bisnuto <https://github.com/bisnuto>, you ever get this sorted? I'm
> working on trying to figure it out as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenschobert/instafeed.js/issues/358#issuecomment-187399471>
> .
>



-- 
<http://nomad.blog.br/>

**Comment by benjamin-hull** [comment]
I'm going to close this one as stale - it's almost definitely outside the scope of instafeed.js anyway.
