### ISSUE TITLE
Videos.

### ISSUE THREAD

**Issue by alir6716** [stevenschobert/instafeed.js#359]
Any option for adding videos onto a site, or is instafeed just for images?

**Comment by evejweinberg** [comment]
https://github.com/evejweinberg/instafeed.js/commit/e370f7a294f1f0a10de28b49883a7a4faed1a088
It only works for standard_resolution for now, but you can access the video variable in the template and change width/height:

template: '<a class="animation" href="{{link}}"><video src="{{video}}" width="200" height="200" autoplay loop muted ></video></a>'

**Comment by alifeinbinary** [comment]
Is {{video}} no longer supported? It doesn't seem to be pulling in the links to videos from feeds for me and it's not mentioned in the documentation.

**Comment by laurelstreng** [comment]
@alifeinbinary - is {{model.videos.standard_resolution.url}} or {{model.videos.low_bandwidth.url}} still working for you? I haven't been able to get either to work in my filter function that gets thrown into my template.

**Comment by alifeinbinary** [comment]
@laurelstreng I'm using {{link}}. Check out this Gist to see how I made it work. https://gist.github.com/alifeinbinary/d2738575bdce3358b24016b9f0f84d09
