### ISSUE TITLE
Request: templating directive for retrieving specific resolutions of the media

### ISSUE THREAD

**Issue by hrag** [stevenschobert/instafeed.js#361]
In my case, I'm building my own media viewer so I want to use a thumbnail then when it's clicked to show the "standard_resolution" version of the image.

A more elegant version of something like:
`{{image.standard_resolution}}`
would be nice.

**Comment by danfiscus** [comment]
Yes! I am doing the same thing with [Intense Images](https://github.com/tholman/intense-images) on [my website](http://danfisc.us/instagram.html) and would love to specify a separate resolution (in my case, I'd like support for `1080x1080` finally) but leave the thumbnails at `low_resolution`.
