### ISSUE TITLE
How do I add different tagname in instafeed?

### ISSUE THREAD

**Issue by waisie** [stevenschobert/instafeed.js#362]
Right now, all the four are showing the same tagName and cliedId. How do I use other tagnames for the other tabs ? The tab is working fine and that is the way I want it. I just want tab 2, tab3, and tab4 showing other tagnames. Can anyone help me? Appreciated.

Check my code.
http://stackoverflow.com/questions/34207489/how-do-i-add-different-tagname-in-instafeed

**Comment by benjamin-hull** [comment]
The SO question linked has been removed, @waisie please re-open this should you still need help.
