### ISSUE TITLE
Deprecated support w/o access_token for newer apps, will be removed in mid 2016

### ISSUE THREAD

**Issue by MaffooBristol** [stevenschobert/instafeed.js#364]
As per https://www.instagram.com/developer/changelog/

It seems that not including an `access_token` has been removed for any apps created after November 17th 2015, and will be removed for **all apps** in April 2016, meaning that when that time comes, all sites using this module will die.

Is there anything we can do to get around this? It seems that they're going to entirely ditch non-authed non-logged-in requests, which seems utterly ridiculous.

**Comment by stevenschobert** [comment]
Hey @MaffooBristol! Yeah, its been a bummer to see these new restrictions go into place. I'm not sure yet what/if anything I can do about it.

Please move your thoughts to #345, there is an ongoing thread about it.
