### ISSUE TITLE
No results for tag 404 does not trigger error callback

### ISSUE THREAD

**Issue by ry167** [stevenschobert/instafeed.js#366]
Using: 

```
var feed = new Instafeed({
    get: 'tagged',
    tagName: 'thistagdoesnotexistandtherearenoresultsforit',
    accessToken: ACCESS_TOKEN,
    error: function(err){
        console.log("Instagram Error: "+err);
    }
});
feed.run();
```

Makes a request like `https://api.instagram.com/v1/tags/thistagdoesnotexistandtherearenoresultsforit?access_token=ACCESS_TOKEN` which returns a 404 web page, not a JSON response.

Then the error callback is also not run, so no action can be taken by the user and the script dies.

I am working on a work-around at the moment which uses [Tag Search](https://www.instagram.com/developer/endpoints/tags/#get_tags_search) in the Instagram API, then iterates the list, and checks if the requested tag exists and has items in it. I will post this when I complete it.

I see there are some other issues mentioning callbacks not working, I am not sure if they are related to this or not. I am also not sure if this is part of Instagram's recent API changes either.

**Comment by HarrisRobin** [comment]
+1

**Comment by ErikVeland** [comment]
+1 [Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (recent, line 0) 
https://api.instagram.com/v1/users/...

**Comment by kalves** [comment]
Hi, i'm having the same issue. Did you fix it ?
Thanks !

**Comment by corexz** [comment]
+1
