### ISSUE TITLE
AccessTokens and Sandboxes

### ISSUE THREAD

**Issue by Ewster** [stevenschobert/instafeed.js#367]
Can I suggest flagging the current issue with new access tokens on the main website? As it stands currently the instructions listed at http://instafeedjs.com/ are misleading for anyone trying to nut out why they are getting the following error:

"Uncaught Error: Error from Instagram: The access_token provided is invalid."

Was glad to have eventually seen the discussion on thread #345, but could have saved half a day of digging and failing.

**Comment by stevenschobert** [comment]
Sorry about that! I haven't had any time to go back and update any documentation. Though I'm not really sure what I would add/change. I don't really have a solid direction to take to deal with the authentication changes yet.

**Comment by Ewster** [comment]
Well I can't be too grumpy because the code works so nicely when you do have a valid access token :)

**Comment by FranciscoG** [comment]
I found the tools on this site helpful:  [http://jelled.com/instagram](http://jelled.com/instagram)

I am still only in sandbox development mode though but I was able to get my access token by doing what they described in their access token post and everything works locally

**Comment by joshuagutierrez** [comment]
@FranciscoG I wasn't able to get my access token using that tutorial...

**Comment by frankzandres** [comment]
Done! Using this URL and enabling implicit oAuth under 'Security' tab on your client:
https://instagram.com/oauth/authorize/?client_id=YOUR_CLIENT_ID&redirect_uri= 	YOUR_ORIGINAL_REDIRECTING_URL&response_type=token&scope=likes+comments+relationships+basic

**Comment by stevenschobert** [comment]
You really don't want to set `scope` to anything other than basic, since the token is essentially public (people can see it in your page source code)

All those other scopes are going to write the token access to post likes on your behalf, etc.

**Comment by jddh** [comment]
Wonderful software. Thank you. But it could really use a one-paragraph preamble at least to the effect that accessToken is now required and one could look eg. at the Jelled site to learn more.

**Comment by stevenschobert** [comment]
@jddh Yea it does need it. Sorry I've been busy with other projects. I'll update it as soon as I get a chance :)

**Comment by Orange-Fox** [comment]
The method, frankzandres suggested to us was really helpful and now I have my photos without white borders! Huge thanks, man!

> frankzandres commented on Jan 29
Done! Using this URL and enabling implicit oAuth under 'Security' tab on your client:
https://instagram.com/oauth/authorize/?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_ORIGINAL_REDIRECTING_URL&response_type=token&scope=likes+comments+relationships+basic

**Comment by black-owling** [comment]
Is there a way to obtain new access token automatically after old one have expired?
