### ISSUE TITLE
Uncaught Error: Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by drfinklestein** [stevenschobert/instafeed.js#368]
Hi there,

I'm new to this, so I might be doing something wrong.

I followed the instructions at: http://instafeedjs.com, but cannot get anything to show up when I load my test html page in a browser.

I think I successfully created a client on the Instagram site and entered the clientId in the html file, but I keep getting this error:

*Uncaught Error: Error from Instagram: The access_token provided is invalid.*

Appreciate any suggestions.

Thanks,

dr-f

**Comment by Ammet** [comment]
I have this issue too.

**Comment by stevenschobert** [comment]
You are seeing that error because of new API restrictions that Instagram introduced last November.

Please see #345 for more information.

**Comment by yuchant** [comment]
@stevenschobert somehow, I'm finding this very difficult to understand. #345 mentions that they are able to pull their own feed without the `access_token` issue. 

Should I be able to pull my own feed with a new Instagram ClientId & the same UserId that generated that ClientId?

**Comment by willpaige** [comment]
I've got three sites that were working but now get 'Uncaught Error: Error from Instagram: The access_token provided is invalid.' I haven't changed anything and my instagram clients are the same.

**Comment by relish27** [comment]
I actually had this working, too, and it just recently stopped working.

**Comment by madduci** [comment]
any update about this error? I was trying to test instafeed.js but I get the same error

**Comment by notflip** [comment]
Any update on this?

**Comment by NickEngmann** [comment]
Any update about this error?

**Comment by TheFrost** [comment]
Hey @NickEngmann, what is the lifetime of the token ?, Can I use it forever ?

**Comment by nanoputian** [comment]
I don't believe that the generated token has an explicit lifetime, only that Instagram don't guarantee that it will be valid 'forever' - seems to be more of a disclaimer to avoid liability than anything else.  If you're only pulling your own Instagram feed then there seems little else to do.  Your 'app' will be in Sandbox mode and you can pull the last 20 of your own posts.  If you need to use instafeed for a client, you'll need to add them as a sandbox user and have them accept the Sandbox invitation, then log into Instagram and use pixelunion to generate a token for their own userID.

**Comment by OneSixFour** [comment]
Thanks @NickEngmann worked for me.

**Comment by ricardogil** [comment]
with @NickEngmann strategy it worked for me. Just remember to use the full accessToken generated in the accessToken js field

**Comment by peanutShells** [comment]
Thank you nick, but can we get tagname not ourself's feed/

**Comment by damasocurto** [comment]
Great,  @NickEngmann it worked for me too..
thanks.

**Comment by jackiboy** [comment]
I had trouble with this myself.

I followed these instructions and got it to work.

[](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

The access token is the token from Step 8. remember to add your client as a sandbox user so you can access their feed.

**Comment by mefynn** [comment]
@jackiboy that url is down. please provide alternative

**Comment by onnoverbeek** [comment]
@jackiboy Thanx for sharing, it was really helpful!

**Comment by Natz162** [comment]
@NickEngmann thanks it worked for me 👍
