### ISSUE TITLE
RESPONSIVE IMAGES

### ISSUE THREAD

**Issue by mayramoca** [stevenschobert/instafeed.js#371]
Is there a way to make the images responsive I have a row of 4 square images and I would like them to adjust to the width of the page in a responsive way

**Comment by MohitHasmukh** [comment]
Try using bootstrap and it will do the job.

**Comment by ongerit** [comment]
@mayramoca- you can achieve this without a framework. Try using %(percent) instead of px(pixels) on the width of your images and that should do the trick. Use media queries to increase the %(percent) of the image for small device widths.

**Comment by benjamin-hull** [comment]
I'm going to close this as stale - it's really a layout question, not an instafeed.js one, anyway.
