### ISSUE TITLE
How to make it work on liquid layouts

### ISSUE THREAD

**Issue by nyuu26** [stevenschobert/instafeed.js#373]
Hi, 

I have tried many times in different ways to make it work on shopify.. but it just doesn't seem to click.. 
Would you know how to do this?

**Comment by Tardis1234** [comment]
I had the same issue. The problem ended up being that Instagram simply didn't approve my app. Take a look at this [discussion](url). For what it's worth it looks like a Shopify employee, @cshold, had the same problem though he may have not been working with Liquid.

**Comment by cshold** [comment]
:+1: @Tardis1234. Not a liquid/Shopify issue. Their API got a revamp and now has much tighter restrictions on its usage. No fix as far as I know.

**Comment by coffeeneed** [comment]
I managed to build it with Isotope. That was a little tricky, but it worked :) I'm on vacation, but willing to share code when back.
