### ISSUE TITLE
Unable to get instafeed to pull images.

### ISSUE THREAD

**Issue by caleyg** [stevenschobert/instafeed.js#376]
I can see a valid response from the InstaAPI with valid json, but my div is never populated. I'm trying to do this from localhost. Code is below:

```javascript
<script type="text/javascript" src="js/instafeed.min.js"></script>
<script type="text/javascript">
var feed = new Instafeed({
  get: 'user',
  userId: 12######82,
  clientId: 'e0e######################420',
  accessToken: '12#####182.e###7.ce2e###################b3b6bd85a',
  target: 'InstaDisplay',
  limit: 5,
  resolution: 'low_resolution',
  template: '<a href="{{link}}"><img src="{{image}}" /></a>',
  useHttp: true,
  filter: function(image) {
    return image.tags.indexOf('fancythings') >= 0;
  }
});
feed.run();
</script>


<div id="InstaDisplay"></div>```


Thoughts?

Thanks

**Comment by ongerit** [comment]
@caleyg - If you comment out the following lines you'd be able to see your images populate:

```
  /*filter: function(image) {
    return image.tags.indexOf('fancythings') >= 0;
  } */
```

The reason you are not seeing images is that you are using a filter to filter images with the hashtag 'fancythings'. In your feed there aren't any image with that tag, so you're getting no results. I hope this helps.

**Comment by caleyg** [comment]
you were absolutely correct!! thank you so much!
