### ISSUE TITLE
Responsive display options?

### ISSUE THREAD

**Issue by madebyelmcity** [stevenschobert/instafeed.js#377]
Hello:

What's the best solution to show a different number of images depending on screen resolution? 

e.g., Eight images show when resolution is > 768 px. On smaller screens, only four images show. 

Thanks! Great plugin.

**Comment by ongerit** [comment]
Have you considered using nth-child ranges and media queries to achieve this?

**Comment by madebyelmcity** [comment]
I have. That's my fallback, but I was hoping there might be something built-in that I don't know about so I don't need to load images and then display:none them.

**Comment by ongerit** [comment]
@madebyelmcity- You can also accomplish this by javascript by detecting the width of the browser and displaying a limit. Please let me know if this helps. 

`var limitWidth;
var width = $(window).width();

if ( width <= 768) {
    limitWidth = 4;
} else {
    limitWidth = 12;
}

var userFeed = new Instafeed({
    clientId: '9980****4c',
    get: 'user',
    userId: 2****12,
    accessToken: '2010*****3ba8',
    limit: limitWidth,
    useHttp: true,
    target: 'instafeed',
    template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes">&hearts; {{likes}}</div></a>',


});
userFeed.run();
`

**Comment by madebyelmcity** [comment]
This worked! Thank you.

On Mon, Feb 8, 2016 at 6:09 PM, Thomas Ongeri <notifications@github.com>
wrote:

> @madebyelmcity- You can also accomplish this using javascript by detecting
> the width of the browser and displaying a limit. Please let me know if this
> helps.
>
> var limitWidth;
> var width = $(window).width();
>
> if ( width <= 768) {
>     limitWidth = 4;
> } else {
>     limitWidth = 12;
> }
>
> var userFeed = new Instafeed({
>     clientId: '9980****4c',
>     get: 'user',
>     userId: 2****12,
>     accessToken: '2010*****3ba8',
>     limit: limitWidth,
>     useHttp: true,
>     target: 'instafeed',
>     template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes">&hearts; {{likes}}</div></a>',
>
>
> });
> userFeed.run();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenschobert/instafeed.js/issues/377#issuecomment-181582602>
> .
>



-- 

[image: Made by Elm City] <http://madebyelmcity.ca>

Sean Sullivan
sean@madebyelmcity.ca

Made by Elm City
65 York Street Fredericton, N.B. E3B 3N4
madebyelmcity.ca

[image: Twitter] <https://twitter.com> [image: LinkedIn]
<https://www.linkedin.com/in/seanps>

**Comment by ongerit** [comment]
@madebyelmcity- My pleasure. Feel free to close this issue. 

Thomas

**Comment by alFrame** [comment]
This works well but it's not dynamic. Meaning, if someone turns the i.e. the tablet from portrait to landscape, or if the the browser window is resized, the post count doesn't re-evaluate.

Any way this could be made dynamic? (Sorry my programming skill is limited to copy paste and edit, not writing code on a empty sheet...)

Thanks!

**Comment by kylem038** [comment]
@alFrame using the nth-child + css media queries would be the way to go then. For example I have a media query where anything below 800px only shows the first 4 pictures from the feed. It does require some css knowledge, but this is how I did it. 

```
@media only screen and (min-width: 300px) and (max-width: 800px) {
  #instafeed a:nth-child(n+5) {
      display: none;
  }
}
```
