### ISSUE TITLE
Opening the images in a new tab and also in a lightbox 

### ISSUE THREAD

**Issue by heenac** [stevenschobert/instafeed.js#378]
Hi,

This is the first time with instafeed and Its a great addon to the website.

However I wanted some help for the following.

Currently instafeed loads the images in a div on my webpage. When i click on an image, it takes my to the instagram on the self tab. How do i open the instagram image on a new tab.

Also,is there a way i can open the image in a light box. Could you please give me some sample code on that. That would be very helpful.

Thanks,

**Comment by ongerit** [comment]
@heenac- I did this this for one of my sites and I used ui-kit and templates by instafeed. Take a look [here](http://www.collegefashionista.com/style-guru-love/).  Below is the code:

```
        var feed = new Instafeed({
            //var modalCode = "{target:&#39;#modal-"+photoId+"&#39;}";  //omit to use later
            target: 'instafeed2',
            get: 'user',
            userId: 2**3,
            accessToken: '2*****************b',
            limit: 60,
            links: false,
            template: '<div class="instaPhoto"><a  href="#" data-uk-modal="{target:&#39;#modal-{{id}}&#39;}"><img class="main-image" src="{{image}}" /> <div id="modal-{{id}}" class="uk-modal"><div class="uk-modal-dialog"><h1><img class="profile-image" src="/wp-content/themes/collegefashionista/images/heart-lrg.png"/> <a class="profile-link" target="_blank" href="http://www.instagram.com/{{caption}}">{{caption}}</a></h1><div class="caption-body"><img src="{{image}}"/></div> <!--<div class="uk-modal-caption">{{caption}}</div>--></div></div></a></div>',

            resolution: 'standard_resolution',
            useHttp: true,

            success: function() {
                foundImages = 0;
            },
                if (!this.hasNext()) {
                    loadButtonPartner.style.display = 'none';
                }
            },


        });
```

**Comment by heenac** [comment]
Hi This dint seem to work for me. May be I was missing something or doing it wrong. Could you please give me a small example if possible. on codepen/jfiddle. Hope I'm not asking for too much.  Also i have a trouble getting the instafeed div center aligned. Inspite of adding the margin as 0 auto. 

Thanks
