### ISSUE TITLE
Lazy loading?

### ISSUE THREAD

**Issue by pudgereyem** [stevenschobert/instafeed.js#38]
Hi, I wonder if someone has implemented [Lazy loading](http://en.wikipedia.org/wiki/Lazy_loading) with instafeed.js?

@stevenschobert what are your thoughts on this? Thanks for the amazing job so far with instafeed.js :+1:

**Comment by yairEO** [comment]
@pudgereyem - @stevenschobert didn't misunderstand you, but you mislead everyone when you mixed the term "lazy loading" with "load more" functionality, which is never ever called or referenced "lazy"... 

There is also a thing called "infinite scroll" where more content is loaded when the scroll has reached the end of the content, although this is happening automatic, and not by clicking any "show/load more" button
