### ISSUE TITLE
can any instagram user get their own pictures in my website?

### ISSUE THREAD

**Issue by lansas** [stevenschobert/instafeed.js#382]
Can any instagram user get their own pictures via instafeed.js to login (with instagram account) in my website?

**Comment by dzotokan** [comment]
Yes.

DO NOT expose your `access-token` on the client - anyone can get it and use the api on your behalf.

Also, access token can expire at any point.

**Comment by danfiscus** [comment]
@dzotokan The script doesn't work without specifying an `access-token`, so how do I protect my token?

**Comment by dzotokan** [comment]
You would need to generate it on every request (which requires authentication).

If it's a sandbox api client (most likely) - the data you'l be able to access with your access token will be restricted to your user's API clients only. The API is not designed for public sharing.

**Comment by dmzza** [comment]
I think the only risk in exposing your access token would be that someone could find it and use it for their own app, but if your access token has only been granted basic permissions, then they would only be able to display the 20 most recent photos from your Instagram account. I can't imagine anyone would want to do that. As long as you stay in sandbox mode, your client ID and access token are virtually useless to anybody else. 

With that in mind, you should never expose an access token that has anything beyond basic permissions if it is an account that you care about.
