### ISSUE TITLE
[Feature Request] Add an "each" advanced options function

### ISSUE THREAD

**Issue by FranciscoG** [stevenschobert/instafeed.js#384]
Just like you have the "before" and "after",  I'd also like to request an "each" function which is run each time you iterate over the array of images.   Useful if you want to change the template for every third image or something like that.   

I hacked this idea locally for a project.  I put the following snippet right above line [#161](https://github.com/stevenschobert/instafeed.js/blob/master/instafeed.js#L161)

``` javascript
if ((this.options.each != null) && typeof this.options.each === 'function') {
              this.options.each.call(this);
 }
```

Putting it above the imageString area allows me to also changed the template on the fly from within my "each" function

I'm using a grid system where every 3 images are wrapped in a row and I wanted to do that in the template.   This is how I'm using it for now and it's an example of what I'd use the "each" function for:

``` javascript
var count = 0;
var feed = new Instafeed({
    get: 'user',
    userId: ########,
    accessToken: 'XXXXX',
    resolution : 'standard_resolution',
    limit : 9,
    each: function(){
      count++;
      if (/[1,4,7]/.test(count)){
        templateToUse = templateRowStart + myTemplate;
      } else if (/[3,6,9]/.test(count)) {
        templateToUse = myTemplate + templateRowEnd;
      } else {
        templateToUse = myTemplate;
      }
      this.options.template = templateToUse;
    },
    after: function() {
        // disable button if no more results to load
        if (!this.hasNext()) {
            loadButton.setAttribute('disabled', 'disabled');
        }
    },
    template: templateRowStart + myTemplate
});
```

**Comment by stevenschobert** [comment]
I'd be onboard with this idea! Seems like something prime for a user-submitted contribution :)

@FranciscoG Are you interested in submitting a pull-request for this idea?

**Comment by leowebdev** [comment]
This worked for me using bootstrap... I'm not using the next button, so I took it out.
thanks to @FranciscoG 

`    jQuery(document).ready (function() {

        var templateRowStart = '<div class=row>';
        var templateRowEnd = '</div>';
        var myTemplate = '<div class=col-md-4><a href=\"{{link}}\" target=\"_blank\"><img width=\"400\" height=\"400\" src=\"http:{{image}}\" /></a></div>';
        var templateToUse = '';

        var count = 0;
        var feed = new Instafeed({
            get: 'user',
            userId: XXX,
            clientId: 'ZZZZZ',
            limit: 9,
            resolution: 'standard_resolution',

            each: function(){
              count++;
              if (/[1,4,7]/.test(count)){
                templateToUse = templateRowStart + myTemplate;
              } else if (/[3,6,9]/.test(count)) {
                templateToUse = myTemplate + templateRowEnd;
              } else {
                templateToUse = myTemplate;
              }
              this.options.template = templateToUse;
            },
            template: templateToUse
        });
        feed.run();
	});`

**Comment by FranciscoG** [comment]
@stevenschobert 
Sure I'll make a pull request at some point today.  

@leowebdev
I switched from using the regex test to simple modulus checking.  That way it's agnostic to how many rows it can handle.  For my purpose I was outputting the instagram feed in a 3x3 grid so that's why I was originally only testing using numbers but I think this way is better.

Also be warned that if you're doing columns of 3 that the API only returns a max of 20 which will leave your last row with only 2 so you'll have a `<div class="row">` without a closing `</div>`.  You might not notice in Chrome or FF but it'll definitely show in older IE.

```javascript
// var count =  0
...
         each: function(){
              // moved the count++ below
              if (count % 3 === 0){
                templateToUse = templateRowStart + myTemplate;
              } else if (count % 3 === 2) {
               // everything in the third column (2,5,8,etc) will always have a modulus 3 remainder of 2
                templateToUse = myTemplate + templateRowEnd;
              } else {
                templateToUse = myTemplate;
              }
              this.options.template = templateToUse;
              count++; // increment count here instead of above so we can start at 0
            },
```

**Comment by leowebdev** [comment]
thanks @FranciscoG 
I have my function encapsulated as a shortcode for visual composer, so the modulus check is better is perfect as users have the possibility to set the number of images/rows.

**Comment by FranciscoG** [comment]
@leowebdev 
if you want to make number of columns more dynamic for users to choose, you can do something like this

```javascript
count = 0
columns = 4  // or whatever number you want
if (count % columns === 0) {
  // add opening div class row 
} else if (count % columns = columns - 1) {
  // add closing div
} else {
  // middle column, do nothing, drink a beer
}
count++
```

might want to run a few tests on that to make sure I got that right but I _think_ it should work


@stevenschobert 
I'm working on that pull request, unit test keeps failing but I know it works because when I test it in the browser I can see it working.

**Comment by stevenschobert** [comment]
@leowebdev Cool I like the direction. If you want put up what you have so far in a pull request, I'll help look at the specs.

I'd also recommend we pass the item, index, and full array as parameters to the `each` option, that way users are not required to track that information themselves.

**Comment by FranciscoG** [comment]
pull request submitted
https://github.com/stevenschobert/instafeed.js/pull/386
