### ISSUE TITLE
hasNext() doesn't work correctly if a filter is applied. 

### ISSUE THREAD

**Issue by ariok** [stevenschobert/instafeed.js#388]
It seems that the `hasNext()` check doesn't work correctly when a filter is applied:

```
                    filter: function(image) {
                        return image.tags.indexOf("MY-TAG") >= 0;
                    },
```

Let's say that the `get` property  is set to `user` and we receive 100 images. Applying the tag filter, the images used to calculate the `hasNext` check probably are still 100 and the `has_next` function returns `true` even when I've already shown the last filtered image.

**Comment by vaghawan** [comment]
You could limit the number of image per request by using limit key. 

```
limit:10,
after:function(){
  if(!this.hasNext()){
   loadButton.setAttribute('disabled','disabled');
  }
  }
```
This works with me.
