### ISSUE TITLE
Template not working on Shopify

### ISSUE THREAD

**Issue by FloBorg** [stevenschobert/instafeed.js#389]
Hi,
the code works great on Shopify, thank you! But the templating doesn't seem to work. Using your example of        `template: '<a href="{{link}}"><img src="{{image}}" /></a>',`
simply returns empty boxes. Am I missing something? or is it conflicting with Shopify liquid codes?
thank you.
Flo

**Comment by ongerit** [comment]
Do you have a url of where the whole code lives?

**Comment by awarner023** [comment]
I'm experiencing the same issue with my Shopify testing site here: http://hari-mari-testing-environment.myshopify.com

**Comment by awarner023** [comment]
I think I may have found a solution in the Closed Issues here:  https://github.com/stevenschobert/instafeed.js/issues/318

**Comment by ongerit** [comment]
What is your store password to view the page?

On Mon, Mar 7, 2016 at 5:55 PM, awarner023 <notifications@github.com> wrote:

> I'm experiencing the same issue with my Shopify testing site here:
> http://hari-mari-testing-environment.myshopify.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevenschobert/instafeed.js/issues/389#issuecomment-193492829>
> .
>



-- 
*THOMAS ONGERI*

**Comment by awarner023** [comment]
The solution from https://github.com/stevenschobert/instafeed.js/issues/318  worked for me. Thanks!

**Comment by FloBorg** [comment]
solution on 318 worked for me too, brilliant, thank you! now I will try to combine it with Slick :D

**Comment by FloBorg** [comment]
Maybe a need to open a new case, let me know.. so combining the #318 solution with other info I found, I am trying to get my instagram feed into a carousel using slick. This is what I have:

`{% assign instafeed_template = '<a href="{{link}}"><img src="{{image}}" /></a>' %}

  <script type="text/javascript">

  var smallfeed = new Instafeed({
        get: 'tagged',
        target: 'smallfeed',
        tagName: 'HappyCrochetHooks',
        clientId: 'xxxxxxx',
        resolution: 'standard_resolution',
         template: '<div>{{ instafeed_template }}</div>'
        limit: '12',
        after: function () {
        $('.multiple-item').slick({ 
         infinite: true,
          slidesToShow: 3,
          slidesToScroll: 3 });
    }
    });

    smallfeed.run();
  </script>`

It comes up empty. If I remove the template, I have images but no carousel. If I remove the carousel and leave the template, I have the gallery. Any idea?  

@ongerit there is no password, it is on an unpublished template:
http://happy-crochet-hooks.myshopify.com/?preview_theme_id=90355969

**Comment by FloBorg** [comment]
this is the part that works (it displays the pictures in one single column)

```
 <script type="text/javascript" src="{{ 'instafeed.js' | asset_url }}"></script>
  {% assign instafeed_template = '<a href="{{link}}"><img src="{{image}}" /></a>' %}

 <script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'tagged',
        tagName: 'HappyCrochetHooks',
        userId: 1355706644,
	    clientId: '365a237621984751bc88869da18d9849',
  	    limit: 12,
  	    resolution: 'standard_resolution',
  	    template: '<div>{{ instafeed_template }}</div>'
    });
    userFeed.run();        
  </script>
```

**Comment by tenold** [comment]
#318 worked for me! Cheers!

**Comment by jbreneman** [comment]
In case anyone is still having issues with this: wrap the script tag (or just the `<a href="{{link}}"><img src="{{image}}" /></a>` line) with `{% raw %}{% endraw %}` tags to stop shopify from trying to parse the template.
