### ISSUE TITLE
Is there a way to get the full sized image?

### ISSUE THREAD

**Issue by lucasdidthis** [stevenschobert/instafeed.js#393]
Is there a way to get the natural sized image (1080px) from Instagram?

standard_resolution still returns the 640px image and I can't find another working size (like maximal_resolution or high_resolution) to get the full image. :-(

Thanks.

**Comment by danfiscus** [comment]
I agree, this should really be supported by now. I tried a few other peoples' solutions but no dice.

**Comment by lucasdidthis** [comment]
I'm afraid Instagrams API doesn't support the full resolution yet. I tweeted at them, but didn't get any response up to now; https://twitter.com/lucasdidthis/status/710390811360411648

**Comment by despecial** [comment]
Hint: you can manipulate the url of the thumbnail to get the full size image. (remove 000x000, etc.)

**Comment by danfiscus** [comment]
@despecial Is there a way to implement this in the code?

**Comment by despecial** [comment]
I don't think it will be implemented since this is not an official way to get the full size image. Just wanted to say you can modify the code yourself and don't make it public available ;)

**Comment by wielsma** [comment]
You could do the replacement yourself by using the after: fallback. First you put the image URL inside a data-source or similar tag inside the image container without specifying the src attribute (this is how most lazyload plugins work btw).

`<a href="{{link}}" class="instagram__post" target="_blank"><img data-source="{{image}}" class="instagram__image" height="320" /></a>`

After that, you can write a simple function as after callback to get the data-source value, do some replacements and set it as the image src, like so:

`after: function() {
/* Alter image URL to load high-res images */
jQuery('.instagram__post .instagram__image').each(function(key,element) {
jQuery(element).attr('src', jQuery(element).attr('data-source').replace("/s150x150/","/"));
});
}`

Hope this helps someone.

**Comment by isaumya** [comment]
@wielsma I cannot thank you enough for this. I was trying to implement the same logic for hours but it was failing and never occurs to me that I should put it in the `after` section. Thanks a lot for the snippet.

**Comment by isaumya** [comment]
@wielsma it seems Instagram has stopped this approach. Now for many images when you try to pull images like this way, it gives `403` error saying invalid URL structure
