### ISSUE TITLE
Uncaught Error: No user specified. Use the 'userId' option.

### ISSUE THREAD

**Issue by chochocho** [stevenschobert/instafeed.js#395]
Hi... I'm getting the error in the subject with the most basic implementation of instafeed:

```
    var feed = new Instafeed({
        get: 'user',
        userID: XXX,
        clientId: XXX,
        limit: 6
    });
    feed.run();
```

Is this an error other people are running into? As far as I'm aware, my userID and clientId are correct. Any help would be much appreciated.

**Comment by poacher2k** [comment]
Documentation says `userId` - above you are using `userID` (with capital D at the end).

StackOverflow is usually a better place for questions like this btw :)
