### ISSUE TITLE
Instafeed less thumbnail

### ISSUE THREAD

**Issue by awaahaab** [stevenschobert/instafeed.js#396]
Hi
I have managed to install the instafeed.js. 
But it s displaying all my insta pictures. I only want it to display 3 x 2 thumbnails 

I am using this:

```
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: '***************',
        accessToken: '**********************'
    });
    userFeed.run();
</script>
```

Many thanks for all your help. :+1:

**Comment by randomobject** [comment]
Add limit 

    <script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: '***************',
        accessToken: '**********************'
        limit: 3, 
    });
    userFeed.run();
</script>
