### ISSUE TITLE
404 ()

### ISSUE THREAD

**Issue by qLb** [stevenschobert/instafeed.js#398]
I tried to add a gallery for one of my friend's sites but it failed...
this is the console output:
`https://api.instagram.com/v1/media/popular?client_id=91474e03ddfd483eb403831b8b395c17&count=12&callback=instafeedCache8c2d1b8ce02f76b1.parse 404 ()`

my full code:

```
var feed = new Instafeed({
  clientId: '91474e03ddfd483eb403831b8b395c17', //qlbio
  limit: 12,
  sortBy: 'most-liked',
  resolution: 'standard_resolution',
  after: function () {
    var images = $("#instafeed").find('a');
    $.each(images, function(index, image) {
      var delay = (index * 75) + 'ms';
      $(image).css('-webkit-animation-delay', delay);
      $(image).css('-moz-animation-delay', delay);
      $(image).css('-ms-animation-delay', delay);
      $(image).css('-o-animation-delay', delay);
      $(image).css('animation-delay', delay);
      $(image).addClass('animated flipInX');
    });
  },
  template: '<div class="image-box" style="background: url({{image}});background-size:120%;background-position:center center;"><a class="image fit" href="{{link}}" target="_blank"><div class="likes">&hearts; {{likes}}</div></a></div>'
});
feed.run();
```

any ideas where i made a mistake?

**Comment by peterholcomb** [comment]
In the same boat as you.  Also getting a 404 returned from api.instagram.com

**Comment by RyabokonRoman** [comment]
+1

**Comment by qLb** [comment]
Fix:

Right at: http://instagram.com/developer
Log in 
Click on Manage Clients
Register a New Client

Fill  the form 
Make **SURE** to set the OAuth redirect_uri field to `http://localhost`
**Also, make sure to uncheck the `Disable implicit OAuth` box or else this method will not work**
Find out your instagram user id: http://jelled.com/instagram/lookup-user-id
And finally, paste the following url into your web browser (UPPERCASE strings should be typed in by YOU :)
https://instagram.com/oauth/authorize/?client_id=[YOUR_CLIENT_ID]&redirect_uri=http://localhost&response_type=token

now inside your instafeed configuration:
```
  ...
  clientId: 'YOUR_CLIENT_ID',
  get: 'user',
  userId: 'YOUR_USER_ID',
  accessToken: 'YOUR_ACCESS_TOKEN',
  ...
```

Be advised that storing your accessToken in client side scripts is **VERY DANGEROUS**, i strongly suggest using something like https://www.firebase.com/ for storing your secret and then making the database available only to a specific domain (**NOT localhost** :)

**Comment by qLb** [comment]
ps. There is ofcourse a limit for sandbox clients (500 requests/hour) and for approved clients (5000 requests/hour)

**Comment by MeK-KeM** [comment]
Look here: https://github.com/stevenschobert/instafeed.js/issues/571
