### ISSUE TITLE
Limit Bug when Getting Photos by Tag Name

### ISSUE THREAD

**Issue by MichaelMarcialis** [stevenschobert/instafeed.js#4]
Hello, I encountered what I think might be a bug with instafeed.js when setting the options to get tagged photos in concert with certain limit count integers. For example, whenever the two options are used together, using any tagName and a limit of 12, only 11 photos will actually be pulled loaded on the page. When I tried to get smart and change the limit number to 13 (hoping it would load 12), it instead correctly loads the 13 photos. This missing photo issue also happens when the limit is set to 8.

Strangely enough, when I remove the option to get tagged entirely, the script will then load the correct number of photos based on my set limit.

**Comment by stu2you** [comment]
Steven is there a limit to photo amount? I used to load more than 20 
http://stuartmansfield.com
