### ISSUE TITLE
Dynamic Use

### ISSUE THREAD

**Issue by Basilakis** [stevenschobert/instafeed.js#401]
Hey Guys,

I am working with Instafeed, you guys have done some amazing work, good job.
I would like to ask, I can work on the following:

```

function instafeed_instagram() {
    if ($.exists('.instagram-feeds')) {

        $('.instagram-feeds').each(function() {
            var $this = $(this),
                $size = $this.attr('data-size'),
                $sort_by = $this.attr('data-sort'),
                $count = $this.attr('data-count'),
                $userid = parseInt($this.attr('data-userid')),
                $access_token = $this.attr('data-accesstoken'),
                $column = $this.attr('data-column'),
                $id = $this.attr('id');



            var feed = new Instafeed({
                get: "user",
                target: $id,
                resolution: $size,
                sortBy: $sort_by,
                limit: $count,
                userId: $userid,
                accessToken: $access_token,
                template: '<a class="featured-image ' + $column + '-columns" href="{{link}}"><div class="item-holder"><img src="{{image}}" /><div class="hover-overlay"></div></div></a>'
            });
            feed.run();
        });
    }
};

```

So, when loaded, there is something like that

`echo '<div id="instagram-feeds-'.$id.'" class="instagram-feeds '.$el_class.'" data-size="'.$size.'" data-sort="'.$sort_by.'" data-count="'.$count.'" data-userid="'.$instagram_id.'" data-accesstoken="'.$access_token.'" data-column="'.$column.'"></div>';`

I would like to ask, if it is OK, if I do load variables, and they are empty.
For example, I want to change the code to either load based on user id, or load based on a tag.
If I do that, is it OK if I send empty variables back to the script and have some been empty and others have data? Or what will create issues?

Thanks a lot

**Comment by stevenschobert** [comment]
Yes! You can have multiple unique instances on the same page, provided all of them have unique `target`s set:

```js
var instances = [];
for (var i=0; i < feeds.length; i++) {
  instances.push(new Instafeed({
    target: 'instafeed-'+ i,
    //.. other options here
  }));

  instances[i].run();
}
```

Then on your page, just make sure you have the matching divs:
```html
<div id="instafeed-0"></div>

**Comment by Basilakis** [comment]
Great thanks a lot for the reply, really appreciate! :_)

**Comment by electrikfreak** [comment]
Hey guys,  
so, we are looking to use variable like Basilakis but looks like we are no able to.
Even when using his exact code our variables are not rendering inside the instafeed object.
example:

       
```
function instafeed_instagram() {
   if ($.exists('.instafeed')) {

       $('.instafeed').each(function() {
           var $id = 4;
           var feed = new Instafeed({
             get: 'user',
             limit: $id, //this is just rendering as $id and not as 4
             resolution: 'low_resolution',
             userId: 'theid',
             accessToken: 'thetoken,
             template: '<a href="{{link}}"><img src="{{image}}" /></a>'
           });
           feed.run();
       });
   }
};
```

Is there something I am not getting right?
I appreciate the help!
