### ISSUE TITLE
Custom Thumbnail

### ISSUE THREAD

**Issue by ricardo-oi** [stevenschobert/instafeed.js#403]
Hi there, I want to get my instafeed to pull high resolution square cropped photos from Instagram's API. Today I found out that if you change the s150x150 in instagrams cdn link to another size, you can access a higher resolution square thumbnail. Example:

This is what instafeed calls: https://scontent.cdninstagram.com/t51.2885-15/s150x150/e35/c0.134.1080.1080/13183261_265250253824418_1765742570_n.jpg?ig_cache_key=MTI0NDMxMDY1NjczOTAyMzkyNw%3D%3D.2.c

This is what i want to call: https://scontent.cdninstagram.com/t51.2885-15/s640x640/e35/c0.134.1080.1080/13183261_265250253824418_1765742570_n.jpg?ig_cache_key=MTI0NDMxMDY1NjczOTAyMzkyNw%3D%3D.2.c

It's a simple switch on the url. I'm trying to implement this code with no success: var thumbnail = post.images.thumbnail.url.replace('s150x150/', 's640x640/');

Is there any way to switch the url that instafeed posts to access this thumbnail?

**Comment by samuelorf** [comment]
I am trying to do this exact same thing. Please someone!

**Comment by ndimatteo** [comment]
+1 looking to do the same here.

**Comment by cristiandagnino** [comment]
just add:
`resolution: 'standard_resolution'`
to the call...

```
var feed = new Instafeed({
	get: 'user',
	userId: 'XXXXXX',
	clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	accessToken:'XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX',
	template: '<a taget="_blank" href="{{link}}"><img src="{{image}}" /><span>{{caption}}</span></a>',
	limit: 3,
	resolution: 'standard_resolution'
});
feed.run();
```

**Comment by ndimatteo** [comment]
@cristiandagnino that doesn't fix the issue. the low_resolution and standard_resolution, while returning square images, keep the original aspect ration and add white bars, which is undesirable.

What we are asking is for the thumbnail (cropped, full-bleed square) to utilize the higher resolution version, rather than the 150x150 (come on... what could this size possibly be used for in today's times).

**Comment by cristiandagnino** [comment]
As I can't see the example links, I don't really understand... Hope to.
Does it has something to do with the new "Migrations" option (Non square media) on the "Edit Client" ?

**Comment by ndimatteo** [comment]
@cristiandagnino no unfortunately, that eliminates the white bands on the low/standard sizes leaving them non-square. It does not affect the thumbnail.

**Comment by cristiandagnino** [comment]
U could use the "non square media" and use css like:
```
var feed = new Instafeed({
    get: 'user',
    userId: 'XXXXXX',
    clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXX',
    accessToken:'XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX',
    template: '<a class="insta_img" style="background: url('{{image}}') no-repeat center center;background-size:cover;width:200px;height:200px;display:inline-block;"  href="{{link}}"><span>{{caption}}</span></a>',
    limit: 3,
    resolution: 'standard_resolution'
});
feed.run();
```

**Comment by ndimatteo** [comment]
That is a technique others have posted before, however it's not ideal for a number of reasons:

- No guarantee it won't show white bars when the image is scaled to fit
- Have to rely on messy CSS to get the div to be responsive (ie. ```padding-top: 100%```)
- Image display may differ from how Instagram shows thumbnails, causing inconsistencies

An option in the plugin to switch between the two would be great. For now I've done this which works, but is less-than-ideal for all the extra code:

```javascript
var feed = new Instafeed({
    clientId: 'xxxxxxxxxxxxxx',
    accessToken: 'xxxxxxxxxxxxxx',
    get: 'user',
    userId: 'xxxxxxxxxxxxxx',
    sortBy: 'most-recent',
    limit: 9,
    mock: true,
    success: function(images) {
      $.each(images.data, function(imageID, post) {
        var highResThumb = post.images.thumbnail.url.replace('s150x150/', 's640x640/');
        var originalImage = post.images;
        $('#instagram-feed').append('<a href="'+post.link+'" class="thumbnail" target="_blank"><img src="'+highResThumb+'"/><div class="overlay"><span>'+post.likes.count+' Likes</span></div></a>');
      });
    }
  });
```
