### ISSUE TITLE
Load images in "rows"

### ISSUE THREAD

**Issue by progrmor** [stevenschobert/instafeed.js#404]
I'm trying to load images from my account in rows of 4 images.
So I thought I could implement multiple feed runs like:

```
var feed = new Instafeed({
    target: "insta-images",
    get: 'user',
    userId: "xxxxx",
    clientId: "xxxxxxx",
    accessToken: "xxxxxxxxxxxxxxxxx",
    limit: 4,
    template: '<li id="insta"><a href="{{link}}"><img src="{{image}}" /></a></li>'
});

var feed2 = new Instafeed({
    target: "insta-images2",
    get: 'user',
    userId: "xxxxxxxxxx",
    clientId: "xxxxxxxxxxxxxx",
    accessToken: "xxxxxxxxxxxxxxxxxxxxxxxxx",
    limit: 4,
    template: '<li id="insta2"><a href="{{link}}"><img src="{{image}}" /></a></li>'
});

feed.run();
feed2.run();
```

and load them into html like:

```
<div id="insta-images"></div>
<div id="insta-images2"></div>
```

But this causes the second feed to load the same 4 first images, which defeats the point. So how can I "count" to load the next 4 images on the second feed? OR use some other method to achieve this?

**Comment by paulbremer** [comment]
@progrmor use 1 feed to load 8 images into #insta-images and use css to set the width of each image to 25%, that way the last 4 images will be displayed on the second row.
