### ISSUE TITLE
How to install it on magento?

### ISSUE THREAD

**Issue by mefornazari** [stevenschobert/instafeed.js#405]
How can I install instafeed on magento?

**Comment by WPUtvecklare** [comment]
I'm also wondering how to install it on Magento. I've tried inserting everything as described but nothing shows up.

**Comment by aymadhiya** [comment]
@mefornazari and @WPUtvecklare 

Please follow below steps to add instafeed in your Magento 2.

**Step 1:**  Add instafeed.min.js to your theme folder inside web/js/ folder.
**Step 2** now you have to use your instafeed code like this. 
<script type="text/javascript">
require(["js/instafeed.min"], function(Instafeed) {
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: 'YOUR_CLIENT_ID'
    });
    feed.run();
});
</script>

It's much simple. :) I hope it will work for you.
