### ISSUE TITLE
issue with instagram API

### ISSUE THREAD

**Issue by waldoalvarez00** [stevenschobert/instafeed.js#406]
Hi folks with this URL I get a json reply from the Instagram API

https://api.instagram.com/v1/media/popular?client_id=97ae5f4c024c4a91804f959f43f2635f&callback=instafeedCache9fdd2f016a712ab6.parse

now however when I try to use my own clientid i get a 404 from Instagram

https://api.instagram.com/v1/media/popular?client_id=ba9a76966f53481ba890124b3e6b7068&callback=instafeedCache9fdd2f016a712ab6.parse

Is this a configuration problem on my side or just the script is outdated? Looking forward to fix it if that is the case. If I need to fix something at Instagram please someone shed some light. Thanks.

**Comment by jetsynthesys** [comment]
Hi, 
Instagram has deprecated media/popular and some other apis. You can refer these links
https://www.instagram.com/developer/endpoints/media/
https://www.instagram.com/developer/deprecated/endpoints/media/#get_media_popular

**Comment by waldoalvarez00** [comment]
Ahh thanks

**Comment by amandeepmittal** [comment]
I think, this issue can be closed since the endpoint is deprecated by Instagram.
