### ISSUE TITLE
forced square format issue after fixing the new access token issue

### ISSUE THREAD

**Issue by Fanetteg** [stevenschobert/instafeed.js#409]
Hey,

Bit of a newbie here.
I am displaying on my website the last image of my Instagram feed, vertical sized (not square) adjusted in height to fit a box.
Everything worked perfectly until I had to update the access token, which I just did.
My Instagram was perfectly fitting the box, now it seems like it's adding left and right white borders to force a square format.
(I ticked the "non-square format on the Instagram website, is it just not supporting other formats now ?)

Thanks,

Edit : got my new access token via pixelunion - have no idea where to get my own

**Comment by paxnot** [comment]
having the same exact problem, i configured to work with new non-square media. Then it broke today. New access token made images comeback, but back to only square.

**Comment by Fanetteg** [comment]
@paxnot where did you get your new access token ?

**Comment by Fanetteg** [comment]
@paxnot found the solution. You need to get the access token by yourself on your instagram developer's page. Here is a simple step by step explaination on how to get it.
You still need to tick the "non-square media" box in your app settings. 
Worked perfectly for me ! 

http://jelled.com/instagram/access-token

**Comment by sortsen** [comment]
@Fanetteg Thanks, this worked for me. Don't forget to set your redirect_url to localhost and untick   Disable implicit OAuth in your client security settings.

**Comment by paxnot** [comment]
@Fanetteg hey thanks a lot for that. I got both my feeds working again. 
One of them was from tagged photos, which appears to now be impossible to do...

I needed to get my user ID and every tool for that seams to be broken but this page has a super easy way to do so:

http://www.otzberg.net/iguserid/
