### ISSUE TITLE
Working (Failing) with Jekyll

### ISSUE THREAD

**Issue by ChrisSki** [stevenschobert/instafeed.js#41]
I've done a lot of searching and can't seem to find a solution. I am currently using Jekyll for my blog and I can not seem to get Instafeed to render my images. I have tested the same code I have in a plain html page and it renders my images fine, so I have to assume it's failing because of Jekyll. I don't have any other plugins or anything strange working with Jekyll. I'm using a template with Instafeed and in my source code is show's my image tag rendered like this: <img src>. If anyone can direct me to a solution, I'd love to find one.

**Comment by kamburi** [comment]
Hi @maxatbrs ,

I´ve used your suggestion about verbatim and Twig and got it working.

Thank You very much.

**Comment by maxatbrs** [comment]
@armaduarte :100:
