### ISSUE TITLE
no images were returned

### ISSUE THREAD

**Issue by stefanoalmonte** [stevenschobert/instafeed.js#411]
i have used this link:
https://gist.github.com/mojaray2k/b502d75dd7a9fa277876
but this is the result:
Uncaught Error: No images were returned from Instagram

why ??? please help me ... thanks !!!

**Comment by ctmaloney** [comment]
Are their any images in the user account your pulling from... sounds stupid but thats what was happening to me!

**Comment by stefanoalmonte** [comment]
yes ... over 100 ...!

2016-06-08 23:53 GMT+02:00 Christian Maloney <notifications@github.com>:

**Comment by schricka** [comment]
i can get the tags
https://api.instagram.com/v1/tags/apple?access_token=xav
`{"meta": {"code": 200}, "data": {"media_count": 13860744, "name": "apple"}}`
but when trying to got get the recent media with
https://api.instagram.com/v1/tags/apple/media/recent/?access_token=xav
`{"pagination": {"deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead"}, "meta": {"code": 200}, "data": []}`
the returning data is empty.

**Comment by stefanoalmonte** [comment]
thanks so much but now why the plugin not show the images?

( sorry for my poor english )

2016-06-10 16:40 GMT+02:00 Rainer W. <notifications@github.com>:

**Comment by schricka** [comment]
yes, this is because "data": [] is empty

 but why instagram do this - i also don't know

**Comment by stefanoalmonte** [comment]
ah ok ok ... i'am waiting some solution thanks ...

2016-06-10 17:21 GMT+02:00 Rainer W. <notifications@github.com>:

**Comment by ctmaloney** [comment]
@stefanoalmonte you need to read the docs you're not using the correct endpoint and you should remove your real access token from the comment above!

https://www.instagram.com/developer/endpoints/tags/#get_tags_media_recent

Also, you _can't_ get public tag feeds anymore unless you have an app that you can get reviewed.  Which if you're just trying to show a feed on your website you can't do.  So bottom line is if you're trying to show a tag feed on your website it isn't going to work.

**Comment by stefanoalmonte** [comment]
thanks again ... but you can show me how i can review my app for my scope
or can make new app ?

2016-06-10 18:51 GMT+02:00 Christian Maloney <notifications@github.com>:

**Comment by ctmaloney** [comment]
Sorry, I'll have to leave that one up to you... plenty of info out there on how to go about that already.  But like I said if all you're trying to do is show a public tag feed on your website it is my understanding that it isn't going to happen per Instagram's new policies.

**Comment by stefanoalmonte** [comment]
ok Chris
 ...
thanks
...
see you

2016-06-10 19:41 GMT+02:00 Christian Maloney <notifications@github.com>:

**Comment by NicolasVanhecke** [comment]
I am getting this error for a while now. I am pulling 'user' info and not tagged (i am aware of the changes in the API since this summer). 

**The only thing I get in console is this: Uncaught Error: No images were returned from Instagram**

And my code works on ANY other instagram app I have. I don't see anything special about this app, and the user DOES have photo's, so no issue there...
Anyone have some ideas on how this can be fixed or what seems to be wrong?

**Comment by stevenschobert** [comment]
@NicolasVanhecke if you think this might be a problem with Instafeed.js, please create a new issue with your specific settings.

Otherwise try posting your question to StackOverflow!

**Comment by stevenschobert** [comment]
Closing this issue.

@ctmaloney thanks for you help! It's very much appreciated!
