### ISSUE TITLE
Older Images not being returned

### ISSUE THREAD

**Issue by aluckymuse** [stevenschobert/instafeed.js#414]
I finally got my feed to work correctly after Instagram's API update. But now I've noticed a new problem, it seems that if I'm asking for instafeed to return a specific hashtag from a specific user account it will only show more recently tagged images and not all the images tagged with the specific hashtag up to the limit of images set to show.
Any help with this?

**Comment by ongerit** [comment]
Do you have a code snippet or a link to your site?

**Comment by aluckymuse** [comment]
Sure, here's the code I'm using:

```
<!DOCTYPE HTML>
<html>
	<head>
		<title>instafeed test</title>
		<meta charset="utf-8" />

		
<script type="text/javascript" src="instafeed.min.js"></script>
      
	</head>
	<body>
      
	  
<script type="text/javascript">	
	 var feed = new Instafeed({ 
	 get: 'tagged', 
	 tagName: 'abpstonecarvings', 
	 userId: '[USER_ID]', 
	 accessToken: '[ACCESS_TOKEN]', 
	 sortBy: 'none', 
	 resolution: 'thumbnail',
	 limit: '100',
	 template: ' <a href="{{link}}" target="_blank" class="instagram-image"><img src="{{image}}" /></a> '
	 }); 
	 feed.run();
</script>

			
      <div id="instafeed"></div>
	</body>
</html>
```

**Comment by jolora** [comment]
The API change means Instagram will only ever show the latest 20 images for sandboxed accounts.
Unfortunately I don't think there will be a workaround for this any time soon.

**Comment by gnyangolo** [comment]
Hi @jolora  Do you happen to have an example that actually works you help me  with the code...
thank you in advance

**Comment by jolora** [comment]
@gnyangolo as I said, there is no way around this at the moment. Previously the cap was based on being able to retrieve about 20 images per API request, so the trick was to make multiple requests with a different offset each time. Now, you can only ever retrieve the most recent 20 images - there is no way to set an offset beyond that. So unless you meet the criteria to escape the sandbox I think you are out of options I'm afraid.
