### ISSUE TITLE
Issue getting all tagged Images

### ISSUE THREAD

**Issue by WebD00D** [stevenschobert/instafeed.js#417]
For some reason only 1, or 2 of a specified tagged image are being pulled in, when I know there are obviously way more than that. Anyone dealing with the same issue?

```
 var userFeed = new Instafeed({
               get: 'tagged',
               tagName:'tag',
               target: 'instafeed2',
               template: ' <a class="fancybox" target="_blank" href="{{image}}" rel="group" ><img class="instaimg" src="{{image}}" /> </a> ',
               limit:14,
               resolution:'standard_resolution',
               accessToken:'XXXXXXX'
              });
              userFeed.run();

```

**Comment by FloBorg** [comment]
Read the recent issues, tagged is not possible anymore since beginning of June because of Instagram changes in API policies. Unless someone will find a workaround...

**Comment by rodrigokono** [comment]
So.. I get the changes. But when I use the accessToken + clientId + `tagged`, is returned the user owner feed insted of hashtag feed.

**Comment by invaderhd** [comment]
@rodrigokono Can you explain how do you do that?

**Comment by rodrigokono** [comment]
@invaderhd easy... Just get throught "bower install instafeed.js" and after coded the instructions like to below:

var feed = new Instafeed({
                get: "tagged",
                tagName: "corregoiania",
                clientId: 'myClientId',
                userId: myuserId,                
                accessToken: 'myTokenId',
                limit: 12,
                sortBy: 'most-recent',
                resolution: 'low_resolution',
                template: '<a target="_blank" title="{{caption}}" href="{{link}}" rel="prettyPhoto[gallery]"><img src="{{image}}" /></a>'
            });

So, is returned the "user feed" instead of "hashtag feed".
I am wrong or it's a instafeed bug?

**Comment by invaderhd** [comment]
With that code I get my tagged images but only recent ones. Old images don't appear

**Comment by louiswalch** [comment]
Also looking for a solution to this.

**Comment by rodrigokono** [comment]
@invaderhd tagged is not working is this last instagram update. We have a problema with this.
@louiswalch I'm also looking a solution for this.

**Comment by StillOnMyWay** [comment]
Old feed, I know, but the answer to the question by @fabiomlferreira is below (taken from the [instafeed page](http://instafeedjs.com/)

`let feed = new Instafeed({
        get:'user',
        filter: function(image) {
            return image.tags.indexOf('YOURTAG') >= 0;
        } ,
        accessToken:'xxx',
        userId:'xxx',
        template: '<a href="{{link}}"><img src="{{image}}" /></a>'
    })
    feed.run();`

This gives you all of your uploaded tagged images, with your specified tag.
