### ISSUE TITLE
Orientation Landscape

### ISSUE THREAD

**Issue by wirnico** [stevenschobert/instafeed.js#418]
Hey everyone,
I read a lot about Instafeed and the possibility to get rid of the white borders when wanting to show images as non-square images on the site, but I everything I try, I don't get it to work.
How do I have to implement the orientation tag. Is my code correct below?
And where can I define the landscape option?

Here is the example on my site (you have to scroll down a little bit to see the Insta Section)
www.stillekonzerte.de/test2

Thanks in advance

Here ist my JS Code:

```
    <script type="text/javascript">
      var userFeed = new Instafeed({
        get: 'user',
        useHttp: true,
        userId: xxxxxxxxx,
        accessToken: 'xxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxx',
        sortBy: 'most-recent',
        template: '<a class="instagram-{{orientation}}" href="{{link}}" target="_blank" id="{{id}}"><img class="col-lg-4 col-md-2 col-sm-6 instafeed" src="{{image}}" /></a>',
        limit: 10,
        clientId: 'xxxxxxxxxx',
        resolution: 'standard_resolution'
      });
      userFeed.run(); </script>
```

**Comment by ptraceur** [comment]
I wanted to know how to do this too, get the default image without white lines as borders.

**Comment by PrafullaKumarSahu** [comment]
@rafamds I am getting "Cannot read property 'each' of undefined" can you please help me to solve it .

`Array.isArray($images); `is true, but 

```
 images.each(function( index ) {
    console.log(index);
});
```
is showing images.each is not a function
and also 

```
 $.each(images, function(){
     console.log(this.images);
 })
```

is showing Cannot read property 'each' of undefined .

**Comment by rafamds** [comment]
Hey @PrafullaKumarSahu, `$.each` is a jQuery function. Without jQuery you should implement with:

```
images.forEach(function(){
            var thumb = this.images.thumbnail.url.split('/');
            if(thumb[6] == 'c' && typeof thumb[7] !== "undefined"){ //if not, that means the 6th section is the image itself and that means it is already with its correct ratio
                thumb = this.images.thumbnail.url.replace(thumb[6]+'/', '');
            }
            thumb = this.images.thumbnail.url.replace('s150x150', 's640x640');
            // now you have it, use thumb variable to insert the link wherever you want
        });
```

**Comment by PrafullaKumarSahu** [comment]
yes, I did it with forEach at last, but I removed all as, I was trying to add the media post's data  like

`<div class="sbi_item" target="{{model.type}}" id="sbi_{{id}}"><div class="sbi_photo_wrap"><input type="checkbox" name="image_arr[]" value="http:{{image}}" target="{{caption}}" class="instagram-check"><span id="{{id}}" class="span_check"><input type="hidden" class="insta-time" value="{{model.created_time}}"></span><a href="{{link}}"><img src="{{image}}" alt="{{caption}}" /></a></div></div>` in side a div and I was unable to do it :(
