### ISSUE TITLE
Any trick to getting feed from hashtag ?

### ISSUE THREAD

**Issue by l2aelba** [stevenschobert/instafeed.js#422]
This topic is about **getting hashtag** only
Since many comments on #408 is so mixed of getting pictures from a user.

---

This is what I got when i trying to submit permission request for `public_content`

![screen shot 2016-06-21 at 10 13 11](https://cloud.githubusercontent.com/assets/983458/16222536/e9510116-3798-11e6-98a2-8e6992e15c89.png)

**Questions :**
- **Any trick and hack or stable/offtical way** about getting picture from hashtag ?
- Any have experience about getting approve for `public_content` 's scope ?
- Why Instragram changed their new pravicy ? _(Does not ppl want to show their own pictures to the world when using hashtags ?, Im using unique hashtags on many campaigns so all broke !)_

**Comment by louiswalch** [comment]
I too am looking for a solution for this. I am stuck because we use hashtags are promotional tie-ins and now there is no way to query for them.

**Comment by nmklong** [comment]
Having problems with this as well, hopefully there will be workarounds. Is there a center where we can submit developer problems to Instagram? I think my company will be fine with paying them for this, but there needs to be a workaround, or some sort of paid service.

**Comment by relish27** [comment]
Yeah, it's not looking great for tag-based feeds.

![instagram developer documentation](https://cloud.githubusercontent.com/assets/534728/16343693/29eb28e8-39fe-11e6-8996-99e06404476d.jpeg)

**Comment by relish27** [comment]
Looks like Instagram suggests looking on StackOverflow.  I found one post, but no answers here: http://stackoverflow.com/questions/38011375/any-workaround-for-new-instagram-api-restriction-with-tags-content
