### ISSUE TITLE
calls to model not working

### ISSUE THREAD

**Issue by shaimanor** [stevenschobert/instafeed.js#423]
Hi Steven,

my initial code was this:

```
<script type="text/javascript">
        var userFeed = new Instafeed({
        get: 'user',
        userId: {{ settings.instagram-user-id }},
        accessToken: '{{ settings.instagram-access-token }}',
        resolution: 'standard_resolution',
        template: '<a class="fancybox" href="{{ url }}" rel="ig" ><img class="instagram-image" src="{{url}}"/></a>'

      });
      userFeed.run();        
</script>
```

But this means that thumbnails are scaled down from 640px by 640px and I would like to serve thumbnails as low-res and the fancybox image as standard res photos.

I have then tried

```
<script type="text/javascript">
        var userFeed = new Instafeed({
        get: 'user',        
        userId: {{ settings.instagram-user-id }},
        accessToken: '{{ settings.instagram-access-token }}',
        resolution: 'standard_resolution',
        template: '<a class="fancybox" href="{{model.images.low_resolution.url}} rel="ig"><img class="instagram-image" src="{{image}}" /></a>'
       });
    userFeed.run();
</script>
```

Which does not work. 

Firstly, <img src> only works with {{url}} and nothing shows up if I use {{image}}
Secondly, it appears I cannot pull anything from the model, so {{model.images.low_resolution.url}} does not work either.

Am I overlooking something?

**Comment by shaimanor** [comment]
Thanks Sonarun,

Not Django - Liquid (Python)

required using {% raw %} and {% endraw %}

final:
<script type="text/javascript">
var userFeed = new Instafeed({
get: 'user', 
userId: {{ settings.instagram-user-id }},
accessToken: '{{ settings.instagram-access-token }}',
resolution: 'low_resolution',
template: {% raw %}'<a class="fancybox" href="{{model.images.standard_resolution.url}} rel="ig"><img class="instagram-image" src="{{image}}" /></a>'{% endraw %}
});
userFeed.run();
</script>

**Comment by sonarun** [comment]
My suggestion would be to place the {% raw %} tags just before the place where you need to escape the token. Perhaps something isn't being parsed if you escape the entire line.

``` javascript
<script type="text/javascript">
        var userFeed = new Instafeed({
        get: 'user',
        userId: '{{ settings.instagram-user-id }}',
        accessToken: '{{ settings.instagram-access-token }}',
        resolution: 'standard_resolution',
        template: '<a class="fancybox" href="{% raw %}{{model.images.low_resolution.url}}{% endraw %} rel="ig"><img class="instagram-image" src="{% raw %}{{image}}{% endraw %}" /></a>'{% endverbatim %}
       });
    userFeed.run();
</script>
```

**Comment by shaimanor** [comment]
Thanks Sonarun,

You've missed a " after the first endraw but yes that works!! Thanks!

` <script type="text/javascript">
        var userFeed = new Instafeed({
        get: 'user',
        userId: '{{ settings.instagram-user-id }}',
        accessToken: '{{ settings.instagram-access-token }}',
        resolution: 'low_resolution',
        template: '<a class="fancybox desktop-2 tablet-1 mobile-half" href="{% raw %}{{model.images.standard_resolution.url}}{% endraw %}" rel="ig" title="Diamesque on Instagram"><img class="instagram-image" src="{% raw %}{{image}}{% endraw %}" /></a>'
       });
    userFeed.run();
</script>`

**Comment by sonarun** [comment]
Great! Glad it works. I just changed it on my site as well in order to future-proof any problems. Thanks!
