### ISSUE TITLE
Uncaught Error: Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by willpaige** [stevenschobert/instafeed.js#424]
I've got 3 production sties that were using instafeed with out any issues. Until a couple of weeks ago when I now get 'Uncaught Error: Error from Instagram: The access_token provided is invalid.' 

I haven't changed anything and my instagram clients are the same.

http://willpowerfitness.co.uk/
http://botanyblend.com/

**Comment by edinchez** [comment]
I think Instagram changed their API on June 1. So until instafeed.js gets updated it probably won't work.

**Comment by NicolasVanhecke** [comment]
Yep same thing.. got this running on a few live sites. Any word on an update?

**Comment by KingScooty** [comment]
This is nuts. There was a fix for this in the issues, and even that seems to be resetting at the moment. Really could do with this getting fixed.

**Comment by amandeepsinghvirdi** [comment]
Follow the instructions from to create access token using the correct client id and it should fix the issue

https://www.instagram.com/developer/authentication/

**Comment by NicolasVanhecke** [comment]
This will not work when my app is still in Sandbox mode right? How long does this usually take? (I'm am working on a project from another developer who is not working at my firm anymore.. don't know his app_id en client_id and stuff.. So i had to create a new one)

**Comment by emersonthis** [comment]
^ @amandeepsinghvirdi 's tip works but you'll need to update the client settings so that `https://elfsight.com/service/generate-instagram-access-token/ ` is included in as one of the redirect URLs.

**Comment by emersonthis** [comment]
Does anyone know if *any* requests still allow the client_id to authenticate? I have yet to find one that didn't auth error without an auth token.

**Comment by marza91** [comment]
I can't authenticate using client ID only either. We're only using this library to display a feed of tagged images without any login required, so it's not really possible for me to store an access token in a secure way.. I don't believe it's considered safe to just generate a token with my own user and paste this in the js-file..?

**Comment by emersonthis** [comment]
That's precisely what I did. It's definitely not ideal but the sandbox token has no permissions so I'm not sure if it's "unsafe" or just a pain in the ass.

**Comment by marza91** [comment]
Yes, I tried with the sandbox version with auth token as well, but I needed all pictures from a tag, which of course wouldn't work.
I'm not sure how the verification process works around this, but maybe it would be possible to create and verify a common user/client for use in instafeed.is? So that we all could use the same access token, but there's no content/images on the account?

**Comment by emersonthis** [comment]
We’d slam into rate limits pretty fast if any substantive group of people started using it. If memory serves, we now get 500 requests/hour, which is fine for modest sites, but easily reachable with “crowd sourcing”.

**Comment by marza91** [comment]
Ah, I see, that's too bad. Seems to me like instagram don't want us to show image feeds on other sites anymore.. Which also seems like a "shoot yourself in the foot" kind of thing to do...

**Comment by emersonthis** [comment]
That’s 100% their intention. This move was entirely calculated with the goal of quashing “unapproved” glimpses of the Ig user experience.
