### ISSUE TITLE
Only response type \"code\" and \"token\" is allowed

### ISSUE THREAD

**Issue by yleng** [stevenschobert/instafeed.js#427]
The following request returns the following error: 
https://api.instagram.com/oauth/authorize/?client_id=7cacf1e144c64c15986e10d2a28aca46&redirect_uri=http://localhost:8000&response_type=6702b4bca55743fcb5a757b81df2bef7

Error 
{"code": 400, "error_type": "OAuthException", "error_message": "Only response type \"code\" and \"token\" is allowed"}

Thank you for the help:)

**Comment by stevenschobert** [comment]
@yleng Please refer to Instagram's API docks, or stackoverflow.com, for errors regarding generating tokens in Instagram's API.
