### ISSUE TITLE
After Callback Executed Before Dom Actually Updates?

### ISSUE THREAD

**Issue by Peege151** [stevenschobert/instafeed.js#428]
I haven't done too much investigating, but here is my use case:

I need to know the height of the isntafeed wrapper (the container height changes after the content is added to the div).  I expected that number to have already updated by the time the after callback has run, but it hasn't.

My container has the same height before the images are added, and when the after callback is executed.  Setting a timeout of 200ms worked to get the new height.  I'm sure I could go lower.  

Thoughts?

**Comment by stevenschobert** [comment]
Hey @Peege151! My first guess would be that the height of the `<div id="instafeed"></div>` isn't going to actually change until all the images have been loaded in.

The `after()` callback does run after all the image **nodes** have been inserted into the div, but not necessarily before the images themselves have been loaded.

The only sure way to know when the images themselves have been loaded would be to pre-load them yourself using an `onload` callback on the image nodes themselves.
