### ISSUE TITLE
get tagged not working, get user alternative

### ISSUE THREAD

**Issue by NicolasVanhecke** [stevenschobert/instafeed.js#430]
`var feed = new Instafeed({  
         get: 'tagged',  
         tagName: 'bavet',  
         clientId: 'clientidhere',  
`
this does not work anymore... What is the correct way to get data from a user profile?
When I try this, i get an error: `Uncaught Error: No user specified. Use the 'userId' option.` 

`var feed = new Instafeed({  
         get: 'user',  
         userId: '2165473687',  
         clientId: 'clientidhere',  
`

How do I get this working?? I really don't find it anywhere

**Comment by emersonthis** [comment]
This is one of the use cases killed by the new API changes. Fetching posts by tag is not allowed by "Sandbox mode." Your app would require permissions that are walled off by the submission process, which only allows apps that feet a very very limited range of uses. Also note that the new restrictions only allow you to access the last 20 posts, so the best you'll be able to do is probably use the `filter:` option to pick out the ones tagged from just those 20. Sorry to be the bearer of bad news.

**Comment by semeano** [comment]
It seems that even on "Live mode" you can't. This was completely removed, right?

**Comment by emersonthis** [comment]
You should be able to do it in live mode. I'm not aware of them removing that endpoint. And technically you can do it in Sandbox mode but in such a narrow way that it's not really useful in most situations. Here's a more thorough explanation: https://css-tricks.com/everything-need-know-instagram-api-integration/#instagram-api-how-to-2-no-tags
