### ISSUE TITLE
Instagram access token is required to display images

### ISSUE THREAD

**Issue by claide** [stevenschobert/instafeed.js#432]
Tried the script and followed the basic example but it throws the error "Instagram access token is required". I read the doc and added accessToken option and put the token value. But I wonder why it's not working too.

**Comment by claide** [comment]
Also when I check the console it says

Unexpected identifier in

accessToken: 'some numbers here..'

**Comment by claide** [comment]
I fixed it. but new error thrown.

 Error from Instagram: This client has not been approved to access this resource.

**Comment by bsullins** [comment]
how did you fix the Access token without asking your users to authorize when they load the page? I'm using the most basic example and getting the same error.

**Comment by claide** [comment]
@bsullins  I tried to remove the client ID and just leave the accessToken. Error resolved but another error thrown.

Error from Instagram: This client has not been approved to access this resource.

**Comment by notflip** [comment]
Same issue here, any news on this?

**Comment by sonarun** [comment]
You can use this site to generate an access token for your application. It worked for me!

http://instagram.pixelunion.net/
