### ISSUE TITLE
User ID does not exist

### ISSUE THREAD

**Issue by pfhenley86** [stevenschobert/instafeed.js#433]
Hi,

My feed has been working about a year now but now I get the error that the User does not exist but the user does exist. Am a missing something? Do I need to update my script? Here is the website in question. https://holinite.com

**Comment by emersonthis** [comment]
You probably have to add that specific user as a "Sandbox User"

**Comment by pfhenley86** [comment]
Seems it had something to do with the site using https but I added my clients username to The  API Client. I updated the Client settings and now I get "This client has not been approved to access this resource". I will see what happens after they accept access to the user through the Client.

**Comment by emersonthis** [comment]
It sounds like you need to request a token with additional scopes. The scope(s) you'll need to add depend on what requests you're trying to make.

**Comment by pfhenley86** [comment]
Yeah after I did[ this process](http://jelled.com/instagram/access-token) to get a new token.

I get the error "Error from Instagram: This request requires scope=public_content, but this access token is not authorized with this scope. The user must re-authorize your application with scope=public_content to be granted this permissions."

This is my script though and when I go through the api permissions it says I don't need permissions to display a feed.

This is my script and I updated to the newest instafeed version. 

 ```
var userFeed = new Instafeed({
        get: 'user',
        userId: 1222775100,
        resolution:'low_resolution',
        accessToken: '11429333.2a95792.91d4b90781954fbdbbd24485fc10d44b',
        template: '<div class="col-xs-12 col-sm-4 col-md-3 animatedParent"><figure class="animated fadeInUp"><a href="{{link}}" target="_blank"><img src="{{image}}" /></a></div>'
    });
    userFeed.run();
```
I will try requesting new permissions and try again.

**Comment by AchilesGomes** [comment]
@pfhenley86 works like a charm =), i just put scopes on request.

`https://instagram.com/oauth/authorize/?client_id=[CLIENT_ID_HERE]&redirect_uri=http://localhost&response_type=token`**&scope=basic+public_content**

**Comment by pfhenley86** [comment]
@AchilesGomes Thanks, that did the trick. I had no clue you could do it that way. lol I tried to manually request it in the API settings page. Anyway it works now. Thanks!

**Comment by emersonthis** [comment]
I know a lot of folks have had trouble with the jelled tokens because it doesn't let you choose scopes. The other day I created my own version with a scope option to save time: https://instagramtoken.com

**Comment by pfhenley86** [comment]
So, it suddenly stopped working again? I event tried the instagramtoken.com and I still get user does not exist.

**Comment by emersonthis** [comment]
Is the user you're looking for an accepted sandbox user?

**Comment by pfhenley86** [comment]
No, that is probably what it is. It was working without it and my client is not wanting to verify their account.

 

Ford Henley

Owner/Developer

Webrestorations

850-725-8718

 <https://webrestorations.co/> Webrestorations.co

**Comment by emersonthis** [comment]
That sounds like it. I'm pretty sure it was a bug that allowed it to work without accepting the invite. They probably "fixed" it.
