### ISSUE TITLE
Android not loading images from the feed

### ISSUE THREAD

**Issue by Hypocrite** [stevenschobert/instafeed.js#435]
It seems that when I use the {{image}} tag from the feed, it works fine from desktop browser.

But it displays a broken image in mobile devices. This seems to because the mobile device is redirecting the image to the application.

Is there any other way to display the image so that it would also work on mobile devices?

**Comment by mairagall** [comment]
I have Android 6.0.1 and it works just fine.

**Comment by OHB-IT** [comment]
same here
