### ISSUE TITLE
Registering Instagram Feed

### ISSUE THREAD

**Issue by whitsey** [stevenschobert/instafeed.js#436]
Is there any way for a novice to get the instagram feed to work?

i have tried every possible way explained in here and the the instagram documenation but I just can't get it to work.

This is well and truly beyond me?

**Comment by gluvian** [comment]
I have the same problem, 3 months ago till now the plugin doesn't work

**Comment by coolwebs** [comment]
Hey guys, it's not actually all that hard. Have you got your token, client ID and user ID setup? You will need to create an Instagram app in https://www.instagram.com/developer to make and app, then get the token.

**Comment by whitsey** [comment]
You just explained the easy bit - that's easy setting up app and getting the clientID and userID.

Now what? What token?

**Comment by coolwebs** [comment]
When you are logged into your Instagram account, open up another tab at this address http://instagram.pixelunion.net/ and follow the steps to generate your token. Please see this thread for more information - https://github.com/stevenschobert/instafeed.js/issues/432

**Comment by whitsey** [comment]
Did that as well and still not working. I have been through all these processes a number of times and I still have a non-functioning app.

That's the point - everything you've described is available in here but it still doesn't work.
