### ISSUE TITLE
Submit Instagram app to go live?

### ISSUE THREAD

**Issue by coolwebs** [stevenschobert/instafeed.js#437]
This is more of a question, rather than an issue. I've got the instafeed.js lib working just fine. My questions is regarding the Instagram app I had to create to get the token for authentication. It has been created in sandbox mode by default. Is it necessary to submit the app to 'GO LIVE'?

All I am concerned about is the rate limits really as I'm quite sure that the homepage I am building will get more than 500 hits an hour. But from what I can gather, that applies to people who are authenticating using their Instagram account, not just public viewing the page.

Link to Instagram developer docs regarding this - https://www.instagram.com/developer/sandbox/

**Comment by coolwebs** [comment]
Bump. This appears to be related to this issue https://github.com/stevenschobert/instafeed.js/issues/442

**Comment by chiggpatel** [comment]
How to Go Live On Instagram: LATEST UPDATE INSTAGRAM  LIVE
[](http://www.themobileupdates.com/how-to/how-to-go-live-on-instagram/)
