### ISSUE TITLE
Does this script work?

### ISSUE THREAD

**Issue by gnyangolo** [stevenschobert/instafeed.js#439]
I heard in some website that this script has failed to show images since 1st June 2015 just asking if this script still works. Please get back to me on how to use it as soon as possible.

**Comment by dawidskowron** [comment]
It doesnt work for me, every user must login..
Try this https://gist.github.com/shahril96/1e5b99080e1465c55d79 
I had to get the latest photo

**Comment by gnyangolo** [comment]
Thank you @dawidskowron  Let me check it out.

**Comment by gnyangolo** [comment]
Hi @mjk-fi I want to get images from a pubic hashtag do i need an access token or clients id ?
 Thank you in advance.

**Comment by mjk-fi** [comment]
I'm not sure. I read somewhere that you can't possibly get public images to website using hashtags anymore. It's because of the requirement of the access tokens. At least not in the way it was done before.

I'm not a Instagram expert or developer, so I don't know for sure.

**Comment by jerewall** [comment]
I would also love to know how to get public images using a hashtag, I got 2 sites down now because of this :(

**Comment by relish27** [comment]
My understanding is that you can no longer pull in any public content, as they are now requiring each user whose content is displayed to have an access token.  Therefore, it's impossible to pull in public tags, as you'd have to get approval from an unlimited number of users.  Major bummer.  I, too, was pulling in public content from an event's hashtag.

**Comment by gnyangolo** [comment]
Just a question to you all can I get a specific users images and filter them with a specific tag or this code  will not work.`
```
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'user',
        userId: 'USER_ID',
        filter: function(image) {
            return image.tags.indexOf('TAG_NAME') >= 0;
        }
    });
    feed.run();
</script>
```
