### ISSUE TITLE
Getting instafeed to load large image for Fancybox

### ISSUE THREAD

**Issue by mt-deva** [stevenschobert/instafeed.js#44]
Trying to get instafeed to load in the large image on click for fancybox - it seems from the filenames that the difference in the _#.jpg at the end, 5 being a small thumbnail, and 8 being the size I need

template: //a class="fancybox" href="{{image}}">//img class="instagram-image" src="{{image}}" /></a>

this makes the Fancybox fire properly, but will only load in the small image, any ideas?

Great plugin btw

**Comment by dudupavani** [comment]
This is work to

template: '<div><div class="insta_img"><a data-fancybox="gallery" href="{{model.images.standard_resolution.url}}"> <img src="{{image}}"/></div></a></div>',

**Comment by dudupavani** [comment]
// template: '<div><div class="insta_img"><a data-fancybox="gallery" href="{{model.images.standard_resolution.url}}"> <img src="{{image}}"/></div></a></div>',
