### ISSUE TITLE
Can some JS genius help?

### ISSUE THREAD

**Issue by joshmeares** [stevenschobert/instafeed.js#440]
<!--Cannot get this thing to bloody work!

Amateur trying to make first website.

Using dreamweaver.

Used http://instagram.pixelunion.net/#access_token=###

to generate access code, and used the numerical before the full stop was my userID.

<div id="instafeed">

<script type="text/javascript">
var userFeed = new Instafeed({
  get: 'la_cucinaitaliana',
  userId: '29********',
  accessToken: '29********.***********************************5242a9'
});
userFeed.run();
</script>
</div>

used <script type="text/javascript" src="js/instafeed.min.js"></script> just before body tag.

Wont run at all!

Please help!

--!>

**Comment by mjk-fi** [comment]
You can see the working one here:
[http://www.kareinen.fi/instagram.php](url)

I have this on the  <head>:
`<script type="text/javascript" src="js/instafeed.js"></script>`

Then this Div where the content should be:
`<div id="instafeed" style="padding-left:10px;padding-right:10px;text-align:center;"></div>`

And lastly this script under the page:
```
	<script type="text/javascript">
			
	var userFeed = new Instafeed({
		
		get: 'user',
		userId: 'ID IS FIRST 10-NUMBERS FROM TOKEN',
		accessToken: 'GENERATED ACCESS TOKEN',
		template: '<div class="instakoonti"><div class="instakuva"><a href="{{link}}"><img width="195" height="195" src="{{image}}" /></a></div><div class="instakommentit">&#128172; {{comments}} / &#10084; {{likes}}</div><div class="instapaivays">{{model.created_time}}</div></div>',
		resolution: 'low_resolution',
		limit: '20',
		filter: function(image) {

			var date = new Date(image.created_time*1000);

			m = date.getMonth();
			d = date.getDate();
			y = date.getFullYear();

			var month_names = new Array ( );
			month_names[month_names.length] = "Jan";
			month_names[month_names.length] = "Feb";
			month_names[month_names.length] = "Mar";
			month_names[month_names.length] = "Apr";
			month_names[month_names.length] = "May";
			month_names[month_names.length] = "Jun";
			month_names[month_names.length] = "Jul";
			month_names[month_names.length] = "Aug";
			month_names[month_names.length] = "Sep";
			month_names[month_names.length] = "Oct";
			month_names[month_names.length] = "Nov";
			month_names[month_names.length] = "Dec";

			var thetime = month_names[m]   + ' '+  d +' ' + y;

			image.created_time = thetime;

			return true;
		}
		
	});
	
	userFeed.run();

	</script>
```

**Comment by TheTonyStarks** [comment]
@mjk-fi , I updated my code to follow what you have. Still no luck for me. Wanted to ask a few things.

1. I'm trying to use a bootstrap template, should that matter?
2. I'm testing this locally on my PC, should that matter?
3. Will 'user' stay as it is or is that replaced by 'kareinen.fi' ( from your example site)?

Thanks

**Comment by mjk-fi** [comment]
1. I think it shouldn't matter
2. It works locally for me (I tested and opened simple html-file with Chrome)
3. User stays "user"

Do you have the access token made and the user-id is right?

**Comment by TheTonyStarks** [comment]
I believe so,  I followed the steps in the start-up and got the green success box with the id and token from the instafeed.js website.

Any other troubleshooting ideas?

**Comment by mjk-fi** [comment]
Not much, but I upload a test packet (one html-file and two javascript-files) here:
https://drive.google.com/open?id=0B1QOcmU3C18eWThCYXVTMzlzV28

Just modify the userid and accesstoken in main.js file.

If that test page doesn't work then you a problem in your access token, browser or server...

**Comment by TheTonyStarks** [comment]
@mjk-fi  - Thanks for all of you help so far. At this point i'm still hitting a wall.

I've taken the files you provided and tried to modify them as you suggested. When I run test.html I just get a blank screen. I've changed the following:

in main.js:

`	var userFeed = new Instafeed({
		
		get: 'user',
		userId: '12345678',
		accessToken: '12345678.XXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
		template: '<a href="{{link}}"><img src="{{image}}" /></a>',
		resolution: 'low_resolution',
		limit: '20',
		
	});
	
	userFeed.run();
`

So assuming your on the right path with where the issue could be I've created a new access token from scratch. 

That brings up 2 new questions:
1. When creating the token, what was your REDIRECT URI. Some tutorials I've seen say use "localhost" others say use "instafeed.js"?

2.Did you get the userId and Accesstoken from from using the link:

https://instagram.com/oauth/authorize/?client_id=YOURCLIENTIDHERE&amp;redirect_uri=HTTP://YOURREDIRECTURLHERE.COM&amp;response_type=token

And replacing the **YOURCLIENTIDHERE** and **HTTP://YOURREDIRECTURLHERE.COM** ?

**Comment by mjk-fi** [comment]
I didn't create access token with Instagram site... Or first I created but I didn't make it right and couldn't get it working. So I went with easier route and I used Pixel Union's access token generator:
http://instagram.pixelunion.net/

**Comment by TheTonyStarks** [comment]
@ mjk-fi - I think the situation may have been the same. I used the link you provided and I was able to see images on the page.

So 1 last question:
How would I pull all images with a specific hashtag.....like #supercar. Do all post have to be from me?
