### ISSUE TITLE
Orientation always square

### ISSUE THREAD

**Issue by JonnyBoggon** [stevenschobert/instafeed.js#443]
I cannot get the feed to pull through cropped portrait or landscape images.

I have changed the Instagram settings to allow for non-square images and they appear with white around them.

Here is my code.

```
var feed = new Instafeed({
        get: 'user',
        limit: 8,
        userId: 'xxxxxxxx',
        accessToken: 'xxxxxx.xxxxxxxx',
        filter: function(image) {
            return image.tags.indexOf('test') >= 0;
        },
        target: 'home-feed-instagram',
        resolution: 'standard_resolution',
        template: '<a class="instagram-{{orientation}}" href="#"><img src="{{image}}" /></a>'
    });
    feed.run();
```

The orientation, which I am displaying as a class, is always square - even if the image is landscape (within a square).

Can somebody please help?

**Comment by stevenschobert** [comment]
Make sure you re-generate your access token after updating the API settings in Instagram.

**Comment by JonnyBoggon** [comment]
Is non-square media the only setting I need to change in the API settings?

I created the account today and this was always set. I tried to regenerate the key and it gives me the same one again.

My keys look like this (few numbers changed)...

userId: '3357945875',
accessToken: '3657955805.1677ed0.a534b2866c3b4ebcab934d596cbd5192',

Images are still coming out in a white square box with the orientation always square.

**Comment by Z-13** [comment]
I have same problem!
I put a tick here **"Migrations > Non square media"**

Image link on my site:
http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/13731121_1106791119405171_1480158474_n.jpg?ig_cache_key=MTMxMzYwNTQ3MzIxNTQwOTMzMw%3D%3D.2.l

Image link on instagram:
https://scontent-amt2-1.cdninstagram.com/t51.2885-15/e35/13715221_185418215209656_1936605680_n.jpg?ig_cache_key=MTMxMzYwNTQ3MzIxNTQwOTMzMw%3D%3D.2

Link on site have it: **s640x640/sh0.08**

I created new client, change client id and generate new token here: [http://instagram.pixelunion.net/](http://instagram.pixelunion.net/)

My code:
```
<div id="instafeed">
<script type="text/javascript">
//<![CDATA[
var feed = new Instafeed({
 get: 'user',
 clientId: 'xxxxxxxxxxxxxxxxxxxxxxxx',
accessToken: 'xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx',
 userId: xxxxxxxxx,
  limit:6,
  sortBy:'random',
template: '<li><a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="insta-likes"><div style="display: table; vertical-align: middle; height: 100%; width: 100%;"><span style="display: table-cell; vertical-align: middle; height: 100%; width: 100%;">{{likes}} <i class="fa fa-heart"></i><br/>{{comments}} <i class="fa fa-comment"></i></span></div></div></a></li>',
 resolution: 'standard_resolution'
 });
 feed.run();
//]]>
</script>
</div>
```

I want to square and rectangular photos display squares without white borders, example here: http://smittentestblogcorinneperry.blogspot.ru/

Thank you!

**Comment by Z-13** [comment]
@JonnyBoggon and @stevenschobert 
I re-generate access token here: http://jelled.com/instagram/access-token and it work!

**Comment by JonnyBoggon** [comment]
Unbelievable @Z-13 thank you very much!!!!

**Comment by yergunes** [comment]
I need to show only square images or if its possible i want to show cropped versions of non-square images on my website.(I'm trying to prevent bad look on the website) Is that possible? And if its possible how can i achive that?

**Comment by jennybeaumont** [comment]
Instagram doesn't seem to want to let me create a client. Stuck in sandbox mode :\ Work arounds?

**Comment by scheibome** [comment]
@yergunes 

Search: `imgOrient = "square";` ... `imageUrl = imageObj.url;`

replace with:

```
imgOrient = "square";
var calcResolution = imgHeight;
var lastPoint = 1080 * (imgHeight / imgWidth * 100) / 100;

if (imgWidth > imgHeight) {
  imgOrient = "landscape";
}
if (imgWidth < imgHeight) {
  imgOrient = "portrait";
  calcResolution = imgWidth;
  lastPoint = 1080 * (imgWidth / imgHeight * 100) / 100;
}

var calcX = (imgWidth - calcResolution)/2;
var calcY = (imgHeight - calcResolution)/2;
var cropImageUrlAdditional = '/c' + Math.round(calcX) + '.' + Math.round(calcY) + '.' + Math.round(lastPoint) + '.' + Math.round(lastPoint) + '/';

imageUrl = imageObj.url + cropImageUrlAdditional;
```

**Comment by scheibome** [comment]
@yergunes 

i have add a pull request.
Please test the full code: https://github.com/stevenschobert/instafeed.js/pull/459

**Comment by yergunes** [comment]
Thanks for help @scheibome i will test that code in couple days but i'm recently working on different project.
