### ISSUE TITLE
Open images in new tab

### ISSUE THREAD

**Issue by JensNielsen81** [stevenschobert/instafeed.js#445]
Thanks for a great plugin :)

Is it posible to open images in a new tab(_blank instead of _self)?

**Comment by stevenschobert** [comment]
Hey @JensNielsen81! Yes, you can use the template tag for that:
```js
var feed = new Instafeed({
  template: '<a href="{{link}}" target="_blank"><img src="{{image}}" /></a>'
  // other settings...
});
```

**Comment by JensNielsen81** [comment]
Great, thanks m8

Sendt fra min iPhone
