### ISSUE TITLE
Access token is now required?

### ISSUE THREAD

**Issue by jazzu20** [stevenschobert/instafeed.js#446]
I would like to confirm if the access token is now required? if it is, is it a huge security threat if we are going to use a 3rd party (e.g outofthesandbox) to generate access token?

I'm only using client ID to pull the feed. and I'm getting this error: 

```
target: 'instafeed',
get: 'user',
userId: xxx,
limit: 10,
links: true,
sortBy: 'most-recent',
clientId: 'xxxx',
resolution: 'standard_resolution'
```

_Uncaught Error: Error from Instagram: The access_token provided is invalid._

please help

**Comment by blackdown** [comment]
having the same issue

**Comment by jazzu20** [comment]
i guess in this case we really need to get access token.  but the security is at risk.

**Comment by blackdown** [comment]
yes it does work with an access token

**Comment by tellstevens** [comment]
so we're supposed to replace "clientID" with "accessToken" with the token created? I tried that and it still didn't work. Is it because I'm trying to pull hashtag content?
```
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'hashtag',
        clientId: 'xxxxxxx',
        limit: 12,
        links: true, 
        resolution: 'low_resolution',
        template: '<li><a href="{{link}}" target="_blank"><img src="{{image}}" /></a></li>'
    });
    feed.run();
</script>
```

**Comment by jazzu20** [comment]
@tellstevens what error do you received?

**Comment by tellstevens** [comment]
@jazzu20 I got the same error. It could've been that the new token was still propagating or something but I had to make a quick change so I just used the Instagram Feed by Smash Balloon to get a feed up and going. You have to upgrade to a pro version to use the hashtag but I just stuck with the feed for now. *I'm using wordpress 

> Uncaught Error: Error from Instagram: The access_token provided is invalid.

**Comment by lebonze** [comment]
I'm having to get a new access_token every few weeks (I'm in sandbox, only displaying a few posts) as it seems to expire - is it normal? it's highly annoying

**Comment by stevenschobert** [comment]
Yes, if you are in sandbox mode, you'll need to use an access token instead of the client ID.

Practically, there isn't a security risk in using an access token, so long as it only has basic read permissions. Without being able to like pictures or post comments on your behalf, the token really wouldn't have any value to anyone malicious.

**Comment by stevenschobert** [comment]
@lebonze I don't have any control over the access token lifetimes, so I'm not sure if/when/why Instagram would revoke them. They didn't use to revoke them, but they could have started recently for any number of reasons.

**Comment by osahyoun** [comment]
I've changed the library slightly to have it work with [BitSalad.co](http://bitsalad.co), which removes the need for an access token - https://github.com/osahyoun/instafeed.js
