### ISSUE TITLE
Remove video entries

### ISSUE THREAD

**Issue by KebiainWoods** [stevenschobert/instafeed.js#447]
Hi y'all,

Hopefully an obvious question, but I don't see a way (without adding tags to every image on instagram) to just return latest posts that are only images, as in no video entries.

The problem is the images generally have black bars top and bottom as they are snapshots from the videos, which look terrible in amongst the wall to wall images. So if I could filter them out it would be perfect.

Any help much appreciated.

Thanks

**Comment by stevenschobert** [comment]
@KebiainWoods Yes, you can remove videos using the following `filter` option:

```js
var feed = new Instafeed({
  // other options
  filter: function(image) {
    return image.type === "image";
  }
});
feed.run();
```
