### ISSUE TITLE
next() function not working

### ISSUE THREAD

**Issue by weirdpuppy** [stevenschobert/instafeed.js#449]
Hi I just downloaded instafeed and I'm trying to load more objects. I have done the thing with Load more button but it isn't working! I'm pretty` new to javascript so maybe  I am doing this all wrong?

`<div id="instafeed">
</div>
 <button id = 'load-more'> Load More </button>

<script src="js/instafeed.js-master/instafeed.min.js"></script>

<script type="text/javascript">
  var loadButton = document.getElementById('load-more');
  var userFeed = new Instafeed({
    get: 'user',
    userId: '3034560',
    clientId: '76ebf5755ee44186b5c5e9e9c8f98d68',
    accessToken: '3034560.1677ed0.67b60906b38b467b8b4b11634cc536c6',
    resolution: 'standard_resolution',
    template: '<p> {{model.location.latitude}} </p> <br> <p> {{model.location.longitude}} </p><img src="{{image}}" />',
      filter: function(image) {
        return image.tags.indexOf('tuckerandroxannesspectacularadventures') >= 0;
    },
    limit: 5,
    links: false,
    after: function() {
        if (!this.hasNext()) {
            moreButton.hide();
    }
      }
  });
    loadButton.addEventListener('click', function() {
        userfeed.next();
    });

```
userFeed.run();    
```

</script>`

**Comment by mirdnas** [comment]
Example: 

<body>

	<div id="instafeed"></div>
	<a href="#" id="next-button">Next</a>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script type="text/javascript" src="node_modules/instafeed.js/instafeed.min.js"></script>
	<script type="text/javascript">

	    var nextButton = document.getElementById('next-button');

	    var feed = new Instafeed({
	    	get: 'user',
	        accessToken: 'my token',
	        userId: 'my user id',
	        clientId: 'my cllient id',
	        limit: '8',
	        resolution: 'low_resolution',
	        template: '<a class="fancybox" rel="instagram" href="{{image}}"><img src="{{image}}" /></a>',
	        // every time we load more, run this function
	        after: function() {
	            // disable button if no more results to load
	            if (!this.hasNext()) {
	                nextButton.setAttribute('disabled', 'disabled');
	            }	            
	        },
	    });

	    // bind the load more button
	    nextButton.addEventListener('click', function(event) {
	    	event.preventDefault();
	    	feed.next();
	    });


	    // run our feed!
	    feed.run();

	</script>
</body>

**Comment by Yohn** [comment]
when using next() I cant get more than 20 images to load.

**Comment by mirdnas** [comment]
Instagram in sandbox.

View: https://github.com/stevenschobert/instafeed.js/issues/442

**Comment by christopherbisman** [comment]
the answer of **mirdnas** works perfect
