### ISSUE TITLE
Any way to set different class names for the first and last instafeed images?

### ISSUE THREAD

**Issue by stidn** [stevenschobert/instafeed.js#450]
Hi,

I'm pretty much tearing my hair out trying to get this to work. I'm a complete noob with Javascripting and can't seem to work out how to set different class names for the first and last images that gets grabbed by instafeed. Could someone please throw me a bone and provide me with some hints on how to accomplish this?

Thanks.

**Comment by stevenschobert** [comment]
Hey @stidn! One option would be to use the CSS `first-child` and `last-child` pseudo selectors for that:

```css
#instafeed a:first-child {
  ...
}

#instafeed a:last-child {
  ...
}
```

You might need to modify the above CSS to match your markup, but hopefully that gives you the idea.

**Comment by stidn** [comment]
Hi Steven, thanks for the reply!

 That was my backup option but I was trying to avoid doing that.

I'm currently trying to swap out another feed that I'm using with Instafeed so I was really hoping that I could just match the classes with the one that I currently use so I didn't have to redo all the styling for it.

**Comment by stevenschobert** [comment]
Ah I see. Do you have a sample of what markup you're trying to achieve.

You have the option of using the `template` option as well.

**Comment by stidn** [comment]
Sure!

This is what the classes currently look like, instagram feed is limited to 4 images:

```
<div id="instagram">
	<div class="four columns alpha"></div>
	<div class="four columns" </div>
	<div class="four columns" </div>
	<div class="four columns omega"></div>
</div>
```

My template for Instafeed is:
`'<div class="four columns"><a href="{{link}}" target="_blank" id="{{id}}"> <img class="il-photo__img" src="{{image}}" alt="Dhuezclothing image"/></a></div>'`

**Comment by stevenschobert** [comment]
Ah I see. One little workaround you can do to achieve that, is to use the `filter` option to add some dynamic attributes to the template:

```js
var count = 0;
var feed = new Instafeed({
  // other options...
  filter: function(image) {
    var className = "four columns";

    if (count === 0) {
      className += " alpha";
    }
    if (count === 3) {
      className += " omega";
    }

    image.customClassName = className;
    count++;
  },
  template: '<div class="{{model.customClassName}}"><a href="{{link}}" target="_blank" id="{{id}}"> <img class="il-photo__img" src="{{image}}" alt="Dhuezclothing image"/></a></div>'
});
```

**Comment by stidn** [comment]
Thanks so much for the help but I still can't get this to work! I've added the code you've provided but now the feed is completely blank and there's nothing in the instafeed target div. As soon as I take away the filter section it comes back again, I can't work out what's wrong with it. Here's my script tag:

```
var count = 0;
var instagram = new Instafeed({
	get: 'tagged',
	accessToken: '3745481769.ba4c844.eee79d1d45ec40638aad9489a945f58c',
	target: 'instagram',
	resolution: 'standard_resolution',		
	tagName: 'awesome',
	limit: 4,
  	filter: function(image) {
    	var className = "four columns";

    	if (count === 0) {
   	   		className += " alpha";
   		}
  	  	if (count === 3) {
      		className += " omega";
    	}

   	 	image.customClassName = className;
    	count++;
  	}, 
    template: '<div class="{{model.customClassName}}"><a href="{{link}}" target="_blank" id="{{id}}"> <img class="il-photo__img" src="{{image}}" alt="Instagram image {{orientation}}"/></a></div>'
	});
	
instagram.run();
```

**Comment by stevenschobert** [comment]
Ah my mistake, you need to add a `return true;` to the end of the filter function.

```js
filter: function(image) {
  //.. Rest of code
  count++;
  return true;
}
```
