### ISSUE TITLE
tagged vs default

### ISSUE THREAD

**Issue by akasophistikat** [stevenschobert/instafeed.js#452]
Has anyone ran into the issue where if you look to pull your own images via tagName, no problem, but pulling down the default images returns a 400 error from Instagram?

I have a website multiple events pages. Some of my events have a tag name and some do not. When they don't have a tag, I simply want to display my feed, whether its most popular, random, most-liked etc. etc.

**Comment by stevenschobert** [comment]
What do you mean by "default images"?

**Comment by akasophistikat** [comment]
option **get** would be unset or set to _popular_
option **sortBy** would be unset or set to _none_

Basically asking it to 'give me whatever you have from my account'. to give you some context, this event has/had a **tagName** associated with it http://adclubca.staging.wpengine.com/our-events/2016-digital-day/ so we only show that **tagName**. It is possible that an event may not have any pictures, in which case we simply want to show our feed based on the two options listed above.

**Comment by stevenschobert** [comment]
The "popular" endpoint is no longer supported by the Instagram API, if your client was created after Nov 17, 2015.
