### ISSUE TITLE
Error from Instagram: invalid media id

### ISSUE THREAD

**Issue by fabolousfrances** [stevenschobert/instafeed.js#453]
I try to use instafeed.js to display the 10 last instagram post from my account, on my magento website.

Here is my script :

`<script type="text/javascript">
        var feed = new Instafeed({
            clientId: 'myclientid',
            accessToken: 'myaccesstoken',
            template: '<a href="{{link}}"><img src="{{image}}" /></a>',
            sortBy: 'most-recent',
            limit: '10',
            resolution: 'thumbnail'
        });
        feed.run();
</script>`

It returns me an error : Error from Instagram: invalid media id

Of course my instagram application is in sandbox mode, and from what I read on the instragram website, it will stay at this state for this kind of use. And I've unchecked the OAuth security.

I don't understand what I means by 'invalid media id'. Can you help me ?

Thanks

**Comment by stevenschobert** [comment]
You need to tell Instafeed.js that you are wanting to get images from a user account:

```js
var feed = new Instafeed({
  // other settings
  get: "user",
  userId: "YOUR_USER_ID"
});
feed.run();
```
