### ISSUE TITLE
Can't get images to appear

### ISSUE THREAD

**Issue by smittymedia** [stevenschobert/instafeed.js#455]
Hey Guys as the title says I can't get the images to appear.

I tried generating my access tokens from both Instagram and Pixel Union.

I am not getting an error just no images.

I am kind of a noob at this so any help would be appreciated.

TIA

Here is my code:

<!DOCTYPE html >

<html lang="en">

<head>

```
<script type="text/javascript" src="js/instafeed.js"></script>
<script type="text/javascript" src="js/main.js"></script>
```

</head>

<body>
     <script type="text/javascript">

```
get: 'user',
userId: '72bfaa66301d4a5cb197ec741xxxxxx',
accessToken: '842110629.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
template: '<a href="{{link}}"><img src="{{image}}" /></a>',
resolution: 'low_resolution',
limit: '20',
```

});

userFeed.run();

```
userFeed.run();

</script>

    Newest pics from my <a href="https://www.instagram.com/smittymedia/">Instagram-account</a>

    <div id="instafeed"></div>
```

</body>

</html>

**Comment by riassmismans** [comment]
Try this: http://pastebin.com/pKybqNDv
