### ISSUE TITLE
Filtering images

### ISSUE THREAD

**Issue by vyshwanara** [stevenschobert/instafeed.js#460]
Can we only ,pull the images that we have liked or commented on so that unnecessary images can be filtered and we can get the images we want from the particular tag

**Comment by stevenschobert** [comment]
Hey @vyshwanara! You might be able to use the `filter` option to do that, by checking the properties like `user_has_liked`.

Keep in mind though, filters are applied after the `limit` option, so you'll most likely won't be able to get very many pictures in your call.

You might have better luck using the Instagram API directly to fetch your own liked pictures: https://www.instagram.com/developer/endpoints/users/#get_users_feed_liked
