### ISSUE TITLE
Limit 60, yet only 33 (?!) images are pulled

### ISSUE THREAD

**Issue by eaglejohn** [stevenschobert/instafeed.js#462]
I set a limit of 60, but only 33 images are pulled. Seems like a very random number?
The Instagram account has 824 posts, that can't be the problem I think.

Site: http://www.tamarakingtattoos.com/gallery/
Instagram: https://www.instagram.com/tamarakingtattoos/

**Comment by stevenschobert** [comment]
@eaglejohn Sometimes the Instagram API will return less images than what you set in the limit option. This has been a long standing issue, you can read more about it in #23.
