### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by Natlalie** [stevenschobert/instafeed.js#464]
Hi,

I've been using InstaFeed on a website for a while and the pagination has been working well before.
It however does no longer work. this.next() always returns null. I haven't done any changes to my code.
Do you know why this is happening. Since it's something that has just happened without any interference from me i suspect that it has something to do with changes to the Instagram API.
I read that their is a 20 images limit when your client in Sandbox mode(which is the only mode my client can be in according to Instagram).

Any help would be appreciated

Here is the code I'm using:

 ```
var loadButton = document.getElementById('load-more');
 var feed = new Instafeed({
 			get: 'user',
 			userId: USERID,
 		        accessToken: 'ACCESSTOKEN',
 			link: 'true',
 			clientId: 'CLIENTID',
 			limit: '20',
 			resolution: 'standard_resolution',
 			template: '<section class="post"><span class="date" id="{{model.created_time}}">{{model.created_time}}</span><a href="{{link}}" target="_blank"><img src="{{image}}" width="{{width}}" height="{{height}}" /></a><div class="info"> <span class="likes">{{likes}}</span><span class="comments">{{comments}}</span><span class="fb"><a onclick="fbClick(&quot; http://www.facebook.com/sharer.php?u={{link}}&display=popup &quot;)"><img src="{{media url="wysiwyg/facebook_insta.png"}}" alt="" /></a></span><span twitter="twitter"><a href="https://twitter.com/intent/tweet?url={{link}}" class="twitter-share-button"  data-count="none"><img src="{{media url="wysiwyg/twitter_insta.png"}}" alt="" /></a></span></div><div class="caption">{{caption}}</div></section>',
 			 after: function() {
 			     $j(".date").each(function(){
 			          var instaTimestamp = $j(this).attr("id");
 			          var created_date = new Date(instaTimestamp*1000);
 
 			          var currMonth = created_date.getMonth();
 			          currMonth++;
                                   $j(this).html(created_date.getDate() +"."+currMonth +"."+created_date.getFullYear())
 			     });
 			    // disable button if no more results to load
 			   if (!this.hasNext()) {
 			      loadButton.setAttribute('disabled', 'disabled');
 			    }
 			  },
 	    });
 	    loadButton.addEventListener('click', function() {
 	         feed.next();
 	   });
 
 	    feed.run();
 
 
           function fbClick(url){
                  openInWindow(url, 290, 290);
            };
```

**Comment by stevenschobert** [comment]
Hey @Natlalie! Yes, in sandbox mode they limit the API to 20 results.

Since you already have your limit set to 20, you probably can't fetch any more than that.

Are you hitting any specific errors you're trying to fix?

**Comment by Natlalie** [comment]
Hey @stevenschobert ,

Unfortunately it doesn't matter what I set my limit to, I can still only get the latest 20 products.

I am not getting any errors while running the code. 

The pagination used to work before but now when the code runs `this.hasNext()` it returns `false` even though there are more pictures on the Instagram account. 

However if I set the Limit to 15, I can click the "Load more"-button and I will get the remaining 5 images.

Is there anyway the InstaFeed plugin can load the next 20 images using pagination or is this no longer possible due to Instagrams API?

**Comment by stevenschobert** [comment]
Ah okay, thanks for the additional info.

Unforturnalty, if you're in Sandbox mode, there's nothing Instafeed.js can do to get around the 20 image limit. That is being controlled by the Instagram API, not Instafeed.js.

You'll have to get your app approved for production mode, by submitting your API client through Instagram's review process.
