### ISSUE TITLE
All values in "users_in_photo" are undefined?

### ISSUE THREAD

**Issue by nwsm** [stevenschobert/instafeed.js#467]
Okay so I'm using the following filter:

```
filter: function(image){
    image.taggedUsers = "";
    for(var i = 0; i<image.users_in_photo.length; i++) {
        image.taggedUsers += image.users_in_photo[i].username + ", ";
    }		
    return image.users_in_photo.length>0;
}
```
So basically I generate a string containing the usernames of all users_in_photo.

However, the string that is created always contains "undefined, undefined, etc" Now, the array I'm getting for users_in_photo does contain the correct number of users, because there is always the correct number of "undefined"s in the string created based on how many people are tagged in the photo.

I've tried this with username, profile_picture, id, and full_name, and they all are undefined. So either I'm accessing them incorrectly or they aren't being pulled from the API.

Any thoughts?

**Comment by stevenschobert** [comment]
@nwsm I believe you want this:

```js
filter: function(image){
    image.taggedUsers = "";
    for(var i = 0; i<image.users_in_photo.length; i++) {
        image.taggedUsers += image.users_in_photo[i].user.username + ", ";
    }		
    return image.users_in_photo.length>0;
}
```

The username is under the `user` object in each entry:

```json
"users_in_photo": [{
    "user": {
        "username": "kevin",
        "full_name": "Kevin S",
        "id": "3",
        "profile_picture": "..."
    },
    "position": {
        "x": 0.315,
        "y": 0.9111
    }
}]
```

**Comment by nwsm** [comment]
Ahhh I see. This is working as intended, thank you.
