### ISSUE TITLE
get deprecation_warning on pull tagged images

### ISSUE THREAD

**Issue by chidalgom1503** [stevenschobert/instafeed.js#471]
Hi, thanks for this great plugin.

Now Im having problems to pull images with specific tag, the plugin works for other tags we used for other projects, but now  that we have our own tag (for a better filtered results), nothing is pulled out. The console show me this error:

pagination": {"deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead"}

This tag works find for other endpoints, like search or get info, even if you search on instagram by this tag will show you some results, but as I said before, if i use other tags everything works, and, if I set this particular tag (that exists in some posted images), this error comes up.

dont know what else to do.

I hope explain my self.
Many thanks!.

the tag results: (just in case)
https://www.instagram.com/explore/tags/denunciapaisajeculturalxv/
 
endpoint results:

- https://api.instagram.com/v1/tags/denunciapaisajeculturalxv?access_token=XXXXXXXXX
{"data": {"name": "denunciapaisajeculturalxv", "media_count": 3}, "meta": {"code": 200}}

- https://api.instagram.com/v1/tags/search?q=denunciapaisajeculturalxv&access_token=XXXXXXXXX
{"data": [{"media_count": 3, "name": "denunciapaisajeculturalxv"}], "meta": {"code": 200}}

- https://api.instagram.com/v1/tags/denunciapaisajeculturalxv/media/recent?access_token=XXXXXXXXX
{"data": [], "meta": {"code": 200}, "pagination": {"deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead"}}

**Comment by nathalipaz** [comment]
Hello @chidalgom1503  
Did you solve your problem or any idea?
I am working with instagram api, executing URLs only for the moment

Thanks

**Comment by ciromine** [comment]
Apparently this is the reason https://stackoverflow.com/a/33845334/2112832
