### ISSUE TITLE
Coupling Instafeed with MixItUp filtering gallery - Issue: instafeed pictures don't show when charging page

### ISSUE THREAD

**Issue by PatrickTrempond** [stevenschobert/instafeed.js#475]
Hi all! I'm new to GitHub and more of a designer than a coder, I'm a real beginner with js. I've been turning around and lack imagination/knowledge to find a solution to my problem.

I'm currently using Instafeed in my own website, as it was included in a template I adapted to my needs, and I must say I found it really awesome! I use it to show only my own pics though.

So now I've a client (carpenter, roofwork, etc.) and in the website I designed for him (html+css), there's a gallery, but instead of a classic gallery, I propose him a gallery based on Instagram feed, so the only thing he would have to do is take pics of his work with his phone and put the wright hashtags corresponding to the gallery filters... et voilà !

To do that, I used Instafeed coupled with a content filter made by Codyhouse (https://codyhouse.co/gem/content-filter/), itself integrating MixItUp (https://github.com/patrickkunka/mixitup/) to filter and display/animate the gallery, but not using the filter lateral pannel.

My problem is that the images from instafeed don't show at the charging of the galley page, but the images I integrated along like in the demo (https://codyhouse.co/demo/content-filter/index.html) show. I can't find what is the problem and need some external view, but I make the supposition it must have something to do with Instafeed as the set of images from demo do show and instafeed don't in the same page.

Here's my code (I used my own instagram id for testing as my client has no pics yet in his own account):

HTML:
The filters
```
<ul class="cd-filters">
    <li class="placeholder"> 
      <a data-type="all" href="#0">TOUTES</a> <!-- selected option on mobile -->
    </li> 
    <li class="filter"><a class="selected" href="#0" data-type="all">TOUTES</a></li>
    <li class="filter" data-filter=".aspet"><a href="#0" data-type="aspet">ASPET</a></li>
    <li class="filter" data-filter=".bonvivre"><a href="#0" data-type="bonvivre">BON VIVRE</a></li>
    <li class="filter" data-filter=".masiadurba"><a href="#0" data-type="masiadurba">MASIA DURBA</a></li>
    <li class="filter" data-filter=".comminges"><a href="#0" data-type="comminges">COMMINGES</a></li>
    <li class="filter" data-filter=".lulouna"><a href="#0" data-type="lulouna">LULOUNA</a></li>
</ul> <!-- cd-filters -->
```
The gallery itself
```
<section class="cd-gallery w960">
  <ul id="instafeed"></ul> <!-- Instafeed -->
  <ul> <!-- Codyhouse demo gallery -->
      <li class="mix instagram-listing aspet masiadurba"><img src="img/img-1.jpg" alt="Image 1"></li>
      <li class="mix instagram-listing bonvire lulouna comminges"><img src="img/img-2.jpg" alt="Image 2"></li>
      <li class="mix instagram-listing lulouna"><img src="img/img-3.jpg" alt="Image 3"></li>
      <li class="mix instagram-listing aspet bonvivre"><img src="img/img-4.jpg" alt="Image 4"></li>
      <li class="mix instagram-listing comminges aspet"><img src="img/img-5.jpg" alt="Image 5"></li>
      <li class="mix instagram-listing masiadurba bonvivre"><img src="img/img-6.jpg" alt="Image 6"></li>
      <li class="mix instagram-listing aspet bonvivre masiadurba comminges lulouna"><img src="img/img-7.jpg" alt="Image 7"></li>
      <li class="mix instagram-listing bonvivre"><img src="img/img-8.jpg" alt="Image 8"></li>
      <li class="mix instagram-listing aspet"><img src="img/img-9.jpg" alt="Image 9"></li>
      <li class="mix instagram-listing masiadurba"><img src="img/img-10.jpg" alt="Image 10"></li>
      <li class="mix instagram-listing comminges"><img src="img/img-11.jpg" alt="Image 11"></li>
      <li class="mix instagram-listing lulouna comminges"><img src="img/img-12.jpg" alt="Image 12"></li>
      <li class="gap"></li>
      <li class="gap"></li>
      <li class="gap"></li>
  </ul>
  <div class="cd-fail-message">Aucune photo pour l'instant...</div>
</section> <!-- cd-gallery -->
```

JS:
```
$(function(){
    var feed = new Instafeed({
      get: 'user',
      resolution :'standard_resolution', //thumbnail (default) - 150x150, low_resolution - 306x306, standard_resolution - 612x612
      limit:'60', //Maximum number of Images to add. Max of 60.
      userId: USER_ID, //Get the user id
      accessToken: 'USER_ID+MANY_FIGURES', //Generate access token http://jelled.com/instagram/access-token
      template: '<li class="mix instagram-listing {{model.tagsFormatted}} col-md-2"> \
                  <a href="{{link}}" target="_blank"> \
                    <img class="img-responsive" src="{{image}}" /> \
                    <div class="instagram-overlay"> \
                      <p class="instagram-caption">{{caption}}</p> \
                    </div> \
                  </a> \
                </li>',

      //filter by tag to remove the comas inside the class

      filter: function(image) {
          image.tagsFormatted = '';
          for(var i = 0; i < image.tags.length; i++) {
            image.tagsFormatted += image.tags[i];
            if(i < (image.tags.length - 1)) {
              image.tagsFormatted += ' ';
            }
          }
          return true;
      }
    });
    feed.run();
});
```
The JS scripts used to filter made by Codyhouse are attached. But I guess the code concerning showing images at the loading of the page would be this:
```
concatenate: function(){
    	var self = this;
    
    	self.outputString = ''; // Reset output string
    
	    for(var i = 0, group; group = self.groups[i]; i++){
	      	self.outputString += group.active;
	    }
    
	    // If the output string is empty, show all rather than none:    
	    !self.outputString.length && (self.outputString = 'all'); 
	
    	// Send the output string to MixItUp via the 'filter' method:    
		if(self.$container.mixItUp('isLoaded')){
	    	self.$container.mixItUp('filter', self.outputString);
		}
  	}
```
[main.js.zip](https://github.com/stevenschobert/instafeed.js/files/677525/main.js.zip)

Hope I'm clear enough and some good soul could help me with that!

**Comment by stevenschobert** [comment]
Hey @PatrickTrempond! The problem you're running into (that happens a lot when trying to integrate Instafeed.js with other plugins), is that your gallery plugin is loading _before_ Instafeed.js has had a chance to run, so it's not aware of the Instagram content.

In order to fix this, you need to use the `after` callback that comes with Instafeed.js, and run the gallery there.

In your specific case, you can do this by changing the content of the `main.js` to a standard function, instead of running it on jQuery's document ready.

*Before:*
```js
jQuery(document).ready(function($){
  //open/close lateral filter
  $('.cd-filter-trigger').on('click', function(){
    triggerFilter(true);
  });
  // rest of function...
});
```

*After:*
```js
function setupPage() {
  //open/close lateral filter
  $('.cd-filter-trigger').on('click', function(){
    triggerFilter(true);
  });

  // rest of function...
}
```

Then, you can run Instafeed.js using document-ready, and call the rest of your setup function inside the `after` callback:

```js
$(function(){
    var feed = new Instafeed({
      get: 'user',
      resolution :'standard_resolution', //thumbnail (default) - 150x150, low_resolution - 306x306, standard_resolution - 612x612
      limit:'60', //Maximum number of Images to add. Max of 60.
      userId: USER_ID, //Get the user id
      accessToken: 'USER_ID+MANY_FIGURES', //Generate access token http://jelled.com/instagram/access-token
      template: '<li class="mix instagram-listing {{model.tagsFormatted}} col-md-2"> \
                  <a href="{{link}}" target="_blank"> \
                    <img class="img-responsive" src="{{image}}" /> \
                    <div class="instagram-overlay"> \
                      <p class="instagram-caption">{{caption}}</p> \
                    </div> \
                  </a> \
                </li>',

      //filter by tag to remove the comas inside the class

      filter: function(image) {
          image.tagsFormatted = '';
          for(var i = 0; i < image.tags.length; i++) {
            image.tagsFormatted += image.tags[i];
            if(i < (image.tags.length - 1)) {
              image.tagsFormatted += ' ';
            }
          }
          return true;
      },
      after: function() {
        setupPage();
      }
    });
    feed.run();
});
```

**Comment by stevenschobert** [comment]
For reference, here is your updated `main.js` script: http://d.pr/f/ZsFS

**Comment by PatrickTrempond** [comment]
Thanks for your quick answer @stevenschobert but it seems something is not working though.

I copied your updated main.js script, put the userId and accessToken in due place and there's no feed at all. Did I miss something?

**Comment by stevenschobert** [comment]
Do you see any errors in the console @PatrickTrempond?

**Comment by PatrickTrempond** [comment]
@stevenschobert I checked the console and there is a succession of syntax errors, I fix one, then another appears.

It begins with this one:
SyntaxError: expected expression, got ')'[En savoir plus]  main.js:159:1
I tried to fix it, then the others following, but it ends with a problem of:
TypeError: buttonFilter is undefined main.js:159:1 which I don't know how to fix...

**Comment by stevenschobert** [comment]
@PatrickTrempond Ah, sorry about that. I made a typo in the version I sent you. Try this version instead: http://d.pr/f/yveQ

**Comment by PatrickTrempond** [comment]
@stevenschobert It now works perfect! Many thanks!
