### ISSUE TITLE
Limit and Filter

### ISSUE THREAD

**Issue by brianmadhan** [stevenschobert/instafeed.js#476]
Hello

I have a problem with showing ig feed with filter and limit.

Give an example:
I have 6 posts with format likes: _image - image - video - image - image - image_

I just wanna show image post, so I use this code

`var feed= new Instafeed({
	    get: 'user',
	    userId: 'xx',
	    clientId: 'xx',
	    accessToken: 'xx',
	    resolution: 'standard_resolution',
	    limit: 6,
	    filter: function(image) {
        	return image.type === 'image';
            }
	  });
	  feed.run();`
but it just show 5 posts.

I hope you can help me.

Thank you..

**Comment by stevenschobert** [comment]
Hey @brianmadhan! Filters are applied _after_ the limit option, so you'll need to raise the limit and remove extras after the fact. See #8 for an example.
