### ISSUE TITLE
Error from Instagram: this user does not exist

### ISSUE THREAD

**Issue by lucija-glavas** [stevenschobert/instafeed.js#477]
I keep getting this error and this plugin used to work just fine before, i just don't get it

this is my code:

```
<script type="text/javascript">
	var feed = new Instafeed({
		get: 'user',
		userId: '2030811713',
		clientId: '2d0b703da7c14a378bc19bc04f120da4',
		accessToken: '1437995179.2d0b703.68a08f9127cb44439dca7d7ca4b48a19',
		target: 'list-inline',
		limit: '10',
		template: '<li><img src="{{image}}"/></li>',
		resolution: 'standard_resolution',
		after: function() {
			var el = document.getElementById('list-inline');
			if (el.classList)
				el.classList.add('show');
			else
				el.className += ' ' + 'show';
		}
	});
	feed.run();
</script>
```
and this is the errori get

/**/ instafeedCache767624e5ae541596.parse({"meta": {"code": 400, "error_message": "this user does not exist", "error_type": "APINotFoundError"}})

Please, help

**Comment by stevenschobert** [comment]
I believe this error comes from the Instagram API directly. The message being => `this user does not exist` means that your API key can't access the user ID `2030811713`.

Possible causes:
- User isn't added to your sandbox account (if you're API client is in sandbox mode).
- User's account is private.
- User's account has been deleted.

I'd check that your API key is still valid, and has access to that user account.

**Comment by Shanupa** [comment]
API Behavior
The behavior of the API when you are in sandbox mode is the same as when your app is live, but comes with the following restrictions:

Data is restricted to sandbox users and the 20 most recent media from each sandbox user
Reduced API rate limits
The first point is important and it means that the API behaves as if the only users on Instagram were your sandbox users, and the only media ever posted were the last 20 for each of these users.

For example, if you query the /users/{user-id}/ endpoint and the {user-id} is a sandbox user, then you will get the normal API response; but if the {user-id} is not a sandbox user, you will get a APINotFound error.
