### ISSUE TITLE
Duplicate instafeed!

### ISSUE THREAD

**Issue by connorv** [stevenschobert/instafeed.js#478]
I'm having a super weird issue with instafeed where the posts are duplicating and I have no idea why. 

Here's my javascript control: 
`<script type="text/javascript">// <![CDATA[
var feed = new Instafeed({
        get: 'user',
        userId: '',
        clientId: '',
        accessToken: '',
        template: '<div id="{{id}}" class="instagram_container"><a href="{{link}}" target="_blank" title="{{caption}} by @{{model.user.username}}"><img src="{{image}}" alt="{{caption}} by @{{model.user.username}}" class="instagram_image" /></a></div><div class="instagram_image_meta"><div class="owner instagram_image_meta_item"></div><div class="caption instagram_image_meta_item"><p>{{caption}}</p></div></div>',
        resolution: 'standard_resolution',
        limit: '30'
    });
    feed.run();
// ]]></script>`

aaaand the CSS:

`#instafeed {
    width: 100%;
    max-width: 1648px;
    padding: 0 24px;
    margin: 0 auto;
    font-size: 0;
    display: -webkit-box;
    display: -moz-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-direction: normal;
    -webkit-box-orient: horizontal;
    -moz-flex-direction: row;
    -ms-flex-direction: row;
    flex-direction: row;
    -ms-flex-wrap: wrap;
 	 flex-wrap: wrap; 
}

#instafeed a {
  width: auto;
}

.instagram_container {
      display: inline-block;
    -webkit-box-flex: 0;
    -moz-flex: 0 1 33.3333%;
    -ms-flex: 0 1 33.3333%;
    flex: 0 1 33.3333%;
    padding: 0 16px;
    margin: 0 0 32px;
}
.owner_profile_picture {
  display: none;
}

.instagram_image_meta {
	top: 50%;
	-webkit-transform: translateY(-50%);
	-moz-transform: translateY(-50%);
	-ms-transform: translateY(-50%);
	-o-transform: translateY(-50%);
	transform: translateY(-50%);
	position: absolute;
	width: 100%;
	color: black;
	opacity: 0;
	pointer-events: none;
	letter-spacing: 2px;
}

.caption a {
font-size: 13px;}
.instagram_container:hover .instagram_image_meta {
	opacity: 1;
}
.caption {
  padding:20px;
}
.instagram_image_meta a {
	color: black;
}
`

check it out here: https://www.bearbuttteam.com/pages/instagram
I'm probably doing something wrong, but the issue is not CSS or the script so I don't know what it could be. Any help is greatly appreciated

**Comment by ry167** [comment]
There is no duplicate feed on that page anymore, so could you close this issue?

**Comment by connorv** [comment]
Sure thing Steve

**Comment by raphaelparent** [comment]
Issue is still not closed. @connorv can you close it?

**Comment by stevenschobert** [comment]
Closing this issue.

**Comment by connorv** [comment]
how do i close it
