### ISSUE TITLE
Unable to Display: How can I debug and display an Error message

### ISSUE THREAD

**Issue by jakeingit** [stevenschobert/instafeed.js#481]
I am calling the instafeed.min.js at the head, have a div with the id, and calling this script in the bottom with:
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'user',
        tagName: '3250741546',
        clientId: 'my client id tag from the dev page'
    });
    feed.run();
</script>

However, I'm not getting any feedback about why it is not working or displaying much.

How can I try and solve this problem? I am in my local enviroment.

**Comment by ry167** [comment]
It could be that you are using `get: 'user'` instead of `get: 'tagged'` while supplying a `tagName`. Try it either without the `tagName` or with `get: 'tagged'`

**Comment by jakeingit** [comment]
This isn't successful. I have it at the bottom before my </body>	

<script type="text/javascript">
    var feed = new Instafeed({

        clientId: 'f117da407805447f9776e35eb5414ef6' <- look like this ( I also have an access_token)
    });
    feed.run();
		</script>

**Comment by jakeingit** [comment]
How is it possible to debug this? I'm able to get the API codes from Instagram.

**Comment by ry167** [comment]
Could you post the full code you are using?

**Comment by jakeingit** [comment]
Here is the entire project file, feel free to edit within. Check out
Index.html.
https://www.dropbox.com/sh/8ttl9zgo5e3yo7v/AADpm9nrVVk7juSrPHEemSz_a?dl=0

**Comment by ry167** [comment]
Is the code you are having trouble with in index.html? If so, its missing the access token

Also in future its easier for people to help if you just post the snippet you are having problems with

**Comment by jakeingit** [comment]
I have an access token in the comments next to the script.

**Comment by jakeingit** [comment]
The snippit is exactly as recomended in the readme.

basic <div> in the index & called the instafeed.js in head.

<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: '67ff982107e74b7e93c8de9fc77b46ea',
		accessToken: "3250741546.67ff982.cbd7092dc6e945c9917bf6fb55a979cf"
    });
    feed.run();
</script>

**Comment by ry167** [comment]
I ran that code and its not working because your accessToken needs `scope=public_content` added to the authorization request. You can read more about that here: https://www.instagram.com/developer/authorization/

**Comment by jakeingit** [comment]
Ah, I got a new accessToken then and added it to the script. However, Its not showing anything.

```
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: '67ff982107e74b7e93c8de9fc77b46ea',
		accessToken: "3250741546.67ff982.cbd7092dc6e945c9917bf6fb55a979cf"
    });
    feed.run();
</script>
```

**Comment by ry167** [comment]
Hmm, this is caused by Instagram's API Sandboxing. You can read up on it here: https://www.instagram.com/developer/sandbox/

The main quote to take from there is: 

> let's consider an endpoint that returns a list of media: /tags/{tag-name}/media/recent. The response returned by this endpoint will contain only media with the given tag, as expected. But instead of returning media from any public Instagram user, it will return only media that belongs to your sandbox users, restricted to the last 20 for each user.

So you will need to submit your application for Permissions review in order to display a proper list of tagged posts.

**Comment by jakeingit** [comment]
I just want it to return the latest 20 posts from the developer's own
instagram. For permissions on my app, selecting the option for posting
instagram posts on my site I get:

You do not need to submit for review for this use case. If you are a
developer and you want to display Instagram content on your website, then
you do not need to submit your app for review. By using a client in sandbox
mode, you can still access the last 20 media of any sandbox user that
grants you permission.

You can find more information in the Permission Review documentation
<https://www.instagram.com/developer/review/>.

I just don't see how this can be worked in with their rules.
