### ISSUE TITLE
Get images by tag name

### ISSUE THREAD

**Issue by mikrafizik** [stevenschobert/instafeed.js#484]
Hi, i have this sample
```
var feed = new Instafeed({
get: 'tagged',
tagName: 'awesome',
target:'instagramFeed',
accessToken:'***',
template: '<div class="col-xs-6 col-md-3"><a href="{{link}}" class="thumbnail"><img src="{{image}}"></a></div>'
});
feed.run();
```
But i see an error in my console:

> Error: No images were returned from Instagram

Anybody knows what the problem? 
I get my token with scope=public_content

**Comment by mathewleland** [comment]
I also am having this problem.  I'm not sure if instafeed still works for tagNames?

**Comment by mikrafizik** [comment]
so, i find the problem:
you need submit your app, to get public_content scope, that means that you can show photos only from your own profile which tagged.
for example  i have 1 photo tagged #wayexplorer, but in public scope i get 3 photos.
So, that is not Instafeed issue.

**Comment by stevenschobert** [comment]
@mikrafizik If you API client is in sandbox mode, yes. You can only get pictures from your own account (or any users that have been invited to your sandbox).

Live API clients approved by Instagram don't have that restriction.
