### ISSUE TITLE
Instafeed works only on the test environment

### ISSUE THREAD

**Issue by felipenanni** [stevenschobert/instafeed.js#487]
[EDIT: Added a link to the website}

Hello!

I'm trying to use instafeed on my girlfriend's online store, but I don't have any experience with web development, HTML, Javascript, CSS. 

Her store is on an online platform like Shopify, called Iluria. We'd like to show the feed of her profesional Instagram. The problem that I'm having is that the feed works perfectly on the store test environment, but when I go to the live store (sorry if I'm not using the right terms), the Instagram feed doesn't load. If I press F12, I get the following error messages:

```
GET http://testedonanni.iluria.com/instafeed.min.js
Uncaught ReferenceError: Instafeed is not defined at (index):110
```

Here's the code that's in index.html, before </body>:

```
<center> 
    <a href="https://www.instagram.com/XXXXXXXXX/">    
        <img src="titulo-instagram.jpg" alt="text text tet" style="width:908px;height:59px; margin-left:15px; margin-top:-150px;">
    </a>
    <p></p>
    <div id="instafeed" style="margin-left: 14px;"></div>
</center>

<script type="text/javascript" src="instafeed.min.js"></script>
<script type="text/javascript">
    var feed = new Instafeed ({
        get: 'user',
        userId: 'XXXXXXXXXX',
        accessToken: 'XXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
	clientId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        limit: 5,
        resolution: 'standard_resolution',
        template: '<a href="https://www.instagram.com/XXXXXXX/"><img src="{{image}}"style="margin: 0 10px 0 0; width: 173px; height: 173x;"/></a>'
    });
    feed.run();
</script>
```

Here's an image showing the test environment, with the feed working the way I need (the images are the black squares):

![test](https://cloud.githubusercontent.com/assets/10394840/23827852/9b2e422c-069c-11e7-8779-1c1b321387f3.PNG)

Here's an image showing the live site, with the feed in blank:

![live](https://cloud.githubusercontent.com/assets/10394840/23827853/9b2fea0a-069c-11e7-8763-d87f2ae79b4a.PNG)

I've had some trouble understanding the instragram.developer part of setting up instafeed, but here's how it is:

**Sandbox mode
Valid redirect URIs: http://instafeedjs.com
implicit OAuth is disabled**

I already did the thing where I go to a link with my user_id and the redirect uri, and it loaded the instafeedjs website, with the following message:

> Success! Use the userId and token listed below to get your images:
> userId: XXXXXXXXXX
> accessToken: XXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

I'm sorry if I wrote too much, I'm just trying to give as much details as I can. Can anyone help me with this?

Here's the link to the site:
[http://testedonanni.iluria.com/](url)

Thanks!

**Comment by ongerit** [comment]
@felipenanni  Try pointing your instafeed.js to a CDB. Right your script is referencing to "instafeed.min.js" change that to " https://cdnjs.cloudflare.com/ajax/libs/instafeed.js/1.4.1/instafeed.min.js"

Below is an example. 

http://jsbin.com/babonejona/edit
