### ISSUE TITLE
Designer trying to implement - No images appearing

### ISSUE THREAD

**Issue by baboles** [stevenschobert/instafeed.js#488]
I'm struggling with getting instafeed.js to work correctly. So far I have this...

<script type="text/javascript" src="https://raw.githubusercontent.com/stevenschobert/instafeed.js/master/instafeed.min.js"></script><script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: '0c91cac4bf9f450fac###############
        accessToken: '4477402464.aeeff59.12dd511f392b42f98###############'
    });
    feed.run();
</script>
<div id="instafeed"></div>

I used elfsight to generate my accessToken, so I'm just assuming that should work. Other than that I'm not sure what I'm not doing correctly.

I'm not getting an error message or anything.

 Any help would be appreciated

**Comment by acbpro** [comment]
dont use github as your js source
download the file and include yourself

**Comment by kitwalker12** [comment]
@baboles you're missing the `clientId` parameter

**Comment by kitwalker12** [comment]
@baboles example code using target

```
          $(document).ready(function() {
              var feed = new Instafeed({
                clientId: "*****************",
                target: "instafeed",
                get: "user",
                userId: *****************,
                accessToken: "*****************",
                template: '<a href="{{link}}" class="instagram-image" target="_blank"><img src="{{image}}" /></a>'
              });

              feed.run();
          });
```

**Comment by MikeTheVike** [comment]
@kitwalker12 I used your example code after not having much luck, and I get a 404 not found error on the resource its trying to pull. Any ideas? Obviously the code below has the clientID, userID, and accessToken edited out.

`<script>
          $(document).ready(function() {
              var feed = new Instafeed({
                clientId: "XXXXXXX",
                target: "instafeed",
                get: "user",
                userId: XXXXX,
                accessToken: "XXXXXXXXX",
                template: '<a href="{{link}}" class="instagram-image" target="_blank"><img src="{{image}}" /></a>'
              });

              feed.run();
          });
</script>	
`

**Comment by kitwalker12** [comment]
@MikeTheVike sorry. not sure. It probably has something to do with incorrect clientID or accesstoken.

**Comment by MikeTheVike** [comment]
@kitwalker12 it turns out the userID is a number I had to find, and not username of the account like I thought. Added the number and it worked for me. Thanks!
