### ISSUE TITLE
Template not working.

### ISSUE THREAD

**Issue by josiahwiebe** [stevenschobert/instafeed.js#49]
I've setup instafeed and it seems to be working correctly, but every time I add the "template" string, it immediately stops displaying my photos.

I'm using this as my script:

``` js
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: USER_ID,
        limit: 5,
        accessToken: 'ACCESS_TOKEN',
        clientId: 'CLIENT_ID',
        resolution: 'standard_resolution',
        template: '<li><a href="{{link}}"><img src="{{image}}" /></a></li>'
    });
    userFeed.run();
</script>
```

When I look at my source on loading the page, it shows that div as:

``` html
<div id="instafeed">
     <a href><img src></a>
     <a href><img src></a>
     <a href><img src></a>
     <a href><img src></a>
     <a href><img src></a>
</div>
```

Any insight? Seems like it's not properly reading the variables, but I can't figure out why.

**Comment by stu2younow** [comment]
All works fine but not grouping the photos older version no problem, this is Fancybox3

 var button = document.getElementById("button");       
		 var feed = new Instafeed({
		              get: 'user',
		              userId: removed,
		              accessToken: 'removed',
		              limit: 12,
					  resolution: 'standard_resolution',
		              after: function () {
		                var images = $("#instafeed a").fancybox();
						$.fancybox.reposition()
						$.fancybox.update()
						$.fancybox.resize()
		                $.each(images, function(index, image) {
		                  var delay = (index * 75) + 'ms';
		                  $(image).css('-webkit-animation-delay', delay);
		                  $(image).css('-moz-animation-delay', delay);
		                  $(image).css('-ms-animation-delay', delay);
		                  $(image).css('-o-animation-delay', delay);
		                  $(image).css('animation-delay', delay);
		                  $(image).addClass('animated flipInX');
		                })
		              },
		              template: '<a rel="group" class="fancybox" href="{{model.images.standard_resolution.url}}" target="_blank"><img style="width:100%;" class="fancybox" src="{{image}}" /></div></a>'
		            });
		            feed.run();
					button.addEventListener("click", function() {
  feed.next();
});
