### ISSUE TITLE
The access_token provided is invalid.

### ISSUE THREAD

**Issue by cluber22** [stevenschobert/instafeed.js#490]
All of a sudden I have had the error **The access_token provided is invalid.** and my feed is not displayed, think this happened a week or two ago all of a sudden.

Last year when the new API changes came in I did all the required changes and generated a new token. It was all working fine.

Note that I am still in the **Sandbox mode** but i thought that should be okay. 

This is my code

```
var feed = new Instafeed({
          get: 'user',
          userId: 99999, /* removed */
          accessToken: '8420owjdojwdjwodd05be9968c46ed973c55fdd2d40c88', /* removed */
          link: 'true',
          limit: '8',
          template: '<div class="col-xs-6 col-sm-4 col-md-3" style="padding-right:5px;"><a href="{{link}}" class="thumbnail" target="_blank"><img src="{{image}}" width="120" height="120" alt="{{caption}}" title="{{caption}}"></a></div>'
      });
      feed.run();
```

**Comment by KhairulA** [comment]
Same issue

**Comment by cluber22** [comment]
I renewed my token and it seemed to do the trick, not sure why it stopped working.

**Comment by stevenschobert** [comment]
I've heard other reports of people's access tokens getting invalidated. Not sure why Instagram does that, but renewing the token is the correct fix.

Closing this issue.
