### ISSUE TITLE
Higher resolution images

### ISSUE THREAD

**Issue by vdecree** [stevenschobert/instafeed.js#492]
Is it possible to get the plugin to access images around 1080x1080 pixels? I've heard you can get access to images this size from instagram, though I've not been able to get it working. 

Has anyone achieved this using instafeed?

**Comment by sandyno** [comment]
Yeah you can achieved this using instafed,  just add the code  below on line 164 before this line "imageUrl = imageObj.url;"

if(this.options.resolution == 'standard_resolution'){
              imageFull = imageObj.url.replace("/s640x640/","/");
              imageUrl = imageFull;
            } else{
              imageUrl = imageObj.url;  
            }
