### ISSUE TITLE
404 when accessing v1/users/<username>/media/recent

### ISSUE THREAD

**Issue by crockpotveggies** [stevenschobert/instafeed.js#494]
Possibly related to https://github.com/stevenschobert/instafeed.js/issues/485 but different result. Using v1.4.1.

When using instafeed like:

```
$(document).ready(function() {
  // instagram feed
  var feed = new Instafeed({
      clientId: '834293472937492734',
      accessToken: '12312341.123.1231.231123123',
      get: 'user',
      userId: '<username>',
      limit: 7,
      resolution: 'thumbnail',
      template: '<div class="footer-instagram">' +
                '<a class="my-classes" href="{{link}}"><img alt="{{post.title}}" '+ 'src="{{image}}"></a>'+
              '</div>'
  });
  feed.run();
});
```

I get a `404` from the Instagram API. The following request is being made in the browser:

```
https://api.instagram.com/v1/users/<username>/media/recent?access_token=<accesstoken>&count=7&callback=instafeedCacheddd6ef313f3b2890.parse
```

Unfortunately there's no other information returned from the API.

*Can confirm the username is valid.*

**Comment by crockpotveggies** [comment]
Solved, was not using *unique* ID.

**Comment by AMAFsoft** [comment]
What does mean a unique Id??

**Comment by IOIIOOIO** [comment]
@AMAFsoft I think I found the answer here, under the section "How to find your user ID":

https://css-tricks.com/everything-need-know-instagram-api-integration/#article-header-id-12
