### ISSUE TITLE
All images are not displaying

### ISSUE THREAD

**Issue by sayamkanwar** [stevenschobert/instafeed.js#496]
Hi, This is my script:
  var feed = new Instafeed({
      get: 'tagged',
      target: xxx,
      tagName: xxx,
      accessToken: xxx,
      clientId: xxx,
      resolution: 'standard_resolution',
  });

feed.run();

I read about this thing on instagram's developer portal and I think it has something to do with sandbox mode.

Can someone please help me?

**Comment by wuno** [comment]
Did you ever get this to work? In the docs it says,

> Instafeed with automatically look for a <div id="instafeed"></div> and fill it with linked thumbnails.

But when I follow the instructions it will not work for me either. I found some people saying you have to have a accessToken. I got one but I am still having the same issue of nothing rendering. 

```
<div id="instafeed"></div>

<script type="text/javascript" src="scripts/instafeed.min.js"></script>

<script type="text/javascript">
var feed = new Instafeed({
    get: 'user',
    userId: '909090',
    clientId: '909090',
    accessToken:'909090',
    target: 'instafeed',
    limit: 5,
    resolution: 'low_resolution',
    });
</script>
```

Anyone have any input on this? I can not get it to work. I have read all the docs multiple times, what am I missing?

**Comment by budzik12** [comment]
I'm having a similar issue. I am complete n00b and i'm struggling to get instagram posts to appear within my website. Any help would be greatly appreciated! 
I have the above in my html file with a instafeed.min.js within my scripts directory. This is a direct copy of that provided. 
I've also included the following within the css template:
	/* Instafeed */
	instafeed.instakoonti{
    display:inline-block;
    margin:5px;
    border:1px solid #c6c6c6;
    }

instafeed.instakuva{

    padding:0px;
    margin:0px;
    background-color:#F0F0F0;

}

instafeed.instakommentit{
    background-color:#F0F0F0;
    padding-top:0px;
    padding-bottom:3px;
    margin:0px;
}

Any help would be greatly appreciated.

**Comment by wuno** [comment]
Here is the full example of what I got running, I hope it helps!

In head
```
<head>
<!-- slick -->
	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick-theme.css"/>
</head>
```

Output for instafeed
```
<!-- Instafeed Image Feed -->	
	<div  class=" slickitup shift mtop20 " id="instafeed"></div>
```

After Footer
```
<script type="text/javascript" src="scripts/instafeed.min.js"></script>
<script type="text/javascript"> 
var feed = new Instafeed({ 
	clientId: 'GETTHISFORYOURINSTAGRAMACCOUNT', 
	accessToken: 'GETTHISFORYOURINSTAGRAMACCOUNT', 
	get: "user",
  	userId: "5427181789", 
  	sortBy: 'most-recent',
  	limit: '30',
  	after: function () {
       $('.slickitup').slick({
            infinite: true,
  			slidesToShow: 9,
  			slidesToScroll: 9,
  			 responsive: [
		{
		  breakpoint: 1324,
		  settings: {
		    slidesToShow: 7,
		    slidesToScroll: 7,
		    infinite: true,
		  }
		},
		{
		  breakpoint: 1224,
		  settings: {
		    slidesToShow: 6,
		    slidesToScroll: 6
		  }
		},
		{
		  breakpoint: 1024,
		  settings: {
		    slidesToShow: 5,
		    slidesToScroll: 5
		  }
		},
		{
		  breakpoint: 800,
		  settings: {
		    slidesToShow: 4,
		    slidesToScroll: 4
		  }
		},
		{
		  breakpoint: 624,
		  settings: {
		    slidesToShow: 3,
		    slidesToScroll: 3
		  }
		},
		{
		  breakpoint: 480,
		  settings: {
		    slidesToShow: 2,
		    slidesToScroll: 2
		  }
		},
		{
		  breakpoint: 324,
		  settings: {
		    slidesToShow: 1,
		    slidesToScroll: 1
		  }
		}
	],
       });
    }
  }); 
  	feed.run(); 
 </script>
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
```
[Example of it working here!](https://repliconradio.com/)

**Comment by budzik12** [comment]
Wuno, thank you so much! That has worked perfectly. I have it all set up now, with the ability to display all the images or specific ones with tags. Thanks :)
