### ISSUE TITLE
Nothing is showing

### ISSUE THREAD

**Issue by evilfx** [stevenschobert/instafeed.js#501]
Hi,

I'm using this:

`<!doctype html>

<html lang="en">
<head>
<script type="text/javascript" src="instafeed.min.js"></script>
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'kawibikinis',
        clientId: 'aa5871aaa4fd4a7b8xxxxxx'
    });
    feed.run();
</script>
</head>
<body>
<div id="instafeed"></div>
</body>
</html>`

But i get a blank page. What am i doing wrong?

**Comment by nicpro85** [comment]
me too
