### ISSUE TITLE
Access Token keeps invalidating

### ISSUE THREAD

**Issue by justinhough** [stevenschobert/instafeed.js#506]
The access token that I created for a client keeps showing as invalid every day or so. The only resolution that I have been able to find is to create a new access token but having to do that every day or so seems unfeasible.

Here is the init:
```
var userFeed = new Instafeed({
      get: 'user',
      userId: '1234567890',
      accessToken: '1234567890.0000000.222222222222222222222222222222',
      template: '<a href="{{link}}" id="{{id}}" class="instagram-block"><img src="{{image}}" class="instagram-image" /><span class="instagram-icon"></span></a>',
      resolution: 'standard_resolution',
      limit: 12
  });
```

**Comment by rhcarlosweb** [comment]
here too, i don't know what is, but from time to time i need to generate a new token, my guess, it's because the quantity of requisitions, i don't know

@justinhough Did you get any solutions?

**Comment by justinhough** [comment]
@rhcarlosweb I haven't been able to track down the specific issue since it happens randomly.

**Comment by spadilha** [comment]
Same here...

**Comment by taraskhvyl** [comment]
The same problem.
Any solutions?

**Comment by benjamin-hull** [comment]
This might be a side-effect of sandbox users being limited to 5 clients? Not sure - it's an instagram API issue, rather than something that can be fixed in instafeed.js. I'm going to close this for now - feel free to re-open with any new info.
