### ISSUE TITLE
Limit max of 60

### ISSUE THREAD

**Issue by elenaramirez** [stevenschobert/instafeed.js#508]
Hi there! i've found in documentation "Maximum number of Images to add. Max of 60." and i've a doubt. 

60 is the max number even if i use Pagination? I'm sure my project will have more than 60 images to show, so i need to show all of them one way or another. 

Is there another way to increase the max number???

Thank you very much!!

**Comment by CHEWX** [comment]
I believe Instagram have a limit of 20 on their API.

You'd need to create an app to get more by using pagination.

**Comment by rediris** [comment]
This is a great resource for folks confused by the sandboxing and rate limits: https://css-tricks.com/everything-need-know-instagram-api-integration/

**Comment by benjamin-hull** [comment]
Closing this as stale.
