### ISSUE TITLE
Select range (from 3rd post till the 9th post)

### ISSUE THREAD

**Issue by MarsallD** [stevenschobert/instafeed.js#509]
I am looking into making a grid where the last two posts are big and the rest are displayed at half the size. Like this:

|¯¯|¯¯¯¯|¯¯|¯¯¯¯|¯¯|
|¯¯|       |¯¯|       |¯¯|
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
I was thinking of having two different Instagram feeds, one limit:2, displayed big. 
And then the second limit:6, displayed small, but that then somehow had to start with the 3rd post... 
Is this possible, to pick a range like from post 3 till post 9?

**Comment by stevenschobert** [comment]
You might could use the `filter` option to eliminate posts based on created time, but it's not a great solution because the filtering happens after the images and limit have been applied.

For what you're trying to do, using CSS `:nth-child` sounds like the best option.
