### ISSUE TITLE
Get the name of one who post and the date he / she posted 

### ISSUE THREAD

**Issue by mingtam** [stevenschobert/instafeed.js#511]
Hi,

Would like to ask for some help. I would like to capture the name who posting the post and the date he / she posted. Went through the document and it seems not the function available now, can anyone share some light to me how I can extract the data? thanks!

** Picture for reference on the data required, thanks again!
![images](https://user-images.githubusercontent.com/25152555/28161035-91be3b2a-67f4-11e7-85d9-d2fcfc817f50.png)

**Comment by stevenschobert** [comment]
Hey @mingtam! Check #21 for a full list of data that's available.

In your case, you can use `{{model.user.username}}` to get the user's username.

For the created date, check #55.

**Comment by mingtam** [comment]
Thanks a lot! Problem resolved!
