### ISSUE TITLE
Works for only some Instagram users?

### ISSUE THREAD

**Issue by xaiyeon** [stevenschobert/instafeed.js#512]
I want to say thank you for making this! So I'm able to get this to work, but for certain users the feed is never fetched at all, but for some users it works (unless people set their profile to private, but otherwise even public yields no feed). Is there a limitation to a User Instagram ID?

**Comment by hghazni** [comment]
I've come across the exact same issue, my account works which is private. Though another front end dev's account didn't and neither did our clients account. Both their accounts are public. Not sure what the solution would be?

**Comment by rediris** [comment]
Folks having issues with this are probably in sandbox mode: https://www.instagram.com/developer/sandbox/
