### ISSUE TITLE
load all images from a post with multiple photos 

### ISSUE THREAD

**Issue by mingtam** [stevenschobert/instafeed.js#513]
Hi, 

Some posts may have one images like this one.

https://www.instagram.com/p/BUwtRaTg30c/

(it contains 9 images in one post). Is there method I can use to grap all the images in this post? Thanks for your help first!

**Comment by nsina** [comment]
@mingtam The Instagram API was [updated in April 2017](https://www.instagram.com/developer/changelog/) with `carousel ` that returns `url` for all photos that are part of the initial link. Check the response code (specifically the `carousel_media` portion):
https://www.instagram.com/developer/endpoints/media/#get_media

I haven't integrated this functionality yet, but I believe that it only works if you have `public_content` permission, thus you can't integrate the carousel if you're testing in the sandbox.

**Comment by pauloqueiros** [comment]
By any chances this has been integrated yet? I am looking to get carousel posts off instagram but the plugin returns only the first image of the carousel. Is there any way I can have access to the rest of the images to use in template?

**Comment by stevenschobert** [comment]
@pfvqueiros Not yet! I've set up an issue to track the progress of it here: #650 

But we'll probably address #646 and #649 before we tackle carousel images.
