### ISSUE TITLE
Hidden 1080px Resolution

### ISSUE THREAD

**Issue by jakekimpton** [stevenschobert/instafeed.js#514]
Hi, just been doing some research on how to obtain the max_res from Instagram.

Apparently, a 1080px wide version is available through the img url.

So here's a 640 link:
[https://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/19436479_145349929369857_3470429623521640448_n.jpg](https://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/19436479_145349929369857_3470429623521640448_n.jpg)

And if the s640x640 is changed to s1080x1080... You've guessed it... The 1080px wide version is displayed.
[https://scontent.cdninstagram.com/t51.2885-15/s1080x1080/sh0.08/e35/19436479_145349929369857_3470429623521640448_n.jpg](https://scontent.cdninstagram.com/t51.2885-15/s1080x1080/sh0.08/e35/19436479_145349929369857_3470429623521640448_n.jpg)

It isn't documented anywhere on Insragram's Documentation so I wonder how this could be incorporated into your script.

**Comment by jakekimpton** [comment]
Have just spotted an identical issue.

Although I had to modify the solution for it to work:

```
if (this.options.resolution == 'standard_resolution') {
                            imageFull = imageObj.url.replace("640x640/", "/");
                            imageUrl = imageFull;
                        }
                        else {
                            imageUrl = imageObj.url;
                        }
```

**Comment by thejohnvu** [comment]
Hi Jake,

Where did you add the code to make the 1080px resolution work? What line etc?

Thank you,
John.

**Comment by jakekimpton** [comment]
Hi John,

In the unminified script:

Find
```javascript
imageUrl = imageObj.url
```

And replace with
```javascript
if (this.options.resolution == 'standard_resolution') {
                            imageFull = imageObj.url.replace("640x640/", "/");
                            imageUrl = imageFull
                        } else {
                            imageUrl = imageObj.url
                        }
```
