### ISSUE TITLE
Pull multiple resolutions. 

### ISSUE THREAD

**Issue by jakekimpton** [stevenschobert/instafeed.js#515]
Is it possible to pull through multiple image sizes for each image? I'd like to pull through a low res version for the thumb and then a standard res for my lightbox to load up.

Unsure how I'd go about setting up a new filter to do this.

**Comment by CHEWX** [comment]
Hi Jake,

Yes, use the `{{modal.images.low_resolution.url}}` and `{{modal.images.standard_resolution.url}}` for your templating.

Thanks,
Tom

**Comment by jakekimpton** [comment]
Hi, thanks but for some reason using those code snippets breaks my lightbox. I end up with 
`Uncaught TypeError: $(...).simpleLightbox is not a function`
No images load at all.

Code with updated resolution template:

```javascript
<script type="text/javascript">
    var gridElem = document.querySelector('#instafeed');
    var msnry;
    var feed = new Instafeed({
        get: 'user'
        , clientId: 'xx'
        , accessToken: 'xx'
        , userId: 'xx'
        , sortBy: 'none'
        , resolution: 'standard_resolution'
        , template: '<div class="grid-item"><a href="{{modal.images.standard_resolution.url}}" data-fancybox="gallery"><img src="{{modal.images.low_resolution.url}}" /></a></div>'
        , after: function () {
            var $grid = $('.grid').imagesLoaded(function () {
                $grid.masonry({
                    columnWidth: '.grid-sizer'
                    , itemSelector: '.grid-item',
                    percentPosition: true
                });
                $('.grid-item a').simpleLightbox();
            });
        }
    });
    feed.run();
</script>
```

**Comment by CHEWX** [comment]
@jakekimpton Sorry, there was a typo `{{model.images.low_resolution.url}}` and `{{model.images. standard_resolution.url}}`

Cannot spell :)

**Comment by jakekimpton** [comment]
Great thanks, all working now!
