### ISSUE TITLE
Instafeed in safari Version 10.1.1

### ISSUE THREAD

**Issue by chris30web** [stevenschobert/instafeed.js#517]
All images are not displaying in Safari version 10.1.1.

**Comment by chris30web** [comment]
any suggestions? thanks

**Comment by stevenschobert** [comment]
Hey @chris30web! Double check that you have:

1. Put the `<div id="instafeed"></div>` on your page
2. Put the Instafeed.js script tag at the bottom of the page, before the closing `</body>` tag
3. Have provided a valid access token

If you're still not seeing images after verifying those things, you can use the web inspector console to check for additional errors.

Thanks!
