### ISSUE TITLE
change limit after click on pagination

### ISSUE THREAD

**Issue by ahmedbana** [stevenschobert/instafeed.js#518]
Hello All,

I need to load 3 photos when load the page and 4 photos each time i click on pagination button, i tried to edit the after: function() but with no good results.

any suggestion for the algorithm i need ?

Thank's for help

**Comment by jdelmore83** [comment]
The only way I can think of is to give the script an ID, find it after the page has loaded, remove it, then reinsert the new script with the new limit.

**Comment by ahmedbana** [comment]
Wow, Great idea thank you

**Comment by benjamin-hull** [comment]
Closing.
