### ISSUE TITLE
Hashtags are returned in a random order

### ISSUE THREAD

**Issue by jdelmore83** [stevenschobert/instafeed.js#521]
Hi Guys,

I'm trying to write a function that relies on getting the **first tag** as it appears in the original instagram post.

When I get {{ model.tags }} they are always returned in a seemingly random order and always a different order.

Hoping someone might be able to point me in the right direction..

Here's my code:

```
var feed = new Instafeed({
    get: 'user',
    userId: '222',
    accessToken: '222',
    limit: 4,
    resolution: 'low_resolution',
    template: '<a class="instapic" data="{{model.tags}}"><img src="{{image}}" /></a>'
    
    });
    
    feed.run();
```

```
$('.instapic').on('click', function() {
    var instapicObject = $(this).attr('data');
    var firsttag = instapicObject.toString().split(',')[0];
    console.log(firsttag);
  });
  });
```

**Comment by benjamin-hull** [comment]
One way to do this would be to use the `model.tags` collection to scan the caption text to work out which one appears first (this just shows the concept - you'll need to adapt for your situation:

```
var tags = ['cats', 'dogs', 'fish'],
    caption = "Check out my new #fish, hope the #cats and #dogs don't eat him!",
    tagSearchResults = tags.map(function(t){
      return caption.indexOf('#' + t);
    }),
    firstTagIndex = Math.min(...tagSearchResults),
    firstTag = tags[tagSearchResults.indexOf(firstTagIndex)];

console.log(firstTag); // Returns 'fish'
```

**Comment by benjamin-hull** [comment]
I'm going to close this for now, on the assumption it's pretty old. Feel free to re-open if it's still current!
