### ISSUE TITLE
Is there a way to return tagged images that are also "liked by" a user (us)?

### ISSUE THREAD

**Issue by ci5ic** [stevenschobert/instafeed.js#522]
Wanted to create a fun campaign where users would use a hashtag and their image would be put up on our website/in-store media, etc.

Obviously, that could get sideways without some moderation, so I was hoping there would be a way to return a set of images with that hashtag that were also "liked" (approved) by us.

Any thoughts?

**Comment by jdelmore83** [comment]
The model object includes a user_has_liked: boolean, so you should be able to use that with the filter option.

**Comment by benjamin-hull** [comment]
Sadly, this is no longer possible due to changes/deprecations in Instagram's API.
