### ISSUE TITLE
Instafeed stopped pulling pictures..

### ISSUE THREAD

**Issue by dfvink** [stevenschobert/instafeed.js#524]
But console shows no errors..

http://derodewinkel.nl/collectie/

Any idea? Other sites where I used this plugin are working fine..

UPDATE: found out it has something to do with filtering on a certain tag..

**Comment by imnz730** [comment]
it could be caused by changes to the API terms

**Comment by dfvink** [comment]
It is stuck in sandbox mode - so it stopped after 20 pics..
