### ISSUE TITLE
Uncaught Error: Error from Instagram: invalid media id

### ISSUE THREAD

**Issue by Tatsuman** [stevenschobert/instafeed.js#525]
Hello, I'm getting this error with the code below.
Couldn't find the reason why this happening and I wanted get help.
Client id and accessToken are just created and cannot be wrong. I tried this several time and couldn't get this work. 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/instafeed.js/1.4.1/instafeed.min.js"></script>
</head>
<body>
    <div id="load-more">Click!</div>

    <script type="text/javascript">
    var loadButton = document.getElementById('load-more');

    var feed = new Instafeed({
        get: 'popular',
        clientId: '*************************************',
        accessToken: '***************************************'        
    });

    // bind the load more button
    loadButton.addEventListener('click', function() {
        feed.next();
    });

    // run our feed!
    feed.run();
</script>
</body>
</html>
```

**Comment by rediris** [comment]
Are you in sandbox mode? If so, you won't be able to get media or users who aren't also sandboxed.

https://www.instagram.com/developer/sandbox/

**Comment by benjamin-hull** [comment]
Yes, sandbox clients only ever have `basic` access permissions, which means that endpoints like `/popular` don't work. Sorry to be the bearer of bad news!
