### ISSUE TITLE
Instagram API Announcement - how it will impact on instafeed?

### ISSUE THREAD

**Issue by PrestaShark** [stevenschobert/instafeed.js#528]
I have reveived this email

> Hi Instagram Sandbox Developer,
> 
> We have recently announced new features to the Instagram API and are upgrading it to Facebook's Graph API. We encourage you to check out the exciting announcement shown here: https://business.instagram.com/blog/new-instagram-api-features/. With these new implementations, we will only be allowing and reviewing new applications for the basic permission level of the existing Instagram API (instagram.com/developer). 
> Starting October 1st, developers will no longer be able to apply to access any permissions other than the basic permission via the existing API. Since you are in sandbox mode, this means that you are in development so we highly encourage you to submit your API application before the end of September if you are interested in accessing more than the basic permissions.
> 
> For more information on the new Instagram Graph API, including the new permissions and what they can offer your product, please navigate to the facebook.com/developer site. 
> 
> 
> Thanks,
> The Instagram Platform Team

**Comment by richjdsmith** [comment]
A bit concerned as well 😟

**Comment by sidan5** [comment]
@PrestaShark Are you sure this is real and not some spam email? What's the reply-to address?

**Comment by richjdsmith** [comment]
@sidan5 I think it's pretty serious.

![image](https://user-images.githubusercontent.com/11435593/31053278-27f7951c-a69a-11e7-952d-ec75acfc6d63.png)

**Comment by sidan5** [comment]
@richjdsmith Saw it only after log out...

That's a bad move :(

**Comment by alFrame** [comment]
I hope this is not too off topic, but is using this script to simply show an instagram feed on a html website dead with this new API. Besides, I can't even get past registering a new client because the re-captcha fails and some imaginary data that is not completely filled in. And yeah, no issues on using this script have been resolved for ages. Dead fish in the water?

**Comment by Dannymx** [comment]
@alFrame Today I had all of those problems. First I fixed by registering my app in a incognito window (with Chrome, [details here](https://stackoverflow.com/questions/46339662/instagram-captcha-error-on-new-app-creation/46760811#46760811)) and now I can't get the instafeed to work, seems like the API has changed something that made this plugin to break.

**Comment by alFrame** [comment]
@Dannymx Thanks for chiming in. I tried to register in incognito mode in Chrome on Windows. And tried it in any other browser on Windows and Mac (not Chrome on Mac though). To no avail. That form is broken.

And you say the plugin is broken too now? Is there any intention of the team behind this plugin to fix it (hope hope)?

How on earth can we implement a specific users Instagram feed on a manually coded website then? It's a breeze using WordPress, but I kinda stepped away from WordPress for simple websites. The maintenance with updates and everything became a hassle...

Anyone good some good advice on this?

**Comment by markfinst** [comment]
@alFrame, I read somewhere that someone managed to register it via Firefox on Windows. 

I've written here all I know about current situation  https://stackoverflow.com/questions/46635195/how-to-access-instagram-feed-of-any-user-with-new-graph-api

**Comment by alFrame** [comment]
@markfinst thanks! It Worked in a FireFox private window... Thought I tried that, but apparently not. So much about sing and dance... sigh...

**Comment by alFrame** [comment]
I thought I post here again that after being able to register a client with Instagram and figuring out how to get my userId (RTFM) I am actually able to get the script to work. Seems that the new API does not have that much implication on the functionality of instafeed.js.

That said, I would like to thank everybody who contributed to this script and this thread!

**Comment by igorsantos07** [comment]
Still on the registering issue @alFrame, were you able to get the script running simply using a `cliend_id`? It seems that option is not available anymore on the API, only by using oAuth right?

**Comment by alFrame** [comment]
This is the code I got it running with:
```
var userFeed = new Instafeed({
  get: 'user',
  userId: 'number you get from here: https://smashballoon.com/instagram-feed/find-instagram-user-id/ or the first group of numbers in the access token, until the period ',
  accessToken: 'acces token you get form registering the app with instagram',
  sortBy: 'most-recent',
  limit: limitWidth,
  resolution: 'low_resolution',
  template: '<div>... customize to your needs</div>'
});
userFeed.run();
```

**Comment by bluecrabweb** [comment]
@alFrame How did you get the access token?  I wasn't allowed to register the app w/ Instagram

**Comment by alFrame** [comment]
I got it through in FireFox on windows in a private window... Launched FireFox private window with no other instance open.

**Comment by wiesson** [comment]
You can attach `?__a=1` to your instagram Link to load JSON content. example: `https://instagram.com/eightyfourrooms/?__a=1`

```
{
  user: (...), # <- contains media/nodes
  logging_page_id: "..."
}
```

**Comment by dec23rd1986** [comment]
Hi all, I can't seem to figure out how to get the client ID for my client or token. Per all the examples I have seen they are using their own Instagram ID. Can someone tell me how to obtain this? Do I have to have the client request it and then send it to me? 

I'm trying to put an Instagram feed carousel on the homepage of their website.

**Comment by jimlakey** [comment]
@dec23rd1986 Register your application at https://www.instagram.com/developer to get your client ID then follow all the instructions at https://www.instagram.com/developer/authentication/ to get your access token. It involves posting to https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=code with your info where it's all caps, and then after this in terminal, making a request as follows (again with your info where the caps are. The code is what you get a the end of the URL once you follow the step above) : 
    curl -F 'client_id=CLIENT_ID' \
    -F 'client_secret=CLIENT_SECRET' \
    -F 'grant_type=authorization_code' \
    -F 'redirect_uri=AUTHORIZATION_REDIRECT_URI' \
    -F 'code=CODE' \
    https://api.instagram.com/oauth/access_token

Follow the instructions at https://www.instagram.com/developer/authentication/  and you'll get there.

**Comment by wesley6j** [comment]
My summary of the steps to do:
1. Login instagram developer.
2. Create a managed client with redirect_uri `http://localhost` and uncheck `Disable implicit OAuth`.
3. Open this url in browser (replace the placeholder `[CLIENT_ID_HERE]`) `https://instagram.com/oauth/authorize/?client_id=[CLIENT_ID_HERE]&redirect_uri=http://localhost&response_type=token`
4. The token is in the redirected link. User id is the beginning part of the token( `user_id = token.split('.').first`).
