### ISSUE TITLE
Client ID supplied, but get error: The access_token provided is invalid

### ISSUE THREAD

**Issue by heaversm** [stevenschobert/instafeed.js#530]
According to [the documentation](http://instafeedjs.com/#user) - as of version 1.4, an access token is no longer required to display a user's feed when supplying a client ID, but I still get this error.

```
initFeed = function () {
        var feed = new Instafeed({
            clientId: '###',
            get: 'user',
            userId: '###',
        });
        feed.run();
    }
```

I am in Sandbox mode, but cannot submit requests as Instagram says this is not needed for a third party app to display my posts.

<img width="756" alt="screen shot 2017-09-29 at 3 28 33 pm" src="https://user-images.githubusercontent.com/520541/31038319-fa2fe82a-a52a-11e7-8134-fe32e25e8c67.png">

**Comment by stevenschobert** [comment]
Hey @heaversm! Shortly after 1.4 was released, Instagram changed their API terms and introduced the Sandbox mode you're referencing.

To work inside sandbox mode, you'll need to issue yourself an access token using the client ID Instagram gives you.

Sorry for the out-of-date docs!

**Comment by suture** [comment]
> To work inside sandbox mode, you'll need to issue yourself an access token using the client ID Instagram gives you.

How do we do that?

**Comment by hihellosm** [comment]
@suture try https://rudrastyh.com/tools/access-token
