### ISSUE TITLE
Instafeed and modal

### ISSUE THREAD

**Issue by boiy** [stevenschobert/instafeed.js#531]
hi 

I am not sure if someone has solved this but would be glad to see and know how 
i am developing a website/webapplication and will love to display IG feeds on it, the idea came from here
https://www.danielwellington.com/au/ .. when you click on the images under the DW IG section it will display a modal box ..like lightbox showing the image and the product... this is what i want to achieve

i have been able to get the feeds into the website, but can customize it like that... is there a way to achieve this with instafeed... am more of a server side developer 

Thank you

**Comment by benjamin-hull** [comment]
Hi @boiy - do you still need help with this? It's definitely possible using custom templating - the specifics depend on what lightbox approach/library you're using. Please re-open the issue if you like.
