### ISSUE TITLE
Like and comment formatting

### ISSUE THREAD

**Issue by eliaguilar** [stevenschobert/instafeed.js#532]
Not sure if anyone had a solutions but is there a way to format the likes and comments count? i.e. currently 1111 would like 1,111.

**Comment by benjamin-hull** [comment]
If you're using a custom template, you could use [toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) for the formatting, something like this:

```javascript
template: '{{model.likes.count.toLocaleString()}}'
```

**Comment by benjamin-hull** [comment]
I'm closing this as it's already pretty old. Feel free to re-open if needed.
