### ISSUE TITLE
Variables conflict with TWIG templating variables

### ISSUE THREAD

**Issue by toddpadwick** [stevenschobert/instafeed.js#535]
I am using Twig templating and it uses the same {{}} syntax. Meaning the instafeed variables conflict with it, breaking the site.
Do you know how I can get round this?

**Comment by stevenschobert** [comment]
Hey @toddpadwick! There are some workarounds for Twig suggested in issue #41.

Hope it helps!

**Comment by toddpadwick** [comment]
@stevenschobert  Excellent yes thats great, thanks :)
