### ISSUE TITLE
Does this work for other's feeds?

### ISSUE THREAD

**Issue by bluecrabweb** [stevenschobert/instafeed.js#539]
So, can I use this to display other people's feeds on my site?

I'm in Sandbox mode, and I didn't know how to get an access token.  I don't think I can "go live" with my app.

Any help is greatly appreciated!

**Comment by kiritokatklian** [comment]
Yes, you should be able to.

You can use services such as [Pixel Union](http://instagram.pixelunion.net/) to generate an access token with a click of a button, then copy that in your JS code. Keep in mind that you need to be signed in to that specific user's Instagram account before generating the token, or ask that user to generate and send the access token for you (which is what I usually do).

From what I read, you can’t do anything with the access token aside from browsing photos. This token doesn’t give any access to your personal data. Moreover, it doesn’t allow making any action from your account. Although I still have my own doubts on it, it should be safe to have someone else's access token.
