### ISSUE TITLE
Template config

### ISSUE THREAD

**Issue by shaunhalldesign** [stevenschobert/instafeed.js#541]
I use craft for my websites and this plugin is perfect except the template config uses {{ for the variables in the structure which is breaking as craft uses twig for compliling. 

Is there a way I can change the template config, perhaps the pattern in the function for the template:

Pattern = /(?:\{{2})([\w\[\]\.]+)(?:\}{2})/;

Sadly, I cannot fathom the pattern setup here, so perhaps its easy to do or perhaps if this is still managed an option can be added to change the template variable wrappers from {{ }} to something else like ## ##

**Comment by benjamin-hull** [comment]
Hi @shaunhalldesign - you can use `[verbatim](https://twig.symfony.com/doc/2.x/tags/verbatim.html)` or [escaping](https://twig.symfony.com/doc/2.x/templates.html#escaping) in twig to escape the template variables for instafeed.js and other mustache-y style templates.
