### ISSUE TITLE
Blank page is displaying

### ISSUE THREAD

**Issue by linas01** [stevenschobert/instafeed.js#542]
<script type="text/javascript">
<div id="instagram"></div>
feed = new Instafeed({
    get: 'user',
    userId: 6242153993,
    accessToken: 'my access token',
    target: 'photo-feed',
    sortBy: 'most-recent',
    limit: 5,
    template: '<li><a href="{{link}}" rel="external"><img src="{{image}}" /><span class="info"><small class="likes">{{likes}}</small><small class="date">{{model.created_time}}</small></span><span class="icon-instagram"></span><span class="black-stripe"></span></a></li>',
    clientId: 'cbbff2c49f4e4c9fb66ae2b1dc5281a6',
    resolution: 'low_resolution',
    filter: function(image) {
        var date = new Date(image.created_time*1000),
            hour = date.getHours(),
            min = date.getMinutes(),
            thetime = hour + 'h ' + (min ? min + 'min' : '');
        image.created_time = thetime;
        return true;
    },
    after: function() {
        // disable button if no more results to load
        if (!this.hasNext()) {
            loadButton.attr('disabled', 'disabled').addClass('hidden');
        }
    }
});
</script>

Above is the code that i used.but it is displaying me a blank page.can anyone please help me.

**Comment by HD9Host** [comment]
Have you tried this? Helped me:
https://gist.github.com/mojaray2k/b502d75dd7a9fa277876

**Comment by benjamin-hull** [comment]
Hi @linas01 - this is a fairly old issue, and there's not a lot to go on here. If you need help, please re-open the issue with an example which shows the problem (codepen.io is good). Thanks!
