### ISSUE TITLE
Not working with template option

### ISSUE THREAD

**Issue by liamxtensive** [stevenschobert/instafeed.js#543]
Hi,

Using this on a BigCommerce website and it all works fine until I try using the templates option.

It shows no Javascript errors but the code shows on the live site as '<img src alt>' in the source code.

I have the following:
template: '<a href="{{link}}" target="_blank" id="{{id}}"><img src="{{image}}" /></a>'

Any ideas?

**Comment by benjamin-hull** [comment]
Hi @liamxtensive - could you provide a bit more example of the code you're using? That image attachment is not displaying for me. Thanks.

**Comment by benjamin-hull** [comment]
Sorry - closed by mistake!
