### ISSUE TITLE
Hashtag filtering

### ISSUE THREAD

**Issue by switz1873** [stevenschobert/instafeed.js#544]
Is this method still supported presently? 

    var userFeed = new Instafeed({
        get: 'user',
        userId: '[USER_ID_HERE]',
        limit: 12,
        resolution: 'standard_resolution',
        accessToken: '[ACCESS_TOKEN_HERE]',
        sortBy: 'random',
        template: '<div class="col-sm-6 col-md-4 col-lg-3 instaimg"><a href="{{link}}" title="{{caption}}" target="_blank"><img src="{{image}}" alt="{{caption}}" class="img-fluid"/></a></div>',
		filter: function(image) {
            return image.tags.indexOf('[TAG_NAME_HERE]') >= 0;
        }
    });

I'm using this call and nothing is returned. If I remove the filter, everything works as expected. Any suggestions / obvious mistakes?

**Comment by dmcanaveral** [comment]
Not sure if you've found a solution or not yet, but that return statement worked for me today on my own project. Just to clarify, I didn't have [] around the 'hashtag'. Keep in mind, it looks within your set limit, so if you don't have any posts with your specified hashtag within that limit, nothing will appear. Hope that helps!

**Comment by switz1873** [comment]
I was able to get this running well on my project finally. Not sure what the issue was but after refactoring, things are working as expected. Thanks for the info.
