### ISSUE TITLE
Only tagged images of my account!

### ISSUE THREAD

**Issue by federicociani** [stevenschobert/instafeed.js#545]
I see only the images of my account! Can I do for load all images with a specif hashtag? ...all images on Instagram and not only of my account? Where is the problem in your opinion? On Instagram or on this plugin?

**Comment by portellapedro** [comment]
I have had the same problem, did you solve this?

**Comment by beejamin** [comment]
Instagram has been making changes to limit the scope of what can be done with the API. If you're using a token generator tool, then it will not have the types of access scopes required to get published images.  For example, [this popular tool](http://instagram.pixelunion.net/) and others like it give you a token scoped to the account you're logged into at the time (so you can see your own images, but not others).

So, unless you have a token with public+read access, no, you can't create a feed of public images with a certain hashtag. Instagram won't issue that token either - they explicitly say they don't allow the use of the API to embed the images elsewhere. 

Sorry to be the bearer of bad news!
