### ISSUE TITLE
After trying for half-a-day, STILL CANT get "Load More" to work...

### ISSUE THREAD

**Issue by msarit** [stevenschobert/instafeed.js#546]
When I comment out my "Load More" code, my feed renders just fine. But once I add the "Load More" code, my feed disappears :(

I've included my code as an image file (it would render correctly when I typed it in).
(Note: I am a JS novice)

https://nofile.io/f/R1rC7scpobF/instafeed.js+code+snippet.png

**Comment by stevenschobert** [comment]
I believe if you Instagram API Client is in sandbox mode, they don’t support loading more images anymore.
