### ISSUE TITLE
Problems with Hashtag Search

### ISSUE THREAD

**Issue by IvanSupo** [stevenschobert/instafeed.js#547]
This is the code that I currently use
<html>
    <script src="instafeed/instafeed.min.js"></script>
    <script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'emelec',
        clientId: '5668955601.4557df3.9968cae6c3a5448a885d392da2c5619b'
    });
    feed.run();
</script>
</html>

![code](https://user-images.githubusercontent.com/35199342/34653191-c082aaec-f3b6-11e7-8e4b-f51ea135ae3b.PNG)

![my access_token](https://user-images.githubusercontent.com/35199342/34653179-7ea78b42-f3b6-11e7-93e5-9ef26c2b9caf.PNG)

**Comment by rondog** [comment]
that appears to be an access token, not client

**Comment by altcointrading** [comment]
how can the hashtag search be done with clientID only? I keep getting console error `Uncaught Error: Error from Instagram: The access_token provided is invalid.` 


```
<script type="text/javascript">
      var feed = new Instafeed({
          get: 'tagged',
          tagName: 'thehashtag',
          clientId: 'fXXXa0e2ce4749f98ddd0afd59d66097'
      });
      feed.run();
    </script>
```

**Comment by eyeoashephard** [comment]
`var feed = new Instafeed({
      get: 'tagged',
      tagName: 'thehashtag',
      clientId: 'fXXXa0e2ce4749f98ddd0afd59d66097',
      accessToken: '<YOUR_ACCESS_TOKEN>
  });`

Now, to get the access token which will allow you to display hashtag content, generate it by visiting this website: http://instagramwordpress.rafsegat.com/docs/get-access-token

Worked for me. Did it about 15 minutes ago.

**Comment by rondog** [comment]
yeah, I would not trust doing that through some 3rd party tool

**Comment by benjamin-hull** [comment]
@altcointrading hashtag search (as in public posts tagged with `thehashtag`) can no longer be accessed with newly issued client IDs. Sorry to be the bearer of bad news!
