### ISSUE TITLE
Invalid URL signature

### ISSUE THREAD

**Issue by sarthakss** [stevenschobert/instafeed.js#549]
I am accessing Instagram and it was working fine till yesterday. But now I am only getting some images and not all. I am attaching a screenshot of my screen and success and failure network headers. Trying to solve this for half day but I am unable to understand the issue as it is saying Invalid URL signature. 
![website screen shot](https://user-images.githubusercontent.com/18018357/34848535-1f763ddc-f6ed-11e7-9be4-38a24a9e804d.png)
![failure network header](https://user-images.githubusercontent.com/18018357/34848565-41874ab0-f6ed-11e7-80a4-328055fa2e8d.png)
![sucess network header](https://user-images.githubusercontent.com/18018357/34848607-5ed482cc-f6ed-11e7-9c3f-7ac3eb3a2bea.png)

Please help.

**Comment by sarthakss** [comment]
Error I am getting is this: Failed to load resource: the server responded with a status of 403 ()

**Comment by rondog** [comment]
This just started happening to one of our web sites yesterday as well. Spent a couple hours researching this and nothing has come up. I even reauthenticated the client. If I refresh, they work, refresh again, all 403, refresh they work, refresh again 403. Not sure what is happening.

If you inspect the js call that goes to api.instagram.com and open up data[0].images.thumbnail.url and copy/paste that url in the browser the images loads just fine.

**Comment by rondog** [comment]
I think I am on to something. In our code someone on my team wrote

```
      $('#instafeed img').each(function(){
        //var scaledThumb = $(this).attr('src').replace('s150x150/', 's280x280/');
        //$(this).attr('src', scaledThumb)
      })
```

If I remove the scale it works. I noticed that they work now.

**Comment by sarthakss** [comment]
I have also used replace method in my code. But are you sure that is the reason for this unexpected behavior? 
I have used that function to get square images.

**Comment by rondog** [comment]
It has to be an issue on instagrams side. They maybe no longer accept those scaling values. We require square images for our design as well.

**Comment by sarthakss** [comment]
That is possible. 
@stevenschobert or anyone else have any updates on this problem?

**Comment by rondog** [comment]
My temp fix was use `resolution: 'low_resolution' via instafeedjs option, not scale the image via url and then set the "low_resolution" image as a backround image with background-size: cover. In my case, our images needed to 280x280

**Comment by sarthakss** [comment]
Thank you for sharing this. I was also using low_resolution before but I wanted images to be squared hence I used that function. In my case, I want images to be responsive and should take size according to screen width and that why I cannot give fix width and height to my image.

**Comment by saturday1** [comment]
Please post if anyone finds a more solid solution then making the images 150x150. I still have no clue what is going on.

**Comment by dec23rd1986** [comment]
Hi all, I can't seem to figure out how to get the client ID for my client or token. Per all the examples I have seen they are using their own Instagram ID. Can someone tell me how to obtain this? Do I have to have the client request it and then send it to me?

I'm trying to put an Instagram feed carousel on the homepage of their website.

**Comment by saturday1** [comment]
@rondog Thanks. 

I found out that `background-position: center` and `background-size: 100%` fitted me the best using this template:

```
<div class="insta-obj">
  <div class="img-container">
    <a href="{{link}}" class="img-link" data-type="{{model.type}}" style="background: url(\'{{image}}\') no-repeat;"></a>
  </div>
  <div class="meta-data">
    <span class="likes">{{likes}}</span>
    <span class="comments">{{comments}}</span>
    <p>{{caption}}</p>
  </div>
</div>
```

Result is visible here: https://arenagodemo.axiell.com/web/arena

**Comment by sarthakss** [comment]
@JamoDevNich Is there any way to remove those signatures from URL?

**Comment by JamoDevNich** [comment]
@sarthakss Running this regex on the URL `vp.*\/.{32}\/.{8}\/` will match the signature, so replacing that with nothing will get rid of the signature from the URL.

**Comment by sarthakss** [comment]
@JamoDevNich Okay, I will try to implement that. Thanks. Can you share code sample of your implementation for a reference.

**Comment by JamoDevNich** [comment]
@sarthakss This should work
```javascript
e.images.thumbnail.url.replace(/vp.*\/.{32}\/.{8}\//, '').replace('150x150', '600x600')
```

**Comment by sarthakss** [comment]
Thank you so much @JamoDevNich. Its working for me.

**Comment by just-omarj** [comment]
@JamoDevNich You're a hero man, thank you so much!!!!

**Comment by joeygallegos** [comment]
Thanks to @JamoDevNich I was able to fix this error too. I spent about an hour or two trying to fix this on my own.

**Comment by ssuhas855** [comment]
replacing url -- **vp.*\/.{32}\/.{8}\/** worked for me as well, @JamoDevNich thank you!

**Comment by jduncanator** [comment]
You should only need to remove the `/vp/` from the URL, everything else can stay and the URL will work fine.

**Comment by datio** [comment]
[549#issuecomment-358049610](https://github.com/stevenschobert/instafeed.js/issues/549#issuecomment-358049610) doesn't work anymore, it returns an 'Access Denied' error.
Anyone could grab original resolution profile images, even from private accounts, before IG fixed that by returning the above error.

**Comment by arnoholzer** [comment]
Same problem, and the url returned by the api start with https://instagram.fgva1-1.fna.fbcdn.net/

**Comment by sarthakss** [comment]
Yes Instagram changed their URL again and its breaking the code. Any solutions here?

**Comment by sarthakss** [comment]
Yes we will need a new regex again i think.  @JamoDevNich Please help us out (like last time), I am also working on this.

**Comment by prateek707** [comment]
Have you got any solution?

**Comment by sarthakss** [comment]
Not yet. Anyone has any updates on this issue? @JamoDevNich @stevenschobert

**Comment by JamoDevNich** [comment]
@sarthakss No solutions as of yet, I've been investigating the hashes though and how Instagram's website works. The first part of the url hash is MD5, the other part CRC-32.

Higher resolution pictures are loaded on the website when the user's device has a low screen resolution [such as this](https://scontent-lht6-1.cdninstagram.com/vp/af1931f26b048e3731976e5cbc09fa50/5B6F88DA/t51.2885-15/e35/29095348_163936157601642_2081626930175541248_n.jpg) and lower resolution images are returned when the user's device has a high screen resolution. However, the higher resolution images are not the same quality as the ones we were previously able to retrieve from the API with the regex.

I'm trying to find the script being used to check device screen resolution in an attempt to reverse engineer it, and hopefully find a way to workaround the hashed URLs or generate them ourselves.

**Comment by jduncanator** [comment]
You'll never be able to generate the hashes yourself (assuming Instagram have actually implemented this correctly). They'll almost certainly be signatures, rather than hashes, and you'll need to have access to Instagram's private key to generate the signatures yourself, something that we don't have access to. For the time being, assuming they are now signing the image URLs, there isn't really any other option to get alternate versions of the images provided by the API.

**Comment by sjsagar001** [comment]
So I was scrolling down the reddit and I found this http://wizblogger.com/instadp/
It actually worked.I don't know how they did it, I am hoping you guys can figure out?

**Comment by hamza-anis** [comment]
First you have to copy/paste this URL `https://scontent-ams3-1.cdninstagram.com/vp/9ef178c2be6e25735e9be90b3698822b/5B3B8F46/t51.2885-19/`
then for example add the photo name L ex: `19228783_1421845407904949_3402248722799656960_a.jpg`
after the URL.

**Comment by iHelp101** [comment]
I did find a solution for profile icons. However, unofficial API's are being shutdown. So I have no idea how long this will stay working. If you get the users ID (You can from the first link below) you can use the mobile API (Without token) to get the user profile icon in all it's sizes. Like mentioned by others, the actual signature generation is unlikely to be cracked. Instagram has been working on this for many months (Originally started with disappearing/direct messages). 

https://www.instagram.com/natgeo/?__a=1
https://i.instagram.com/api/v1/users/787132/info/

**Comment by benjamin-hull** [comment]
@sjsagar001 - the tool you linked works because they don't attempt to rewrite the size of the image, they just use the URL as provided by the API. This means the signature matches the options provided on the URL, so everything works.

If you attempt to request a non-standard size for that URL, you get the `403` response as with the other images.

**Comment by sjsagar001** [comment]
@benjamin-hull Now I understood. Thank You

**Comment by datio** [comment]
The first part of @iHelp101 's solution has also stopped working. We cannot get a user's id from their username anymore.

The second v1 API link still returns the expected full resolution profile picture.

**Comment by benjamin-hull** [comment]
@datio is right - the `?__a=1` JSON endpoint is no longer provided.

**Comment by datio** [comment]
As a closing note, it is currently still possible to get a user's profile id through the source HTML of their page.

![screenshot from 2018-06-18 16-56-22](https://user-images.githubusercontent.com/15472/41540392-dba05b58-7318-11e8-9690-93c8215c9edd.png)

**Comment by siddhartharora02** [comment]
One possible solution that is working right now is to use official Instagram API suggested way.

So if the link of the video is - [https://www.instagram.com/p/Bv3fbKGnmNK/](https://www.instagram.com/p/Bv3fbKGnmNK/) 

You can get **Thumbnail** here  - [https://www.instagram.com/p/Bv3fbKGnmNK/**media?size=m**](https://www.instagram.com/p/Bv3fbKGnmNK/media?size=m)

Change **`size=l`** for larger images

Let me know if it works!!

**Comment by yezarela** [comment]
@siddhartharora02 It only works for public instagram account, but not for private account.
