### ISSUE TITLE
Instafeed doesn't work

### ISSUE THREAD

**Issue by ac-barros** [stevenschobert/instafeed.js#555]
Hi everyone!
The instafeed on my blogger website is not working (doesn't show images) and it's probably because the instagram API changed. Can you please tell me how to fix it?

Thanks

**Comment by JamoDevNich** [comment]
Could you link the page or provide sample implementation code? (ommitting the api key of course)

**Comment by ac-barros** [comment]
Hi JamoDevNich,

Here's the page: [Dimples Blog](www.dimplesblog.com/)

**Comment by JamoDevNich** [comment]
The images are returning 403 when inspected saying the signature is invalid, I think this is a result of the replace code you have to get higher res images
```javascript
var highResThumb = post.images.thumbnail.url.replace('s150x150/', 's640x640/');
```
To fix this you need to remove the url signature from the url, I posted a fix for this in another thread https://github.com/stevenschobert/instafeed.js/issues/549#issuecomment-358049610 I don't know how long this workaround will work before instagram eventually enforces url signing though.

**Comment by ac-barros** [comment]
Thanks! It worked but the images are showing up with a gap between them and in poor quality! Is it fixable?

**Comment by JamoDevNich** [comment]
Change
```javascript
var highResThumb = post.images.thumbnail.url.replace(/vp.*\/.{32}\/.{8}\//,'s640x640/');
```
to
```javascript
var highResThumb = post.images.thumbnail.url.replace(/vp.*\/.{32}\/.{8}\//,'').replace('150x150', '600x600')
```

**Comment by ac-barros** [comment]
Thank you so much! It is working just fine!

**Comment by JamoDevNich** [comment]
@ac-barros No problem 😁
