### ISSUE TITLE
Remove # from {{caption}}

### ISSUE THREAD

**Issue by DocColor** [stevenschobert/instafeed.js#556]
Hi,

Is there an easy way to remove all hashtag from the {{caption}} ?

eg: {{caption}} = Blabla #nofilter #food #ilovemyjob

I'd like to have something like : {{caption-clean}} = Blabla

Thanks

**Comment by benjamin-hull** [comment]
Hi @DocColor - I know this is an old issue, but for the sake of completeness, you can use the 'success' callback option to manipulate the response data before it goes into your template, for example:

```
success: function(response) {
          response.data.forEach(function(i){
            var cleanCaption = i.caption.text.split(/\s+/).map(function(s){console.log(s[0], s[0] == "#");return s[0] == "#" ? "" : s}).join(" ")
            i.caption.text = cleanCaption
          });
        }
```

This is a very quick 'throw away hashtags' function, and it won't catch everything, but it should give you the idea.

**Comment by DocColor** [comment]
Hi Ben,
Thanks for the trick, I'll give it a try asap

**Comment by gusbemacbe** [comment]
@benjamin-hull 

Your code works no longer. Analyse my pen:

https://codepen.io/gusbemacbe/pen/WNxOgPN

**Comment by gusbemacbe** [comment]
@benjamin-hull, ah, no need to help, it works in reference to https://github.com/stevenschobert/instafeed.js/issues/670.
