### ISSUE TITLE
Demo access_token invalid

### ISSUE THREAD

**Issue by lacymorrow** [stevenschobert/instafeed.js#558]
It seems your token for the `gh-pages` demo has expired

**Comment by venits** [comment]
If you need to work with Instagram API and have problems with access_token you can check this library. Right now it is better to build own image downloader ;)
https://github.com/venits/instagram-web-oauth

**Comment by lacymorrow** [comment]
yeah, not a problem for me, just a heads-up that the demo is broken. Cheers!

🍻
