### ISSUE TITLE
Cut off caption without breaking up the words

### ISSUE THREAD

**Issue by wilcarter15** [stevenschobert/instafeed.js#560]
I found the solution from back in 2015 [https://stackoverflow.com/questions/29041115/text-length-limit-not-working-in-my-instafeed-template?answertab=active#tab-top](url).  But I can only get the first part to work.  I even added an ellipse '...' to the end of the caption.  Since the first solution breaks up the last word I tried to use the second solution.  This is where the problem happens.  When I try to do the second solution the feed does not show.

I am working with Bootstrap 4 and using jekyll.  Here is the working code with the caption being broken up (the function written for 'success' makes all images square) it pulls the caption and stops it at 80 just like it should ...

`$(document).ready(function() {
   

    var userFeed = new Instafeed({
        get: 'user',
        userId: '6864543261',
        limit: 4,
        resolution: 'square',
        success: function(response){
            response.data.forEach(function(e){
              // Now insert the 'square' size into each image's data:
              e.images.square = {
                url: e.images.thumbnail.url.replace(/vp.*\/.{32}\/.{8}\//, '').replace('150x150', '600x600'),
                width: 600,
                height: 600
              };
            });
          },
        accessToken: '6864543261.1677ed0.047f5bd50b3c4c96b7fed8fc491a9537',
        sortBy: 'most-recent',
            filter: function(image) {
              var MAX_LENGTH = 80;
               

              // here we create a property called "short_caption"
              // on the image object, using the original caption
              if (image.caption && image.caption.text) {
                image.short_caption = image.caption.text.slice(0, MAX_LENGTH)+"...";
              } else {
                image.short_caption = "";
              }

              // ensure the filter doesn't reject any images
              return true;
            },
        template: 
        '<div class="col-6 col-xl-3 mt-2"><div data-aos="fade-up"><a href="{{link}}" target="_blank"><div class="insta-widget"><img class="ig-hover" src="{{image}}" alt="{{user.full_name}}"/><div class="likes"><div class="box"><div class="row text-center"><div class="col-12"><img class="profile" src="{{model.user.profile_picture}}"/></div><div class="col-6"><p><span class="fas fa-heart mr-1"></span>{{likes}}</p></div><div class="col-6"><p><span class="fas fa-comment mr-1"></span>{{comments}}</p></div><div class="col-12"><p class="caption">{{model.short_caption}}</p></div></div></div></div></div></a></div></div>',
    });

    userFeed.run();

});

`

Now, this is my attempt at using the second solution so the last word doesn't get broken up...

`  $(document).ready(function() {
   

    var userFeed = new Instafeed({
        get: 'user',
        userId: '6864543261',
        limit: 4,
        resolution: 'square',
        success: function(response){
            response.data.forEach(function(e){
              // Now insert the 'square' size into each image's data:
              e.images.square = {
                url: e.images.thumbnail.url.replace(/vp.*\/.{32}\/.{8}\//, '').replace('150x150', '600x600'),
                width: 600,
                height: 600
              };
            });
          },
        accessToken: '6864543261.1677ed0.047f5bd50b3c4c96b7fed8fc491a9537',
        sortBy: 'most-recent',
           filter: function(image) {
              var MAX_LENGTH = 100;
              var closestIndex = MAX_LENGTH;

              if (image.caption && image.caption.text) {
                while(true) {
                  if (text.charAt(closestIndex) === ' ') {
                    break;
                  }
                  closestIndex -= 1;
                }
                image.short_caption = image.caption.text.slice(0, MAX_LENGTH);
              } else {
                image.short_caption = "";
              }

              return true;
            },
        template: 
        '<div class="col-6 col-xl-3 mt-2"><div data-aos="fade-up"><a href="{{link}}" target="_blank"><div class="insta-widget"><img class="ig-hover" src="{{image}}" alt="{{user.full_name}}"/><div class="likes"><div class="box"><div class="row text-center"><div class="col-12"><img class="profile" src="{{model.user.profile_picture}}"/></div><div class="col-6"><p><span class="fas fa-heart mr-1"></span>{{likes}}</p></div><div class="col-6"><p><span class="fas fa-comment mr-1"></span>{{comments}}</p></div><div class="col-12"><p class="caption">{{model.short_caption}}</p></div></div></div></div></div></a></div></div>',
    });

    userFeed.run();

});

`

I am not great with javascript although I can follow along.  I am hoping this is just a simple typo or syntax issue I am missing.   Thanks for your help!

**Comment by radekvechet** [comment]
I would love this feature for captions. It's especially handy for smaller "one column" feeds.

**Comment by benjamin-hull** [comment]
I'm not sure about that second approach - it looks quite clever, and is possibly efficient for very long captions, but I wonder if a 'dumb but effective approach' might be easier to understand: https://codepen.io/benjamin-hull/pen/rKYgoM
 
(I've remove the 'squarifying' function from `success` because that no longer works due to instagram's URL signing)

A `success` function like this should do the trick:

```javascript
    var maxLength = 100;
        
response.data.forEach(function(e){
  if (!e.caption && e.caption.text) {
    return false;                                                 //Skip if there's no caption
  }
  
  e.shortCaption = '';                                            //Initialize to an empty string
  
  var textParts = e.caption.text.split(' ');                      //Split the caption into words
    
  while(true) {
    var nextWord = textParts.shift();                             //Pull the next word from the front

    if (!nextWord) {
      break;                                                      //If we hit the end of the caption before we hit the limit, bail out
    }
    
    if (e.shortCaption.length + nextWord.length < maxLength - 1){ //Check if the next word will fit into the limit (minus 1 includes the space)
      e.shortCaption += ' ' + nextWord;                           //If so, append it with a space
    } else {
      e.shortCaption = e.shortCaption.trim() + '…';               //If not, finish with an ellipsis and bail out
      break;
    }
  }

  // the short caption is available in the template with {{model.shortCaption}}
}); 
```

Caveat - this only splits on plain ordinary space ` ` - other whitespace or punctuation might mess it up. See how you go!
