### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by VerDan777** [stevenschobert/instafeed.js#561]
Hi! I have a problem with render my instagramm photos in DOM. When  i try set this config, i can't wrapp my images tag in  a - tag.I don't understand why. Please, help. Thanks!

My config:
const InstaFeed= require("instafeed");

    let feed = new InstaFeed({
    get: "user",
    userId: "6312841675",
    clientID: "c4dc1832e4ea4f4a9f2fe01b7a88dcbe",
    accessToken: "6312841675.1677ed0.4fe2a42c6bf7405bbc04c953f7ecd7dd",
    resolution: "standard_resolution",
    limit: 10,
    template: '<a href="{{link}}"><img src="{{image}}" /></a>'
});
feed.run();

**Comment by benjamin-hull** [comment]
Hi @VerDan777 - I know this is an old issue, do you still need help with this?
