### ISSUE TITLE
Links in templates not working

### ISSUE THREAD

**Issue by Mediage** [stevenschobert/instafeed.js#562]
Hi,

I think there's something wrong with the latest version of Instafeed (1.4.1). When using a template, a template string gets created with a prepending slash (/) in the URL's. I think this somehow has to do something with the order in which elements get created and browsers adding a slash to an empty href or src attribute. But I'm really not sure of that, so it might be something else.

Now to the actual problem:
Let's assume we use the following template code:

`template: '<a target="_blank" href="{{link}}" data="{{link}}" ><img src="{{image}}" /></a>'`

The generated link becomes something like:
`template: '<a target="_blank" href="/https://instagram.com/xyz/" data="https://instagram.com/xyz/" ><img src="//instagram.com/xyz/" /></a>'`

Please notice the prepending slash on the href attribute. This doesn't happen on the data-attribute or any other 'fake' attribute.

This happens throughout the template generation. When transforming the template in Instafeedjs, the output becomes something like this:
`template: '<a target="_blank" href="/{{link}}" data="{{link}}" ><img src="/{{image}}" /></a>'`

So somewhere along the lines a slash gets added to the href and src attributes, before they are replaced with the actual URL.

Now i've created this small work-around for now, please notice the output.replace. This replaces all occurrences of /{{ and replaces them with {{. It might not be fool-proof for all situations, but it works in my case. You can of course always create your own replacement.

```
Instafeed.prototype._makeTemplate = function(template, data) {
      var output, pattern, ref, varName, varValue;
      pattern = /(?:\{{2})([\w\[\]\.]+)(?:\}{2})/;
      output = template;

      /* slash-fix on next line */
      output = output.replace(/\/{{/g, "{{");

      while (pattern.test(output)) {
        varName = output.match(pattern)[1];
        varValue = (ref = this._getObjectProperty(data, varName)) != null ? ref : '';
        output = output.replace(pattern, function() {
          return "" + varValue;
        });
      }
      return output;
    };
```

I hope this can be properly fixed in the next release of Instafeed. For now this is a work-around that does the trick.

**Comment by christopherbisman** [comment]
so, 
you could tell me where to insert the code that you share to correct the error


mi code actully is:

<script type="text/javascript">var nextButton = document.getElementById('next-button');

    var feed = new Instafeed({
        get: 'user',
        accessToken: '',
        userId: '',
        clientId: '',
        limit: '8',
        resolution: 'low_resolution',

        template: '<a target="_Blank" href="{{link}}"><img src="{{image}}" /></a>',
        // every time we load more, run this function
        after: function() {
            // disable button if no more results to load
            if (!this.hasNext()) {
                nextButton.setAttribute('disabled', 'disabled');
            }               
        },
    });

    // bind the load more button
    nextButton.addEventListener('click', function(event) {
        event.preventDefault();
        feed.next();
    });


    // run our feed!
    feed.run();</script>

thank you. :)

**Comment by MyBookings** [comment]
The code is inserted near 
`Instafeed.prototype._makeTemplate = function(template, data) {`
on line 308
