### ISSUE TITLE
Getting net::ERR_ABORTED from instagram api

### ISSUE THREAD

**Issue by bmoe872** [stevenschobert/instafeed.js#563]
My code:

HTML
```
<div id="instafeed"></div>
```

Javascript
```
<script type="text/javascript">
    var feed = new Instafeed({
		get: 'user',
		userId: '<myuserid>',
		accessToken: '<myaccesstoken>',
		limit: 4,
    });
    feed.run();
</script>
```

That error doesn't really tell me whats going on. I've went through all the steps to get an access token and the client id. I was reading elsewhere from other issues to not pass the clientid if you have the acccessToken which is why I've removed it from the code.

Thanks for any help!

**Comment by bmoe872** [comment]
I fixed it! Just in case anyone else comes across a similar error.

I had my userId set to my actual IG Username, when in actuality it needs to be set to 'self'.

Cheers!

**Comment by stevenschobert** [comment]
Glad you got it working! 👍
