### ISSUE TITLE
Move Instagram feed further up my Shopify homepage

### ISSUE THREAD

**Issue by Cazmic** [stevenschobert/instafeed.js#565]
Hi there! Just wondering how I get the Instafeed to appear further up the page instead of at the bottom above the footer, which is where it automatically got added when activating Instafeed.

**Comment by ConduciveMammal** [comment]
@Cazmic This isn't an Instafeed issue, you should contact the developer of your theme.

**Comment by Cazmic** [comment]
No problem - already done soon after I emailed you.

Thanks for your reply :)

Caz Hoad
CAZMIC DESIGN
+61 412 745 280
http://www.cazmicdesign.com.au

On 23 Mar 2018, at 9:43 am, Liam Merlyn <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cazmic<https://github.com/cazmic> This isn't an Instafeed issue, you should contact the developer of your theme.

-
