### ISSUE TITLE
How to alter size of instafeed thumbnails

### ISSUE THREAD

**Issue by leannehel** [stevenschobert/instafeed.js#566]
Sorry for what is probably a very basic question (I'm extremely inexperienced and don't know what 
i'm doing). I have an Instafeed widget on my blog, and the thumbnails used to be square until they suddenly changed to all different sizes, which match the photos on my instagram account. The only way I can get them square again is to change the resolution to 'thumbnail', but they're too small. The first photo is how they used to look (and how I want it), and the second photo is how they are now. 
This is the CSS code currently:

![e70ec090-6175-46c9-be93-9304952cef43](https://user-images.githubusercontent.com/37679531/37808657-707c9e5a-2e43-11e8-91ae-51b2806f18e7.jpeg)

![446c0998-c1b6-4dc8-bf34-4466a4bc3604](https://user-images.githubusercontent.com/37679531/37808383-0f891b2e-2e42-11e8-9bc4-235afbff0bbc.jpeg)

![ab4adb42-e974-4a50-9a73-a562efe737e5](https://user-images.githubusercontent.com/37679531/37808397-1a385576-2e42-11e8-9bf5-0751e0b725f1.jpeg)

What do I need to add/change? Any help is greatly appreciated!

**Comment by benjamin-hull** [comment]
Hi @leannehel - there's been a bit of discussion of this issue: It's due to Instagram changing things at their end. A simple fix is in the works, though you can check here: https://github.com/stevenschobert/instafeed.js/issues/527#issuecomment-376763768 for some CSS solutions you can use in the meantime.

**Comment by benjamin-hull** [comment]
I'm closing this one for now, feel free to reopen if you need more help!
