### ISSUE TITLE
It started

### ISSUE THREAD

**Issue by chasevorn** [stevenschobert/instafeed.js#571]
![2018-04-05_15-19-36](https://user-images.githubusercontent.com/15035595/38365440-fca738ee-38e4-11e8-9fb4-cce58430eaed.png)

This wasn't supposed to happen until Dec 11, 2018 according to their website: https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

Are there any other solutions for this?

**Comment by benjamin-hull** [comment]
There have been some "effective immediately" deprecations made today. See https://github.com/stevenschobert/instafeed.js/issues/345

Which endpoint were you requesting from?

**Comment by georanma** [comment]
@chasevorn It depends on what endpoints you need to use. This should be a pretty easy library overhaul for the most part. I was able to update my agency's usage of the library at the user endpoint with small changes. 

line 259 of instafeed.js
`          if (!this.options.userId) {
            throw new Error("No user specified. Use the 'userId' option.");
          }
          endpoint = "users/self/media/recent";
          break;`

This should fix any queries to the user endpoint to get the most recent posts. This was only tested for our use case, and not for all library options.

**Comment by chasevorn** [comment]
/v1/users/USERID/media/recent

I have this js set up
`          var feed = new Instafeed({
              get: 'user',
              userId: USERID,
              accessToken: 'TOKEN',
              limit: '8',
              template: '<a href="{{link}}" target="_new" class="instapics"><img src="{{image}}" /></a>'
          });
          feed.run();`

**Comment by georanma** [comment]
@chasevorn How are you loading up the library?

**Comment by ckhatton** [comment]
@georanma THANK YOU!! ![bitmoji](https://render.bitstrips.com/v2/cpanel/5ac82034-71ae-4bef-a427-d437206edd89-a3bfc5c5-2c1c-463c-8904-3acfc6845447-v1.png?transparent=1&palette=1&width=246)

**Comment by tatof** [comment]
@georanma your code gets my own instagram feed not the one from the customer that i'm building the feed for :( 

`var feed = new Instafeed({
    get: 'user',
    userId: '5888308871',  
    clientId: '***************************',
    accessToken: '************************************',
    resolution: 'standard_resolution',
    template: '<a href="{{link}}" target="_blank" style="background-image: url({{image}})"></a>',
    limit: '6'
});`

**Comment by georanma** [comment]
@tatof you will need to update to using an access token generated from your client's instagram account. It is no longer possible to pull another user's instagram feed via their userId. 

https://www.instagram.com/developer/endpoints/users/

**Comment by chasevorn** [comment]
This got solved for me only by creating an app and generating a new access token from my client account and not from mine.

**Comment by tatof** [comment]
I see thanks! :)

**Comment by georanma** [comment]
@tatof np. 

@chasevorn yes, see my previous response.

**Comment by rfearing** [comment]
@chasevorn Thanks for your fix. Since @stevenschobert doesn't seem to be keeping this active at the moment I created a fork [here](https://github.com/rfearing/instafeed.js) (at least while InstaFeed is inactive). It includes your fix which solved the issue I was having of   `Uncaught Error: Error from Instagram: This endpoint has been retired`

**Comment by stevenschobert** [comment]
@rfearing Hey there! Thanks for the contribution!

For what it's worth -- I am still here, I've just been extremely busy with other projects, so that's why many of the PRs haven't been merged or deployed yet. I'm happy to see other people sharing knowledge in the issues though, which is why I've left many issues open.

Given Instagram's decision to sunset their API, I'm not sure yet what the future of this library will be, but I'll participate as much as I can!

**Comment by rfearing** [comment]
@stevenschobert That totally makes sense! I hope my comment didn't come off as rude at ll, as I definitely appreciate the plugin and your work!

Thanks again!
