### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by sultanwork77** [stevenschobert/instafeed.js#572]
I have added instafeed js and given div tag in html.
The script I have used is
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: 'userid',
        clientId: 'clientid'
    });
    userFeed.run();
</script>

But I am getting as 404 error in console and is stating as
Failed to load resource: the server responded with a status of 404
When i click that line then its navigating to new tab of instagram and getting as following

Sorry, this page isn't available.
The link you followed may be broken, or the page may have been removed. Go back to Instagram.

https://api.instagram.com/v1/users/sultanahmed313/media/recent?client_id=dfdd3513a8fa4696963275d163b09936&callback=instafeedCache8bbb6f493982a461.parse

**Comment by benjamin-hull** [comment]
Hi @sultanwork77 - not a good idea to post your client ID publicly.

That said, the user you're retrieving for https://www.instagram.com/sultanahmed313/ has no posts, so there'll be nothing to show.
