### ISSUE TITLE
403 Access Denied

### ISSUE THREAD

**Issue by eaglejohn** [stevenschobert/instafeed.js#573]
I'm getting a 403 error for every image and no images are displayed anymore. Trying to access the image directly also results in a 403 (Access Denied) error.

Example: https://scontent.cdninstagram.com/t51.2885-15/s600x600/e35/29718193_598279400506031_2790445539315941376_n.jpg

**Comment by benjamin-hull** [comment]
Hi @eaglejohn - sounds like it's likely related to Instagram API deprecations, and/or sandbox mode. 

Could you post the config you're using for instafeed.js, and the username/id you're trying to fetch images from?

**Comment by ryanschmidt** [comment]
I think I'm having the same issue so I'll post my config so that it might help everyone. Do you think this just an issue a small group of people are having?

```
<script>
 var feed = new Instafeed({
     get: 'user',
     userId: '1551171447',
     accessToken: '***',
     template: '<a class="insta-cube photo-{{orientation}} item" target="_blank" href="{{link}}" style="background:url({{image}}) no-repeat center center;padding-bottom:33%;"></a>',
     limit: 6,
     resolution: 'thumbnail',
     after: function(){
      $('.insta-cube').each(function(){
        var bg = $(this).css('background-image');
        bg = bg.replace('url(','').replace(')','').replace(/\"/gi, "").replace(/vp.*\/.{32}\/.{8}\//, '').replace('s150x150', 's306x306');
        $(this).css('background-image', 'url(' + bg + ')');
      });
      $('.instagram-images').css('opacity','1');
     }
 });
 feed.run();
</script>
```

**Comment by benjamin-hull** [comment]
@ryanschmidt - were you logged in as the user with ID `1551171447` when you generated your accessToken?

**Comment by ryanschmidt** [comment]
@benjamin-hull I wasn't sure so I just grabbed a new access token and update the client id. I believe it was another developer on the team that had set that up originally. So now it should be good but I'm getting 403 on all images. This code had worked previously but stopped the same day @eaglejohn posted this.

**Comment by benjamin-hull** [comment]
It's possible this is only affecting some users, but I know of several instances of instafeed.js which are working with a similar config. The new/upcoming API restrictions are discussed in more detail in #345 - perhaps have a look there.

Other possible sources of errors relate to the sandbox-mode restrictions detailed here: https://www.instagram.com/developer/sandbox/

Just to be sure, what's the username of the account you're trying to load posts from?

**Comment by ryanschmidt** [comment]
@benjamin-hull rosewater_market is the username.

**Comment by benjamin-hull** [comment]
Hmm - as a test, what do you get if you hit the API endpoint directly?

https://api.instagram.com/v1/users/1551171447/media/recent?access_token=[your_access_token]

**Comment by ryanschmidt** [comment]
@benjamin-hull that works just fine and I figured out my issue thanks to you pointing me in the right direction.

Looking through the response, I see the urls look like this:

`https://scontent.cdninstagram.com/vp/9382a041cd5e555b5c7d8deac6fe49f6/5B82BA16/t51.2885-15/s150x150/e35/c0.35.1080.1080/31176376_235175523725977_2791178058873176064_n.jpg`

when the 403 errors I receive on the site show a url like this:

`https://scontent.cdninstagram.com/t51.2885-15/s306x306/e35/c0.35.1080.1080/31176376_235175523725977_2791178058873176064_n.jpg`

I was still using [this method](https://github.com/stevenschobert/instafeed.js/issues/555) to get higher resolution images. I assume the script was updated recently to support this differently? Regardless, I updated the code I posted above to the following and it's all working as intended. Thanks!

```
<script>
  var feed = new Instafeed({
    get: 'user',
    userId: '1551171447',
    accessToken: '***',
    template: '<a class="insta-cube photo-{{orientation}} item" target="_blank" href="{{link}}" style="background:url({{image}}) no-repeat center center;padding-bottom:33%;"></a>',
    limit: 6,
    resolution: 'standard_resolution',
    after: function(){
      $('.insta-cube').each(function(){
        var bg = $(this).css('background-image').replace('url(','').replace(')','');
        $(this).css('background-image', 'url(' + bg + ')');
      });
      $('.instagram-images').css('opacity','1');
    }
});
feed.run();
</script>
```

**Comment by benjamin-hull** [comment]
Ah - yep, instagram started enforcing the signed URLs a little while back, so that workaround stopped working. Glad you got it working.

PS. Did you guys do rosewatermv.com? It's lovely!

**Comment by ryanschmidt** [comment]
We built the site a couple years ago along with our friends at bonfirered.com. Thanks!
