### ISSUE TITLE
Screen or replace some symbols

### ISSUE THREAD

**Issue by DaemonHK** [stevenschobert/instafeed.js#574]
Sometimes in posts we can see double-quotes or one-quotes or line-wrapping and instafeed give not processed content to us. My offer add something as (after 294 line):

`if(typeof ref === "string"){`
`    varValue = varValue.replace(/"/g,"'").replace(/\r\n|\r|\n/g,"<br />");`
`}`

but after this we must return double-quote like:

`somestring.replace(/'/g,"\"")`

P.S. Sorry for my English

**Comment by benjamin-hull** [comment]
Hi @DaemonHK - are you able to show me any examples of posts that cause the issue? Thanks!

**Comment by DaemonHK** [comment]
Hi @benjamin-hull - I mean some strings in posts like - Today we tell about text with "double quotes" or 'simple quotes' #double #bug #somethingelse
