### ISSUE TITLE
I want to get the image scrolling but just in client side

### ISSUE THREAD

**Issue by chetabahana** [stevenschobert/instafeed.js#580]
One of the examples you have put [VinThomas.com](VinThomas.com ) by [Vin Thomas](https://twitter.com/vinthomas). I want to get the image scrolling like that. From the page source I found it using json from a [_php_](http://php.net) page. How to do then just in client side without any code on server side?

[![instagram_spinner](https://user-images.githubusercontent.com/36441664/39819610-0ad588ea-53ce-11e8-9bd7-6600277f4ae2.jpg)](https://vinthomas.com/)

**Comment by chetabahana** [comment]
Hi thanks. 
I forked that [simplyscroll](http://logicbox.net/jquery/simplyscroll/). I still have a question. 
Would you mind to see [_my feed_](https://chetabahana.github.io/#templatemo-footer) as pointed in the picture. 
I want to make the images in one row instead of 2 rows. How to do it?

[![chetabahana-feed](https://user-images.githubusercontent.com/36441664/39826897-6f0d987c-53e0-11e8-99e2-f43e464c4f4d.png)](https://chetabahana.github.io/#templatemo-footer)

**Comment by chetabahana** [comment]
I made my [_own fiddle_ ](http://jsfiddle.net/chetabahana/qbx9b5pm/) to check the ouput from[ _the source_](https://www.instagram.com/chetabahana/). Whatever a change is made on styling it always split in 2 rows. Seems it comes by default setting of 6 (six) collums in maximum per rows from the [instafeed.js](https://github.com/stevenschobert/instafeed.js) script. That's why I am asking here in this repo (not on stackoverflow).

[![fiddle](https://user-images.githubusercontent.com/36441664/39849636-85cfdec4-5437-11e8-86bd-18b50cb75030.png)](http://jsfiddle.net/chetabahana/qbx9b5pm/)

**Comment by benjamin-hull** [comment]
instafeed.js doesn't do any styling at all - that's all up to whatever CSS you provide. I can see from your fiddle that your CSS includes `width: 16.666%`, which is what's breaking the row after 6 columns.
