### ISSUE TITLE
Is get tagname supported in react-instafeed?

### ISSUE THREAD

**Issue by mattlr20** [stevenschobert/instafeed.js#582]
I am having troubling getting by tagname in react. Is it supported yet?

```javascript
<div id={instafeedTarget} className="container gal-container">
      <Instafeed
        get='tagged'
        tagName='weddings'        
        limit='12'
        ref='instafeed'
        target={instafeedTarget}
        resolution='standard_resolution'
        sortBy='most-recent'
        template=''
        userId='myuserid'
        clientId='myclientid'
        accessToken='mytoken'
      />
      </div>

**Comment by benjamin-hull** [comment]
Sadly, the answer is "it's not supported _anymore_". Instagram API changes have removed access to these endpoints for new access tokens. See #345 for more details and discussion on the topic.

You're probably seeing an error like `This client has not been approved to access this resource.` ?
