### ISSUE TITLE
Instagram Images are not loading

### ISSUE THREAD

**Issue by jainnidhi** [stevenschobert/instafeed.js#583]
I am getting this error:

**Uncaught Error: No images were returned from Instagram**

Can you please help me out?

Thanks in advance!!

**Comment by benjamin-hull** [comment]
Could you post your code, please @jainnidhi ?

**Comment by antigenius** [comment]
I suspect this is the result of [recent API changes](https://www.instagram.com/developer/changelog/).

**Comment by jainnidhi** [comment]
@antigenius yes it was because of recent API changes. Previously my account was private and when I set it to public this issue was solved.

**Comment by jainnidhi** [comment]
Solved!
