### ISSUE TITLE
Not all images are showing

### ISSUE THREAD

**Issue by agrevia** [stevenschobert/instafeed.js#588]
On my clients website, **not all images** are showing.
For example: http://debobelettering.be/galerij/index.html?tagname=voertuig
In the url there is a query, tagname, if you chose tagname=car, all the cars will show with the tag car on instagram.
There are more than **10 images** with the tag "car" but only 5 showing.
![afbeelding](https://user-images.githubusercontent.com/40198416/41279819-c0bc51b0-6e2d-11e8-81f6-38a5ea92866c.png)

**Comment by agrevia** [comment]
Problem solved, limit was not set

**Comment by benjamin-hull** [comment]
Glad you got it working!

Do note that Instagram's API sandbox limits you to the 20 most recent images per user, and tagged images will come from that set. So, if you have 20 images tagged `car` in your whole feed, but only 5 in your latest 20 posts, you'll only ever get those 5 images back, no matter what limit you set.
