### ISSUE TITLE
"No images were returned" intermittently

### ISSUE THREAD

**Issue by MitchEff** [stevenschobert/instafeed.js#593]
Okay this one's pretty difficult to diagnose, cause it only appears occasionally (and seemingly on only some devices). 

Every now and then, across several of our clients' sites (WordPress and Shopify), Instafeed won't load any images, saying "no images were returned" in the console. Access tokens are all valid, and the images return eventually. 

I'm not sure how to give much more detail on this one as it seems entirely random. Has anyone encountered this by any chance?

**Comment by hongzhou85** [comment]
Still seeing the same problem today

**Comment by hongzhou85** [comment]
I believe this may be an issue of token expiring?

**Comment by MitchEff** [comment]
I thought as much too, but it doesn't seem like it. I can refresh the token and it'll do the same the next day. Only on _some_ devices and in _some_ contexts. 

Weird.

**Comment by stevenschobert** [comment]
It could be that you’re hitting the API rate limit, which is pretty low under the new API rules.

So you’re token isn’t _invalid_, but could be returning no images until the next hour or day, when your limit resets.

**Comment by stevenschobert** [comment]
Instafeed.js doesn't have caching built-in, but you could modify the library to use the browser's [local storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage) to cache data.

However browser-side caching only prevents extra API calls for recent repeat visitors. So a large number of new visitors could still push your client over the API limit.
