### ISSUE TITLE
scope=public_content doesn't work

### ISSUE THREAD

**Issue by fabitohenrique** [stevenschobert/instafeed.js#594]
I have one travel blog, and made one page to show all pictures that use my tag.

http://www.vaimesmo.com/p/flymesmo.html

But, still show just pictures of my instagram account.
I just get access token with scope=public_content, but keep to show just my account pictures.

This is my code.
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'flymesmo',
        resolution: 'low_resolution',
        accessToken: 'xxxxxxxx',
    });
    feed.run();
</script>

**Comment by benjamin-hull** [comment]
Hi @fabitohenrique - at a guess, this is a result of [instagram's API deprecations](https://www.instagram.com/developer/changelog/). If you can make a simple example page (on codepen or similar) showing the problem, I can check for sure.
