### ISSUE TITLE
Carousel_media

### ISSUE THREAD

**Issue by btoran** [stevenschobert/instafeed.js#595]
Hi all,

I have a post in Instagram with multiple photos.

I need show all photos oh that post.

The type of photo is 'carousel' but the template only show the first of them.

```
filter: function(image) {

                console.log(image); 
            },

template:'<a href="{{link}}"> <img src="{{image}}" style="width: 95%; height: 95%; text-align:center"/></a>',
```

In the console log, I see that image has a carousel_media property with all photos whit its url each one.

How can I show all the photos of the carousel_media?

Thanks in advance.

**Comment by benjamin-hull** [comment]
Hi @btoran - instafeed.js doesn't have built in support for carousel media, though that would be nice to have. For now, you can use the `mock: true` option and the `success` callback to retrieve the data and insert it into the page yourself.
