### ISSUE TITLE
Get actual Comments?

### ISSUE THREAD

**Issue by jdcauley** [stevenschobert/instafeed.js#6]
I'm assuming its just on the docket to pull the full list of comments?

Also you're my favorite person ever

**Comment by veevee06** [comment]
@stevenschobert - I'm pulling a series of images using get: 'tagged' and there are images posted by one or more ig users that I want to filter out.  Is it possible using your filter to filter out username?  I haven't been able to get the filter to work when using the tagged method.

Thanks,
Vernon Davis
