### ISSUE TITLE
Template is not working in v2.0

### ISSUE THREAD

**Issue by svkmedia** [stevenschobert/instafeed.js#600]
I just discovered that template option is not working in version 2.0.
When I switch back to v1.9.3 everything works fine.
Using it with angularJS. Tried also $timeout to show instafeed but no success. Feed is working but it loads just plain images.

**Comment by austinhutchison** [comment]
Hi - the issue appears to be that instead of `template` you need to use unique templates depending on the instagram item type, e.g:
`imageTemplate`
`carouselFrameTemplate`
