### ISSUE TITLE
Instafeed Template help!!

### ISSUE THREAD

**Issue by CMAgency** [stevenschobert/instafeed.js#601]
Hi,

I have created a 3x3 Grid but I want the top row to be moved to the right but one image so one image on the right hangs off, what is the best way to achieve this?

**Comment by benjamin-hull** [comment]
Hi @CMAgency - this is really a general layout/CSS question, and so out of scope for an instafeed.js issue. You'd be better off sketching out a diagram and asking a question over on [StackOverflow](https://stackoverflow.com/questions/tagged/css) or doing some reading on CSS grid layouts, for example [here](https://gridbyexample.com/) or [here](https://codepen.io/rachelandrew/pen/RGwyAb).

Good luck!
