### ISSUE TITLE
Error from Instagram: The access_token provided is invalid

### ISSUE THREAD

**Issue by keslo** [stevenschobert/instafeed.js#602]
In manual says that "**accessToken is no longer required to fetch images from user accounts!**" 
But I have a message in console "**Uncaught Error: Error from Instagram: The access_token provided is invalid**".
```
var feed = new Instafeed({
        get: 'user',
        tagName: 'awesome',
        userId: 'this_my_user_id',
        clientId: 'this_my_client_id',
    });
    feed.run();
```
Where's mistake?

**Comment by benjamin-hull** [comment]
Hi @keslo - it looks as if Instagram no longer supports requests without an access token. I'll update the documentation, thanks.
