### ISSUE TITLE
is it compatible with european dsgvo / gdpr?

### ISSUE THREAD

**Issue by paddymaster** [stevenschobert/instafeed.js#604]
does instagram collect any data from the clients ?

**Comment by benjamin-hull** [comment]
Instafeed.js makes a request directly from the client's browser to the Instagram API, which determines what information is collected and how it is used and stored. Following is the only GDPR statement on the Instagram website: https://help.instagram.com/2000935033561463

You can inspect the data sent to the API by using your browser's dev tools - here's an example:

![instagram api request](https://user-images.githubusercontent.com/53896/44373760-040d7380-a52a-11e8-8d9e-7ab4a7d5844d.jpg)

My understanding is that this is not considered personally-identifiable information, and as such is compatible with GDPR. I could well be wrong on that, though!
