### ISSUE TITLE
Loading feeds stops at Video

### ISSUE THREAD

**Issue by c0c0t3** [stevenschobert/instafeed.js#605]
Hello,I tryto usethis plugin on my custom theme for WP.

URL : http://dev.escaunes.com/

Everything is almost alright, but I have 2 problems :

- ### get : User
**Issue :** loading insta feed stop when I have a video.

```
<script>
    var userFeed = new Instafeed({
        get: 'user',
        sortBy: 'most-liked',
        userId: 'xxxxxxxxxx',
        accessToken :'xxxxxx.xxxxxxx',
        resolution: 'standard_resolution',
        limit: '8',
        template: '<a target="_blank" href="{{link}}" class="instafeed-link w-inline-block"><img src="{{image}}" class="instafeed-image {{orientation}}"><div class="instaffed-caption"><div class="counter"><img src="<?php echo get_template_directory_uri(); ?>/images/heart.png" width="24" class="instafeed-caption-icon"><div class="instafeed-caption-counter">{{likes}}</div></div><div class="counter"><img src="<?php echo get_template_directory_uri(); ?>/images/chat.png" width="24" class="instafeed-caption-icon"><div class="instafeed-caption-counter">{{comments}}</div></div></div></a>'

    });
    userFeed.run();
  </script>
```

- ### get : Location or Tagged
I can't retrieve feed from a location, even I reistred a new client et authorize it, with a new clientId and a new accessToken.

https://www.instagram.com/explore/locations/807754699/le-domaine-des-escaunes/?hl=fr

Can you help me please ?

**Comment by benjamin-hull** [comment]
Hi @c0c0t3,

To address your issues:

1) Video support currently requires a workaround as shown here: https://github.com/stevenschobert/instafeed.js/issues/359

2) Permissions to query location and tag are no longer being granted by Instagram. Your queries are limited to your [own sandbox feed](https://www.instagram.com/developer/sandbox/), which is just for the user who generated the access token by default.
