### ISSUE TITLE
Feed only loads on mobile

### ISSUE THREAD

**Issue by bubsly** [stevenschobert/instafeed.js#607]
Hi all,
My feed only loads when running on my local machine or on mobile.
The website is www.scarborows.com
The feed is located in the news section.

The web console gives this error: 

> Loading failed for the <script> with source “https://api.instagram.com/v1/users/8474079368/media/recent?access_token=8474079368.1677ed0.9f40f5a7e3674d3c8db8f707c144bac2&count=4&callback=instafeedCacheb216bb6771af1c30.parse”.

I have tried using a CDN, changing the access token, running without an access token. But still doesnt work. 
But how can it work on mobile? (Android)

**Comment by benjamin-hull** [comment]
Hey @bubsly - this looks fine to me. I've reproduced it here: https://codepen.io/benjamin-hull/pen/xaXOZX

Could it be an ad-blocker or privacy extension on the browser you're using on your machine? A good way to test is to try it in an incognito/private browsing window, as these generally don't load extensions by default.
