### ISSUE TITLE
Image limit option is working differently for different accounts.

### ISSUE THREAD

**Issue by jainnidhi** [stevenschobert/instafeed.js#609]
If I add image limit '6' for one account and its working fine.
But when I add image limit '6' for another account then it shows 5 images.

And both are public account.

**Comment by benjamin-hull** [comment]
Hi @jainnidhi,

This sounds like an effect of Instgram's [API Sandbox mode](https://www.instagram.com/developer/sandbox/) - where only the most recent 20 images are available to be queried by the API. If you add extra conditions (ie, limiting by tag), you will only see images that match those conditions from within those 20 most recent.

Perhaps take a look at the Sandbox link, and if you think this isn't the issue, please post back with a sample of your code (a working example in something like codepen.io is ideal).
