### ISSUE TITLE
When will /users/self/media/recent stop working?

### ISSUE THREAD

**Issue by nmobregon** [stevenschobert/instafeed.js#610]
Hello everyone, I have a doubt, Instagram is updating its api, and I'm not sure if this endpoint will be deleted in December, or in 2020. Which is it? Thanks!

https://www.instagram.com/developer/

Public Content - all remaining capabilities to read public media on a user's behalf on December 11, 2018
Basic - to read a user’s own profile info and media in early 2020

**Comment by benjamin-hull** [comment]
My understanding is that `/users/self/media/recent` is considered 'basic' access, which should mean that it's available until 2020. The wording there doesn't make it 100% clear though.
