### ISSUE TITLE
Uncaught Error: Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by glasgowm** [stevenschobert/instafeed.js#611]
Getting this error. I've generated my token using this tutorial

https://elfsight.com/service/generate-instagram-access-token/

Tried it with both Disable implicit OAuth ticked and unticked - same error?

**Comment by glasgowm** [comment]
Site here : http://gutic.org.uk/new/

Insta : https://www.instagram.com/guticnow/

**Comment by glasgowm** [comment]
Also tried using the client ID instead of the access token - same error

**Comment by glasgowm** [comment]
Okay, fixed the errors by changing the code to this

  <script type="text/javascript">
              var feed = new Instafeed({
                  get: 'tagged',
                  tagName: 'awesome',
                  userId: '8463228644',
                  accessToken: '8463228644.25ac3c2.28fc1e7db04e4c7387ed5c226b37f405',
                  template: '<a href="{{link}}"><img src="{{image}}" /></a>'
                  scope => 'public_content'
              });
              feed.run();
          </script>

Now just getting a 404 error...why is it so complex to pull in some public images? 😭

**Comment by benjamin-hull** [comment]
Hi @glasgowm - the error I'm seeing is that 'tagged' requires an access token with 'public_content' scope, which aren't being provided by Instagram any more (and haven't been for a couple of years now). Check issue #345 and the README for more info.  

The bulk of your code is fine - check this [working example](https://codepen.io/benjamin-hull/pen/JaxQvR)

**Comment by zezettepglc** [comment]
Your "working example" does'nt work :)

**Comment by eyouan360** [comment]
> Hi @glasgowm - the error I'm seeing is that 'tagged' requires an access token with 'public_content' scope, which aren't being provided by Instagram anymore (and haven't been for a couple of years now). Check issue #345 and the README for more info.
> 
> The bulk of your code is fine - check this [working example](https://codepen.io/benjamin-hull/pen/JaxQvR)

his solution worked for me...thanks benjamin-hull
