### ISSUE TITLE
instafeed works on my localhost, not online

### ISSUE THREAD

**Issue by romainlepretre** [stevenschobert/instafeed.js#613]
Hi,

I'm using the instafeed.js, everything is fine and works perfectly on my localhost.
Once I upload on OVH and get online the website, no pictures are displayed.
I really don't understand why this is not working
This is a picture of my website on the localhost :
![sans titre 3](https://user-images.githubusercontent.com/43847807/46469370-7503a480-c7d3-11e8-8e6a-07e1f9087cae.jpg)

As you can see on the online one, there is nothing :
http://www.sarl-lepretre.fr/nos-realisations.html

Do you have any ideas of what's going on? Is there  something to fix about http and localhost?

Thank you for your help

**Comment by romainlepretre** [comment]
I just tried with another ID and token, same trouble.

**Comment by romainlepretre** [comment]
Hum... I named "instafeed.js" by "Instafeed.js"
So weird this works on my localhost and not online... For an upercase
Now it works, thank you for your help.

**Comment by benjamin-hull** [comment]
That’s pretty common - if your development OS is case insensitive (eg Windows) but your production OS is case sensitive (Linux etc - which is basically everywhere), this will happen.

It’s a good idea just to treat all web development as case sensitive (I just use all lowercase for file names for everything).

Glad you got it fixed!
