### ISSUE TITLE
Instafeed with automatically look for a <div id="instafeed"></div> and fill it with linked thumbnails

### ISSUE THREAD

**Issue by tristaneljed** [stevenschobert/instafeed.js#614]
`Instafeed with automatically look for a <div id="instafeed"></div> and fill it with linked thumbnails`
This is not working.

**Comment by stevenschobert** [comment]
Hey @tristaneljed! Can you share some more details about whats not working? Are you seeing errors in the web inspector console?

**Comment by tristaneljed** [comment]
Hi @stevenschobert , so what I did is a simple implementation following your tutorial:
I downloaded your javascript library:
`<script type="text/javascript" src="../static/js/instafeed.min.js"></script>`
Then in my HTML body I added:
```
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: 'awesome',
        clientId: 'YOUR_CLIENT_ID'
    });
    feed.run();
</script>
```
Then created this empty div:
`<div id="instafeed"></div>`
When I open it, it doesnt show anything, and I have a valid client ID that I used in other libraries.

**Comment by stevenschobert** [comment]
Hey @tristaneljed! The Instagram API doesn't support fetching "tagged" images with a client ID anymore. You'll only be able to fetch your own images, and you'll need an access token to do it. See [this section of the README](https://github.com/stevenschobert/instafeed.js#warning-important-instagram-is-changing-the-api-that-instafeedjs-depends-on).

Sorry for the confusion!
