### ISSUE TITLE
New IG Posts Not Displaying

### ISSUE THREAD

**Issue by davidloop** [stevenschobert/instafeed.js#617]
As the subject states, new IG posts are not displaying. I have the limit set to display 7 thumbnails. When the code was first set up, all the images, including 1 video thumbnail displayed successfully. I have since made 2 additional IG video posts and they are not displaying, and there are now 2 blank areas which means now only 5 thumbnails are displaying rather than the 7. Thanks!

**Comment by benjamin-hull** [comment]
Closing as idle - @davidloop, please re-open if more help is needed.
