### ISSUE TITLE
Load More option is not working

### ISSUE THREAD

**Issue by userofit123** [stevenschobert/instafeed.js#618]
I have set up the code to use the load more option, it worked in the beginning, i move the code to a different part of the site and now it is not working, clicking on the button does nothing now.

This is the code i have:

```
//Script for instagram feed
var loadButton = document.getElementById('load-more');
var feed = new Instafeed({
    get: 'user',
    userId: 'filled in',
    clientId: 'filled in',
    accessToken: 'filled in',
    template: '<a href="{{link}}"><img src="{{image}}" /></a>',
    after: function() {
        // disable button if no more results to load
        if (!this.hasNext()) {
            loadButton.setAttribute('disabled', 'disabled');
        }
    },
});


// bind the load more button
loadButton.addEventListener('click', function() {
    feed.next();
});


// run our feed!
feed.run();
```

**Comment by benjamin-hull** [comment]
Hi @userofit123 - could you post a URL showing the problem and any errors being generated, please?

**Comment by ry167** [comment]
I encountered this issue too. It seems like the Instagram API returns nothing in the `pagingation` object of its response
