### ISSUE TITLE
Template not render after instagram api update

### ISSUE THREAD

**Issue by ipodjms** [stevenschobert/instafeed.js#620]
After last instragram change, the instafeed dont show and render images ...

the endpont "tags" is disable ...  the endpoint "user" no math json into template....

You know how i can fix it ???

**Comment by rwilsond** [comment]
I have the same problem.
```javascript
<script>
var feed = new Instafeed({
get: 'user',
  accessToken: 'MY TOKEN',
  resolution: 'standard_resolution',
  useHttp: 'true',
  limit: 10,
template: '<a class="animation" href="{{link}}"><img src="{{image}}" /></a>'
</script>
```

Returns just the img tags, no wrapping.

**Comment by anephew** [comment]
Same here, option "template" not work, returns markup without "image" or "link" data.
