### ISSUE TITLE
Error: Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by scottynorris** [stevenschobert/instafeed.js#621]
As above, client id provided, but access token error. When I try to update permissions via instagram:

" You do not need to submit for review for this use case. If you are a developer and you want to display Instagram content on your website, then you do not need to submit your app for review. By using a client in sandbox mode, you can still access the last 20 media of any sandbox user that grants you permission."

All I'm trying to do is populate div with a handful of thumbnails, so sandbox should cover this according to that statement. Moreover, it's actually impossible to obtain an access token with my intended usage. Any ideas?

**Comment by scottynorris** [comment]
Okay I solved this by going to my dev account, managing the client, then unchecking, Disable implicit OAuth, then visiting this url:

https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token

Client ID is your insta dev client id.
Redirect ID is set to whatever you put in the security tab of your dev account manage clients section.

This will load a permissions box from instagram and then redirect to whatever url you listed with a query string holding your access token!

**Comment by PrestaShark** [comment]
Thanks this works fine! But only temporarily... Given token today is again invalid... WTH?

**Comment by siemiatj** [comment]
Tokens invalidate after a while https://www.instagram.com/developer/authentication/
