### ISSUE TITLE
help if you can?

### ISSUE THREAD

**Issue by silentjim1980** [stevenschobert/instafeed.js#624]
I recently learned of GitHub pages & am currently in the process of building one. instafeed was working flawlessly when I was using just strict html.  I wanted to use a jekyll theme so I switched over to that.

Now for some reason the instafeed will not show up even though it works locally (windows) & displays semi properly (formatting / layout).  I have tried six ways from Sunday to fix this & am pulling my hair out. 

I've inserted the proper code (I think) in the proper places.  I think it's either JS error I can't find or a something related to GitHub or even Jekyll that I'm unaware of since I'm new to the hold Github thing.

I don't know coding, Javascript or Jekyll & know just enough HTML to get myself in trouble.  I cobbled together the site from my own html page & used [JekyllNow](https://github.com/barryclark/jekyll-now), inserting my old html code in the appropriate places in the new jekyll template.

My site is here: [SilentJim](https://silentjim1980.github.io/)  the feed is supposed to show to the left of my current blog post.  As I said it was working (on GitHub) before I switched to using Jekyll & I can't figure out what changed.  Any help would be appreciated.

I apologize if this is the wrong place to ask but I don't know where / how else to ask for help with it.

This is what it looks like locally: [![Image from Gyazo](https://i.gyazo.com/31329c8e2f4a28becb3937c2e4c47abd.png)](https://gyazo.com/31329c8e2f4a28becb3937c2e4c47abd)

**Comment by benjamin-hull** [comment]
Hi Jim,

Looking at the console on your site, I can see the error `Error from Instagram: The access_token provided is invalid.` - perhaps try generating a new access token and trying again? Instagram doesn't guarantee that these won't change over time, so it's possible your previous one has expired.

**Comment by silentjim1980** [comment]
Hi,
The original issue was due to the fact I'm not that familiar with the markdown & liquid template system.  I fixed it by adding the {% raw %} / {% endraw %} around the JS for instafeed.  The token issue I wasn't even aware of until I checked the site when I got a notification about this message.  Thanks for the help.
