### ISSUE TITLE
Poll: How much is instafeed.js worth to you?

### ISSUE THREAD

**Issue by benjamin-hull** [stevenschobert/instafeed.js#641]
With the [closure of the legacy API looming](#640), we're trying to work out a solution to keep instafeed.js working. The new API works in a different way, which means a `copy+paste-done` solution can no longer work. 

However we approach it, a new version of instafeed.js would require some server resources to run, to handle updating user tokens and talking with the Instagram API. Of course, resources like that cost money, so a replacement service probably can't continue to be free.

So, our next big question is: 

# How much is instafeed.js worth to you?

_Answers are one-click and anonymous._

[![](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/I'd%20only%20use%20a%20free%20service)](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/I'd%20only%20use%20a%20free%20service/vote)
[![](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/Up%20to%20USD%202.00%20per%20month)](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/Up%20to%20USD%202.00%20per%20month/vote)
[![](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/USD%202-5%20per%20month)](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/USD%202-5%20per%20month/vote)
[![](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/USD%206-10%20per%20month)](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/USD%206-10%20per%20month/vote)
[![](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/More%20than%20USD%2010%20per%20month)](https://api.gh-polls.com/poll/01E04944A3JVRW1KQKXEKM2Q5T/More%20than%20USD%2010%20per%20month/vote)

The ease and freedom of instafeed.js is a big part of what made it so popular in the first place, and we've [wracked our brains](#635) trying to work how to keep it that way. There are other services out there that use short-cuts and undocumented APIs to do what they do, but we don't want to make something that people can't rely on, especially for the small businesses that use instafeed.js to display their content.

We can't make promises at this stage, but if people do want a reliable, paid service, that at least tells us that it's something worth investigating. If you have other thoughts on this topic, please do leave them below.

Many thanks!

**Comment by jhvanderschee** [comment]
There is a dead simple alternative for showing just the users pics on a website, see https://github.com/stevenschobert/instafeed.js/issues/640#issuecomment-590744994.

**Comment by kaleidografik** [comment]
Hi guys, any updates on a road-map/timescale for this, if considering? Thanks!

**Comment by benjamin-hull** [comment]
Hey @kaleidografik - sorry for the late response here! Just a quick update - we are working on a solution and will have more info in a few days time. Stay tuned!

**Comment by jnicol** [comment]
Hi guys, any idea if the proposed solution will be available before the 31st of March cutoff date? I'm worrying that instafeeds on my clients websites are all going to die in 5 days time.

**Comment by benjamin-hull** [comment]
Hi folks! @stevenschobert and I are trying our absolute best to have something ready before the API shut-off - I'd say it's looking like 80% at this point.

We're just determining which parts of the old API can be kept - there are a bunch of options in the old API which just don't work with the new one, so there will be some changes to make (though we're aiming to minimize them). 

There will also be a server-side component required - we will have a couple of options to recommend for this, both 3rd-party (not part of instafeed.js) and free to use - one based on a small Heroku app that you set up yourself, and another with a service you sign up to. We'll include information on those in the release of the new version.

Thanks for sticking with us - we'll have more info for you ASAP.

**Comment by benjamin-hull** [comment]
Instafeed v2 now supports the new Basic Display API. Thanks for all the helpful feedback, folks!
