### ISSUE TITLE
Provide tags on the data model

### ISSUE THREAD

**Issue by benjamin-hull** [stevenschobert/instafeed.js#644]
It should be possible, and would be useful, to extract hashtags from the caption field and provide them as an array.

**Comment by stevenschobert** [comment]
If we go to implement this, it can be added into the `getItemData` method: https://github.com/stevenschobert/instafeed.js/blob/dc304bb3a3d9f488b04d81bf46d8e1ad2f9c62d5/src/instafeed.js#L230

**Comment by stevenschobert** [comment]
This is implemented in v2.0.0-rc2
