### ISSUE TITLE
[FIREFOX] CORSCross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/me/media?fields=caption,id,media….. (Reason: CORS request did not succeed).

### ISSUE THREAD

**Issue by RaudelWeb** [stevenschobert/instafeed.js#648]
Hello. I have been updating my instafeed.js feed on my website. It works perfectly in Chrome, but in firefox I get this error. 

![image](https://user-images.githubusercontent.com/33099992/78135775-17cdcb00-742b-11ea-86d5-d7c3b41dbaca.png)

At first I thought it was my own problem but I went to the updated instafeed.js codepen and I saw that it had the exact same error.

**Comment by RaudelWeb** [comment]
Actually. You might want to check that you don't have your Ad Blocker on. It worked right after I turned it off.

**Comment by stevenschobert** [comment]
Thanks for sharing @RaudelWeb -- the v2 version does use a cross-origin XHR request, whereas the old v1 used JSONP, so this is good to be aware of.

**Comment by tristyb** [comment]
I thought I'd also point out as I had a similar problem that if you're viewing in Firefox and have their Facebook Container (or have setup your own containers) that this will fail too.
