### ISSUE TITLE
API is not supporting IE browsers

### ISSUE THREAD

**Issue by ngocthinh192** [stevenschobert/instafeed.js#651]
Thanks so much for your API.
That was a huge upgrade. But I realize the API is not supporting IE browsers. Including IE 11, IE 10, IE 9, ...

**Comment by benjamin-hull** [comment]
Hi @ngocthinh192 - and thanks!

What specifically about v2 is not working for you in those browsers? 

I'm fairly sure the v2 code is written with older IE's in mind, though we definitely need to do more testing. We'll also need to publish the list of supported browsers - I'm not sure if IE9 will be supported, but I think 10 & 11 will be (TBC).

**Comment by ngocthinh192** [comment]
Hi Ben.
Thank you for supporting me.
I used your code on Codepen.io. The API works great on Chrome, Safari. But
it still doesn't seem to work on IE 11, IE10, IE 9.

I am using Windows 10 Home.


*IE 11 :*
[image: image.png]

*IE 10 :*

[image: image.png]

*IE 9 :*

[image: image.png]

Vào Th 3, 14 thg 4, 2020 vào lúc 12:02 Ben <notifications@github.com> đã
viết:

**Comment by benjamin-hull** [comment]
Hi again - I can't see your image attachments (I don't think they work when you reply-via-email). 

That said, I think it's _Codepen.io_ that doesn't work with IE, not Instafeed, so you won't be able to test Instafeed that way with those browsers. You would need to set up your own install locally to test that way.

**Comment by ngocthinh192** [comment]
I so sorry about the image error.
I understand that Codepen.io does not work in IE.
I have set it up on my website and tested it.
I only use your AccessToken for my testing.

IE 11 : 
![IE11](https://user-images.githubusercontent.com/19874151/79190174-d0453700-7e4d-11ea-98fb-b5ef7e1e811b.png)

IE10 :
![IE10](https://user-images.githubusercontent.com/19874151/79190207-e3580700-7e4d-11ea-8108-dcb96de4db25.png)

IE9:
![IE9](https://user-images.githubusercontent.com/19874151/79190216-e94de800-7e4d-11ea-8859-35d9dd53b77b.png)

Thank you so much !

**Comment by benjamin-hull** [comment]
Alright - looks like we have some mores testing to do. Thanks for raising this.

**Comment by stevenschobert** [comment]
Hey @ngocthinh192, can you try using the non-minified source and let me know what you see?

**Comment by ngocthinh192** [comment]
Hi stevenschobert !
This is a screenshot when I using the non-minified source.

![IE_11_01](https://user-images.githubusercontent.com/19874151/79242637-c4ce2c00-7e9e-11ea-98e9-a68e46cfbf06.png)

![IE_11_02](https://user-images.githubusercontent.com/19874151/79242650-c861b300-7e9e-11ea-9112-7ddb7e8f02e1.png)

**Comment by stevenschobert** [comment]
Cool, thanks for the report @ngocthinh192! We'll take a look and get back to you!

**Comment by ngocthinh192** [comment]
Oh thank you so much and thank you for your great API.
@stevenschobert

**Comment by stevenschobert** [comment]
Hey everyone! This has been fixed in [v2.0.0-rc2](https://github.com/stevenschobert/instafeed.js/releases/tag/v2.0.0-rc2) 🎉
