### ISSUE TITLE
Complete list of data returned by {{model}}?

### ISSUE THREAD

**Issue by kaleidografik** [stevenschobert/instafeed.js#652]
Hi guys. I'm aware the V2 docs are a WIP, but wondering if you could collate a list of all the data options returned by the {{model}} option? I saw you can return the post ID {{model.id}}, but what about things like date posted, like count etc? Anything possible here? Thanks.

**Comment by stevenschobert** [comment]
The complete list of fields can be found in the Instagram Basic Display API docs: https://developers.facebook.com/docs/instagram-basic-display-api/reference/media/

We’ll work on getting those added to the docs, thanks for the reminder!

**Comment by kaleidografik** [comment]
Perfect, thanks @stevenschobert. Shame not to be able to grab like and comment counts any longer (thanks Instagram). Any suggestions how to convert the moustache timestamp (i.e 2020-03-31T08:00:33+0000) into a human readable format?

**Comment by benjamin-hull** [comment]
Hey @kaleidografik - I've dropped those into the docs here: https://github.com/stevenschobert/instafeed.js/wiki/Templating#accessing-the-instagram-api-response. 

As for converting times, https://momentjs.com is probably the gold standard (and it's more modern child https://moment.github.io/luxon is even better for this purpose), though if all you're doing is converting times, something more built in like [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#Browser_compatibility) might be all you need.

Thanks for the feedback!

**Comment by kaleidografik** [comment]
Thanks @benjamin-hull - just having trouble implementing this into Instafeed. Given that the timestamp (2020-03-31T08:00:33+0000) is retrieved only via the templating feature {{model.timestamp}}, how can I get this ISO string and output in a simple format (DD/MM/YY) inside the template? Moment and Luxon seem overkill for this task?

**Comment by benjamin-hull** [comment]
Hey @kaleidografik - you've probably solved this by now, but if not, something simple using the [transform](https://github.com/stevenschobert/instafeed.js/wiki/Data-Transformations) method like this could work:

````javascript

var feed = new Instafeed({
  transform: function(item) {
    item.date = [d.getDate(), d.getMonth(), d.getYear()].join('/');
    return item;
  }
});

````

This creates a separate attribute `date` you can use for display.

**Comment by benjamin-hull** [comment]
I'll close this now as the original issue is solved - feel free to open a new one with any other questions you have.

**Comment by kaleidografik** [comment]
Hey @benjamin-hull - thanks for this. However, having trouble implementing: `Error: error in transform: d is not defined`

Where should this be defined, and how would we output this new date into the templating?

**Comment by benjamin-hull** [comment]
Oops - I missed a line mate! Updated now with `var d = new Date(item.timestamp);`

**Comment by kaleidografik** [comment]
Perfect, thanks @benjamin-hull!

**Comment by kaleidografik** [comment]
Hey @benjamin-hull - I thought this was fully resolved (and this may be above and beyond), but the above does not work in Safari. it seems that Safari has a problem with date strings formatted in the way Instagram returns them (ISO 8601). I don't suppose you could suggest how to get this working x-browser?

**Comment by kaleidografik** [comment]
Hey @benjamin-hull - just wanted to share a date solution for cross browser compatibility. The below transform option creates a {{date}} attribute, and any date format can be built up from the array keys. Hope this is of use to somebody.

```
transform: function(post) {
  // Create {{date}} attribute from timestamp
  // Get timestamp returned by API
  var timestamp = post.timestamp;
  // Split timestamp into array ([0]Year, [1]Month, [2]Date, [3]Hours, [4]Minutes, [5]Seconds, [6]Timezone)
  var array = timestamp.split(/[^0-9]/);
  // Format date (DD/MM) 
  post.date = array[2] + '/' + array[1];
			
  return post;
},
```
