### ISSUE TITLE
use of images on a site

### ISSUE THREAD

**Issue by Aaronzinhoo** [stevenschobert/instafeed.js#658]
the library is easy to use, but for actually using these images on a site are there any other details that must be added to embedded posts? I am just not sure if Instagram will shutdown my site if I display the photos similar to how you do in the "Basic Display API Demo". Any info will help! Thx

**Comment by benjamin-hull** [comment]
Hi @Aaronzinhoo - this is more a question of what Instagram allows and requires rather than something specific to instafeed.js. There's some info available here on their section on embedding: https://developers.facebook.com/docs/instagram/embedding.

Thanks!
