### ISSUE TITLE
Instagram API connection refused with 2.0.0rc1

### ISSUE THREAD

**Issue by pimschaaf** [stevenschobert/instafeed.js#662]
I've set up Instafeed 2.0.0rc1 as described (with Heroku etc.) and this worked earlier. Now I'm getting the following JS error:

`Error: api request error: api connection error`
at instafeed.js:124
at f (instafeed.js:370)
at XMLHttpRequest.e.onerror (instafeed.js:382)

together with a 
`GET https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&access_token=<access_token_hidden> net::ERR_CONNECTION_REFUSED`

I've tried doubling the default apiTimeout (#661) to no avail.

I have one live site where this is happening, but I'd rather share that url privately.

I'm hoping to get some insight in what can be done to fix this issue.
Great work regardless! 🙇‍♂️ 

Edit: line numbers from non-minified instafeed.js

**Comment by stevenschobert** [comment]
Hey @pimschaaf, thanks for the report!

> `Error: api request error: api connection error`

This error gets logged by Instafeed.js when there is a problem with the underlying HTTP connection, and the request never made it to the API.

I'll probably need some more information about the specific site to debug the problem. Is it possible something is blocking the API request (ad-blocker, or proxy)? Are you seeing the same error across multiple browsers/computers?

**Comment by pimschaaf** [comment]
@stevenschobert Thanks! Pointed me in the right direction. Testing on different system confirmed your suspicion that something was blocking requests to graph.instagram.com.

Keep up the good work! Have a good weekend.
