### ISSUE TITLE
instafeed SEO img compression

### ISSUE THREAD

**Issue by wallythewebdev** [stevenschobert/instafeed.js#663]
Hi insatfeed, god it's good to have you guys back! 
---

Loading images via instafeed - is there any way to control the size of the images being passed into the website i.e. the dimensions and compression of those images. 

I am getting a warning saying that the img sizes are not appropriate so wondering if there are any controls for this? 

Thanks in advance

**Comment by stevenschobert** [comment]
Hey @wallythewebdev, thanks for the report (and thanks for the compliment, we're happy the project is going to live on!)

I too have noticed the images coming back from the API are pretty large. When I was implementing v2, I didn't see a way in the API to specify an image size in the Instagram Basic Display API docs. But its possible I overlooked it, or that its in the more generic Facebook Graph API docs (I had a similar problem finding pagination docs, but later found them in a different Facebook API docs section).

We'll have to take another look and see if there is a way to request smaller sizes from the API.

**Comment by wallythewebdev** [comment]
Hi Steve, 

Thanks for the reply, yeah super happy you guys are back! 

Ok cool look forward to any info you might be able to find, I'd be happy to help if this is an open source problem? 

Cheers again,
Wally

**Comment by benjamin-hull** [comment]
Hey @wallythewebdev - just to expand on @stevenschobert 's info a bit, the Basic Display API only returns a single URL for each post, which is generally Instagram's largest resolution (I believe limited to 1920px in each dimension). I've checked the full [Graph API docs](https://developers.facebook.com/docs/instagram-api/reference/media) and there's no way I can see to request alternate sized versions like there used to be. The Facebook CDN's that now serve the images also sign the URLs to prevent tampering - Instafeed V1 used to take advantage of the ability to re-write the provided URL to request different sizes, but this is not possible anymore.

If this is critical for you, one solution would be to set up a 'pass-through' service between your front end and IG's image servers to process your images - some CDN's, such as [KeyCDN](https://www.keycdn.com) offer this service. Of course, by the time you're doing this, you're almost at the point it would be better to integrate with Instagram's API on the server side anyway.

Definitely not an ideal situation, I know! I might drop a line to our contact at FB and ask about the possibility of getting access to alternate sizes.

**Comment by wallythewebdev** [comment]
HI @benjamin-hull - 

Thanks for your reply and adding in the extra detail about the images and sizing - 
It's an odd one and I'm only after it to minimize the UI payload, so being blunt its not the end of the world. 

It would be a great feature - but I'm just happy that instafeed.js is back up and running. 

Thanks again - can close this if it's not a core concern of instafeeds. 

W

**Comment by benjamin-hull** [comment]
Hey @wallythewebdev - I've heard back from the IG API guys, there's no such feature currently, but they've added it as a feature request. Who knows if/when that might happen, but I think that's about as much as we can do for now. I'll let you know if anything changes.

Thanks again!

**Comment by shanomurphy** [comment]
I came up with this solution to get images of different resolutions, see [#681 (comment)](https://github.com/stevenschobert/instafeed.js/issues/681#issuecomment-686733674)
