### ISSUE TITLE
Likes count 

### ISSUE THREAD

**Issue by Jaune8** [stevenschobert/instafeed.js#665]
Hi,

I discovered this plugin yesterday, and thank you it's all i need, to display instagram content in my template. I only want to show the like count, i try a lot of code option but the field is empty do you have any ideas ? :) 

my code : 
`var feed = new Instafeed({
accessToken: '**************************************',
transform: function(post) {
// Create {{date}} attribute from timestamp
// Get timestamp returned by API
var timestamp = post.timestamp;
// Split timestamp into array ([0]Year, [1]Month, [2]Date, [3]Hours, [4]Minutes, [5]Seconds, [6]Timezone)
var array = timestamp.split(/[^0-9]/);
// Format date (DD/MM) 
post.date = array[1] + '/' + array[2] + '/' + array[0];
//count
return post;
},
template: '<div class="likecount">{{likes}}</div><div class="likecount">{{model.likes.count}}</div><div class="likecount">{{model.like}}</div><div class="likecount">{{model.likes}}</div>

<article class="liElement post-29169 post type-post status-publish format-standard has-post-thumbnail hentry category-news"><div class="tflex h100 FlexEspaceCenter    "><header><h2 id="{{model.id}}" class="entry-title tleft newstitle">{{date}}</h2></header><div class="  thumb-more"><div class="img-news  "><div><a href="{{link}}"><img title="{{caption}}" src="{{image}}" /></a></div></div></div><div class=" ttttt h100 tflex tflexcol tright"><div class="entry-content h100 tflex tflexcol "><p>{{caption}}</p></div></div></div></article>',

});
feed.run();`

Thanks have a good day :)

**Comment by MattBudz** [comment]
I noticed the same problem for both likes and comments. I can't seem to make it work.

**Comment by stevenschobert** [comment]
Hey @Jaune8 and @MattBudz! Instagram's Basic Display API does not give us likes and comment values, so they are not available in Instafeed.js v2.

You can see all the data that Instagram gives here: https://developers.facebook.com/docs/instagram-basic-display-api/reference/media
