### ISSUE TITLE
Dynamic add instafeed lib by CDN

### ISSUE THREAD

**Issue by Giovancruz** [stevenschobert/instafeed.js#668]
Hi, first of all thanks for this amazing plugin.

This is a question not a bug. Related to #656 and #519.

I'm also having problems with the request limit. Now i'm following the path mentioned by benjamin-hull [on this comment](https://github.com/stevenschobert/instafeed.js/issues/519#issuecomment-548158741) on #519  to create an intersect observer and only call when the user sees the feed's container.

But i'm afraid that the way that i adding the plugin are making differece on this. Because my client site is dynamic, and, for improve performance, i adding plugin only if component container exists on page:
```javascript
if (typeof(instafeed) != 'undefined' && instafeed != null) {
    var script = document.createElement('script');
    script.async = true;
    script.type = 'text/javascript';
    script.src = 'https://cdn.boomcdn.com/libs/instafeed-js/1.4.1/instafeed.min.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
   script.onload = function(e){
       new Instafeed(options).run();
   }
}
```
I'm also noticed that the request URL have a param cache, ``&callback=instafeedCachef25a5d92150d3bb4.parse`` this param code are changing between page reloads.  
Maybe it's irrelevant, but I prefer to ask if this way can interfere in any way in the plugin and if this URL code can be used somehow for requests with cache.

**Comment by benjamin-hull** [comment]
Hi @Giovancruz - it looks like you're using instafeed.js v1.4.1, which won't work for new installations, and is about to stop working entirely (Instagram will turn off the v1 API at the end of June).

We're currently working on a v2 release, which you can test by following the instructions in the [project readme](https://github.com/stevenschobert/instafeed.js).

**Comment by Giovancruz** [comment]
Thank you! 
We ended up going for a solution involving the request API on the backend and saving the images on database.
