### ISSUE TITLE
The `access_token` provided is invalid

### ISSUE THREAD

**Issue by RichMatthews** [stevenschobert/instafeed.js#669]
I'm making a request here: https://api.instagram.com/oauth/access_token

with all the required stuff `client_id`, `client_secret`, `code`, `grant_type` and `redirect_uri`

which returns me an `access_token` and `user_id` but when I pass that into here:

```
       var feed = new Instafeed({
            get: 'tagged',
            tagName: 'awesome',
            accessToken:
                'IGQVJYZblahbalh',
        })
        feed.run()
```
it says `instafeed.js:81 Uncaught Error: Error from Instagram: The access_token provided is invalid.`

how do I fix this? or get the correct `access_token`?

**Comment by stevenschobert** [comment]
Hey @RichMatthews! Looks like you’re using the `get: “tagged”` option in v1 version of Instafeed.js, which Instagram disabled a while back.

You’ll probably want to upgrade to v2, which you can find under the [releases page](https://github.com/stevenschobert/instafeed.js/releases).
