### ISSUE TITLE
Remove hashtags from captions

### ISSUE THREAD

**Issue by orderoftheditch** [stevenschobert/instafeed.js#670]
Thank you so much for this project, I really appreciate the work being put in.

I am trying to use transform to remove the hashtags from the captions.

I have tried the following but it isn't working, any help would be much appreciated. 

`<script type="text/javascript">

var feed = new Instafeed({
 accessToken: InstagramToken,
 limit: 10,
 target: 'instafeed',
 transform: function(item) { //Transform receives each item as its argument
// Over-write the original timestamp
item.timestamp = new Date(item.timestamp).toLocaleString('en-AU', {
   
   year: 'numeric', 
   month: 'long', 
   day: 'numeric'
 });

// return the modified item
return item;

},

transform: function(item)  {
item.caption = new RegExp('#([^\\s]*)','g'),
(caption.replace(regexp, '').replace(/  +/g, ' '));
return item;

},

 template: '<div class="vertical-line"></div><div class="post-title">{{timestamp}}</div><div class="vertical-line"></div><div class="post-container"><div class="post-image"><img src="{{image}}"/></div> <div class="post-caption"> {{caption}}</div></div>',
});
feed.run();
</script>`

**Comment by benjamin-hull** [comment]
Hi @orderoftheditch - thanks for the kind words, it means a lot!

I'm not sure what the exact issue is with your code - the paste into Github hasn't been kind to it. One thing that stands out is that you have the `transform` option being passed in twice, which isn't right. I would think the second one (yours) would overwrite the first one in that case, but it's never what you want anyway.

If you use a version of the Regular Expression that Instafeed uses internally to locate hashtags, everything works as expected. There's a quick demo here: https://codepen.io/companionstudio/pen/XWmwpLm

The key part is the body of the transform function:

```javascript
transform: function(item) {
  item.caption = item.caption.replace(/#[^~`!@#$%^&*\(\)\-\+={}\[\]:;"'<>\?,\./|\\\s]+/gi, '').trim();
  return item;
}

That should do the trick. Let me know if you still have trouble!
```

**Comment by orderoftheditch** [comment]
Thank so much, that worked great for me.
