### ISSUE TITLE
How to show likes in instafeed.js V2 

### ISSUE THREAD

**Issue by laamfh013** [stevenschobert/instafeed.js#671]
Hello @stevenschobert ,

First we need to thanks for putting the code here, it really helps us a lot!! 

But I was wondering if it is still possible to show likes (or just get the number of likes) using the instafeed.js version two ? what is the format of using template to show likes ?  (I tried to search the format but they didn't work ..)

Thanks!!

**Comment by benjamin-hull** [comment]
Hi @laamfh013,

I'm afraid you're out of luck on accessing the like count: Instagram no longer publishes that data (along with a lot of other information) via the new Basic Display API that Instafeed.js v2 uses. See the [API Developer reference at Facebook](https://developers.facebook.com/docs/instagram-basic-display-api/reference/media#fields) for a list of the information that Instafeed receives about each image.

**Comment by MattBudz** [comment]
@benjamin-hull @stevenschobert maybe an update to the doc's is in order. It seems like the docs still list `{{likes}} - Number of likes the image has.` as well as `{{comments}} - Number of comments the image has.` amongst others. This may be causing the confusion here.

**Comment by stevenschobert** [comment]
@MattBudz Yep! The docs are definitely in need of an update. I’m working on replacing them!

**Comment by benjamin-hull** [comment]
Hi @MattBudz - could you point out the docs that include `{{likes}}` info? I can only find it in the old v1 Readme.

**Comment by NightOwlKeyboards** [comment]
Is the legacy API still working? I am curious because some Instagram feeds are still able to pull Like and Comment counts. (Example elfsight) I have done some digging but am not able to figure out how they are getting this data.

**Comment by vulkanus** [comment]
> Is the legacy API still working? I am curious because some Instagram feeds are still able to pull Like and Comment counts. (Example elfsight) I have done some digging but am not able to figure out how they are getting this data.


I think you need a business account but I tried to change it but I can't filter the data
https://developers.facebook.com/docs/instagram-api/guides/business-discovery/

**Comment by benjamin-hull** [comment]
@NightOwlKeyboards, no the Legacy API is definitely shut down. It's my understanding (though I could be wrong) that Elfsight goes outside the API for that - they're basically screen-scraping the data and normalizing it to use in their feeds. That's not something that can be done with a client-only library like Instafeed, and in any case would need constant attention to stay working: Elfsight must be in a constant arms-race with Instagram to continue to access that info. Not fun!

I'll close this for now, as there's no official support for this, so Instafeed can't provide it.
