### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by orderoftheditch** [stevenschobert/instafeed.js#672]
On Apple devices any formatted date (e.g dd/mm/yy or the transformation example in the Wiki)  is displayed as "Invalid Date".

**Comment by Matra-Simca** [comment]
I'm getting "Invalid Date" too when using the transform example on macOS Safari (seems fine in macOS Chrome/Firefox/Opera)

**Comment by orderoftheditch** [comment]
I have found a workaround.

The JS library  `moment.min.js` has to be referenced.

Then the following can be used.
`moment.lang('en-AU');

transform: function(item) {
item.timestamp = moment(item.timestamp).format("DD MMMM YYYY");
return item};`
