### ISSUE TITLE
Token from instant-tokens.com

### ISSUE THREAD

**Issue by sjabby** [stevenschobert/instafeed.js#674]
Hi,

Could anyone add instructions on how to include the token from https://www.instant-tokens.com/?
How would the code samples look then?

The heroku app is not working :(

**Comment by ringerce** [comment]
Hi,

They have a wiki page with a codepen example to help you out located here:
https://github.com/codingbadger/instant-tokens.com/wiki/3.-Instafeed.js-Demo

Have fun!

**Comment by ringerce** [comment]
They have a wiki page and codepen example on their website.

**Comment by stevenschobert** [comment]
Hey @sjabby! You should be able to use the new asynchronous access token feature in V2, to fetch your token dynamically from instant tokens:

```js
var feed = new Instafeed({
  accessToken: function(done) {
    $.ajax({
      url: instantTokenApiUrl,
      dataType: 'json'
    }).done(function(response) {
      if (response.Token) {
        done(null, response.Token);
      } else {
        done(new Error('error: ' + response));
      }
    });
  }
});
```

**Comment by stevenschobert** [comment]
@ringerce thanks for chiming in too!
