### ISSUE TITLE
Cross-Origin Request Blocked / api request error: api connection error

### ISSUE THREAD

**Issue by tyssen** [stevenschobert/instafeed.js#676]
I'm trying to implement instafeed on a site and am getting:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&access_token=xxxxxx. (Reason: CORS request did not succeed).

and

> Error: api request error: api connection error

So I checked another site which I'd just done the same thing on and am getting the same error there now too when it was working OK a couple of weeks ago.

**Comment by benjamin-hull** [comment]
Hey @tyssen - this sounds like it could be a couple of things: either API limits or token problems. How are you handling getting your token currently?

**Comment by tyssen** [comment]
The site that was working is using the Heroku Instagram agent (the app is still working), but the one I've been working on used instant-tokens.com because I couldn't create apps on Heroku yesterday.

**Comment by benjamin-hull** [comment]
Not sure if this is still relevant, @tyssen , but the issue with Heroku not allowing new instances of instagram-token-agent has been resolved now.
