### ISSUE TITLE
Image sizes?

### ISSUE THREAD

**Issue by chrismaaz** [stevenschobert/instafeed.js#677]
How do I query the image size I want? I don't want the original size but the s640x640 that's available (or any other smallish size), can't find any documentation about it anywhere. I assume it can be done via the "transform" argument? Any help would be appreciated.

**Comment by benjamin-hull** [comment]
Hi @chrismaaz - unfortunately the Basic Display API does not provide multiple sizes for each image. There's a bit more information here: https://github.com/stevenschobert/instafeed.js/issues/663#issuecomment-624492666

We've put in a request with the Instagram API team to provide a thumbnail-sized URL, but I don't have any info as to if/when it might be considered.

Sorry I can't be more help!

**Comment by chrismaaz** [comment]
Cheers! It is as I feared then. But seeing it is OpenGraph based now it shouldn't be very difficult for Facebook/Instagram to add more fields that are returned through the API.

**Comment by shanomurphy** [comment]
I came up with this solution to get images of different resolutions, see #681 (comment)
