### ISSUE TITLE
Uncaught Error: Error from Instagram: This endpoint has been retired

### ISSUE THREAD

**Issue by boseakash7** [stevenschobert/instafeed.js#678]
Suddenly not working from yesteday.

**Comment by stevenschobert** [comment]
Hey @boseakash7! Instagram has retired the API in favor of the new Basic Display API:

From the [Instagram API page](https://www.instagram.com/developer/)
> The remaining Instagram Legacy API permission ("Basic Permission") was disabled on June 29, 2020. As of June 29, third-party apps no longer have access to the Legacy API. To avoid disruption of service to your app and business, developers previously using the Legacy API should instead rely on Instagram Basic Display API  and Instagram Graph API . Please request approval for required permissions through the App Review process.

You’ll need to upgrade to the v2 version of Instafeed.js to use the new Basic Display API
