### ISSUE TITLE
How to retrieve images with different resolutions?

### ISSUE THREAD

**Issue by masiorama** [stevenschobert/instafeed.js#681]
Hello there, in the docs it is stated that:

> thumbnail_url: The Media's thumbnail image URL. Only available on VIDEO Media.

Does this mean that if I want to retrieve the feed images in a lower resolution I simply cannot?

I haven't found a way to retrieve the images in a resolution lower than 900x900...

Can anyone clear this up to me please?
Thanks in advance.

**Comment by masiorama** [comment]
I fear it is not possible: https://stackoverflow.com/questions/59930227/instagram-basic-display-api-alternative-image-size

**Comment by vulkanus** [comment]
Too bad! :(((

**Comment by masiorama** [comment]
Has anyone find a way to get small images directly from the source? Any ETA from Instagram? I definitely understand that this is not an Instafeed problem, nonetheless I think this is a big problem for this library too. 
Thanks for any info!

**Comment by shanomurphy** [comment]
I found the following url pattern works for retrieving images of different sizes:

Get the post permalink:

`https://www.instagram.com/p/CEriQnOMwW9/`

and append `media?size=t` to it like this:

- `media?size=t` returns a 150x150 px image
- `media?size=m` returns a 320x320 px image
- `media?size=l` returns a 1080x1080 px image

This resolves to a corresponding image on their CDN e.g.:

`https://scontent-lht6-1.cdninstagram.com/v/t51.2885-15/e35/s150x150/118725806_2684783481838717_5792380552439146436_n.jpg?_nc_ht=scontent-lht6-1.cdninstagram.com&_nc_cat=1&_nc_ohc=gi9Y2_xUxfAAX_82RD5&_nc_tp=15&oh=fc3a5ca4968ef2fa3dea1237584ce627&oe=5F7C05C9`

So in instafeed we can use the template option and the {{link}} templating tag to get the image size we need like so:

`<a href="{{link}}"><img src="{{link}}media?size=t" /></a>`

Or add our own size attributes using the `transform` option and `model` tag:

```javascript
var feed = new Instafeed({

    accessToken: InstagramToken,
    
    // Add image size attributes
    transform: function(item) {
        item.model.image_thumb  = item.link + 'media/?size=t';
        item.model.image_medium = item.link + 'media/?size=m';
        item.model.image_large  = item.link + 'media/?size=l';
        return item;
    },

    template: '<a href="{{link}}"><img src="{{model.image_thumb}}" /></a>'

});

feed.run();
```

I'm guessing this could break at any moment if Instagram stop supporting that url pattern though.

**Comment by benjamin-hull** [comment]
Good detective work, @shanomurphy!

Your observation:

> I'm guessing this could break at any moment if Instagram stop supporting this (undocumented?) url pattern though.

is pretty much on-point though: Instagram did take extra steps to stop Instafeed v1 from using these undocumented URLs, so I would be very hesitant to use them in a production setting.

I'm going to close this issue, as there's no official support for image resolutions, so it's not something that Instafeed can look after. Thanks again!

**Comment by vulkanus** [comment]
I think already breaked :(
Any resolution?
