### ISSUE TITLE
Instagram blocked Picture

### ISSUE THREAD

**Issue by mark-baumann** [stevenschobert/instafeed.js#682]
Hey guys, 
if you are clicking more often on a picture the following error message comes:

For your protection, www.instagram.com does not allow Firefox Developer Edition ### (other Browsers too) to display this page if it is embedded in another page. To display the page, it must be opened in a new tab.

<img width="642" alt="Bildschirmfoto 2020-07-08 um 12 26 45" src="https://user-images.githubusercontent.com/60445235/86908511-e98d1500-c116-11ea-98e5-70cc6636222c.png">

Does someone know how to solve it?

Thank you!
Mark Baumann

**Comment by mark-baumann** [comment]
On Smartphone: I only can see the picture at Instagram, if I tap the Picture in a new Tab

**Comment by stevenschobert** [comment]
Hey @mark-baumann, thanks for report!

Are you able to reproduce the problem in an example CodePen, or something similar?

**Comment by mark-baumann** [comment]
I have postet the Code on repl.it: https://bv-viehbach--markymark1.repl.co

There is a error message called "ReferenceError: Instafeed is not defined". 
but the script is integrated into the HTML and it works productively. You can see it at http://bv-viehbach.de
