### ISSUE TITLE
Isotope

### ISSUE THREAD

**Issue by vulkanus** [stevenschobert/instafeed.js#683]
I run in my project isotope by metafizzyco, and I would like to know how can I integrate with instafeed.
What is happening, is, when I load the page from first time, Isotope cannot (re)layout the page/  "target" (DOM elem.) where the instafeed shows the images, I have to do manually to show all images (i.e resize images with button plus css).

Can anyone help me understand how can I refresh instafeed together with isotope() in the first load page?

Thank you in advance.

**Comment by stevenschobert** [comment]
Hey @vulkanus!

You’ll need to use the `after` option, so you can start isotope _after_ Instafeed.js has run and inserted the images into the DOM.

**Comment by vulkanus** [comment]
> Hey @vulkanus!
> 
> You’ll need to use the `after` option, so you can start isotope _after_ Instafeed.js has run and inserted the images into the DOM.

Yes, it was that. Thank you.
