### ISSUE TITLE
Cannot seem to increase limit

### ISSUE THREAD

**Issue by eluce2** [stevenschobert/instafeed.js#685]
I'm trying to use this script to pull photos from a single Instagram account, but only display the ones with a certain hashtag. I'm able to get this working using the transform function, but the limit seems to be stuck at 25 images regardless of what it set in the "limit" option. Is there something I'm missing here, or is there a way to get all the images from a single user account?

**Comment by vulkanus** [comment]
Hi,

I think you should reed this [#649 ](https://github.com/stevenschobert/instafeed.js/issues/649)

**Comment by bigskillet** [comment]
I'm having the same issue.

**Comment by bigskillet** [comment]
Ping

**Comment by stevenschobert** [comment]
Hey @eluce2 and @bigskillet, thanks for the report! I've heard similar reports that some people are only seeing 25 images returned from the API.

If you get the chance, could you try upgrading to v2.0.0-rc3, and trying out the pagination feature, and new `apiLimit` option? I'm wondering if Instagram has an undocumented default limit of 25 images, or if they are refusing to return a larger set for another reason.

Thanks!

**Comment by bigskillet** [comment]
It's working, but the limit must be set to return more/less than 25 images. Not setting the limit, it defaults to 25 images as you mentioned above. Either way, it looks like it working!

**Comment by vulkanus** [comment]
> It's working, but the limit must be set to return more/less than 25 images. Not setting the limit, it defaults to 25 images as you mentioned above. Either way, it looks like it working!

Hi,
Did you used the default instafeed and the pagination button appeared automatically? or did you add any option to the var feed = new Instafeed({}) ?

thank you

**Comment by bigskillet** [comment]
I have it set up very basic with no pagination: 
```
fetch('https://ig.instant-tokens.com/users/token-here')
  .then(resp => resp.json())
  .then(data => {
    const feed = new Instafeed({
      accessToken: data.Token,
      template: 'html-here',
      limit: 24
    });
    feed.run();
  })
  .catch((error) => {
    console.log(error)
  }); 
```

**Comment by vulkanus** [comment]
@bigskillet 

thank you for reply.
In my case I use direct token via FB/IG API, so in my fetch data, I see the the pagination data:

`"paging": {
      "cursors": {
         "before": "**removed token**",
         "after": "**removed token**"
      },
      "next": "https://graph.instagram.com/v1.0/removedID/media?access_token=**Removed Token**&pretty=1&fields=caption\u00252Cid\u00252Cmedia_type\u00252Cmedia_url\u00252Cpermalink\u00252Cthumbnail_url\u00252Ctimestamp\u00252Cusername&limit=25&after=**removed string**"
   }
}`


But cannot see How can I add the pagination button, hummm, but in the Wiki there isn´t yet update information for RC3.
Did have the website online to see working, or a codePen?

Thank you any way.

**Comment by stevenschobert** [comment]
Hey @vulkanus! Sorry that there aren't examples in the documentation yet, but here is a basic example of using pagination with a "next" button:

```html
<div id="instafeed"></div>
<button id="next">Next</button>

<script src="dist/instafeed.min.js"></script>
<script>
  var next = document.querySelector('#next');
  var feed = new Instafeed({
    after: function() {
      if (!feed.hasNext()) {
        next.setAttribute('disabled', 'disabled');
      }
    },
    accessToken: '...'
  });
  next.addEventListener('click', function(event) {
    event.preventDefault();
    feed.next();
  });
  feed.run();
</script>
```

The basic idea is there are two functions:

1) `hasNext` - a function you can call to check if pagination data is available
2) `next` - a function you call to show the next set of images

In my basic example, I've used the `after` option to disable the button when the pagination data is exhausted, and a click handler on the button to call `next()`.

Hope that helps!

**Comment by vulkanus** [comment]
Hi @stevenschobert 

Thank you so much. 
Now I´m in a good direction, that´s it! Now I´ll adjust my code.

But the FB API limits is a big piece of A!!!!
"Error: api request error: 4 Application request limit reached                 instafeed.js:411"

:(

**Comment by diwakarmishra** [comment]
Hi @stevenschobert It appears older versions of the instafeed.js had the pagination (**.next**)  functions built in. Which are now removed. It would be very helpful if you could add a pagination example to the documentation. Thank You!

**Comment by vulkanus** [comment]
+1

**Comment by vulkanus** [comment]
ping
