### ISSUE TITLE
load more button

### ISSUE THREAD

**Issue by mmjaeger** [stevenschobert/instafeed.js#686]
Hello
I was wondering how difficult it would be to e.g. load an initial 12 pictures and then add a button to load more images if so desired?

Thanks

**Comment by kaimikinkino** [comment]
Great question.

**Comment by vulkanus** [comment]
May be you want to follow this issues #649

**Comment by stevenschobert** [comment]
Hey @mmjaeger and @kaimikinkino! Sounds you are looking for the pagination feature, like @vulkanus mentioned.

Good news though, pagination is now available in v2.0.0-rc3 of Instafeed.js. Give it a try and let me know if you run into any issues!
