### ISSUE TITLE
Filter by #hashtag

### ISSUE THREAD

**Issue by sonets2017** [stevenschobert/instafeed.js#688]
Hi,

i try filter post image with "hashtag". Is it possible?

I use "filter".

`    filter: function(image) {
        console.log(image);
        return image.tags.indexOf('wip') >= 0;
    }`

Filtering doesn't work. Please help.

**Comment by stevenschobert** [comment]
Hey @sonets2017! What’s not working for you? Are you seeing any error messages in the console?
