### ISSUE TITLE
Pulling hair out on App Review

### ISSUE THREAD

**Issue by keithstone97** [stevenschobert/instafeed.js#689]
I am beyond frustrated with Facebook. I had working server code that managed the tokens for V1 that stopped working. OK, so we updated the code and have it working fine with test users, and got the token refresh working. We updated Instafeed to V2. So far so good. So we're trying to use something besides test users and need to go through an App Review. Facebook's comments on why they keep rejecting our "app" are next to worthless. I eventually got the user_profile privilege approved, but they keep rejecting user_media privilege (the part I assume Instafeed.js uses) with "We cannot find a valid use case for this privilege". Then they attach a screen shot that SHOWS THE USE CASE THEY SAY THEY CAN'T FIND. Is Instafeed.js considered an invalid use case? Do I not need user_media? Are all the Facebook reviewers ignorant twits? 

Everything works fine in development mode. But the minute I make it "live" with only the user_profile permission approved I cannot generate a token.

**Comment by benjamin-hull** [comment]
Sorry to hear that, @keithstone97 - but issues with app review are out of scope for Instafeed.js. You'll probably find better information on the [Facebook dev support forums](https://developers.facebook.com/community/).
