### ISSUE TITLE
Instafeed fails to load on Firefox

### ISSUE THREAD

**Issue by zdebra** [stevenschobert/instafeed.js#690]
Hello, I am using firefox (79.0b8) and instafeed doesn't work because it is rejected for CORS protection. I've tried to send `Access-Control-Allow-Origin: *` header from the server without any luck.

Even your minimal example doesn't work https://codepen.io/companionstudio/pen/rNVPGOz 

This is the problematic line from browser console: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&access_token=XXX. (Reason: CORS request did not succeed).
```

It does work on chrome.

Is it a known issue?

**Comment by benjamin-hull** [comment]
Hi @zdebra - do you have a privacy add-on or 'facebook blocker' active in Firefox by any chance? 

I can definitely run the minimal example in Firefox 80.xx here, and that CORS request isn't something Instafeed could affect anyway, since the policy will be set by graph.instagram.com. My hunch is that there's something in your Firefox setup that is getting in the way of that CORS request to make it fail.

**Comment by zdebra** [comment]
> Hi @zdebra - do you have a privacy add-on or 'facebook blocker' active in Firefox by any chance?
> 
> I can definitely run the minimal example in Firefox 80.xx here, and that CORS request isn't something Instafeed could affect anyway, since the policy will be set by graph.instagram.com. My hunch is that there's something in your Firefox setup that is getting in the way of that CORS request to make it fail.

Actually, I am using the Facebook container addon https://github.com/mozilla/contain-facebook and it is working when I disabled the addon. But that should just containerize facebook cookies not blocking requests.

**Comment by terehru** [comment]
I have the same issue.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://instafeed.nfcube.com/feed/v4?charge=0&fu=0&limit=8&account=orlova-jewellery.myshopify.com&fid=0&hash=9bbec1203fcc1f20df4f18ed76095514&callback=cache.parse. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://xyz.myshopify.com’).`

**Comment by jhvanderschee** [comment]
I also could not get it to work on Firefox, so I build my own solution (for all of you to use). You can find it at https://profilepageimages.usecue.com/. It is limited in its functionality, but aims to be the simplest way to load your instagram images.

**Comment by clarencefoy** [comment]
Same issue here:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&access_token=XXX. (Reason: CORS request did not succeed).

**Comment by clarencefoy** [comment]
Same error message here:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&[access token here]. (Reason: CORS request did not succeed).

**Comment by jhvanderschee** [comment]
You are not an idiot. Are your own instagram images ads? Is Firefox blocking them wrongfully? Those things are up for debate. But it is clear that Firefox does not want you to trade your visitors privacy for a few images you could host anywhere.
