### ISSUE TITLE
Procedure to use this script to mix multiple feeds

### ISSUE THREAD

**Issue by Nofrek** [stevenschobert/instafeed.js#694]
**hi**

I am currently trying to build a really simple website that has a section combining all the posts from instagram accounts from me and my friends, sorted by date of publication. I already added it for one account (mine) using the Heroku method and it works well, but I can't seem to find an option to use multiple tokens and accounts with this script. Do you know if this is possible at all? I used the same code used in the Ultra basic demo found on the Instafeed help

sorry if this is trivial i'm not the best programmer/html developper out there but i'm willing to learn so any tip is welcome !

thanks,

you can visit the page to have an idea of what i mean here [http://bifre.fr/](url) (i want the same thing but with posts from multiple accounts sorted by post order

**Comment by Nofrek** [comment]
what i've read from the other issues is that u used to simply create different instafeed instances with different clientID variables. But in the V2 th client ID doesn't exist anymore, how am I supposed to differentiate between the multiple accounts that are linked as instagram testers in the facebook developper/basic display api form?

**Comment by stevenschobert** [comment]
Hey @Nofrek! You're on the right track! You can create multiple instances of Instafeed.js on the same page:

```js
var feedA = new Instafeed({
  target: 'feedA',
  accessToken: '...'
});


var feedB = new Instafeed({
  target: 'feedB',
  accessToken: '...'
});

feedA.run();
feedB.run();
```

You'll need to have separate `<div>`s on your pages, and separate access tokens for each feed.
