### ISSUE TITLE
Likes and Comments count not show on instafeed v2

### ISSUE THREAD

**Issue by Alnsentry** [stevenschobert/instafeed.js#695]
Hi i am wanna ask something, 
why likes and comment count ( {{ likes }}, {{ comments }} ) in instafeed v2 doesn't show?. 
Does this require special permission from facebook api or in instafeed v2 {{ likes }} and {{ comments }} is deleted?

Thanks you, sorry if my english doesn't great

**Comment by benjamin-hull** [comment]
Hi @Alnsentry - the unfortunate answer is that Instagram's new API doesn't provide this data at all: there's just no way to get it any more.
