### ISSUE TITLE
cannot put it in owl carousel

### ISSUE THREAD

**Issue by sourabh48** [stevenschobert/instafeed.js#696]
Hi,
I was trying this out for the past few days. I need to use it in the carousel. can you help me to build one?

**Comment by jansolo76** [comment]
You should install the owl2row plugin and use this snippet:

  customTemplate = '<a href="{{link}}" target="_blank" ><img data-src="{{image}}" class="{{orientation}} owl-lazy" /></a>';

var feed = new Instafeed({
      get: 'user',
      userId:'DONTKNOWIFYOUNEEDTHISANYMORE', 
                  accessToken: 'YOURTOKEN',
                  template: customTemplate,
                  resolution: 'low_resolution', 
                  limit:12,
                  after: function () {
                          
                          var owl = jQuery('.owl2row-plugin');
                          owl.owlCarousel({
                              loop: true,
                              margin: 0,
                              navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
                              nav: true,
                              dots: false,
                              lazyLoad:true,
                              //lazyLoadEager: 1,
                              responsive:{
                                0:{
                                  items:1,
                                  autoheight: true
                                },
                                768:{
                                  items:4,
                                  autoheight: false
                                }
                              }
                          });
                      }
          });
          feed.run();

**Comment by benjamin-hull** [comment]
@jansolo76 - that snippet is for Instafeed v1 and won't work anymore.

**Comment by jansolo76** [comment]
@benjamin-hull Not true. There might be too many options involved, but it still does work 100%

**Comment by sourabh48** [comment]
Thanks for the information
