### ISSUE TITLE
How to get instafeed working with masonry 

### ISSUE THREAD

**Issue by gertjanjanssen** [stevenschobert/instafeed.js#697]
Hi, even since i upgraded instafeed to version 2 i haven't been able to get it to work with the masonry. I've been able to get masonry working with other Wordpress posts, but i haven't been successful with instafeed. 

Does anyone has a suggestion to get it working;

**Comment by gertjanjanssen** [comment]
Got it! https://github.com/stevenschobert/instafeed.js/issues/118#issuecomment-44438003 this helped; 
In my case: 

<script>$(document).ready(function() {
  var feed = new Instafeed({
    accessToken: InstagramToken,
	  template: '<div class="col-md-4 col-sm-4 col-xs-6 margin_bottom"><a href="{{link}}"><img class="img-responsive" title="{{caption}}" src="{{image}}" /></a></div>',
   after: function () {
// init Masonry
var $grid = $('.grid').masonry({
  itemSelector: '.col-md-3, .col-md-6, .col-md-4',
  percentPosition: true,
  columnWidth: '.col-md-3, .col-md-6, .col-md-4'
});
// layout Masonry after each image loads
$grid.imagesLoaded().progress( function() {
  $grid.masonry();
}); 
  }
});
feed.run();
  });

**Comment by stevenschobert** [comment]
Hey @gertjanjanssen! Glad you were able to get it working! 🎉
