### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by kaleidografik** [stevenschobert/instafeed.js#698]
Hi guys. We've had V2 up and running for a while now, with no problems. However this week a couple of the sites have started returning 400 errors stating 'Failed to load resource: the server responded with a status of 400 ()'.

We're using instant-tokens.com to generate the Token, and that URL has been tested and is successfully still returning a Token. This therefore suggests there is no issue with the connection to Instagram itself?

Please see code below for reference, thanks.

// Init instafeed.js
// Access token needs refreshing every 60 days, done automatically via ajax call to instant-tokens.com
$.ajax({
  type: 'get',
  dataType: 'json',
  url: 'https://ig.instant-tokens.com/users/............',
  // If request is successful
  success: function (response) {
      var feed = new Instafeed({
        target: 'instagram-carousel',
        accessToken: response.Token, // Access token from json response
        apiTimeout: 10000,
        limit: 20,
        template: '<figure><a href="{{link}}" target="_blank"><img src="{{image}}" /></a></figure>',
      });
      feed.run();
    }
  }
});

**Comment by stevenschobert** [comment]
Hey @kaleidografik, thanks for the report! Do you have any more details on the error you were seeing, or a link I could take a look at?
