### ISSUE TITLE
Should remove permalink

### ISSUE THREAD

**Issue by rwblue** [stevenschobert/instafeed.js#699]
This permalink filter cause exception in API

https://github.com/stevenschobert/instafeed.js/blob/d287c68329a7afc88d9505f189e11ade78baf364/src/instafeed.js#L119

**Comment by mastrup** [comment]
Seems to be temporary issues at Facebooks end.
It would be nice with at feature to exclude some fields though (e.g. permalink).

**Comment by jannemecek** [comment]
I wouldn't call this a feature request. Instafeed is broken for me until `permalink` is removed the request.

**Comment by stevenschobert** [comment]
Hey @rwblue and @mastrup! Thanks for the heads up -- strange to hear an specific field request could be causing troubles in the Instagram API.

I like the idea of adding an option to control which fields are requested though! I've added a feature request #706 to track that.
