### ISSUE TITLE
Carousel items

### ISSUE THREAD

**Issue by mmjaeger** [stevenschobert/instafeed.js#700]
Hello
I was wondering whether your script allows to show carousel items as well

Thanks

**Comment by stevenschobert** [comment]
Hey @mmjaeger, thanks for the question! Instafeed.js does not currently support showing the extra images from carousels, it will only show the 1st image from the album.

There is an open feature request for it in issue #650. It's not planned for an upcoming release right now, but you can subscribe to that issue to be notified of progress.
