### ISSUE TITLE
Getting error message on all feeds: site-min.js?ver=5.5.1:4 Error: api request error: 190 Error validating access token: Session has expired on Wednesday, 30-Sep-20 16:51:54 PDT.

### ISSUE THREAD

**Issue by dayneh88** [stevenschobert/instafeed.js#702]
Hi,

Is anybody all of a sudden getting a similar error message on all of their feeds:

**Error: api request error: 190 Error validating access token: Session has expired on Wednesday, 30-Sep-20 16:51:54 PDT.**

We are using Version 2 RC2 and it was all working fine before.

Thanks,
Dayne

**Comment by Jeemusu** [comment]
I wonder if there has been some change to the instagram API as all the tokens I have issued today or that have renewed themselves in the last few days are returning "Uncaught Error: Error from Instagram: The access_token provided is invalid." errors from instafeed. instant-tokens.com also seems to be having problems issuing me new tokens. I have checked all the tokens in the facebook token debugger, but they seems fine.

**Comment by vulkanus** [comment]
Hi,

I´m not sure, but I think if you don´t have the API in live mode, that will happened, I think I was have an similar issue.
What I done was regenerate new token, in my developed API.

but you can check it out here: https://developers.facebook.com/blog/post/2011/05/13/how-to--handle-expired-access-tokens/

sorry if I was not correct

**Comment by stevenschobert** [comment]
Hey @dayneh88! In the new Instagram Basic Display API, which powers v2 of Instafeed.js, access tokens do have a limited lifespan (60 days).

This means that with v2, you need some mechanism to refresh the access tokens routinely, to keep Instafeed.js working. I'm still working on documenting some of the details, but you can find a couple of potential solutions in the [WIP "Managing Access Tokens" document](https://github.com/stevenschobert/instafeed.js/blob/bc3c109abe088a322b97eb530d5613c1a1642a2d/docs/managing-access-tokens.md).
