### ISSUE TITLE
Image {link} goes direct to cloud storage, not the Instagram Page

### ISSUE THREAD

**Issue by jordanhammond** [stevenschobert/instafeed.js#703]
This appears to be a problem with the response that Facebook provides in media_url.  The {link} property goes directly through to the cloud storage for each image, and not the owner's Instagram page displaying the image.

Is there any way to resolve this?

**Comment by stevenschobert** [comment]
Hey @jordanhammond! Thanks for the report.

Would you be able to produce a runnable version of this bug, using CodePen or some other public page so I could take a look?

Thanks!

**Comment by vulkanus** [comment]
Hi,

I think that I have the same issue. 
I have changed to<img src="{{image}}" /> insteed <img src="{{link}}" />

I used <a href="{{link}}"></a> for target IG image.

cumpz

**Comment by stevenschobert** [comment]
Are you still seeing this behavior @jordanhammond? I'm wondering if  it could have been a temporary problem with Instagram's API.

**Comment by vulkanus** [comment]
ping
