### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Deyfenn** [stevenschobert/instafeed.js#705]
I've setup my Facebook dev as needed, generated a long token, but nothing is added to my webpage.  Instafeed.min.js is added properly also.  Run out of things to try...(want to make this work before moving on to auto-token update).

<div id="instafeed"></div>

<script type="text/javascript">
    var feed = new Instafeed({
      accessToken: 'longstringhere'});
    feed.run();
</script>

**Comment by stevenschobert** [comment]
Hey @Deyfenn! Do you see any errors in the console? You may also try turning on the `debug` option to see more information in the console.

**Comment by Deyfenn** [comment]
No errors at all which is weird.  Using Dreamweaver.  In know its verboten, but this is the token in question -> ‘IGQVJVYTZAPZAmxkVWtsT3ZAIQVBtYVhDcnlOQ2VEbDVaTkJ4SUROdUhsRlJXRURxUXhsV1dYS2JQV2VHWEEteEVsVUhjSjdjN0FST0RZAaDdqS2I0QVNEZAjl5WEpnd1psSDc2NTdaaG9kUnMwU1ZANZAkI4cgZDZD’  (I can always reset it anyways)

 

I feel like I am missing a setup, just can’t see what it is L  I assume it is ok to simply paste in the 60-day token to test at least?

 

Anything you can think of would be great J (ps, thanks for dev.ing this tool….I really want to stay away from the aggregate sites that pull for you.

**Comment by stevenschobert** [comment]
Hey @Deyfenn! I tried out the access token you sent over, and was able to get Instafeed.js fetching images (see screenshot below).

Have you double checked that your `Instafeed.min.js` script is uploaded to your site, and that you added `<div id="Instafeed"></div>` to your page?

![CleanShot 2020-11-11 at 21 56 30@2x](https://user-images.githubusercontent.com/896486/98893749-c5e12f00-2468-11eb-8550-458b54887845.png)

**Comment by Deyfenn** [comment]
Strange…I was just testing with something super basic.  The script is loaded and pathed properly…

 

<!DOCTYPE html>

<html lang="en">

<head>

                <script src="_scripts/instafeed.min.js"></script>

</head>

                                

<body id="home">

<div id="Instafeed"></div>

 

<script type="text/javascript">

    var feed = new Instafeed({

      accessToken: "IGQVJVYTZAPZAmxkVWtsT3ZAIQVBtYVhDcnlOQ2VEbDVaTkJ4SUROdUhsRlJXRURxUXhsV1dYS2JQV2VHWEEteEVsVUhjSjdjN0FST0RZAaDdqS2I0QVNEZAjl5WEpnd1psSDc2NTdaaG9kUnMwU1ZANZAkI4cgZDZD"

    });

    feed.run();

</script>

                </body>

</html>

**Comment by stevenschobert** [comment]
If you enable the `debug: true` option, you should see at least some logs in the web console when Instafeed.js runs. You'll either see debug logs, if everything was successful, or an error log if something failed.

**Comment by Deyfenn** [comment]
Hi Steven,

 

Chrome spits this out (with or without debugging turned on) (ps, I’m using Dreamweaver 2019 to code but it doesn’t have much in the way of debugging itself)

 

http://www.mandysaile.com/v5/test.html

 



 

I grabbed the script from -> https://github.com/stevenschobert/instafeed.js/tree/master/dist so I know that’s right at least…

**Comment by Deyfenn** [comment]
Arg…doesn’t matter what I do I can’t get it working.  This is frustrating that I can make it work…especially since you were able to load the stream with the token.  If you have any thoughts it would greatly be appreciated.

 

JP

 

From: deyfennslayd@gmail.com [mailto:deyfennslayd@gmail.com] 
Sent: Sunday, November 15, 2020 11:13 AM
To: 'stevenschobert/instafeed.js' <reply@reply.github.com>; 'stevenschobert/instafeed.js' <instafeed.js@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [stevenschobert/instafeed.js] Token (#705)

 

Hi Steven,

 

Chrome spits this out (with or without debugging turned on) (ps, I’m using Dreamweaver 2019 to code but it doesn’t have much in the way of debugging itself)

 

http://www.mandysaile.com/v5/test.html

 



 

I grabbed the script from -> https://github.com/stevenschobert/instafeed.js/tree/master/dist so I know that’s right at least…

**Comment by Alnsentry** [comment]
Hi @Deyfenn i have same issue with you, the problem is Instafeed.min.js file you use.

my solution is redownload instafeed.js file from https://github.com/stevenschobert/instafeed.js/releases/tag/v2.0.0-rc2 or https://github.com/stevenschobert/instafeed.js/archive/v2.0.0-rc2.zip, and copy instafeed.js from /dist to your directory code.

i dont know why your Instafeed.min.js file doesn't work, maybe old version or have some bug. I hope this will help you
