### ISSUE TITLE
Instafeed no work in localhost ? No error..

### ISSUE THREAD

**Issue by Vinibch** [stevenschobert/instafeed.js#712]
Hello,
No work instafeed in Prestashop !

**Setup HTML  :**
`<div id="Instafeed"></div>`

**Setup Javascript :**
```
{/if}
{if $page.page_name=='index'}

<script type="text/javascript" src="{$urls.js_url}instafeed.js">
    var feed = new Instafeed({
      accessToken: 'XXX'
    });
    feed.run();
</script>

{/if}
```
**Information console :**
`No error`

Is the problem related to a local installation?

**EDIT :** 
{$urls.js_url} : Simplify code (http://localhost/v1/themes/classic-rocket/assets/js/instafeed.js), **url is correct !**

**Comment by mazhar1987** [comment]
You called the instafeed.js file in the wrong place.  You have to call it seperately inside the file before </head> or before </body> tag. You can use the code <script type="text/javascript" src="{$urls.js_url}instafeed.js"></script>

**Comment by Vinibch** [comment]
Thank you very much, the module is working fine. However, cannot use the forward parameters :(

<script type="text/javascript" src="{$urls.js_url}instafeed.min.js"></script>
<script type="text/javascript">
       var feed = new Instafeed({
             accessToken: 'my-key',
             limit: 8,
             template: '<a href="{{link}}"><img title="{{caption}}" src="{{image}}" /></a>'
        });
        feed.run();
</script>
