### ISSUE TITLE
Instafeed Not Working

### ISSUE THREAD

**Issue by thedanholt** [stevenschobert/instafeed.js#713]
Hello

I have been using version 2 of Instafeed along with the token agent but it suddenly stopped working a few days ago.

I have been through everything and can't see anything wrong my end. I noticed the demo doesn't work on Codepen doesn't work either.

Any ideas?

**Comment by mkdub** [comment]
Ok, so maybe it's bad timing on my part, but I've just found time to fix my IG feed that's been broken for a while now. I am trying everything to migrate to V2 but I am getting an error noting: 

> api request error: api connection error
> at instafeed.min.js:2

Is that what you are experiencing Dan?

**Comment by thedanholt** [comment]
I think my issue might be to do with the Instagram Token Agent. When I run the app, I am getting stuck on 'Checking status...' and it doesn't show as successful. I have tried to re-create the app using the deploy button but I run into issues there too. Once I've filled out the config vars, I get an error message: "Couldn't find either the add-on service or the add-on plan of "temporize:developer".".

**Comment by mkdub** [comment]
I am also experiencing the same thing, that's why I am just trying to get the feed initiated with just the token generated from Facebook, even though I know it will expire. Once I have the plugin working, I'll look into why Heroku app isn't working, I have a feeling it might be because you have to purchase the temporize scheduler,

**Comment by mkdub** [comment]
Any update Dan or anyone?

**Comment by dsanti82** [comment]
Same here, same error as 

> Ok, so maybe it's bad timing on my part, but I've just found time to fix my IG feed that's been broken for a while now. I am trying everything to migrate to V2 but I am getting an error noting:
> 
> > api request error: api connection error
> > at instafeed.min.js:2
> 
> Is that what you are experiencing Dan?

I'm getting the same error

**Comment by SandyWyper** [comment]
Try removing the template option

**Comment by amoln360** [comment]
Hello,

Not showing insta videos in my HTML page. How can I get videos. Thank you!

var feed = new Instafeed({
            userId: 'XXXXXXXXX',
            get: 'user',
            accessToken: 'XXXXXXXXX',
            resolution: 'standard_resolution',
            target: "instafeed-container",
            limit: 33,
            template: '<div class="col-xl-4 mb-4 gallery"><a href="{{image}}" title="{{caption}}" target="_blank"><img src="{{image}}" alt="{{caption}}" class="img-fluid" /></a></div>',
            sortBy: 'most-recent',
        });
        feed.run();

**Comment by ninkstan** [comment]
I also got the 'Couldn't find either the add-on service or the add-on plan of "temporize:developer".' :( Has anyone found the solution??
