### ISSUE TITLE
Template isn't working v2

### ISSUE THREAD

**Issue by Heqma** [stevenschobert/instafeed.js#715]
templating isn't work after adding any code to it

**Comment by MrPeanutButter99** [comment]
Same happened to me

**Comment by SandyWyper** [comment]
Same here. 

```html
<a href>
  <img alt src(unknown)>
</a>
```

Omit the template option and it works, but would be good to have control.

**Comment by giists** [comment]
Did you manage do get code inside the template running? Mine doesn't.
