### ISSUE TITLE
Integration with igfeed-proxy

### ISSUE THREAD

**Issue by Faylixe** [stevenschobert/instafeed.js#717]
Hello and thanks for your project which is great !

I have been pretty inspired by your library and I came up with an alternative for token and data proxing that may be nice to integrate in this project : https://github.com/Faylixe/igfeed-proxy.

The idea is to provide a service running on a free Heroku dyno to replace the instagram token agent, by actually performing the Instagram API call from the service it self and caching the fetched data in memory. It avoid exposing the access token to the client, any form of rate limiting since it only fetch data at a fixed interval and caching. Plus the application also ping itself at fixed interval to prevent from dyno idling without having to setup any external service or tweak :).

I was wondering if integrating this kind of service directly with Instafeed would be ok for you by offering user the possibility to either use the old model (based on token agent and direct IG API querying) and this one by simply providing a proxy URL to fetch directly data from it). If you are interrested please let me know and I will submit a PR for it.

**Comment by Chinoman10** [comment]
I'm pretty sure this Steven stopped doing development altogether. Just look at his commit activity.
My solution instead of a Heroku worker was using CF Workers :)
No need to have a constant server running waiting for requests, and using KV storage I can also cache the results.

**Comment by stevenschobert** [comment]
@Chinoman10 if you’re referring to the commit graph that GitHub shows on profile pages — those only show commits in public repositories.

**Comment by Chinoman10** [comment]
> @Chinoman10 if you’re referring to the commit graph that GitHub shows on profile pages — those only show commits in public repositories.

Ah. Makes sense. Fair point! 😬
Apologies for the snarky comment then 🧐
🍻

**Comment by stevenschobert** [comment]
Hey @Faylixe! Thanks for sharing your project!

> I was wondering if integrating this kind of service directly with Instafeed would be ok for you by offering user the possibility to either use the old model (based on token agent and direct IG API querying) and this one by simply providing a proxy URL to fetch directly data from it)

This would be great, and something I'd be happy to have a PR created for!

The URL construction is currently in lines 201-212: https://github.com/stevenschobert/instafeed.js/blob/bc3c109abe088a322b97eb530d5613c1a1642a2d/src/instafeed.js#L201-L212

I'd like to have this code lifting out into its own method, and add options around it. Possible options worth adding are:
* Base URL — option to change the base URL for API requests, which would default to: `https://graph.instagram.com`
* Extra URL parameters — an object of URL parameters to append to requests, defaulting to `null` or `{}`
