### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by Soneji** [stevenschobert/instafeed.js#719]
Hi

I want to update the wiki but I don't think it's letting me.

I want to change this page:
https://github.com/stevenschobert/instafeed.js/wiki/Managing-Access-Tokens

specifically where it says: "Follow the instructions to deploy the Instagram Token Agent app, providing the starting token"

I think this should be a new sub list with multiple options as I tried the linked [Instagram Token Agent](https://github.com/companionstudio/instagram-token-agent) but this is currently not usable. See [here](https://github.com/companionstudio/instagram-token-agent/issues/33).

The solution is to use: https://www.instant-tokens.com/

Thanks, this js plugin is amazing :)

**Comment by AnaFCPreto** [comment]
I raised a PR for this exact purpose :)
https://github.com/stevenschobert/instafeed.js/pull/718

**Comment by soneji** [comment]
Oh, amazing, thanks @AnaFCPreto
