### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by DNevens** [stevenschobert/instafeed.js#72]
Hi,

I have Instafeed working (very nice, thanks!) but I am quite confused on how to get the pagination to work.

I really don't know Javascript, but can follow examples. Is there any example/demo on how to use the pagination? I just tried plopping the script into the page, but obviously that didn't work.

Many thanks!

**Comment by waisie** [comment]
Hi DNevens , 
How do u make the "load more" button work?
When I click my load more button it works but, but it will start from the beginning. it doesn't go to the bottom like yours. Can you help me?

**Comment by leandrosa** [comment]
Hi @stevenschobert, this code is save my life(hehehe), but I have a scenary that I don't solve.

I wrote **tagName: 'cafecommentor'** and I didn't any response. I got a pagination error like below

`/**/ instafeedCache5d4df710978ea757.parse({"pagination": {"deprecation_warning": "next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead"}, "meta": {"code": 200}, "data": []})`.

What this means?

Thanks in advance

**Comment by jatinderka** [comment]
$(document).ready(function() {
    var feed = new Instafeed({
            target: 'instafeed',
            get: 'user',
            userId: xxxx,
            clientId: ‘xxxx',
             accessToken: ‘xxxxx',
            link: 'true',
            resolution: 'standard_resolution',
            limit: '60',
            sortBy: 'most-recent'
    });
    feed.run();
});

$('#mybutton').on('click', function() {
     $("#instafeed").fadeTo(400, 0, function() {
        $(this).empty(); // remove this line if you want to keep previously loaded images on the page
        feed.next();
     })
});
i m using the same function but everything blank...page doesnot show anything

**Comment by kcmvillarino** [comment]
@jatinderka 
  although your question is a year ago, i've encountered the same problem using the fadeTo function, just put this $(this).css('opacity','1'); inside your $("#instafeed")
