### ISSUE TITLE
refresh div?

### ISSUE THREAD

**Issue by vincentddd** [stevenschobert/instafeed.js#78]
Hey (me again...),
is it possible to refresh the content? like every x secondes?
I tried to refresh the div with jquery but it multiplies the tags and the photos (3 times the same content) and it gets crazy after 10 refresh. 

this is the code I used:

var auto_refresh = setInterval(
  function ()
  {
    $('#instafeed').load('#instafeed');
  }, 10000);
    feed.run();

do you have any idea of how I should do?

Thanks!

**Comment by benjamin-hull** [comment]
Closing as stale - remaining issue is for the slider implementation anyway.
