### ISSUE TITLE
USER + Specific tag

### ISSUE THREAD

**Issue by ndwl** [stevenschobert/instafeed.js#80]
Is it possible to pull all the images from a "user" that have a specific tag?

**Comment by thunderkee** [comment]
I have tried the lowercase tag, but it still results 0 images. the code structure is same with above, any suggestion?

**Comment by thunderkee** [comment]
<pre><code><script type="text/javascript">
        var feed = new Instafeed({
        	get: 'user',
  userId: 329535466,
 
  clientId: '02d26456d268470b95f3a621df85f4f1',
 accessToken: '329535466.02d2645.beec464bb049448b8bdb412e6804bb8b',
     
            resolution: 'low_resolution',
            useHttp: 'true',
            sortBy: 'most-liked',
            limit:4,
            template: '<div class="col-md-3"><div class="instagram-card"><a href="{{link}}"><div class="info-top"><img class="instagram-profile-photo" src="{{model.user.profile_picture}}">{{model.user.username}}</div><img class="instagram-post-photo" src="{{image}}" /><div class="info-bottom"><div class="meta text-center"><ul><li class="likes"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> {{likes}}</li><li class="comments"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> {{comments}}</li></ul></div></a></div></div></div>',
 
       filter: function(image) {
return image.tags.indexOf('thunderkee') >= 0;
}
        });
        feed.run();
    </script>
</code></pre>
