### ISSUE TITLE
Problem with pagination & limit

### ISSUE THREAD

**Issue by nathinah** [stevenschobert/instafeed.js#82]
Hi Steven! 
Thank you for this plugin. You saved my life :)

I have a problem with pagination. The code I use is this:

---

$('#load-more').on('click', function() {
     feed.next();
});

---

The console doesn't give me any error, but the button (at the bottom of the page) doesn't work :(

Also the limit option seems not to work. I would like to have 60 images at a time, but it only shows 20.

Can someone tell me what is wrong?
The website is the following: http://www.milanoeveryday.it/

Thank you all.
Much love, Nathalie

**Comment by waisie** [comment]
Hi nathinah  , 
How do u make the "load more" button work?
When I click my load more button it works, but it will start from the beginning. it doesn't go to the bottom like yours. Can you help me?

**Comment by asegari** [comment]
I'm also trying to figure out how to load more without it going back to the top of the page

**Comment by sebastianwr** [comment]
@asegari Use `event.preventDefault();` or `return false` at the end of the click handler function
