### ISSUE TITLE
Photos I like and with hashtag

### ISSUE THREAD

**Issue by naderby** [stevenschobert/instafeed.js#87]
Great js guys, please forgive my limited knowledge but what code do I use to get photos I've liked (including my own) but also have a specific hashtag?

**Comment by nickfmc** [comment]
Just a heads up, using this filter with the new method of not using an access token but only the clientID doesn't seam to work, and the link to get an access token from the Instafeed site seams to have been removed with the last update so people still may need an access token I believe 

<code> filter: function(image) {
        return image.user_has_liked;
    }</code>
