### ISSUE TITLE
Moderating Photos seen on Client side

### ISSUE THREAD

**Issue by mcclaskiem** [stevenschobert/instafeed.js#95]
I really love the simplicity but power of instafeed.js. I was curious if there is any sort of back end script out there that can assign an approved variable to a photo and then be called in the image filter so that ones with "approved" will be shown. 

Basically I would want to set it up so that I can use this to populate a back-end and then go through and assign variables through some sort of form. Following that alter the script so that it calls the cached images with the approved filter.

**Comment by jegheddermilos** [comment]
Did anyone find a solution to this? :)
