### ISSUE TITLE
Limit with filter

### ISSUE THREAD

**Issue by jaredprice** [stevenschobert/instafeed.js#97]
Is it possible to limit the number of images while applying a filter, such that it will look through all the images in the user's feed to satisfy the limit?

```
    var feed = new Instafeed({
        get: 'user',
        userId: USER_ID,
        clientId: 'CLIENT_ID',
        accessToken: 'ACCESS_TOKEN',
        template: '<a href="{{link}}"><img src="{{image}}" /></a>',
        limit: 12,
        filter: function(image) {
            return image.tags.indexOf('mytag') >= 0;
        }
    });
    feed.run();
```

**Comment by rhysburnie** [comment]
This is what I use when I want a max and a min (I also happen to want to grab my images and filter by multiple tags)

```
var min = 10,
    max = 10,
    lastMatchedImages = 0;

var recent = new Instafeed({
    
    // whatever
    
    limit: 60,
    filter: function()
    {
        // I want to have multiple tags or plurals
        // so FYI this is how you do it
        var match = image.tags.join(',').match(/plant[s]{0,1},|building/gi) || [];

        if(match.length > 0 && lastMatchedImages < max) {
            lastMatchedImages++;
            return true;
        }
        return false;
    },
    after: function()
    {
        if(lastMatchedImages < min) {
            if(this.hasNext()) {
                recent.next();
            }
        } else {

            // whatever

        }
    }
};

recent.run();

```

I have a next button to continue pagination it calls `recent.run()` but resets `lastMatchedImages` to `0` first that way I can continue pagination within scope of the tags.

NB: this obviously results in multiple ajax requests so you way want a limit of attempts it makes - I don't care.

**Comment by JimmyRittenborg** [comment]
These workarounds doesn't quite cut it for me - the https://github.com/stevenschobert/instafeed.js/issues/97#issuecomment-42217785 gets close, but it has a huge downside as everything in the difference between the filter and the rest of `maxImages` gets completely ignored and effectively whipped out of the feed - I think for this to work, another array after filterring has to be introduced, which serves as a buffer, and then limit should be set to twice the maximum number of images that should be displayed at once, from this array the entries gets sorted and attached to the dom.

**Comment by tamfr** [comment]
For those of you that really need the functionality proving difficult with this, that is specifying a tag and pulling from all images without limit, try https://github.com/d4nyll/instafetch. It is a bit clunky, but works and was specifically written for this task. The example site is http://d4nyll.github.io/instafetch/. You can also check out www.osteoengineering.com, which uses both instafeed and instafetch (www.osteoengineering.com/team/briswan for example). Each team member page pulls images from our instagram account with the team member in it based on tags.

**Comment by rhysburnie** [comment]
@JimmyRittenborg

Obviously thats the case, as stated that's a custom filter for my own purposes.
You would set up your own filter.

RE: the rest of the results completely ignored - that is the point of a filter

I can get the mechanism described to work in all situations with or without filters, I simply provided an example.

**Comment by JimmyRittenborg** [comment]
@rhysburnie the point of a filter is to strip out what's defined to be filtered out by the filter, and certainly nothing more, which is actually the case.

**Comment by rhysburnie** [comment]
@JimmyRittenborg

What Im guessing is that you are concerned that because the filtered results may only contain 2 images that the pagination would somehow be out of sync?
Fair enough assumption but it's not the case, the plugin doesn't track any kind of buffer.

The plugin doesn't manipulate pagination based on filtered results, it only uses the `nextUrl` property provided in the instagram json.

If you look at the plugin code the filter function has noting to do with pagination, it only filters what will be displayed. 

So in the following (the result amount per respnse would be based on settings but lets imagine 12):

1st call

actual results: 12
results for displayed: 3 (9 not matched)

2nd call 
- instagram api completly unaware of any filtering etc. it just receives the url defined in `nextUrl` property

actual results: next 12
results for displayed: 5 (7 not matched)

Each load more will always get the next correct set from instagram because it's doing it by simply calling the `nextUrl` property provided by the api and not a buffer.

**Comment by JimmyRittenborg** [comment]
@rhysburnie I'm still referring to https://github.com/stevenschobert/instafeed.js/issues/97#issuecomment-42217785 which doesen't change the fact that 12 images should be showed, 60 gets pulled in 2 gets filtered out (blocking by ID's) and 46 gets laid to rest in you browser memory for no one to ever see.

Conclusion: When using a filter to EXCLUDE items, that https://github.com/stevenschobert/instafeed.js/issues/97#issuecomment-42217785 trick wont work and instead feel really buggy. 

True, nothing gets buffered - and that was actually the reason for why I suggested THAT to be a possible solution to the problem.

**Comment by JimmyRittenborg** [comment]
but it could probably just be in my application.. as it clearly says `maxImages` ;)

**Comment by rhysburnie** [comment]
@JimmyRittenborg 

Yes if max of 10 and the result set of 20 and your filter matches 15 in that result set then those last five will effectively be hidden from display. 

This is a limitation of the plugin itself. The images array only exists within the scope of the recent fetch (see Instafeed.prototype.parse).

**Comment by JimmyRittenborg** [comment]
Exactly - that was just, what I tried to point out :)

**Comment by rhysburnie** [comment]
@JimmyRittenborg

But unlike everyone else on here who are offering solutions your simply throwing around the word `buffer`.

Perhaps the developer intends to fix this in his own time.
Otherwise you could do it.

What you have hit is a technical limitation of the plugin. There are several ways you could go about it but all involve editing the internal code, I would assume the developer wants to keep it clean and simple. The issue rarely happens when it does in my case I would be excluding a small amount of images personally I don't care enough to edit the code and create a pull request.

Im not sure why you would be using a filter to find image by ID anyway when the instagram api allows you to get data for a specific image by ID directly.

**Comment by zanscath** [comment]
@rhysburnie 

I think I took your code one step further. Though not very efficient, this gets you all images of a certain tag filtered by a certain user. If there are more items than the limit, then it adds a class to the item and hides it. The next time the load more button is pressed your variable lastMatchedImages is initialised with the number of hidden images, their class is removed and they are not hidden anymore. This way you don't loose items and always get the right number of new images, unless you're on the last page.

```javascript
	var loadButton = document.getElementById('load-more');
	var min = 20,
		max = 20,
		lastMatchedImages = 0;
    var feed = new Instafeed({
		limit: 60,
        get: 'tagged',
        tagName: 'YOURTAG',
        clientId: 'YOURID',
		template: '<a href="{{link}}" class="{{model.className}}" style="{{model.style}}"><img src="{{image}}" /></a>',
		filter: function(image)
		{
			if(image.user.username == 'USERNAME') {
				if(lastMatchedImages < max){
					lastMatchedImages++;
				}
				else{
					image.className = "fidden";
					image.style = "display: none";
				};
				return true;
			}
			return false;
		},
		  after: function() {
			if(this.hasNext()) {
				if(lastMatchedImages < min) {
					feed.next();
				}
			} else {
			  loadButton.setAttribute('disabled', 'disabled');
			  $('#load-more').hide();
			}
		  },
    });

	// bind the load more button
	loadButton.addEventListener('click', function() {
		numItems = $('.fidden').length;
		$('.fidden').show().removeClass( "fidden" );
		lastMatchedImages = numItems;
		feed.next();
	});

	// run our feed!
	feed.run();
```

**Comment by mmativ** [comment]
How if i am using filter in username and i want to sure that only 16 images shows? this is my code 
`var InstaBigFeed = new Instafeed({
    target: 'InstaOutput',
    get: 'tagged',
    userId: '233178697',
    tagName: 'BiteSizedArmy',
    accessToken: '6678174.467ede5.205a03ebc4b74d4082823781c3149575',
    limit:  '25',
    sortBy: 'most-commented',
    resolution: 'standard_resolution',
    filter: function(image) {
    	
	  var blockedUsernames = ['allieqdub','user','rawwdopefeatures'];

	  // check for blocked users
	  for (var i=0; i<blockedUsernames.length; i++) {
	    if (image.user.username === blockedUsernames[i]) {
	      return false;
	    }
	  }

	  return true;
	},`

**Comment by benjamin-hull** [comment]
Closing as complete.
