### ISSUE TITLE
user id and tag name

### ISSUE THREAD

**Issue by katefarrar** [stevenschobert/instafeed.js#98]
Hi. Is it possible for me to do photos from a specific user with a certain tag?

Thanks!

**Comment by Digggid** [comment]
If all your tagged specific images are at the bottom of your feed, I have noticed that instagram api only loads 20 images to by pass this increase your limit to 500 or so and add a function within that removes all other images except for the amount that you are willing to show.

@katefarrar has the filter solution.

    <script>

    var feed = new Instafeed({
        get: 'user',
        userId: 'YOUR_ID',           
        accessToken:'YOUR_ACCESS_TOKEN',
        resolution:'low_resolution',
        limit: 500,
        sortBy: 'most-recent',
        template: '<a target="_blank" href="{{url}}" rel="ig"><img class="instagram-image desktop-2 tablet-1 mobile-1 contained" src="{{ igimage }}" /></a>',
        filter: function(image) {return image.tags.indexOf('verve') >= 0;},
   		after: function () {
    	 $('.instagram-image').each(function(i){
     	 if (i>=6){
             $(this).remove();
        }
      });
     }
    });
  
  
    feed.run();

    </script>
