### ISSUE TITLE
Uncaught ReferenceError: instafeedCachexXxXxX is not defined

### ISSUE THREAD

**Issue by lanceschi** [stevenschobert/instafeed.js#99]
Hi @stevenschobert,

looking at Chrome v34.0.1847.132 console, I see the above error many times. Same unique identifier after instafeedCache. It seems to get logged in console randomly after a call to `instafeed_obj.next()` method.

`Uncaught ReferenceError: instafeedCache4cb3eb627384a2a5 is not defined`

I've developed an infinite scroll wallpaper of instagram thumbs filterd by tag. Everything works as expected (despite Instagram server 503s due to limited capacity), nevertheless that Uncaught ReferenceError makes me wonder.

You can have a look at this demo with development tags and hit F12 while scrolling down:
[www.raccontareilfoodinrete.it](http://raccontareilfoodinrete.it)

Any clues? Thanks.

btw great plugin! :+1: 

Cheers,
Luca

**Comment by FFae** [comment]
Hi,

I have the same problem, but I´m using a basic script.

    function instagram() {   
        var feed = new Instafeed({
            get: 'user',
            userId: 'xxx',
            limit: 9,
            sortBy: 'most-recent',
            clientId: 'xxx'
        });
        feed.run();
    }
    instagram();

The first time that I load the page is OK, but when I refresh the page, I'm getting this same error.
